### ISSUE TITLE
Extend datadog_logs_metric resource to allow for multipe group by tags

### ISSUE THREAD

**Issue by espey** [DataDog/terraform-provider-datadog#1009]
### Terraform Version

Terraform v0.14.9

### Affected Resource(s)

datadog_logs_metric

### Expected Behavior

I would expect this resource to allow me to specify an array of strings for both path and tag_name within the group_by stanza instead of just a string. I have multipe facets that I want my custom log metric log query, having just one option here makes it pretty useless for my usecase.  

Example of what I want to be able to terraform within DD:
<img width="969" alt="Screen Shot 2021-03-26 at 4 45 51 PM" src="https://user-images.githubusercontent.com/9875629/112700018-d1028d80-8e52-11eb-9bb6-2e28ffb483a6.png">

The only thing I can successfully terraform right now within DD:
<img width="1064" alt="Screen Shot 2021-03-26 at 4 47 21 PM" src="https://user-images.githubusercontent.com/9875629/112700083-f55e6a00-8e52-11eb-9d7e-1ec3353d2d67.png">

Can yall add this as an extensibilty to the current provider? I want the ability to group by multiple tags, not just one.

**Comment by espey** [comment]
Oh I see if I add multiple group_by it works fine -- can you maybe add this to your documenation?

```
resource "datadog_logs_metric" "success" {
  name = "success"
  compute {
    aggregation_type = "count"
  }
  filter {
    query = "\"completed after\" service:tfe-test"
  }
  group_by {
    path = "@env"
    tag_name = "env"
  }
  group_by {
    path = "@region"
    tag_name = "region"
  }
  group_by {
    path = "@test"
    tag_name = "test"
  }
}
```

creates this in DD which is pefection:
<img width="1019" alt="Screen Shot 2021-03-26 at 5 14 30 PM" src="https://user-images.githubusercontent.com/9875629/112701623-c34f0700-8e56-11eb-9e7f-b5fa2294cda7.png">

**Comment by zippolyte** [comment]
The docs mention it's a block list already, but I've added one more block in the example to make it more apparent in #1010

**Comment by espey** [comment]
thank you @zippolyte
