### ISSUE TITLE
Feature Request: data source for latest log forwarder cloudformation template version

### ISSUE THREAD

**Issue by mikeknep** [DataDog/terraform-provider-datadog#1016]
### Historical context
We provisioned the log forwarder lambda via the public Cloudformation template using Terraform:

```terraform
resource "aws_cloudformation_stack" "datadog_forwarder" {
  # ...
  template_url = "https://datadog-cloudformation-template.s3.amazonaws.com/aws/forwarder/latest.yaml"
}
```

The problem with the configuration above is that Terraform cannot detect changes to the template as they are published and the "latest" tag moves from one version to the next—from Terraform's perspective, nothing about the `aws_cloudformation_stack` resource has changed.

Our security tooling clued us in to the fact that our provisioned forwarders were not identical across our several AWS accounts. They were provisioned at different times, and therefore using different versions.

### Current setup
We refactored our Terraform to this:

```terraform
locals {
  datadog_cloudformation_template_version = "3.30.0"
}

resource "aws_cloudformation_stack" "datadog_forwarder" {
  # ...
  template_url = "https://datadog-cloudformation-template.s3.amazonaws.com/aws/forwarder/${local.datadog_cloudformation_template_version}.yaml"
}
```
This yields two big benefits:
1. We maintain consistency across our accounts
2. We have a mechanism for updating the resource via Terraform as Datadog publishes new versions of the template

The downside is that we need to pay attention to Datadog's releases and manually update the local value as new versions are published. We'd like to stay up to date with the latest and greatest automatically.

### Desired future setup (feature request!)
It would be very cool if Datadog provided a data source that returned the latest version of the template. I'm imagining something like this:

```terraform
data "datadog_log_forwarder_cloudformation_template" "latest" {
  version = "latest"
}

resource "aws_cloudformation_stack" "datadog_forwarder" {
  # ...
  template_url = "https://datadog-cloudformation-template.s3.amazonaws.com/aws/forwarder/${data.datadog_log_forwarder_cloudformation_template.latest.semver_version}.yaml"
}
```

As far as I know, there isn't an API for this, so this would require some upstream changes.

### An alternative we attempted

The main alternative we attempted was using an HTTP data source to fetch the YML from the `https://...latest.yaml` link and add it to the `template_body` attribute of the `aws_cloudformation_stack` resource, as described in [this issue on the AWS provider](https://github.com/hashicorp/terraform-provider-aws/issues/13930), and demonstrated below:
```terraform
data "http" "datadog_cloudformation_template" {
  url = "https://datadog-cloudformation-template.s3.amazonaws.com/aws/forwarder/latest.yaml"
}

resource "aws_cloudformation_stack" "datadog_forwarder" {
  # ...
  template_body = data.http.datadog_cloudformation_template.body
}
```
Unfortunately, this does not work because the content-type of the response is `binary/octet-stream`, which Terraform does not handle properly; the error message during `terraform apply` is:
> Warning: Content-Type is not recognized as a text type, got "binary/octet-stream"
>
> If the content is binary data, Terraform may not properly handle the contents
> of the response.
>
> Do you want to perform these actions?
>   Terraform will perform the actions described above.
>   Only 'yes' will be accepted to approve.
>
>   Enter a value: yes
>
> aws_cloudformation_stack.datadog_forwarder: Creating...
>
> Error: configuration for aws_cloudformation_stack.datadog_forwarder still contains unknown values during apply (this is a bug in Terraform; please report it!)

**Comment by skarimo** [comment]
Hello, for your use case, you can do something along the lines of below. The response should also include links to the assets.

```
data "http" "example" {
  url = "https://api.github.com/repos/DataDog/datadog-serverless-functions/releases"
}

locals {
  forwarder_version = regex("[0-9]+.[0-9]+.[0-9]+", jsondecode(data.http.example.response_body)[0]["name"])
}
```

I think above should fit this use case so I will go ahead and close this issue but feel free to re-open if it does not. Thanks!
