### ISSUE TITLE
datadog_dashboard has broken / incorrect registry docs links for `request` elements

### ISSUE THREAD

**Issue by camlow325** [DataDog/terraform-provider-datadog#1024]
### Affected Resource(s)

-  datadog_dashboard

### Expected Behavior

Documentation for the `widget.change_definition.request.apm_query` element should be displayed.

### Actual Behavior

Documentation a different element under the `widget.change_definition.request` element is displayed, e.g., that for `widget.change_definition.request.show_present`. No documentation appears anywhere on the page for the `widget.change_definition.request.apm_query` element.

Not sure if this is a provider issue, a problem with the Terraform Registry itself, or something else?

### Steps to Reproduce

Click on the "below for nested schema" links under various `widget.X.request` sub-elements in the Terraform registry documentation for the `datadog_dashboard` resource. For example, click on the link for the `apm_query` element under [widget.change_definition.request](https://registry.terraform.io/providers/DataDog/datadog/latest/docs/resources/dashboard#nested-schema-for-widgetchange_definitionrequest).

**Comment by zippolyte** [comment]
Thanks for the report. There seem to be a bug with the documentation generation indeed. We'll look into it.

FWIW, the block documented is indeed for `apm_query` even though the title says `show_present` for some reason, so the link brings you to the correct section.
