### ISSUE TITLE
Way to disable Widget/group_definition on Timeboard

### ISSUE THREAD

**Issue by flavio-cadete-cko** [DataDog/terraform-provider-datadog#1033]
Feature request (I'm not finding this on documentation)
Would be awesome if we could disable or dynamically add which Widget/group_definition will show on Timeboard, so we could create some flexible modules that could be reused across services.

This old example, show on how to use with the old "datadog_timeboard" resource graph.
https://github.com/DataDog/terraform-provider-datadog/pull/232/files

How we can use the dynamic for graph/group_definition?

**Comment by zippolyte** [comment]
Hey @flavio-cadete-cko 

Can you please clarify what you want to do ? Dynamic blocks are supported exactly the same in the dashboard resource.

**Comment by flavio-cadete-cko** [comment]
Wanted to create a module to use within my team (maybe across group team) where we would hide/show the group_definition  depending on the modules params.

Looking to achieve 2 behaviors:

1. E.G. Application LB group  (param setting : show/**hide**, host name)

2. E.G. Business metrics (where the caller would specify a **list of queries**), then the module would have that dynamic blocks with an foreach to add widgets within Business Metrics group_definition .
etc...

Each Service would then specify which group_definition it wants for his service timeboard using the same module (e.g. not all service have ALB, Business metrics, Lambdas, SQS, etc...)

**Comment by zippolyte** [comment]
Ah so I think this can indeed be solved with dynamic blocks. Something like the following:

```hcl
variable "hide" {
  default = true
}

variable "queries" {
  default = ["avg:system.cpu.user{*}"]
}

resource "datadog_dashboard" "test" {
  title       = "Test"
  layout_type = "ordered"
  dynamic "widget" {
    # test the boolean var.hide to create a list with one or zero elements and thus conditionally show/hide a widget
    for_each = var.hide ? [0] : []
    content {
      group_definition {
        layout_type = "ordered"
        title       = "a dynamic group widget"
        dynamic "widget" {
          for_each = var.queries
          iterator = query
          content {
            timeseries_definition {
              request {
                q = query.value
              }
            }
          }
        }
      }
    }
  }
  widget {
    note_definition {
      content = "some default widget, always present"
    }
  }
}
```

Of course, just adapt that to your needs, this is just an example on how to use variables to create conditional dynamic blocks.

**Comment by flavio-cadete-cko** [comment]
Thanks, was wandering if there was any option from the datadog provider, but if the HCL language allows it will follow that approach. :D

**Comment by zippolyte** [comment]
Ah no the provider itself doesn't provide such feature directly. HCL is the way to go.
I'm closing this issue then, but feel free to reopen if you encounter any problem.
