### ISSUE TITLE
Support multiple result query from datadog_monitor data source

### ISSUE THREAD

**Issue by jcao02** [DataDog/terraform-provider-datadog#1042]
Hey there,

The specific use-case we are dealing with at Glovo is attempting to create a specific service SLOs from monitors that were created through terraform -- but in different/inaccessible modules -- and monitors that were created through DataDog UI.

A solution for this is to link the monitors through tags (e.g. `uptime-slo`) and use [datadog_monitor data source](https://registry.terraform.io/providers/DataDog/datadog/latest/docs/data-sources/monitor) to query them through `monitor_tags_filter` argument, but multiple results are not supported.

The current workaround is hard-coding these IDs, but it is not scalable and too error prone. Do you think is possible to provide support for this? Or do you have a better solution?

Thanks!

### Terraform Version

```
Terraform v0.13.6
```
### Affected Resource(s)

-   [datadog_monitor data source](https://registry.terraform.io/providers/DataDog/datadog/latest/docs/data-sources/monitor)

The use case is specifically when the data source query returns more than one monitor.

### Terraform Configuration Files

```hcl
data "datadog_monitor" "my_service_monitors" {
  monitor_tags_filter = ["uptime-slo", "service:my-service"]
}

resource "datadog_service_level_objective" "slo" {
  type = "monitor"
  name = "[my-service] Uptime SLOs"
  monitor_ids = data.datadog_monitor.my_service_monitors.*.id
  // ...
}
```

### Expected Behavior

Asuming the query `monitor_tags_filter = ["uptime-slo", "service:my-service"]` returns two monitors with ids `123456` and `789012`:

```bash
+ resource "datadog_service_level_objective" "slo" {
+       groups      = []
+       id          = "<SOME_ID>"
+       monitor_ids = [
+           123456,
+           789012,
+      ]
+      name        = "[my-service] Uptime SLOs"
+ }
```

### Actual Behavior

```bash
Error: your query returned more than one result, please try a more specific search criteria
```

### References

https://github.com/hashicorp/terraform/issues/10123

**Comment by zippolyte** [comment]
Hey, can you tell if the linked PR #1048  would work for your use case ?

**Comment by zippolyte** [comment]
The new data source basically exposes a `monitors` attribute, a list of the monitors that matched the filter, with a few attributes each: the monitor ID, name and type.

**Comment by jcao02** [comment]
Hey @zippolyte that seems to be exactly what we need. Just to confirm, the end API would be something like this?
```hcl
data "datadog_monitors" "my_service_monitors" {
  monitor_tags_filter = ["uptime-slo", "service:my-service"]
}

resource "datadog_service_level_objective" "slo" {
  type = "monitor"
  name = "[my-service] Uptime SLOs"
  monitor_ids = [for monitor in data.datadog_monitors.my_service_monitors.monitors: monitor.id]
  // ...
}
```

Thanks for taking care of this!

**Comment by zippolyte** [comment]
Yes exactly that would be how to use it !

**Comment by jcao02** [comment]
Thanks! Do you have an estimate for #1048 to be merged and released?

**Comment by zippolyte** [comment]
We should release a new version next week. We'll try to merge this before that.
