### ISSUE TITLE
datadog_integration_aws requires manual integration install through UI

### ISSUE THREAD

**Issue by russmac** [DataDog/terraform-provider-datadog#1046]
Apologies if there is an issue for this already as I couldn't find one.

### Terraform Version

Terraform v0.14.9
+ provider registry.terraform.io/datadog/datadog v2.25.0
+ provider registry.terraform.io/hashicorp/aws v3.36.0
+ provider registry.terraform.io/hashicorp/external v2.1.0
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0

### Affected Resource(s)

-   datadog_integration_aws

### Terraform Configuration Files

```hcl
resource "datadog_integration_aws" "datadog_integration" {
  account_id = data.aws_caller_identity.current.account_id
  role_name  = "${local.namespace}-dd-integration"
  host_tags  = ["namespace:*"]
  account_specific_namespace_rules = {
    auto_scaling = false
    opsworks     = false
  }
}
```

The initial configuration was fully deployed in another sandbox, With the manual step already done. However I have reduced it for this reproduction to just using the `datadog_integration_aws` resource in the workspace

### Debug Output
_This will have to do, No time to redact entire log._

https://gist.github.com/russmac/b5d8f6a43ccbefc2b76f892a97e1a78a

```
Error: error getting AWS integration: 400 Bad Request: {"errors": ["AWS Integration not yet installed. Please manually install it to add AWS accounts."]}
```

### Actual Behavior

Cannot provision account without manual steps.

A user must manually click "install" in the UI, which does the following;

- POST to `https://app.datadoghq.com/auth/generate_aws_external_id` a UI route without the require parameters of the documented same named public route which is `https://api.datadoghq.com/api/v1/integration/aws/generate_new_external_id`

- POST to `https://app.datadoghq.com/account/update_integration` with a full payload of the checkboxes associated params in the UI form the context of the install button. but still no `accounts` or role param. `{"accounts":[],"global_options":{........}`

### Expected Behavior

Full DR capability. :mechanic: 

_***edit** Not sure if the actual dd go client SDK requires the params or not._

I could be missing something here , however it seems the received API response and associated behavior is undocumented in the Terraform resource, API docs or AWS integration or at least very hard to find as I cannot find it myself.

Can anyone point me to some reference for the API that does include required/optional? https://docs.datadoghq.com/api/latest/aws-integration/ does not mention this.

### Steps to Reproduce

1. Attempt to create datadog_integration_aws as per DD provider doc 
2. Bad request on a GET reading current integration config. [see gist](https://gist.github.com/russmac/b5d8f6a43ccbefc2b76f892a97e1a78a)

_workaround_

3. Manually install through UI actions (POST to https://app.datadoghq.com/auth/generate_aws_external_id, https://app.datadoghq.com/auth/update_integration with no AWS required params the API route requires)
4. Create datadog_integration_aws as per DD provider doc 

### Important Factoids 

Can we just replicate the UI behavior with the public API route and omit the dd go sdk required params as a local-exec null resource with some trigger (using requests)? 

The API doc for the public route `https://api.datadoghq.com/api/v1/integration/aws/generate_new_external_id` doesn't actually list which params are required other then for AKID and SAKID

### References
https://docs.datadoghq.com/api/latest/aws-integration/
https://gist.github.com/russmac/b5d8f6a43ccbefc2b76f892a97e1a78a

**Comment by russmac** [comment]
@zippolyte Any help figuring out which API params are required and which aren't?

https://docs.datadoghq.com/api/latest/aws-integration/

**Comment by zippolyte** [comment]
I believe the only required attributes are `account_id` and `role_name` OR `access_key_id` and `secret_access_key` depending on your account type.

I'll see about improving the docs 👍
