### ISSUE TITLE
Allow disabling `silenced` via provider config

### ISSUE THREAD

**Issue by glasser** [DataDog/terraform-provider-datadog#1049]
We've found that when we manually mute a monitor managed via `datadog_monitor`, the next apply tends to unmute them because of the `silenced` attribute. We can add `lifecycle {  ignore_changes = [silenced] }` but we have to remember to do that for every monitor.

From the docs, it appears that you share our concern and are removing this attribute in the next major version. Great! Looking forward to it.

My question is: is the next major version likely to be released soon (or maybe there's even already some kind of prerelease)? If not, would you be interested in a patch that let us set something in our `provider` block that just means "just skip querying for `silenced` and keep it always empty"?

**Comment by zippolyte** [comment]
Hi,
The next major should be coming in the next few weeks. We don't have a pre-release yet, but we do have a branch `sdk-v2` on this repo which will be the base for the next major, if you would like to build it locally and test it out.

**Comment by zippolyte** [comment]
Version 3.0.0 has been released, it removes the silenced attribute.
Let us know if it doesn't work for you
