### ISSUE TITLE
Attributes not showing when trying to use it for root-resuable module structure

### ISSUE THREAD

**Issue by oldflame** [DataDog/terraform-provider-datadog#1050]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version

Terraform v0.15.0
on windows_amd64

### Affected Resource(s)

Please list the resources as a list, for example:

-   datadog_monitor

### Terraform Configuration Files
In my re-usable module, I have the following configuration for outputs after creating a datadog_monitor resource.
```hcl
output "datadog_monitor_names" {
  value       = values(module.datadog_monitor.monitor)[*].name
  description = "Names of the created Datadog monitors"
}

output "datadog_monitor_ids" {
  value       = values(module.datadog_monitor.monitor)[*].id
  description = "IDs of the created Datadog monitors"
}

output "datadog_monitors" {
  value       = module.datadog_monitor.monitor
  description = "Datadog monitor outputs"
}
```

In my root module, I have the following configuration for outputs after creating a datadog_monitor resource.
```hcl
output "datadog_monitor_names" {
  value       = values(datadog_monitor.monitor)[*].name
  description = "Names of the created Datadog monitors"
}

output "datadog_monitor_ids" {
  value       = values(datadog_monitor.monitor)[*].id
  description = "IDs of the created Datadog monitors"
}

output "datadog_monitors" {
  value       = datadog_monitor.monitor
  description = "Datadog monitor outputs"
}
```
This is the name of the reusable module.
```hcl
module "datadog_monitor" {
  source = ""
  datadog_monitors = var.datadog_monitors
  alert_tags = var.alert_tags
  datadog_app_key = var.datadog_app_key
  datadog_api_key = var.datadog_api_key
}
```
### Expected Behavior

https://gist.github.com/oldflame/2f4957f924417843ffb2fa49faff04e2

### Actual Behavior

https://gist.github.com/oldflame/18aec08a2c50795e39419d519d37fbed

**Comment by zippolyte** [comment]
It's hard to say for sure without the full module source, but it looks like you're not declaring outputs properly.

First of all, I don't think your reusable module `datadog_monitor` outputs should reference itself.

```hcl
output "datadog_monitor_names" {
  value       = values(module.datadog_monitor.monitor)[*].name
  description = "Names of the created Datadog monitors"
}
```
should instead be 
```hcl
output "datadog_monitor_names" {
  value       = values(datadog_monitor.monitor)[*].name
  description = "Names of the created Datadog monitors"
}
```
where `datadog_monitor` is the resource type (not the module name), and `monitor` is the name of your resource in your module.

Then in your root module, you should just be able to reference the outputs you declared in your child module:
```hcl 
output "datadog_monitor_names" {
  value       = module.datadog_monitor.datadog_monitor_names
  description = "Names of the created Datadog monitors"
}
```

**Comment by oldflame** [comment]
@zippolyte Thank you so much for such a prompt response. I realized this was a mistake that I committed. But even after following your resolution steps, I am still not able to get it working. If I just go the resource route, it creates the outputs just fine, but if via the root and reusable module structure, it fails. 
I have shown below how I my module is set up.

The resource block in the root module for the `datadog_monitor` named `monitor`
```hcl 
resource "datadog_monitor" "monitor" {
  name                = each.value.name
  type                = each.value.type
  query               = each.value.query
  message             = format("%s%s", each.value.message, var.alert_tags)
.
.
.
.

}
```
The outputs in the root module
```hcl 
output "datadog_monitor_names" {
  value       = values(module.datadog_monitor)[*].datadog_monitor_names
  description = "Names of the created Datadog monitors"
}

output "datadog_monitor_ids" {
  value       = values(module.datadog_monitor)[*].datadog_monitor_ids
  description = "IDs of the created Datadog monitors"
}

output "datadog_monitors" {
  value       = module.datadog_monitor.datadog_monitors
  description = "Datadog monitor outputs"
}
```
The reusable module `datadog_monitor` which uses the root module. 
```hcl 
module "datadog_monitor" {
  source = ""
  datadog_monitors = var.datadog_monitors
  alert_tags = var.alert_tags
}
```
The outputs in the reusable module 
```hcl 
output "datadog_monitor_names" {
  value       = values(datadog_monitor.monitor)[*].name
  description = "Names of the created Datadog monitors"
}

output "datadog_monitor_ids" {
  value       = values(datadog_monitor.monitor)[*].id
  description = "IDs of the created Datadog monitors"
}

output "datadog_monitors" {
  value       = datadog_monitor.monitor
  description = "Datadog monitor outputs"
}
```

If I try the above configuration I get the following error.
```
 Error: Reference to undeclared module
│
│   on .terraform\modules\datadog_monitor\datadog\monitors\outputs.tf line 2, in output "datadog_monitor_names":
│    2:   value       = values(module.datadog_monitor)[*].datadog_monitor_names
│
│ No module call named "datadog_monitor" is declared in module.datadog_monitor.
```

So, I changed the setup to the following in the root module. 
```hcl 
output "datadog_monitor_names" {
  value       = values(module.datadog_monitor)[*].name
  description = "Names of the created Datadog monitors"
}

output "datadog_monitor_ids" {
  value       = values(module.datadog_monitor)[*].id
  description = "IDs of the created Datadog monitors"
}

output "datadog_monitors" {
  value       = module.datadog_monitor
  description = "Datadog monitor outputs"
}
```
and get the following error
```
│ Error: Reference to undeclared resource
│
│   on outputs.tf line 7, in output "datadog_monitor_ids":
│    7:   value       = values(datadog_monitor.monitor)[*].id
│
│ A managed resource "datadog_monitor" "monitor" has not been declared in the root module.
╵
```

It would be great if you could help me here. I know this seems like I am doing something wrong and this isn't Stackoverflow, but I would really appreciate it if you could help me. Thanks!

**Comment by zippolyte** [comment]
Hey sorry, I've been away on holidays. Have you managed to sort this out ?
