### ISSUE TITLE
Error: could not find single user with email when recreating previously-deleted, non-validated user

### ISSUE THREAD

**Issue by finferflu** [DataDog/terraform-provider-datadog#1056]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version

0.13.7

### Affected Resource(s)

-   datadog_user

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files

```hcl
data "datadog_role" "standard" {
  filter = "Datadog Standard Role"
}

resource "datadog_user" "standard" {
  for_each = toset(var.users)

  email                = each.key
  roles                = [data.datadog_role.standard.id]
  send_user_invitation = var.send_user_invitation
}
```

### Debug Output

Can provide if needed.

### Expected Behavior

Terraform should have applied my configuration successfully.

### Actual Behavior

```sh
Error: could not find single user with email test@example.com

   with datadog_user.standard["test@example.com"],
   on users.tf line 19, in resource "datadog_user" "standard":
   19: resource "datadog_user" "standard" {
```

### Steps to Reproduce

1. `terraform apply`
2. Do not validate the user
2. `terraform destroy`
3. `terraform apply`

### Important Factoids

I am experiencing this in my automated tests, where I don't really care whether users are validated or not (hence `var.send_user_invitation` is a thing in my config). I believe I can mitigate this by randomly generating a new email each time in my tests, however, I think this issue might show in production at some point, where developers might add a user initially, then remove it before it gets validated, and subsequently add it back.

**Comment by zippolyte** [comment]
Hmm I cannot reproduce with the Datadog provider `0.25.0`. What version are you using ? 
Also can you provide the debug output as it will contain the detailed calls to the DD API ?
Thanks

**Comment by finferflu** [comment]
Hi @zippolyte, thanks for getting back to me. I have this in my `required_providers` block:

```hcl
    datadog = {
      source  = "DataDog/datadog"
      version = "~> 2.25.0"
    }
```

I assume you also meant `2.25.0`, rather than `0.25.0`?

In any case, I'll provide the debugging output as soon as I get back to it, thanks!

**Comment by zippolyte** [comment]
Yeah I meant `2.25.0` sorry 😅 
Looks good, but just for the sake of completeness, what's the entire output of `terraform version` ?

**Comment by zippolyte** [comment]
Hmm it doesn't list the version of the provider. Have you run it the folder of your terraform config ?

**Comment by finferflu** [comment]
Yes, that's where I ran it from, I don't think I've ever seen the provider listed with the `version` command...

**Comment by zippolyte** [comment]
Ah ok that's good then. Well the last thing we need to investigate further now are those debug logs, to try and see what happens exactly when the issue arises.

**Comment by finferflu** [comment]
I have revisited this today, and I was unable to replicate the issue. Could it be related to a Datadog server-side issue, rather than the Terraform provider?

**Comment by zippolyte** [comment]
It is definitely a possibility yes. Since it appears to not be an issue anymore, I'm going to close this. Feel free to reopen if it happens again.
