### ISSUE TITLE
Feature Request: Add RUM Application

### ISSUE THREAD

**Issue by ignas-sakalauskas-cko** [DataDog/terraform-provider-datadog#1058]
Hi there,

I find it super useful to have all the DataDog dashboards, monitors etc. in code and was wondering if it was possible to add RUM Application to Terraform provider as well?

Thanks!

**Comment by pderuiter** [comment]
Indeed, this would be a very convenient feature to have especially when you want to keep everything in code

**Comment by guisilva-cid** [comment]
It has my vote 👍

**Comment by andersro93** [comment]
This is a must have in our case if we are going to use Datadog. Hope that the devs can find time to prioritize this in their backlog. :+1:

**Comment by bsamsom** [comment]
This would be very useful to add so that we could manage all monitors via terraform configs.

**Comment by therve** [comment]
This has been done in #1537
