### ISSUE TITLE
Terraform Datadog Dashboard Issue

### ISSUE THREAD

**Issue by Yokeni** [DataDog/terraform-provider-datadog#1059]
Hi Team,

We have Terraform integration with Datadog and are seeing an issue when we execute the terraform plan for creating the Dashboard in Datadog.  It seems terraform does not support two fields which are supported by Datadog.

Issue:
 In Datadog when we create a Dashboard with note_definition widget type and import the json file we do see the two fields "vertical_align" and "has_padding" in it. However in terraform file if we include these fields we get an error when we run terraform plan command.

Error when "terraform plan" command is run:
An argument named "vertical_align" is not expected here. 
An argument named "has_padding" is not expected here. 

As mentioned in Datadog site the given fields are supported (refer Model section)
https://docs.datadoghq.com/dashboards/widgets/note/
Datadog json details example shows the field has_padding and vertical_align: 
{
  "background_color": "string",
  "content": "",
  "font_size": "string",
  "has_padding": false,
  "show_tick": false,
  "text_align": "string",
  "tick_edge": "string",
  "tick_pos": "string",
  "type": "note",
  "vertical_align": "string"
}

However in terraform dashboard page under "note_definiton" widget section, we do not see these fields:
https://registry.terraform.io/providers/DataDog/datadog/latest/docs/resources/dashboard

Example of note_definition widget on terraform site:
 widget {
    note_definition {
      content          = "note text"
      background_color = "pink"
      font_size        = "14"
      text_align       = "center"
      show_tick        = true
      tick_edge        = "left"
      tick_pos         = "50%"
    }
  }

Source/Version used in the terraform plan:
 source = "Datadog/datadog"
version = ">= 0.14.5"

As the fields are supported by Datadog, we expect it to be supported in terraform also. Can you please look into this issue.

Regards,
Yogesh

**Comment by therve** [comment]
Hello,

Both fields were added in #1044 and will be available in the next release which should happen next week. Thanks for your patience.

**Comment by therve** [comment]
0.14.0 is your terraform, you'll need to upgrade your terraform provider version (ought to be 2.25.0 today).

**Comment by Yokeni** [comment]
Hello,
Just need to check if the new release has happened. Also confirm if the terraform provider version will be 2.26.0 or something else

Regards,
Yogesh

**Comment by therve** [comment]
2.26.0 has been released, thanks.
