### ISSUE TITLE
Unable To Specify public_id for Synthetic API Test

### ISSUE THREAD

**Issue by aminsshahab** [DataDog/terraform-provider-datadog#1060]
### Terraform Version
Terraform v0.15.3

### Affected Resource(s)
datadog_synthetics_test

Hello, I am unable to specify a `public_id` for my Synthetic API Test. When I specify a `public_id`, I get the error:
`An argument named "public_id" is not expected here.`

When I specify an `id`, I get the error:
`invalid or unknown key: id`

According to the DataDog documentation, I should be able to specify a `public_id`
https://docs.datadoghq.com/api/latest/synthetics/

**Comment by therve** [comment]
Hello,

Can you provide a sample tf file? Synthetics resource doesn't have a `public_id`, it does have a `subtest_public_id` though :https://registry.terraform.io/providers/DataDog/datadog/latest/docs/resources/synthetics_test#nested-schema-for-browser_stepparams. Thanks.

**Comment by therve** [comment]
The doc has been updated to remove public_id as a parameter. Thanks.
