### ISSUE TITLE
 "active": this field cannot be set

### ISSUE THREAD

**Issue by flavio-cadete-cko** [DataDog/terraform-provider-datadog#1076]
on  2.26.1:
` "active": this field cannot be set`
 
what's the alternative to mute monitors "in-definitively" ?

**Comment by zippolyte** [comment]
It is done by not specifying an end time to your downtime

**Comment by lirlirlirlir** [comment]
Also on 2.26.1 getting the same error :

`Error: "active": this field cannot be set`  

Any ideas ?

**Comment by zippolyte** [comment]
The `active` field doesn't configure the end time of a downtime. It is a read only field that cannot be changed directly by the user, and so as been properly marked as so in the terraform schema.
Simply remove it from your terraform config.
