### ISSUE TITLE
Add dashboard_lists property to datadog_dashboard_json

### ISSUE THREAD

**Issue by mBouamama** [DataDog/terraform-provider-datadog#1078]
Let's add support for the field in the same fashion as datadog_dashboard.

**Comment by therve** [comment]
Hi,

The `datadog_dashboard` resource supports this via the `dashboard_lists` attribute, but not the `datadog_dashboard_json` one.

**Comment by mBouamama** [comment]
hi, thank for your replying
Do you have any solution ofr my problem? or i need to wait an enhancement?
Regards

**Comment by therve** [comment]
If you want to use the `datadog_dashboard_json`, you can use the `datadog_dashboard_list` resource to defined everything in terraform.

**Comment by mBouamama** [comment]
Hi, thank for your replying
Ok it's alternative but if i want to add my dashboard(`datadog_dashboard_json`) to a existing list, it's impossible as the moment?
it's possible to request an enhancement for this feature?If yes, how ?
Regards

**Comment by therve** [comment]
We'll track this here.

**Comment by mBouamama** [comment]
Thanks
