### ISSUE TITLE
Terraform throwing an error creating a "log alert" type datadog monitor.

### ISSUE THREAD

**Issue by svchandak** [DataDog/terraform-provider-datadog#1079]
Hi,

I am trying to create a log alert type monitor in datadog using terraform datadog provider.
I am looping over a JSON to get the resource attributes.

Please find attached the resources.json and main
[Terraform.zip](https://github.com/DataDog/terraform-provider-datadog/files/6538444/Terraform.zip)

.tf.

If I edit the remove the **env:${var.env}** from the query in json file, then the monitor is successfully works.

Below is the error I get

**Error: error validating monitor: 400 Bad Request: {"errors": ["The value provided for parameter 'query' is invalid: Invalid query: Check for invalid tags or facets in your query."]}

  on modules/monitors/lab_specific_monitors/main_json.tf line 5, in resource "datadog_monitor" "this":
   5: resource "datadog_monitor" "this" {**

**Comment by therve** [comment]
It most likely has to do with value in your `env` variable. For example the query will be invalid if `env` is empty. Let me know if that works for you.
