### ISSUE TITLE
Error: error getting dashboard: Required field height missing:

### ISSUE THREAD

**Issue by venthur** [DataDog/terraform-provider-datadog#1088]
Hi there,

I just changed an existing timeboard to the new dashboard. After trying to update the terraform config plan, I get this error on `terraform plan` and `terraform refresh`:

```
Error: error getting dashboard: Required field height missing: [dump of the whole dashboard]
```

### Terraform Version

Terraform v0.15.1
on linux_amd64
+ provider registry.terraform.io/datadog/datadog v2.26.1
+ provider registry.terraform.io/hashicorp/aws v3.37.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.1.0

Your version of Terraform is out of date! The latest version
is 0.15.4. You can update by downloading from https://www.terraform.io/downloads.html

### Affected Resource(s)

Please list the resources as a list, for example:
- datadog_dashboard

**Comment by therve** [comment]
Hello,

Can you provide a sample TF file? It looks like you're just missing a height attribute in your layout.

**Comment by venthur** [comment]
I've imported the plan using `terraform show ...`, and removed some `id`s so shouldn't that be a bug already? I can send you the file directly but would rather not publish it here.

**Comment by therve** [comment]
If you have private info please contact support. Thanks

**Comment by venthur** [comment]
How?

**Comment by therve** [comment]
You have the various options at https://www.datadoghq.com/support/, email should be good for sending data.

**Comment by dscullion365** [comment]
I'm having this exact same issue, coping a json from a dashboard and putting it into a datadog resource gives me this error on a terraform apply.

**Comment by therve** [comment]
Hello,

This should have been fixed in the backend. Thanks for your patience.
