### ISSUE TITLE
can't create Log Stream widget using datadog_dashboard resource

### ISSUE THREAD

**Issue by mikalai-t** [DataDog/terraform-provider-datadog#1089]
Hello.

### Terraform Version
`Terraform v0.12.29`

### Affected Resource(s)
- resource `datadog_dashboard`

### Terraform Configuration Files

```hcl
resource "datadog_dashboard" "my_dashboard" {
  title = "dashboard1"

  layout_type = "free"
  is_read_only = false

  template_variable {
    name    = "eks"
    prefix  = "cluster_name"
    default = local.default_eks_cluster_name
  }
  template_variable {
    name    = "app"
    prefix  = "kube_app_name"
    default = "app1"
  }
  template_variable {
    name    = "namespace"
    prefix  = "kube_namespace"
    default = var.env
  }

// ...

  widget {
    widget_layout {
      x = 72
      y = 14
      width = 70
      height = 96
    }
    log_stream_definition {
      title = "Application logs"
      title_size = 16
      title_align = "center"

      message_display = "inline"
      query = "pod_name:*$app.value* kube_namespace:$namespace.value container_name:(k8s?$app.value* OR $app.value*) cluster_name:$eks.value"
      show_date_column = false
      show_message_column = true

      sort {
        column = "time"
        order = "desc"
      }
    }
  }
}
```

### Debug Output
* none

### Panic Output
* none

### Expected Behavior
`Log Stream` widget must be created succesfully

### Actual Behavior
`Log Stream` widget cannot be created because of its `json` seems to be invalid:
![dashboard-log-stream-error](https://user-images.githubusercontent.com/20296197/120218822-f640bd00-c242-11eb-8c0a-fadc77c9c0b8.png)

- after copying dashboard `json` the following definition can be found:
```json
# ...
    {
      "id": 6066273857713436,
      "layout": {
        "x": 72,
        "y": 14,
        "width": 70,
        "height": 96
      },
      "definition": {
        "title": "Application logs",
        "title_size": "16",
        "title_align": "center",
        "type": "log_stream",
        "logset": "",
        "indexes": [],
        "query": "pod_name:*$app.value* kube_namespace:$namespace.value container_name:(k8s?$app.value* OR $app.value*) cluster_name:$eks.value",
        "sort": {
          "column": "time",
          "order": "desc"
        },
        "show_date_column": false,
        "show_message_column": true,
        "message_display": "inline"
      }
    }
# ...
```
notice deprecated field `logset` and absence of empty `columns` field.

- if widget was created manually from the Datadog console it contains following `.json` snippet:
```json
    {
      "id": 1540744011746278,
      "layout": {
        "x": 72,
        "y": 14,
        "width": 70,
        "height": 96
      },
      "definition": {
        "title": "Logs",
        "title_size": "16",
        "title_align": "center",
        "type": "log_stream",
        "indexes": [],
        "query": "pod_name:*$app.value* kube_namespace:$namespace.value container_name:(k8s?$app.value* OR $app.value*) cluster_name:$eks.value",
        "sort": {
          "column": "time",
          "order": "desc"
        },
        "columns": [],
        "show_date_column": false,
        "show_message_column": true,
        "message_display": "inline"
      }
    },
```
notice absence of the deprecated `logset` field and presence of empty `columns` one

### Steps to Reproduce
1. Configure Datadog provider
2. Implement a `datadog_dashboard` resource code with `Log Stream` widget
3. Run `terraform apply`

### Important Factoids
- Datadog provider version: **2.26.1**
- adding `columns = []` to the resource definition didn't help

### References
didn't find any

---
Thank you!

**Comment by zippolyte** [comment]
Hi ! This issue is fixed on master, which we'll release very soon. This will be released as a major version of the provider 3.0.0, so hopefully that will work for you. Here is a [changelog](https://github.com/DataDog/terraform-provider-datadog/pull/1085/files) of the version for details on what changes you can expect with the release.

**Comment by mikalai-t** [comment]
Great. Thank you for the quick response!

**Comment by billietlsfeir** [comment]
Hi,
I am facing this issue even though I am using the provider at version 3.1. Has this been fixed or has this issue come back since ?

**Comment by zippolyte** [comment]
Ah indeed the logset attribute has been removed, but the columns one is still missing.
Thanks for reporting
