### ISSUE TITLE
Unable to set datadog_synthetics_test resource severity

### ISSUE THREAD

**Issue by bcouto** [DataDog/terraform-provider-datadog#1090]
Hi there,

### Terraform Version

Terraform v0.15.0
on darwin_amd64
+ provider registry.terraform.io/datadog/datadog v2.26.1

### Affected Resource(s)

-   datadog_synthetics_test

### Terraform Configuration Files

```hcl
resource "datadog_synthetics_test" "api_check" {
    for_each = toset( var.api_check_domains )

    status  = "live"
    name    = "API https://${each.key}/ is DOWN"
    message = "Health Check on https://${each.key} is failing, *please check it IMMEDIATELY*."

    type    = "api"
    subtype = "http"

    priority = 2

    request_definition {
        method = "GET"
        url    = "https://${each.key}"
    }

    assertion {
        type     = "statusCode"
        operator = "is"
        target   = "200"
    }

    assertion {
        type     = "responseTime"
        operator = "lessThan"
        target   = "3000"
    }

    locations = [
        "aws:ap-southeast-1",
        "aws:sa-east-1",
    ]

    options_list {
        tick_every = 300
        min_failure_duration = 60

        retry {
            count    = 3
            interval = 60000
        }

        monitor_options {
            renotify_interval = 0
        }
    }
}
```

### Expected Behavior

What should have happened?

I should have been able to set the datadog_synthetics_test severity by the priority argument in the same way it's possible to set for the datadog_monitor resource.

https://registry.terraform.io/providers/DataDog/datadog/latest/docs/resources/monitor
https://registry.terraform.io/providers/DataDog/datadog/latest/docs/resources/synthetics_test
<img width="1522" alt="Screen Shot 2021-05-31 at 18 35 45" src="https://user-images.githubusercontent.com/119095/120244044-8ed53e00-c23f-11eb-9488-45cca32cbe25.png">

### Actual Behavior

│ Error: Unsupported argument
│
│   on synthetics.tf line 13, in resource "datadog_synthetics_test" "api_check":
│   13:     priority = 2
│
│ An argument named "priority" is not expected here.

### Steps to Reproduce

1. `terraform plan`

### References

**Comment by romainberger** [comment]
This was fixed by https://github.com/DataDog/terraform-provider-datadog/pull/1104 with the `monitor_priority` field.

**Comment by bcouto** [comment]
Thx a lot @romainberger and @zippolyte for adding the requested feature. It will be very helpful for all users!  🙂
