### ISSUE TITLE
datadog_logs_index resource does not support num_retention_days and daily_limit fields

### ISSUE THREAD

**Issue by mgarstecki** [DataDog/terraform-provider-datadog#1097]
### Terraform Version

Terraform v0.14.7

### Affected Resource(s)

Please list the resources as a list, for example:

-   datadog_logs_index

### Terraform Configuration Files

```hcl
terraform {
  required_version = "~> 0.14.0"
  required_providers {
    datadog = {
      source = "DataDog/datadog"
    }
  }
}

resource "datadog_logs_index" "sample_index" {
  name = "your index"
  filter {
    query = "*"
  }

  num_retention_days = 7

  daily_limit = 2000000
}
```

### Expected Behavior

The resource plans-applies without errors and the `num_retention_days` and `daily_limit` fields are set on the associated index.

### Actual Behavior

Doesn't plan, the fields are not available in the schema for the resource.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Nothing much, I think the fields should map cleanly to the ones provided in the API : https://docs.datadoghq.com/fr/api/latest/logs-indexes/#create-an-index

**Comment by skarimo** [comment]
Resolved by: https://github.com/DataDog/terraform-provider-datadog/pull/1083

Should be available in the next release.
