### ISSUE TITLE
datadog_logs_custom_pipeline does not support enrichment table lookup pipelines.

### ISSUE THREAD

**Issue by Shadow6363** [DataDog/terraform-provider-datadog#1098]
### Terraform Version
`v0.14.3`

### Affected Resource(s)
-   `datadog_logs_custom_pipeline`

### What and why?
The Datadog UI supports using an "Enrichment Table" as a log pipeline lookup processor table.
![image](https://user-images.githubusercontent.com/70018/120708468-75ff9f00-c470-11eb-81f3-b40f3a2673cf.png)

The Terraform resource does _not_ currently support enrichment tables in lookup processors.

Unfortunately, all of our Datadog log pipelines are Terraformed and to avoid state drift, we can't support people using enrichment tables until the Terraform resource supports them.

**Comment by ebarti** [comment]
Adding myself to the thread as I am having issues as well & would be great to provision pipelines as code with enrichment tables setup

**Comment by jmoyano-koa** [comment]
+1 to this request. Its a key feature for us right now.

**Comment by jbl-proglove** [comment]
Are there any updates or even an ETA on this one? This would allow us to finally remove the last remaining piece of mouse-managed log processing.

**Comment by nkzou** [comment]
Closed by #1800 , enrichment tables have been changed to reference tables. The functionality will be available in the next release (v3.23.0) within the next week.
