### ISSUE TITLE
[v2.25.0] Import dashboard: missing

### ISSUE THREAD

**Issue by chengchengmu** [DataDog/terraform-provider-datadog#1139]
Hi there,

We just noticed some missing field in a toplist widget. The impacted widget has conditional_formats whereas some other without conditional_formats are successfully imported.

More info:

### Terraform Version

`v0.14.11` and `1.0.1` (latest)
datadog provider version: `v2.25.0`
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

### Affected Resource(s)

-   datadog_dashboard

### Terraform Configuration Files

N/A for `terraform import`

### Debug Output

This log contains API key. Unsure if it anything else that is secret. Would like to share once it is confirmed.

### Panic Output

N/A

### Expected Behavior

The imported widget should contain the query information.

<details>
  <summary>This is the corresponding json file by exporting the dashboard via GUI</summary>

```
{
    "requests": [
        {
            "conditional_formats": [
                {
                    "comparator": "<",
                    "palette": "white_on_green",
                    "value": 70
                },
                {
                    "comparator": ">",
                    "palette": "white_on_red",
                    "value": 91
                },
                {
                    "comparator": ">",
                    "palette": "white_on_yellow",
                    "value": 71
                }
            ],
            "formulas": [
                {
                    "formula": "100 * query1 / query2",
                    "limit": {
                        "count": 10,
                        "order": "desc"
                    }
                }
            ],
            "queries": [
                {
                    "aggregator": "avg",
                    "data_source": "metrics",
                    "name": "query1",
                    "query": "max:docker.cpu.usage{ecs_container_name:datadog-agent,$flavor} by {instance-type}"
                },
                {
                    "aggregator": "avg",
                    "data_source": "metrics",
                    "name": "query2",
                    "query": "max:docker.cpu.limit{ecs_container_name:datadog-agent,$flavor} by {instance-type}"
                }
            ],
            "response_format": "scalar"
        }
    ],
    "title": "Top list of CPU usage per instance type in percentage",
    "title_align": "left",
    "title_size": "16",
    "type": "toplist"
}
```
</details>

### Actual Behavior

The imported widget is missing all the query/formula information.
<details>
  <summary>This is the imported terraform snippet</summary>
  
  ```
            widget {
                layout = {}

                toplist_definition {
                    time        = {}
                    title       = "Top list of CPU usage per instance type in percentage"
                    title_align = "left"
                    title_size  = "16"

                    request {

                        conditional_formats {
                            comparator = "<"
                            hide_value = false
                            palette    = "white_on_green"
                            value      = 70
                        }
                        conditional_formats {
                            comparator = ">"
                            hide_value = false
                            palette    = "white_on_red"
                            value      = 90
                        }
                        conditional_formats {
                            comparator = ">"
                            hide_value = false
                            palette    = "white_on_yellow"
                            value      = 71
                        }
                    }
                }

                widget_layout {
                    height = 2
                    width  = 4
                    x      = 4
                    y      = 0
                }
            }
  ```
</details>

### Steps to Reproduce

Steps to reproduce:

1. `Create a dashboard via GUI`, create a top_list widget with conditional_format
2. Run `terraform import` to import the dashboard into terraform code, e.g. `terraform import -state=prod.tfstate -var-file=prod.tfvars datadog_dashboard.my_dashshboard x46-vtq-ab9` (id. and dashboard names have been changed for the example)

### Important Factoids

Are there anything atypical about your accounts that we should know? No

Also tried with latest version of datadog terraform provider, and it gives the following error while import the dashboard:
<details>
<summary>Import error with latest datadog terraform provider (3.1.2.)</summary>

```
│ Error: ConflictsWith
│
│   with datadog_dashboard.my_dashboard,
│   on dashboard.tf line 20, in resource "datadog_dashboard" "my_dashboard":
│   20:     is_read_only     = false
│
│ "is_read_only": conflicts with restricted_roles
╵
╷
│ Error: ConflictsWith
│
│   with datadog_dashboard.my_dashboard,
│   on dashboard.tf line 24, in resource "datadog_dashboard" "my_dashboard":
│   24:     restricted_roles = []
│
│ "restricted_roles": conflicts with is_read_only
```
</details>

**Comment by zippolyte** [comment]
Can you try to upgrade to [2.26.0](https://github.com/DataDog/terraform-provider-datadog/releases/tag/v2.26.0) at least ?
Support for formulas and functions in toplist widget has been added there.

**Comment by chengchengmu** [comment]
2.26.1 works.
Thank you @zippolyte  !
