### ISSUE TITLE
Datadog terraform not able to read new keywords like formulas, name 

### ISSUE THREAD

**Issue by surajtikoo** [DataDog/terraform-provider-datadog#1162]
Hi Team,

We are facing an issue while building our terraform which we wrote to create the dashboards

### Terraform Version 
The current version of terraform is - v1.0.2  and the plugin version v3.0.0

### Affected Resource(s)
We are not able to create the resource due to the formula, name and scaler error 
widget {

        widget_layout {

          x      = 8

          y      = 30

          width  = 8

          height = 6

        }

        query_value_definition {

 #         title        = ""

          title_size   = "16"

          title_align  = "left"

          request {

          #  formula    = timeshift(query1, -172800)

          #  response_format = "scalar"

            q          = "avg:vfde.cdh.datalosscheck.total_exp_record{datalosschecktable:recon-stats-cancellation}"

          #  datasource = "metrics"

          #  name       = "query1"

            aggregator = "last"

          }

          autoscale    = false

          precision    = 0

        }

      }
Please list the resources as a list, for example:

-   opc_instance
-   opc_storage_volume

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### Debug Output

Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output

If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior

What should have happened?

### Actual Behavior

What actually happened?

### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:

1. `terraform apply`

### Important Factoids

Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

### References

Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:

-   GH-1234

**Comment by zippolyte** [comment]
Your widget definition is wrong. It should look something more like the following. See `formula` and `query` in https://registry.terraform.io/providers/DataDog/datadog/latest/docs/resources/dashboard#nestedblock--widget--query_value_definition--request

```terraform
  widget {
    widget_layout {
      x = 8
      y = 30
      width = 8
      height = 6
    }

    query_value_definition {
      title_size = "16"
      title_align = "left"
      request {
        formula {
          formula_expression = "timeshift(query1, -172800)"
        }

        query {
          metric_query {
            query = "avg:system.cpu.user{*}"
            data_source = "metrics"
            name = "query1"
            aggregator = "last"
          }
        }
      }

      autoscale = false
      precision = 0
    }
  }
```
