### ISSUE TITLE
Downtime Start cannot be in the past

### ISSUE THREAD

**Issue by adam-birch-cko** [DataDog/terraform-provider-datadog#1169]
Hi there,

We're attempting to use the `datadog_downtime` provider. However, when using the `rrule` functionality, a `start`/`end` must be specified. The `parent_id` functionality allows for further changes to be run without impacting the downtime. Yet, the impact comes should you wish to tear down the environment and apply from new. As you would receive `API error 400 Bad Request: {"errors":["Scheduled downtime start cannot be in the past"]}`

We have attempted a possible solution to calculate the `start` value relative to `timestamp` and ignoring once created, but this requires a ternary abomination, which is definitely not maintainable.

I realise such a similar issue has been raised before as referenced, although the introduction of the `rrule` has helped. The issue of the start time being in the future still remains.

Is there any plan to address this?

### Terraform Version

`Terraform v0.13.5`

### References
- [Downtime](https://www.terraform.io/docs/providers/datadog/r/downtime.html)
- [Related issue](https://github.com/DataDog/terraform-provider-datadog/issues/393#issuecomment-781308073)

**Comment by therve** [comment]
This should have been fixed in #1811 , let us know if you're still encountering the issue. Thanks.

**Comment by therve** [comment]
Hi,

Depending on how you build your timeoffset object that can still happen. Please open another bug to track it, thanks.

**Comment by pavlo-kheylyk** [comment]
still with us, version 3.59.1
