### ISSUE TITLE
datadog_monitor `new_host_delay` is a deprecated parameter, and does not work well

### ISSUE THREAD

**Issue by chroju** [DataDog/terraform-provider-datadog#1183]
### Terraform Version

```
Terraform v1.0.5
on darwin_amd64
+ provider registry.terraform.io/datadog/datadog v3.2.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
```

### Affected Resource(s)

-   datadog_monitor

### Terraform Configuration Files

```hcl
resource "datadog_monitor" "sample" {
  name           = "sample"
  type           = "query alert"
  query          = "sample"
  message        = "sample"
  new_host_delay = 600

  monitor_thresholds {
    critical = 1
  }
}
```

### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior

`new_host_delay` is already deprecated. [Datadog Docs](https://docs.datadoghq.com/api/latest/monitors/#create-a-monitor) recommends using `new_group_delay` instead. So, I expect to be able to use `new_host_delay` as well as `new_group_delay` . It is expected to set the config shown in the screenshot below.

![image](https://user-images.githubusercontent.com/4526869/130221490-c9f454e1-6716-4d6e-8cd6-2f3cfa686af1.png)

### Actual Behavior

I don't know how `new_host_delay` works.

* No matter what value I apply, the value in the above screenshot will remain the same.
* If I manually set the value in the above screenshot, Terraform will assume it is `0` and try to change it, no matter what the actual value is.

```
  # datadog_monitor.sample will be updated in-place
~ resource "datadog_monitor" "sample" {
        id                  = "20142033"
        name                = "sample"
      ~ new_host_delay      = 0 -> 300
        # (14 unchanged attributes hidden)

        # (2 unchanged block hidden)
    }
```

### Steps to Reproduce

1. `terraform plan`
1. `terraform apply`
1. You see the value in GUI is not changed.
1. You manually set the value in GUI.
1. `terraform plan`
1. You see the diff about `new_host_delay`. `0 -> 300` .

### Important Factoids

N/A

### References

Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:

-   GH-1234

**Comment by zippolyte** [comment]
Hi, this is going to be fixed in the linked PR
