### ISSUE TITLE
[Feature request] Please provide a native JSON object to use in dashboards

### ISSUE THREAD

**Issue by ardrigh** [DataDog/terraform-provider-datadog#1192]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version

Terraform 1.0.2

### Affected Resource(s)

Please list the resources as a list, for example:

-   datadog_dashboard
-   datadog_dashboard_json

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files

```hcl
resource "datadog_dashboard_json" "dart_dashboard" {
  dashboard = <<EOF
{
}
EOF
}
```

### Expected Behavior

`datadog_dashboard_json` should be a native json object.

### Actual Behavior

JSON is a string.

### Steps to Reproduce

Try using `datadog_dashboard_json` 

### Important Factoids

The Terraform AWS provider has a nice clean way of using JSON via a data source. This removes the need for HEREDOC style start and end lines.  And it makes the code easier to read and maintain.

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/iam_policy_document

https://learn.hashicorp.com/tutorials/terraform/aws-iam-policy shows example of usage.

It would be good if the Datadog provider could add a similar method to add and validate JSON, then it will also be easier for our tools to generate the JSON without the need to check for `EOF` style markers.

**Comment by therve** [comment]
Hi,

Could you use `jsonencode`  to turn your JSON object into a string? Thanks.

**Comment by therve** [comment]
I don't really understand this FR. The `iam_policy_document` datasource would just look like the `datadog_dashboard` resource to me.

You can also generate files to be able to not care about EOF markers. 

Feel free to reopen with more information, thanks.
