### ISSUE TITLE
Cryptic error when increasing monitor critical threshold value

### ISSUE THREAD

**Issue by mikegeoffrey** [DataDog/terraform-provider-datadog#1202]
Hi there,

### Terraform Version

v1.0.1

### Affected Resource(s)

Please list the resources as a list, for example:

-   datadog_monitor

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files

```hcl
...
monitor_thresholds {
    warning  = 1
    ok       = 2
    critical = 3
  }
...
monitor_thresholds {
    warning  = 3
    ok       = 3
    critical = 5
  }

```

### Debug Output

```
│ Error: error validating monitor: 400 Bad Request: {"errors": ["Last field should be larger than or equal to max threshold defined in monitor options"]}
```

### Panic Output

If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior

I expect the critical threshold to be increased to 5, or any value assuming threshold values can be greater than 5.

### Actual Behavior

Error: │ Error: error validating monitor: 400 Bad Request: {"errors": ["Last field should be larger than or equal to max threshold defined in monitor options"]}

### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:

1. Create monitor with the first monitor_thresholds block.
2. Apply
3. Change monitor_thresholds block to the second block given above
4. Apply - errors

### Important Factoids

Datadog tf provider 2.20.0

### References

Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:

-   GH-1234

**Comment by zippolyte** [comment]
Hi,

Can you provide more details of your monitor definition ? Like the query for instance, the type of monitor, etc...
The full resource configuration would be best.

**Comment by therve** [comment]
This is unfortunately a backend error, so we can't really do anything about that one.

**Comment by k0t3n** [comment]
@mikegeoffrey your `count` in query seems to be too small
> count must be at greater than or equal to your max threshold (defined in the options). It is limited to 100. For example, if you’ve specified to notify on 1 critical, 3 ok, and 2 warn statuses, count should be at least 3.

https://docs.datadoghq.com/api/latest/monitors/#create-a-monitor
