### ISSUE TITLE
Feature Request: Add support for SAML Mappings API

### ISSUE THREAD

**Issue by michelzanini** [DataDog/terraform-provider-datadog#1209]
Hi,

Would be good to have resources to be able to manage the Federated Authentication to Role Mapping API.
This is the SAML attributes to role mappings available in the UI here https://datadoghq.eu/access/mappings.

And in the API documentation available here
https://docs.datadoghq.com/account_management/authn_mapping/?tab=example#requests

Would be good to have a resource for the mapping (supporting Terraform's lifecycle for create, update, delete).
Also, possibly a resource to enable/disable mappings support.

Thanks.

**Comment by therve** [comment]
That was done in #1358 , thanks.
