### ISSUE TITLE
Two queries using the same `max(last_15):max:` config produce different threshold types

### ISSUE THREAD

**Issue by zsolt-p** [DataDog/terraform-provider-datadog#1218]
Hello,

I've built a composite monitor and its two individual metric alerts shown below. The composite monitor goes in alert state when our RabbitMQ queues have `>100` messages and the ack rate is `<=0`, i.e. when there are messages in my queues but they aren't being processed. 

Problem: I created the below two monitors and the composite monitor works for the most part. The only issue I have is that one of them goes gets its threshold configured as the type `at least once` instead of `at all times`. This leads to occasional false alarms. I could edit the monitors by hand and the false alarms do go away, but I'd like to understand if I'm doing anything wrong in the TF definition, or what may be the reason for my monitors getting configured differently?

### Terraform Version

```
Terraform v1.0.0
on linux_amd64
```

### Affected Resource(s)

- `datadog_monitor`

### Terraform Configuration Files

```hcl
resource "datadog_monitor" "rabbitmq_queue_not_empty_silent" {
  name           = "RMQ queue is not empty"
  type           = "metric alert"
  priority       = 5
  message        = ""
  include_tags   = false
  notify_no_data = false
  notify_audit   = true
  locked         = true
  tags           = ["type:rabbitmq", "created_by:terraform", "env:${terraform.workspace}"]
  query          = "max(last_15m):max:rabbitmq.queue.messages{project:${var.project},cluster-name:${var.cluster}} by {rabbitmq_queue} > 100"

  monitor_thresholds {
    critical = 100
  }

  lifecycle {
    ignore_changes = [silenced, restricted_roles]
  }
}

resource "datadog_monitor" "rabbitmq_queue_msg_ack_rate_zero_silent" {
  name           = "RMQ msg ack rate is 0"
  type           = "metric alert"
  priority       = 5
  message        = ""
  include_tags   = false
  notify_no_data = false
  notify_audit   = true
  locked         = true
  tags           = ["type:rabbitmq", "created_by:terraform", "env:${terraform.workspace}"]
  query          = "max(last_15m):max:rabbitmq.queue.messages.ack.rate{project:${var.project},cluster-name:${var.cluster}} by {rabbitmq_queue} <= 0"

  monitor_thresholds {
    critical = 0
  }

  lifecycle {
    ignore_changes = [silenced, restricted_roles]
  }
}
```

### Expected Behavior

Both above monitors should be created with the queries using the same threshold condition type (not sure what this is called), i.e. `at all times` 

### Actual Behavior

`rabbitmq_queue_msg_ack_rate_zero_silent` is created with the desired `at all times` threshold condition type, but the other one, 
`rabbitmq_queue_not_empty_silent` is created with the threshold condition type `at least once`

### Steps to Reproduce

`terraform apply`

**Comment by zippolyte** [comment]
Hi,
The reason this happens is because you use the same time aggregator (i.e. `max(last_15m)`) for both queries, but the conditions are opposites (`>` vs `<=`).
To get the same `at all times`, you need to use `min(last_15m)` for the query of queue not empty.

Does this make sense ?

**Comment by zsolt-p** [comment]
@zippolyte thank you for your answer, yes it makes total sense 🤦‍♂️ I completely misinterpreted what `max` meant here.
