### ISSUE TITLE
group_definition not supported for datadog_dashboard

### ISSUE THREAD

**Issue by kayman-mk** [DataDog/terraform-provider-datadog#1225]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version

terraform version 1.0.8

### Affected Resource(s)

Please list the resources as a list, for example:

-   datadog_dashboard

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    datadog = {
      source  = "DataDog/datadog"
      version = ">= 3.2.0"
    }
  }

  required_version = ">= 0.13"
}

provider "datadog" {
  api_key = "my_api_key"
  app_key = "my_app_key"
  api_url = "https://api.datadoghq.eu/"

  validate = true
}

resource "datadog_dashboard" "base_price_calculation" {
  title       = "Minimal Example"
  description = "TBD"
  layout_type = "free"

  widget {
    group_definition {
      layout_type = "ordered"
      title       = "Group Widget"

      widget {
        note_definition {
          content          = "cluster note widget"
          background_color = "pink"
          font_size        = "14"
          text_align       = "center"
          show_tick        = true
          tick_edge        = "left"
          tick_pos         = "50%"
        }
      }

      widget {
        alert_graph_definition {
          alert_id  = "123"
          viz_type  = "toplist"
          title     = "Alert Graph"
          live_span = "1h"
        }
      }
    }
  }
}
```

### Debug Output

https://gist.github.com/kayman-mk/773e1c8527d2b545ec4318fa71dbc5aa

### Panic Output

No crash.log file available

### Expected Behavior

Create a new dashboard with a widget group + 2 widget within that group. The example above is from the Datadog provider documentation.

### Actual Behavior

`terraform apply` fails with

```
│ Error: error creating dashboard from https://api.datadoghq.eu/api/v1/dashboard: 400 Bad Request: {"errors": ["Invalid widget at position 0 of type group. Error: Unsupported widget type 'group'."]}
│
│   with datadog_dashboard.base_price_calculation,
│   on main.tf line 20, in resource "datadog_dashboard" "base_price_calculation":
│   20: resource "datadog_dashboard" "base_price_calculation" {
│
```

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

### Important Factoids

None

### References

I didn't found any.

**Comment by skarimo** [comment]
Hi, the group widget type is supported for timeboards(`layout_type = "ordered"`) only and cannot be used with screenboards (`layout_type = "free"`)
