### ISSUE TITLE
Crash in reflect.Value.MethodByName when reading synthetics browser test

### ISSUE THREAD

**Issue by igin** [DataDog/terraform-provider-datadog#1228]
### Terraform Version

```
Terraform v1.0.8
on linux_amd64
+ provider registry.terraform.io/datadog/datadog v3.4.0
```

### Affected Resource(s)

-   datadog_synthetics_test

### Terraform Configuration Files

https://gist.github.com/igin/86de2ab6b53a93b16cc0f71d65c2cb94 (removed element descriptors for privacy reasons)

### Panic Output

https://gist.github.com/igin/5b88bba01d3210c8f6b55d3bdb5fb377

### Expected Behavior

Provider should read the state of the existing synthetic test in the next plan.

### Actual Behavior

Provider tries to read the state of the existing synthetic test and crashes.

### Steps to Reproduce
1. `terraform apply`
2. `terraform plan`

**Comment by skarimo** [comment]
Closing this issue. Feel free to re-open if the behavior is still occurring. Thanks!
