### ISSUE TITLE
Documentation on DD plugin page is cropped

### ISSUE THREAD

**Issue by NersesAM** [DataDog/terraform-provider-datadog#1236]
If you navigate to https://registry.terraform.io/providers/DataDog/datadog/latest/docs/resources/dashboard#optional and click the link to navigate to schema for `template_variable` it doesn't work.
![image](https://user-images.githubusercontent.com/1935500/137281586-394716b3-aa75-49f2-bf70-68649a1b4221.png)

It is because the documentation on that page is somehow cropped. If you navigate to the bottom of the page you can see that 
![image](https://user-images.githubusercontent.com/1935500/137281896-4e02b25a-4f1f-4cf2-9056-af2f2a72699b.png)

**Comment by therve** [comment]
There is now a workaround, I don't think we'll get anything better.
