### ISSUE TITLE
Using datadog_security_monitoring_default_rule gives argument error

### ISSUE THREAD

**Issue by bradleyfrank** [DataDog/terraform-provider-datadog#1243]
### Terraform Version

Terraform v0.14.7

### Affected Resource(s)

-   datadog_security_monitoring_default_rule

### Terraform Configuration Files

```hcl
variable "project" {
  type = string
}

variable "region" {
  type = string
}

provider "google" {
  project = var.project
  region  = var.region
}

provider "datadog" {
  api_key = local.dd_api_key
  app_key = local.dd_app_key
}

data "vault_generic_secret" "datadog_keys" {
  path = "secret/${var.project}/terraform/datadog-security-monitor"
}

locals {
  dd_api_key = data.vault_generic_secret.datadog_keys.data.api-key
  dd_app_key = data.vault_generic_secret.datadog_keys.data.app-key
}

data "datadog_security_monitoring_rules" "dd_default_rule" {
  default_only_filter = true
}

resource "datadog_security_monitoring_default_rule" "dd_default_rule" {
  rule_id = data.datadog_security_monitoring_rules.dd_default_rule.id
  enabled = false
}
```

### Debug Output

Debug output: https://gist.github.com/bradleyfrank/b27fd7ee437e284f46caa3a502a82de1

### Expected/Actual Behavior

I expected a successful Terraform init/plan. I believe I have followed the docs at https://registry.terraform.io/providers/DataDog/datadog/latest/docs/resources/security_monitoring_default_rule but `rule_id` or variation there of all produce the error:

`An argument named "rule_id" is not expected here.`

### Steps to Reproduce

I ran a `terraform init` and `terraform plan`.

### Important Factoids

Tried to import first as implied by the note at the bottom of the page:

```
% terraform import datadog_security_monitoring_default_rule.dd_default_rule <rule_id>
datadog_security_monitoring_default_rule.dd_default_rule: Importing from ID "<rule_id>"...
datadog_security_monitoring_default_rule.dd_default_rule: Import prepared!
  Prepared datadog_security_monitoring_default_rule for import
datadog_security_monitoring_default_rule.dd_default_rule: Refreshing state... [id=<rule_id>]

Error: 404 Not Found
```

### References

Could not find any open or closed issues that matched this error.

**Comment by therve** [comment]
Hi,

The doc is wrong, I created a PR to fix it. Note that you can't create a default rule resource, you have to import it. Thanks.
