### ISSUE TITLE
[Feature Request] Support Metrics without Limits

### ISSUE THREAD

**Issue by hanikesn** [DataDog/terraform-provider-datadog#1259]
Metrics without Limits seems to be [GA](https://www.datadoghq.com/blog/metrics-without-limits/) now and support via Terraform would be greatly appreciated. Happy to bring this up with our Account Manager as well if that helps prioritization.

### Affected Resource(s)

Please list the resources as a list, for example:

-   datadog_metric_tag_configuration

### References

https://docs.datadoghq.com/metrics/metrics-without-limits/
https://docs.datadoghq.com/api/latest/metrics/#update-a-tag-configuration

**Comment by skarimo** [comment]
Hi does the current `datadog_metric_tag_configuration` resource fit your use case? https://registry.terraform.io/providers/DataDog/datadog/latest/docs/resources/metric_tag_configuration

**Comment by hanikesn** [comment]
@skarimo `datadog_metric_tag_configuration` doesn't support the `aggregations` attribute, yet.

**Comment by skarimo** [comment]
Thanks, support for `aggregations` was added in PR #1179 and will be available in the next release. I will go ahead and close this issue but feel free to follow up/re-open.
