### ISSUE TITLE
Support for `datadog_service_account` and `datadog_service_account_application_key` resource (and data source)

### ISSUE THREAD

**Issue by KeisukeYamashita** [DataDog/terraform-provider-datadog#1266]
I recently knew that Datadog has it's own service account and can create a API key. Before this, the API keys were attached to a person who created the key so in my org, some retired member still owned a key. 

This feature makes easy to managed the keys in orgs.

### Affected Resource(s)

None. This request adds new source and data source.

## Referencens

* [Create an application key for this service account](https://docs.datadoghq.com/api/latest/service-accounts/)

**Comment by pderuiter** [comment]
I second this, having this functionality would remove the hassle of removing app keys when users leave

**Comment by jake-scott** [comment]
I added support for service accounts and their app keys in the attached PR.  However, the data source doesn't work well - I think it might need to be redesigned so that it can return a list of users rather than just one and its filtering doesn't seem to work well either (it needs to split out status queries from the username filter part)... I suggest doing this in a separate PR.

**Comment by dal13002** [comment]
+1 to this issue. It would be really helpful- glad there is PR open

**Comment by pavanrayapudi** [comment]
Please, Let us know the status of the PR.

**Comment by jake-scott** [comment]
> Please, Let us know the status of the PR.

I've been working on the requested changes over the last few days.  Should have a new PR ready this week.

**Comment by pavanrayapudi** [comment]
Any update on the PR?

**Comment by skarimo** [comment]
Re-opening this issue. The service account team will be introducing a separate dedicated resource for interaction with service accounts and service account application keys.

**Comment by SharpEdgeMarshall** [comment]
Enterprise customer here, this is absolutely necessary for us

**Comment by jorhett** [comment]
A PR to manage an app key for a service account is available at #1712. It works for update, delete, etc but I can't create -- help needed.

**Comment by EzzioWMoreira** [comment]
Hello, any update about this PR?
