### ISSUE TITLE
Feature request: AWS Integration: update monitor scopes for services listed on status.aws.com

### ISSUE THREAD

**Issue by adampeklay** [DataDog/terraform-provider-datadog#1282]
Hi,

I'm hoping to get a feature request reviewed.  It would be great if we can use all services regarding monitor scopes for the AWS integration.  It seems we are limited to a handful of services, while status.aws.com has quite a bit.  This would be helpful for creating dashbaords that show specific services we use and their health (without using AWS console for personalized dashboard that is).

### Terraform Version

```
$ terraform -v
Terraform v0.14.11
+ provider registry.terraform.io/datadog/datadog v3.2.0
+ provider registry.terraform.io/hashicorp/aws v3.52.0
```

### Affected Resource(s)

Please list the resources as a list, for example:

- resource_datadog_integration

### Terraform Configuration Files

This is just a test, but will suffice to provide context

main.tf
```
// AWS Service Checks

resource "datadog_monitor" "iaas_service_checks" {

  for_each = toset(var.services)

  escalation_message = ""
  evaluation_delay   = "0"
  include_tags       = "true"
  locked             = "false"
  message            = "test test test"

  monitor_thresholds {
    critical = "2"
    ok       = "3"
    warning  = "1"
  }

  name                = "[REDACTED - AWS Service Check] - ${each.key}"
  new_host_delay      = "0"
  no_data_timeframe   = "0"
  notify_audit        = "false"
  notify_no_data      = "false"
  priority            = "0"
  query               = "\"aws.status\".over(\"service:${each.key}\").by(\"region\").last(3).count_by_status()"
  renotify_interval   = "0"
  require_full_window = "false"
  timeout_h           = "0"
  type                = "service check"
}
```
variables.tf
```
variable "services" {
  type = list
  description = "cloud services used by REDACTED"
}
```
services.tfvars
```
services = [
  "ec2",
  "s3",
  "vpc",
  "route 53",
  "cloudtrail",
  "cloudwatch",
  "lambda",
  "elb",
  "iam",
  "certificatemanager",
  "guardduty",
  "rds"
]
```

provider.tf
```
terraform {
  required_version = "~> 0.14"

  required_providers {
    datadog = {
      source  = "datadog/datadog"
      version = "~> 3.2.0"
    }
    aws = {
      source  = "hashicorp/aws"
      version = "~> 3.52.0"
    }
  }
}

```

### Debug Output

n/a

### Panic Output

n/a

### Expected Behavior

I'd like to be able to get data, to see if the AWS IAM service is OK

What should have happened?

Monitor reports status of IAM

_Ideally_ we can use any service that is reported on [status.aws.com](https://status.aws.amazon.com)

### Actual Behavior

Monitor created, however no data

![Screen Shot 2021-11-23 at 9 16 33 AM](https://user-images.githubusercontent.com/13510667/143052894-7c321b6c-985d-415f-8e40-34948ed38c43.png)

### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:

1. `terraform apply`

### Important Factoids

n/a

### References

I searched the open issues for "AWS integration Monitor Scope" however there weren't any results

**Comment by therve** [comment]
Hi,

That seems mostly unrelated to terraform, or do I miss something? Looks like you'd like a new monitor feature.

**Comment by adampeklay** [comment]
Hey @therve,

It may be a monitor feature, I'm just not sure if its part of the DD Terraform provider code or not (I really need to start learning Go soon).  I thought perhaps that maybe part of the DD Terraform provider could be updated to allow us to get more services in the monitor scope screenshot above.  I took that screenshot to show whats currently available, as adding "iam" in my terraform code resulted in no data in the monitor, which is why I took that screenshot to show what is actually there.

If I opened the wrong kind of issue we can close this out for sure.

**Comment by adampeklay** [comment]
Ahh, ok.  I don't think this is related to terraform as you suspected, I jumped the gun on that.

Experimenting on a test dashboard, I see if I create a service check, the services listed through the Datadog UI are showing the same results (in this specific case, `IAM` or `Identity and Access Management` would ideally be available).
<img width="920" alt="Screen Shot 2021-12-07 at 1 42 10 PM" src="https://user-images.githubusercontent.com/13510667/145095386-96d7ebf4-92ec-450f-b3af-12922ab9695c.png">

I believe you are correct that I need a new monitor feature.  As I stated when I originally opened this issue up, it would be great if we could get all services listed on status.aws.amazon.com as options to select.   

It's not the end of the world if this isn't possible, it would just be nice to have a dashboard with all of the monitors I create showing all of services we use, in their respective regions, etc. in one nice to view dashboard.

**Comment by adampeklay** [comment]
<img width="986" alt="Screen Shot 2021-12-07 at 1 56 24 PM" src="https://user-images.githubusercontent.com/13510667/145097220-3f7c8b57-7b8d-4dbd-a13b-311cdde99d5f.png">

I suppose it would make more sense to show a screenshot from monitors --> new --> integration --> AWS --> "integration status" tab.

**Comment by adampeklay** [comment]
ok so let me close this issue out, and I can get a request opened in the proper place.

Thanks for the convo and steering me in the right direction!!

**Comment by therve** [comment]
Sounds good, thank you!
