### ISSUE TITLE
Version 3.5.0 and 3.6.0 not available for download

### ISSUE THREAD

**Issue by leo-genglfs** [DataDog/terraform-provider-datadog#1283]
Hi,

It seems datadog provider 3.5.0 and 3.6.0 are not available for downloading.
Lowered version to 3.4.0 then we can download the provider

Error message when we run terraform init with provider version pinned to 3.6.0, same error applies to 3.5.0
Initializing provider plugins...
--
  | - Finding datadog/datadog versions matching "3.6.0"...
  | ╷
  | │ Error: Failed to query available provider packages
  | │
  | │ Could not retrieve the list of available versions for provider datadog/datadog: no available releases match the given constraints 3.6.0
  | ╵

### Terraform Version

terraform 1.0

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    datadog = {
      source = "DataDog/datadog"
      version = "3.6.0"
    }
  }
}
```

### Expected Behavior

provider should be downloaded successfully.

### Actual Behavior

Failed to download datadog provider

### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:

1. Follow document https://registry.terraform.io/providers/DataDog/datadog/latest, put in terraform provider config:
```hcl
terraform {
  required_providers {
    datadog = {
      source = "DataDog/datadog"
      version = "3.6.0"
    }
  }
}
```
2. Run 'terraform init'

**Comment by therve** [comment]
Hi,

What's your platform? Seems to be working fine at least on darwin amd64. Thanks.

**Comment by therve** [comment]
Note: the output of `TF_LOG=trace terraform init` would be very helpful.

**Comment by leo-genglfs** [comment]
my apologies, it turned out we are using local mirrored plugin, problem is caused by local mirror, thanks again for looking into this, should have done more debugging before raising the issue.
