### ISSUE TITLE
Service level objective - target_display and warning_display are ignored

### ISSUE THREAD

**Issue by joelmarty** [DataDog/terraform-provider-datadog#1284]
### Terraform Version

```
2021-11-24T10:18:23.143+0100 [INFO]  Terraform version: 1.0.11
2021-11-24T10:18:23.143+0100 [INFO]  Go runtime version: go1.16.4
2021-11-24T10:18:23.143+0100 [INFO]  CLI args: []string{"/Users/jmarty/.asdf/installs/terraform/1.0.11/bin/terraform", "-v"}
2021-11-24T10:18:23.144+0100 [INFO]  Loading CLI configuration from /Users/xxx/.terraform.d/credentials.tfrc.json
2021-11-24T10:18:23.147+0100 [INFO]  CLI command args: []string{"version", "-v"}
Terraform v1.0.11
on darwin_amd64
+ provider registry.terraform.io/datadog/datadog v3.6.0

```

### Affected Resource(s)

`datadog_service_level_objective`

### Terraform Configuration Files

```hcl
variable "availability_slo_thresholds" {
  description = "A list of thresholds and targets that define the service level objectives from the provided SLIs."
  type        = list(object({
    target          = string
    target_display  = string
    timeframe       = string
    warning         = number
    warning_display = string
  }))
}

locals {
  availability_slos = {
    "My get endpoint"        = {
      role       = "somevalue"
      request_id = "some-id"
    }
  }
}

resource "datadog_service_level_objective" "metric_based_service_level_objective" {
  for_each = local.availability_slos

  name     = "some availability slo"
  type = "metric"

  query {
    numerator     = "some query"
    denominator   = "some other query"
  }

  dynamic "thresholds" {
    for_each = var.availability_slo_thresholds
    content {
      target         = thresholds.value.target
      target_display = thresholds.value.target_display
      timeframe      = thresholds.value.timeframe
      warning        = thresholds.value.warning
    }
  }
}
```

### Debug Output

[Gist](https://gist.github.com/joelmarty/a1f58ad8e03ab565c8860e9cfad23a3a)

Note output has been cleaned of some unrelated resources.

### Expected Behavior

The `target_display` and `warning_display` values are present in the plan and the created resource.

### Actual Behavior
The plan for the thresholds is:
```
      + thresholds {
          + target    = 99
          + timeframe = "30d"
          + warning   = 99.5
        }

```
The values specified in the thresholds are defined in the parent module but it makes no difference if I hardcode them in the resource definition.

### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:

1. `terraform apply`

### Important Factoids

Not that I know of.

**Comment by zippolyte** [comment]
Hi @joelmarty 

So it turns out `target_display` and `warning_display` values are not configurable, they are simply ignored by The API if specified in PUT/POST request. Those values are only part of the response (see https://docs.datadoghq.com/api/latest/service-level-objectives/#create-an-slo-object).

They've been made configurable in the provider here by mistake, I'll create a PR to mark those as `computed` values.

Thanks for the report
