### ISSUE TITLE
Clarify `new_group_delay` and `new_host_delay` in docs

### ISSUE THREAD

**Issue by nitrocode** [DataDog/terraform-provider-datadog#1292]
### Terraform Version

terraform 1.0.11

### Affected Resource(s)

Please list the resources as a list, for example:

-   datadog_monitor

### Terraform Configuration Files

```hcl
resource "datadog_monitor" "this" {
  # new_host_delay = 300
  new_group_delay = 0
}
```

### Expected Behavior

Knowing how to deprecate `new_host_delay` and when and how to use `new_group_delay`

### Actual Behavior

This is pretty confusing.

In the terraform provider docs it says the following

> * `new_group_delay` (Number) Time (in seconds) to skip evaluations for new groups.

> `new_group_delay` overrides `new_host_delay` if it is set to a nonzero value.

So `new_group_delay: 300` would override `new_host_delay` and `new_group_delay: 0` would do nothing. Makes sense.

> To disable group delay for monitors grouped by host, `new_host_delay` must be set to zero due to the default value of 300 for that field (new_group_delay defaults to zero, so setting it to zero is not required).

So `new_host_delay` should be set and should be set to `0` to override the default of `300`? Does that mean `new_host_delay` should still be used even tho it's deprecated ? Or is this line an old portion of the documentation that should be removed ?

> * `new_host_delay` (Number, Deprecated) Time (in seconds) to allow a host to boot and applications to fully start before starting the evaluation of monitor results. Should be a non-negative integer. Defaults to 300 (this default will be removed in a major version release and new_host_delay will be removed entirely in a subsequent major version release). Deprecated. Prefer using new_group_delay (except when setting new_host_delay to zero).

soooo this deprecated part.

> Deprecated. Prefer using new_group_delay (except when setting new_host_delay to zero).

This means that if we set `new_host_delay` to zero, we don't prefer using `new_group_delay` ???

Then in this comment https://github.com/DataDog/terraform-provider-datadog/issues/1221#issuecomment-931006926 by @zippolyte seemed.

> Hi,
> 
> The `new_host_delay` option could be set on simple monitors, but it never had any effect in that case. It would only have an effect for a multi alert monitor scoped on hosts. You should just remove that `new_group_delay` option in your configuration, as it's not useful to have here.

Is the correct solution ?

* remove `new_host_delay` and use `new_group_delay` for multi alert monitors
* remove `new_host_delay` and remove `new_group_delay` for simple monitors

If so, can we update the docs to clarify this?

### References

-   https://registry.terraform.io/providers/DataDog/datadog/latest/docs/resources/monitor
-   https://github.com/DataDog/terraform-provider-datadog/issues/1221

**Comment by nitrocode** [comment]
I'm still confused by this. The new updates do not clarify my above questions.

@sarina-dd or whomsoever, would you happen to know if I can simply replace `new_host_delay` by `new_group_delay` and have the monitors still apply the same `300` second delay to allow a host to boot and applications to fully start before starting the evaluation of monitor results?

**Comment by nitrocode** [comment]
cc: @therve

**Comment by therve** [comment]
> I'm still confused by this. The new updates do not clarify my above questions.
> 
> @sarina-dd or whomsoever, would you happen to know if I can simply replace `new_host_delay` by `new_group_delay` and have the monitors still apply the same `300` second delay to allow a host to boot and applications to fully start before starting the evaluation of monitor results?

Yes. Don't set `new_host_delay`, and the default with be ignored by the backend.

**Comment by danielcompton** [comment]
I'm still a little bit confused here. When I tried updating from `new_host_delay` to `new_group_delay` I got an error:

```
╷
│ Error: error validating monitor from https://api.datadoghq.com/api/v1/monitor/validate: 400 Bad Request: {"errors": ["The new_group_delay option can only be used for multi-alert monitors"]}
│ 
│   with datadog_monitor.snip,
│   on edge.tf line 1083, in resource "datadog_monitor" "snip":
│ 1083: resource "datadog_monitor" "snip" {
│ 
╵
```

**Comment by gutocarvalho** [comment]
Any news here?

**Comment by jon-ward-unmind** [comment]
The `"The new_group_delay option can only be used for multi-alert monitors"` error is still occurring for us in version 3.28.0 of the DataDog provider. We are using `datadog_monitor_json` rather than `datadog_monitor`.

I notice that whilst the[ DD API docs](https://docs.datadoghq.com/api/latest/monitors/) also state that `new_host_delay` is deprecated, if I create a new monitor manually in the DD console and export it, it uses `new_host_delay` rather than `new_group_delay`.

**Comment by leslie-canva** [comment]
Not sure why the issue was closed, I'm still confused by this

**Comment by Kyslik** [comment]
> Is there a way to set a multi-alert using terraform code?

According to provider docs `notify_by` should convert monitor to multi-alert. Source: https://registry.terraform.io/providers/DataDog/datadog/latest/docs/resources/monitor#notify_by

**Comment by wyardley** [comment]
Sorry to bump an ancient issue... still seems like I get the `new_host_delay` deprecation warning if it's present on a simple monitor (and set to `0`), but if I remove it outright, it wants to set it to the default (300) vs. planning as a noop.

I guess the provider docs say:
> Deprecated. Use new_group_delay except when setting new_host_delay to zero

But still emits a deprecation warning when it _is_ set to 0 🙃 

```
│   22:   new_host_delay    = 0
│ 
│ Use `new_group_delay` except when setting `new_host_delay` to zero.
```
