### ISSUE TITLE
datadog_metric_tag_configuration fails with 409 Conflict: {"errors": ["New gauge/count/rate conflicts with existing tag configuration, use PATCH to update"]} 

### ISSUE THREAD

**Issue by cptkng23** [DataDog/terraform-provider-datadog#1294]
### Terraform Version
Terraform v1.0.11

provider registry.terraform.io/datadog/datadog v3.6.0

### Affected Resource(s)
datadog_metric_tag_configuration

### Terraform Configuration Files

```hcl
resource "datadog_metric_tag_configuration" "my_metric_config" {
  metric_name = "my.metric.name"
  metric_type = "rate"
  tags        = ["tag1", "tag2"]
}
```

### Expected Behavior
Our DD account also has Metrics Without Limits enabled.

The metric already existed in DD before, as we have emitted data points to this metric. If I check the metric in the DD UI in metric summary, the Metric Type is displayed as `Rate`. The metric also has many tags, and we want to limit the _Queryable Tags_ to `tag1`, `tag2`.

I would expect that the `terraform apply` succeeds, and the metric will have only the two mentioned tags.

### Actual Behavior
```hcl
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # datadog_metric_tag_configuration.my_metric_config will be created
  + resource "datadog_metric_tag_configuration" "my_metric_config" {
      + id          = (known after apply)
      + metric_name = "my.metric.name"
      + metric_type = "rate"
      + tags        = [
          + "tag1",
          + "tag2",
        ]

      + aggregations {
          + space = "sum"
          + time  = "sum"
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.
datadog_metric_tag_configuration.my_metric_config: Creating...

Error: error creating MetricTagConfiguration from https://api.datadoghq.com/api/v2/metrics/my.metric.name/tags: 409 Conflict: {"errors": ["New gauge/count/rate conflicts with existing tag configuration, use PATCH to update"]}

  with datadog_metric_tag_configuration.my_metric_config,
  on metrics.tf line 17, in resource "datadog_metric_tag_configuration" "my_metric_config":
  17: resource "datadog_metric_tag_configuration" "my_metric_config" {
```

It seems it uses POST of the DD API instead of PATCH for an existing metric?

### Steps to Reproduce

Execute above listed terraform defintion

### Important Factoids

Funnily, sometimes, and very rarely, this succeeds. I'm not completely sure how that was the case, maybe after changing some metric config in the DD UI, but it's somehow not reliable.

The overall setup of terraform and such all works, as all other resources in the same file are updated well if I comment the non-working tag configuration, e.g. datadog_metric_metadata works fine for the same metric.

**Comment by skarimo** [comment]
Hi, for this case, could you try importing the resource to terraform first. The error is most likely caused by the metric tag configuration being created/managed outside of resource. You can import existing resources with `terraform import datadog_metric_tag_configuration. my_metric_config my.metric.name`. The subsequent applies should then succeed

**Comment by cptkng23** [comment]
> Hi, for this case, could you try importing the resource to terraform first. The error is most likely caused by the metric tag configuration being created/managed outside of resource. You can import existing resources with `terraform import datadog_metric_tag_configuration. my_metric_config my.metric.name`. The subsequent applies should then succeed

Thanks for the hint, I'll try next week.

**Comment by cptkng23** [comment]
I can confirm that this worked. Sorry for bothering you.

_Small note. The import itself as you described somehow didn't work, but manually editing the terraform state file did it._
