### ISSUE TITLE
Add retry on 504 for datadog_monitor resource read

### ISSUE THREAD

**Issue by camlow325** [DataDog/terraform-provider-datadog#1299]
### Terraform Version

```
Terraform v1.0.8
+ provider registry.terraform.io/datadog/datadog v3.2.0
```

### Affected Resource(s)

* datadog_monitor

### Terraform Configuration Files

I don't think the problem is specific to the content in the `datadog_monitor` resources that we use but could provide a more specific example if that would be helpful.

### Expected Behavior

Apply should succeed.

### Actual Behavior

Apply generally succeeds, but we occasionally see errors like the following:

```
Error: error getting monitor from https://api.datadoghq.com/api/v1/monitor/...: 504 Gateway Time-out: <html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
</body>
</html>


  with test,
  on .terraform/test.tf line 1, in resource "datadog_monitor" "test":
   1: resource "datadog_monitor" "test" {
```

### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:

1. `terraform apply`

### Important Factoids

#1038 added the ability to retry for HTTP 504 failures encountered during the `resourceDatadogMonitorCustomizeDiff` function. The 504s that we've seen appear to have happened as the `resourceDatadogMonitorRead` function executes. This function currently has logic to retry for 502 errors but not 504 errors [here](https://github.com/DataDog/terraform-provider-datadog/blob/v3.6.0/datadog/resource_datadog_monitor.go?plain=1#L657). It would seem useful to add retries for the 504 errors.

### References

-   #1038

**Comment by skarimo** [comment]
Closing the issue but feel free to reopen if the above does not fit your use case.
