### ISSUE TITLE
Feature Request: Sensitive data scanner resource

### ISSUE THREAD

**Issue by pphadtare** [DataDog/terraform-provider-datadog#1303]
Hi there,

I raised this ticket coz,
 Datadog recently added new feature to datadog that is **sensitive data scanner**.
https://app.datadoghq.com/organization-settings/sensitive-data-scanner

We are integrated to terraform datadog provider, so we need this resource in the terraform, so we can automate and use this feature.
Can you please add that.

Thanks and regards,
Prajakta

**Comment by skarimo** [comment]
Hi, there are currently no public api's to create a new resource. Could you open a feature request with our support team so it is tracked by the appropriate team: https://www.datadoghq.com/support . Thanks.

**Comment by pphadtare** [comment]
Thanks

**Comment by etiwari307** [comment]
It seems like the API v2(latest) now includes Sensitive Data Scanner (https://docs.datadoghq.com/api/latest/sensitive-data-scanner/). Could you add this SDS functionality to the terraform provider now?

**Comment by ishworg** [comment]
bump! any folks from ddog that can comment on the progress? ta!

**Comment by olympus-fergus** [comment]
I'd vote for this one too.

**Comment by ewascent** [comment]
The required APIs are available now
https://docs.datadoghq.com/api/latest/sensitive-data-scanner/

**Comment by therve** [comment]
The resources are available with the latest release, https://registry.terraform.io/providers/DataDog/datadog/latest/docs/resources/sensitive_data_scanner_rule and https://registry.terraform.io/providers/DataDog/datadog/latest/docs/resources/sensitive_data_scanner_group. Thanks for your patience.
