### ISSUE TITLE
Dashboard: Support group widget in free/grid layouts

### ISSUE THREAD

**Issue by nicolaslt** [DataDog/terraform-provider-datadog#1304]
### Terraform Version

Terraform `v0.14.8`, datadog provider `v2.26.1` (but I don't think those versions matter in this case)

### Affected Resource(s)

-   datadog_dashboard

### Terraform Configuration Files

```hcl
resource "datadog_dashboard" "a_dashboard" {
  title        = "A title"
  layout_type  = "free"

  widget {
    manage_status_definition {
      title= "Monitors"
      query= "tag:(some:tag)"
      summary_type = "monitors"
      display_format = "countsAndList"
      hide_zero_counts = true
      show_last_triggered = true
      sort = "triggered,desc"
    }

    widget_layout {
      x= 0
      y= 0
      width= 12
      height= 3
    }
  }

  widget {
    group_definition {
      title       = "A title"
      layout_type = "ordered"

      widget {
        timeseries_definition {
          title = "Docker CPU usage"
          request {
            q            = "max:docker.cpu.usage"
            display_type = "line"
          }
        }

        widget_layout {
          x= 0
          y= 0
          width= 4
          height= 2
        }
      }
    }
  }
}
```

### Debug Output

N/A (will provide if requested)

### Panic Output

N/A (will provide if requested)

### Expected Behavior

The Datadog API should accept this configuration. I can create such a dashboard & widgets in the UI using my mouse. The values for layouts in this configuration are in fact copy/pasted from the json exported from dashboard I created manually (not the one in screenshot but issue would be the same)

Screenshot:
![Screenshot from 2021-12-13 15-04-40](https://user-images.githubusercontent.com/2162060/145836379-d0379c77-8119-487e-83e8-a01ce41499b4.png)

### Actual Behavior

In the applying phase, datadog's API responds with 
```
error creating dashboard: 400 Bad Request: {"errors": ["Invalid widget at position 1 of type group. Error: Unsupported widget type 'group'."]}

```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

N/A

### References

I found #1225 but the conclusion doesn't seem accurate (anymore?), considering I can create such a dashboard in the UI?

**Comment by therve** [comment]
Hi,

The fact that you have the `clone to screenboard` item in your screenshot would indicate me that you're not in a `free` layout. I believe you want to use the `ordered` layout with a `reflow_type: fixed` setting.

**Comment by nicolaslt** [comment]
Aaah yes I see. `free` is what the UI call `screenboard`, `reflow_type:fixed|ordered` is what the UI calls `grid` or `timeboard`.

It would be helpful if the naming was harmonized between the terraform provider and the UI, or that the UI terms are mentionned in the docs (if not harmonised with the terraform types).

In any case I'm happy to close this ticket.

**Comment by nicolaslt** [comment]
Thanks for the help :smile:  I realised I hadn't said, was in a bit of a rush.
