### ISSUE TITLE
[Synthetics]  Support for AWS Signature auth

### ISSUE THREAD

**Issue by xrn** [DataDog/terraform-provider-datadog#1314]
Datadog provided AWS Signature for their API Synthetics tests. Is there any chance that this Auth method will be also supported by terraform.

Current example of test: 

https://github.com/DataDog/terraform-provider-datadog/blob/ebf49314d3fd0abb3bf28b6f5ac9616605b12ba2/examples/resources/datadog_synthetics_test/resource.tf

**Comment by therve** [comment]
Done in #1336
