### ISSUE TITLE
Error: error validating monitor from https://api.datadoghq.com/api/v1/monitor/validate: 400 Bad Request: {"errors": ["A grouping must be specified for custom checks"]}

### ISSUE THREAD

**Issue by fatbasstard** [DataDog/terraform-provider-datadog#1321]
Hi,

As of today I get the follow error when trying to runTerraform:

```Error: error validating monitor from https://api.datadoghq.com/api/v1/monitor/validate: 400 Bad Request: {"errors": ["A grouping must be specified for custom checks"]}
with module.XXX.datadog_monitor.default["health"]
on .terraform/modules/XXX.health_monitoring/main.tf line 6, in resource "datadog_monitor" "default":
resource "datadog_monitor" "default" {
```

Looks like DataDog updated the API but posting this here in case it can (or must) be fixed in the provider.

### Terraform Version

```
Terraform 1.1.3
Datadog: 3.7.0
```

### Affected Resource(s)

Please list the resources as a list, for example:

-   datadog_monitor

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files

```hcl
resource "datadog_monitor" "default" {
  name                = "health"
  message             = "Test stopped sending data to Datadog"
  query               = "\"datadog.agent.up\".over(\"host:frank\").last(2).count_by_status()"
  evaluation_delay    = 180
  include_tags        = true
  new_group_delay     = null
  no_data_timeframe   = 5
  notify_no_data      = true
  renotify_interval   = null
  require_full_window = true
  timeout_h           = null
  type                = "service check"

  monitor_thresholds {
    ok                = 1
    warning           = 1
    critical          = 1
    unknown           = null
    warning_recovery  = null
    critical_recovery = null
  }
}```

**Comment by therve** [comment]
Hi,

I believe some extra validation has been rolled out to fix queries which may not reflect the intent. In your case your query is missing a grouping clause, so you should add one (for example: ` "\"datadog.agent.up\".over(\"host:frank\").by(\"*\").last(2).count_by_status()"`. 

Sorry for the trouble.

**Comment by fatbasstard** [comment]
@therve 

Thanks for the quick reply, I was guessing it was an additional check. Actually glad it is our check itself, we can easiliy fix it (just tested it).
