### ISSUE TITLE
datadog_integration_aws ignores role_name parameter

### ISSUE THREAD

**Issue by dcarriger** [DataDog/terraform-provider-datadog#1325]
The example Terraform for this resource is the following.

https://registry.terraform.io/providers/DataDog/datadog/latest/docs/resources/integration_aws

```# Create a new Datadog - Amazon Web Services integration
resource "datadog_integration_aws" "sandbox" {
  account_id  = "1234567890"
  role_name   = "DatadogAWSIntegrationRole"
  filter_tags = ["key:value"]
  host_tags   = ["key:value", "key2:value2"]
  account_specific_namespace_rules = {
    auto_scaling = false
    opsworks     = false
  }
  excluded_regions = ["us-east-1", "us-west-2"]
}
```

However, after applying the Terraform (after making changes for our own AWS account), the integration showed as broken within Datadog. I checked the IAM roles within our AWS account, and the role that Datadog actually created was named `DataDogAwsIntegration`. The error Datadog showed for the integration was `Datadog is not authorized to perform action sts:AssumeRole`.

So Datadog uses the `role_name` when attempting to use STS to assume the role, but it does not use the `role_name` when actually creating the IAM role, leading to the broken behavior I'm reporting. Changing the `role_name` parameter within my Terraform to be `DataDogAwsIntegration` fixed the integration, but the IAM role created by the Datadog Terraform provider should still match the role name specified in the resource.

**Comment by skarimo** [comment]
Hi, the `datadog_integration_aws` resource does not create an IAM role so the role was most likely created outside of it. I am going to close this issue but feel free to re-open if I missed something. You can also reach out to datadog support to further understand where the role was created: https://www.datadoghq.com/support/
