### ISSUE TITLE
object contains unparsed element when using request_basicauth with datadog_synthetics_test

### ISSUE THREAD

**Issue by ohookins** [DataDog/terraform-provider-datadog#1335]
### Terraform Version

Terraform 1.1.2
Datadog provider 3.8.1

The issue appears to have been introduced in 3.8.0. 

### Affected Resource(s)

`datadog_synthetics_test`

### Terraform Configuration Files

```hcl
resource "datadog_synthetics_test" "example" {
  locations = ["aws:us-east-2"]
  message   = "Example site synthetic test"
  name      = "Liveness test for example.com"
  status    = "live"
  subtype   = "http"
  type      = "api"

  assertion {
    type     = "statusCode"
    operator = "is"
    target   = "200"
  }

  request_basicauth {
    username = "username"
    password = "password"
  }

  options_list {
    tick_every = 60

    retry {
      count    = 1
      interval = 5000
    }
  }

  request_definition {
    method = "GET"
    url    = "https://example.com"
  }
}
```

### Debug Output

Debug output doesn't really help in this case. It seems like a datastructure used to deserialise the synthetic test response doesn't include the `basicAuth` block in the response, and it ends up captured by the `CheckForUnparsed` function.

This error only started happening from 3.8.0:

│ Error: object contains unparsed element: map[password:xxxx username:xxxx]
│
│   with datadog_synthetics_test.example,
│   on datadog-synthetics.tf line 59, in resource "datadog_synthetics_test" "exampe":
│   59: resource "datadog_synthetics_test" "example" {

### Panic Output

N/A

### Expected Behavior

No error, the configuration has not changed.

### Actual Behavior

Provider bails out with the above error.

### Steps to Reproduce

1. Create a `datadog_synthetic_test` resource with `request_basicauth` block.
2. Apply.

### Important Factoids

N/A

### References

N/A

**Comment by therve** [comment]
Hi,

Can you provide some more details? It's it a browser test, an API test? If you have a completely reproducible resource that'd be ideal. I tested with the following resource and it worked without issue:

```hcl
resource "datadog_synthetics_test" "test_browser" {
  type = "browser"

  request_definition {
    method = "GET"
    url    = "https://www.example.com"
  }

  request_basicauth {
    username = "foo"
    password = "bar"
  }

  device_ids = ["laptop_large"]
  locations  = ["aws:eu-central-1"]

  options_list {
    tick_every = 3600
  }

  name    = "A Browser test on example.org"
  message = "Notify @qa"
  tags    = []

  status = "paused"

  browser_step {
    name = "Check current url"
    type = "assertCurrentUrl"
    params {
      check = "contains"
      value = "example"
    }
  }
}
```

I also tested the same with an API test.

**Comment by ohookins** [comment]
It was an API test, I've updated the description with all of the properties we are using so it is hopefully representative.

**Comment by therve** [comment]
Thanks for the reproducer. I understand the issue, it's a side effect of adding new auth in the SDK in https://github.com/DataDog/datadog-api-client-go/pull/1267. Unfortunately I don't have a great workaround for now: you can either stay on 3.7.0 or recreate your synthetics tests (but you probably need to delete them in 3.7.0 and create them in 3.8.1). We're looking into a solution for the next release, sorry for the trouble.

**Comment by daniel-laszlo** [comment]
I have similar issue with `datadog_authn_mapping` resource. It creates SAML Group Mappings just fine, but the apply ends up erroring.
Example:
```
Error: object contains unparsed element: map[role:map[data:map[id:11ad222c-a302-11ec-b4db-da7ad0900005 type:roles]] saml_assertion_attribute:map[data:map[id:6087 type:saml_assertion_attributes]]]
with datadog_authn_mapping.mapping["XYZ"]
on roles.tf line 6, in resource "datadog_authn_mapping" "mapping":
resource "datadog_authn_mapping" "mapping" {
```

**Comment by stpierre** [comment]
I was able to successfully use the proposed workaround of deleting the synthetic with the 3.7.0 provider and re-creating it with the 3.8.1 provider. It's not perfect but it got us over the hump while waiting for the fix. (We couldn't downgrade because there are 3.8 features we depend on.)

**Comment by therve** [comment]
It should be fixed by https://github.com/DataDog/datadog-api-client-go/pull/1430
