### ISSUE TITLE
treemap widget in a dashboard causes provider errors when changes ignored

### ISSUE THREAD

**Issue by frightenedmonkey** [DataDog/terraform-provider-datadog#1354]
I've linked a related ticket below. The issue is that the deprecated treemap widget, if added to a dashboard that has ignore_changes set to all will error out. I am specifically not requesting that the treemap widget be supported, only that the error not result in plan/apply failures.

### Terraform Version

Applies to terraform 0.15 and 1.1.5, applies to datadog provider 2.20 -> 3.8

### Affected Resource(s)

Please list the resources as a list, for example:

-   datadog_dashboard

### Terraform Configuration Files

```hcl
resource "datadog_dashboad" "test" {
  title       = "Test Overview"    
  description = "Test Overview"    
  layout_type = "ordered"    
    
  lifecycle {    
    ignore_changes = all    
  }    
  widget {    
    timeseries_definition {    
      title = "Some Widget"    
      request {    
        display_type = "line"    
        q            = "#elided because irrelevant"    
    
        style {    
          palette = "classic"    
        }    
      }    
    }    
  }    

}
```

### Panic Output

This is from terraform 1.1 and datadog provider 3.8.1
```
 Error: unsupported widget type: &{%!s(*datadog.TreeMapColorBy=<nil>) %!s(*datadog.TreeMapGroupBy=<nil>) [{%!s(*[]datadog.WidgetFormula=<nil>) %!s(*string=<nil>) %!s(*[]datadog.FormulaAndFunctionQueryDefinition=&[{<nil> <nil> <nil> 0xc000a19840 <nil> <nil>}]) %!s(*datadog.FormulaAndFunctionResponseFormat=0xc001931c10) map[]}] %!s(*datadog.TreeMapSizeBy=<nil>) %!s(*string=0xc001931ec0) treemap map[]}
```

### Expected Behavior

The widget should be ignored, and the provider should not error out.

### Actual Behavior

Planning results in an error.

### Steps to Reproduce

The issue is only relevant to the resource insofar as the following conditions are met:
1. Create the dashboard with terraform initially.
2. Subsequently set the ignore_changes lifecycle rule to all
3. Manually add a TreeMap widget to the dashboard
4. Plan the dashboard resource

### Important Factoids
Nope

### References

Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- https://github.com/DataDog/terraform-provider-datadog/issues/666

**Comment by therve** [comment]
Hi,

I don't think there is anything we can do about that.  Supported has been added in #1331 and will be released soon. Otherwise you can use the dashboard_json resource. Thanks.
