### ISSUE TITLE
What is the specific limitation that going with json addresses?

### ISSUE THREAD

**Issue by Bing-Violet** [DataDog/terraform-provider-datadog#1362]
Hi there,

### Terraform Version

1.1.4

### Affected Resource(s)

Please list the resources as a list, for example:

-   datadog_dashboard_json (Resource)
-   datadog_dashboard (Resource)
-   cdktf

### Context

We currently have some repository using datadog_dashboard_json (Resource) and datadog_dashboard (Resource) for datadog dashboards and monitors. We recently experimented using cdktf instead of hcl for one of the repo using datadog_dashboard which works really well, so we would like to do the same with the rest of the repo including the ones with datadog_dashboard_json (Resource). These repository use datadog_dashboard_json instead datadog_dashboard because some properties are not supported in hcl. I'm wondering is there any potential pitfalls regarding json we need to be aware of before moving them to cdktf?

**Comment by therve** [comment]
Hi,

The main thing with the JSON resource is that error reporting and validation is more lax, as most of the work happens at apply as there is no schema. Other than I'm not sure what you're looking for, so it's a bit hard to tell where you're going to stumble.

**Comment by Bing-Violet** [comment]
Thanks Therve, I see your point, it would make more sense to avoid using json if possible.  I guess the next question is, will all the dashboard/monitor elements will eventually be supported? If so, do we have a timeframe for it? The initial intention to use json was that we stumble upon many errors when converting datadog dashboard elements to terrafrom, eg. 'reflow_type'.

**Comment by therve** [comment]
Closing this one for now, feel free to reopen.
