### ISSUE TITLE
Cloud workload security agent rules

### ISSUE THREAD

**Issue by ebarti** [DataDog/terraform-provider-datadog#1364]
Hey all,

So, since v3.8.0 a monitoring rule is allowed to have more than 5 cases https://github.com/DataDog/terraform-provider-datadog/issues/1310

However, that same version deprecated agent_rule. Which means us, users, have to choose whether to be able to configure agent_rules using terraform, or be able to configure more than 5 cases in said rules.

Any idea when the new `datadog_cloud_workload_security_agent_rule` (that looks ready from an outsider's POV) will be relased?

**Comment by rocketlobster** [comment]
Hello @ebarti!
Thanks a lot for having spotted that, it seems that we missed something here: From what I know `datadog_cloud_workload_security_agent_rule` should already be ready to use. 

I'll double check with the team, and we'll make sure to create the missing doc.

**Comment by rocketlobster** [comment]
> Hey @rocketlobster I think it has not yet been released (last release is 3.8.1 from Jan 19th). Thank you for checking!

Just checked: We are supposed to create a new release very soon (hopefully this week or the next one). 

I just set a reminder for myself to check that at the end of this week, I'll keep you posted then!

**Comment by rocketlobster** [comment]
Hello @ebarti!

[Release 3.9.0](https://github.com/DataDog/terraform-provider-datadog/releases/tag/v3.9.0) is out, and with it the support of the `datadog_cloud_workload_security_agent_rules` resource!

Let me know if that works for you!
