### ISSUE TITLE
Terraform datadog_synthetics_test accept_self_signed certificate is not implemented

### ISSUE THREAD

**Issue by kraangprime** [DataDog/terraform-provider-datadog#1367]
Hello,

Trying to setup datadog_synthetics_test to accept self signed cert through terraform fails to do so. It appears that setting in options_list value accept_self_signed = true (or false) does not do any changes in web UI interface.

### Terraform Version
```
$ terraform -v
Terraform v1.0.1
on linux_amd64
+ provider registry.terraform.io/datadog/datadog v3.8.1
+ provider registry.terraform.io/hashicorp/vault v2.21.0
```

### Affected Resource(s)

Please list the resources as a list, for example:

-   datadog_synthetics_test

### Expected Behavior

Setting in options_list value of accept_self_signed = true should set a checkbox as show on image, but it fails to do so.
![image](https://user-images.githubusercontent.com/42147156/155350161-43be7461-6f30-44bf-8bc6-78c4614f1310.png)

### Actual Behavior

Upon running following snippet in terraform "Ignore server certificate error field" in web UI is not set.

```
resource "datadog_synthetics_test" "test_self_signed_cert" {
    device_ids      = [
        "chrome.laptop_large",
    ]
    locations       = [
        "aws:eu-central-1",
        "aws:eu-west-1",
    ]
    message         = " @test-team"
    name            = "Testing selfsigned cert"
    request_headers = {}
    request_query   = {}
    status          = "live"
    tags            = [
        "xxx",
        "xxx2",
        "env:prod",
    ]
    type            = "browser"

    browser_step {
        allow_failure        = false
        force_element_update = false
        name                 = "Test heading XXX is present"
        timeout              = 0
        type                 = "assertElementPresent"

        params {
            delay      = 0
            element    = jsonencode(
                {
					REDACTED
                }
            )
            modifiers  = []
            with_click = false
            x          = 0
            y          = 0
        }
    }

    options_list {
        accept_self_signed   = true
        allow_insecure       = false
        follow_redirects     = false
        min_failure_duration = 60
        min_location_failed  = 1
        monitor_priority     = 0
        no_screenshot        = false
        tick_every           = 3600

        monitor_options {
            renotify_interval = 0
        }

        retry {
            count    = 1
            interval = 300
        }
    }

    request_definition {
        dns_server_port         = 0
        method                  = "GET"
        no_saving_response_body = false
        number_of_packets       = 0
        port                    = 0
        should_track_hops       = false
        timeout                 = 0
        url                     = "REDACTED"
    }
}
```

**Comment by chrisjamieson12** [comment]
I'm seeing this same issue. We have synthetics tests set up and I can't find an option in Terraform to enable the "Ignore server certificate error" option that I see in the UI. When I manually enable this feature via the UI and then run terraform again it gets reset, causing the synthetics monitor to trigger. Not sure if the "accept_self_signed" option just isn't working or if there is another option that I'm just missing.

**Comment by chrisjamieson12** [comment]
@kraangprime There is now an option in Terraform for this. Add the "ignore_server_certificate_error = true" in the options list

**Comment by therve** [comment]
Closing that one now, feel free to reopen if that doesn't work for you.
