### ISSUE TITLE
Create custom metric

### ISSUE THREAD

**Issue by ramirek** [DataDog/terraform-provider-datadog#1374]
Is there any way to create a custom metric? 
So that it can be linked directly to `datadog_metric_metadata` to avoid the` 404 Not Found: {"errors": ["metric_name not found"]} ` error while trying to create `datadog_metric_metadata` without having published the corresponding metric in advance: https://github.com/DataDog/terraform-provider-datadog/issues/918

**Comment by skarimo** [comment]
Maybe you can use the `null_resource` with provisioner to submit the data point: https://www.terraform.io/language/resources/provisioners/local-exec#interpreter-examples

**Comment by PavanMudigondaTR** [comment]
@ramirek please let me know how you were able to solve this issue ?

**Comment by FarhanSajid1** [comment]
why was this closed? Seems like this still needs to be implemented in Terraform
