### ISSUE TITLE
Synthetics test operators not supported

### ISSUE THREAD

**Issue by kuwas** [DataDog/terraform-provider-datadog#1387]
### Terraform Version

`1.1.3`

### Affected Resource(s)

Please list the resources as a list, for example:

- datadog_synthetics_test

### Terraform Configuration Files

```hcl
  assertion {
    type     = "connection"
    operator = "is"
    target   = "established"
  }
```

### Panic Output

```
│ Error: Invalid enum value
│ 
│   with module.datadog-vpn-tcp.datadog_synthetics_test.default,
│   on .terraform/modules/datadog-vpn-tcp/synthetics/test/main.tf line 99, in resource "datadog_synthetics_test" "default":
│   99:   type      = var.datadog_synthetics_test_type
│ 
│ invalid value 'connection' for SyntheticsAssertionType: valid values are
│ [body header statusCode certificate responseTime property recordEvery
│ recordSome tlsVersion minTlsVersion latency packetLossPercentage
│ packetsReceived networkHop receivedMessage]
```

### Expected Behavior

- `connection` operator should be supported

### Actual Behavior

- `connection` operator is not supported

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

`connection` and possibly other operators are supported by Datadog's UI but are apparently undocumented even in the Datadog API docs (https://docs.datadoghq.com/api/latest/synthetics/#create-an-api-test).

The terraform provider, provider docs, and REST APIs all need to be updated to reflect what the Datadog UI supports.

### References

- N/A

**Comment by DenisShalaevSetronica** [comment]
Looks https://github.com/DataDog/terraform-provider-datadog/pull/1464 contains fix

**Comment by romainberger** [comment]
Should be fixed after https://github.com/DataDog/terraform-provider-datadog/pull/1464 is merged
