### ISSUE TITLE
Synthetics test documentation is incorrect

### ISSUE THREAD

**Issue by kuwas** [DataDog/terraform-provider-datadog#1388]
### Terraform Version

`1.1.3`

### Affected Resource(s)

Please list the resources as a list, for example:

- datadog_synthetics_test

### Terraform Configuration Files

```
  request_definition {
    follow_redirects = true
    allow_insecure = true
  }
```

### Panic Output

```
│ Error: Unsupported argument
│ 
│   on .terraform/modules/datadog-vpn-tcp/synthetics/test/main.tf line 127, in resource "datadog_synthetics_test" "default":
│  127:     follow_redirects        = var.datadog_synthetics_test_api.request.follow_redirects
│ 
│ An argument named "follow_redirects" is not expected here.
╵
╷
│ Error: Unsupported argument
│ 
│   on .terraform/modules/datadog-vpn-tcp/synthetics/test/main.tf line 128, in resource "datadog_synthetics_test" "default":
│  128:     allow_insecure          = var.datadog_synthetics_test_api.request.allow_insecure
│ 
│ An argument named "allow_insecure" is not expected here.
```

### Expected Behavior

- `request_definition.follow_redirects` argument should be supported
- `request_definition.allow_insecure` argument should be supported

### Actual Behavior

- `request_definition.follow_redirects` argument is not supported
- `request_definition.allow_insecure` argument is not supported

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

`request_definition`'s arguments `follow_redirects` and `allow_insecure` are listed in the provider docs (https://registry.terraform.io/providers/DataDog/datadog/latest/docs/resources/synthetics_test#nested-schema-for-api_steprequest_definition) but aren't actually in the code (https://github.com/DataDog/terraform-provider-datadog/blob/master/datadog/resource_datadog_synthetics_test_.go#L127). 

### References

- N/A

**Comment by therve** [comment]
Hi,

For now those arguments are only supported on multi-steps API tests, and are documented as such (note that the link is on api_step, not the top level request_definition.

**Comment by kuwas** [comment]
> therve

Ah, my mistake. Thanks for clarifying.
