### ISSUE TITLE
datadog_security_monitoring_rule rule with new_value cannot contain a named query

### ISSUE THREAD

**Issue by ebarti** [DataDog/terraform-provider-datadog#1394]
Hello there,

### Problem:

When creating a `new_value` security monitor, I struggled a bit. Main reasons:

- Documentation does not mention that `query.metric` can be used to aggregate over for `new_value` aggregations.
- Documentation does not specify that `query.name` cannot be used for monitors using `new_value` aggregations.

### The ask:

- Update documentation to reflect `query.metric`
- Update documentation to reflect the fact that `metric` is actually used in `new_value` type of aggregations.

**Comment by adussarps** [comment]
We should probably have an example available for each detection method.

**Comment by skarimo** [comment]
Closed by https://github.com/DataDog/terraform-provider-datadog/pull/1447
