### ISSUE TITLE
Feature request: Please support restricted_roles in datadog_synthetics_test resource

### ISSUE THREAD

**Issue by Jimcumming** [DataDog/terraform-provider-datadog#1420]
The v1 DataDog api supports the restricted_roles argument for synthetics https://docs.datadoghq.com/api/latest/synthetics/#edit-an-api-test
But this doesn't seem to be supported in the provider. The same option is already supported in the resource datadog_monitor. Can you please add support for this argument?

### Terraform Version
1.0.7

### Affected Resource(s)
- datadog_synthetics_test

### Terraform Configuration Files

```hcl
resource "datadog_synthetics_test" "synthetic" {
...
options_list {
...
   restricted_roles[var.role_id]
...
}
...
}
```

### Debug Output

```
Error: Unsupported argument

  on modules/synthetic/main.tf line 51, in resource "datadog_synthetics_test" "synthetic":
  51:     restricted_roles     = ["1cca88a0-bfe2-11ec-a89b-da7ad0900002"]

An argument named "restricted_roles" is not expected here.
```

### Expected Behavior
The synthetic test is created or updated with permissions restricting editing the test to specified roles

### Actual Behavior

An error is received as detailed above.

**Comment by skarimo** [comment]
Closed by: https://github.com/DataDog/terraform-provider-datadog/pull/1423
