### ISSUE TITLE
Migrating existing datadog monitors to terraform results in a duplicate monitor being created

### ISSUE THREAD

**Issue by eflann** [DataDog/terraform-provider-datadog#1425]
Migrating existing datadog monitors to terraform results in a duplicate monitor being created. Is there any way around this? 

### Terraform Version

Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

Terraform v1.1.7

### Affected Resource(s)

Please list the resources as a list:

-   **datadog_monitor_json**

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### Debug Output

Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output

If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior

What should have happened?

### Actual Behavior

What actually happened?

### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:

1. `terraform apply`

### Important Factoids

Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

### References

Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:

-   GH-1234

**Comment by irons** [comment]
After you create the resource in terraform, you can run `terraform import datadog_monitor_json.your-monitor-name existing-monitor-id-number`, rather than `terraform apply`, to pull the existing monitor into terraform's state. You'll probably run into #1445 unless you define a role UUID under `restricted_roles`, however.

**Comment by skarimo** [comment]
You can additionally use tools such as terraformer as well. Feel free to reopen if you have further questions.

**Comment by stiliajohny** [comment]
Is there a way to add an override option on the terraform resource? 
We running on this issue as well but we can't do a teraform import as we run it from terraform cloud
