### ISSUE TITLE
Could not retrieve the list of available versions for provider hashicorp/datadog

### ISSUE THREAD

**Issue by robmosca-travelperk** [DataDog/terraform-provider-datadog#1427]
Hi there,

### Terraform Version

1.1.5

### Affected Resource(s)

Provider initialisation

### Terraform Configuration Files

```hcl
datadog = {
      source  = "DataDog/datadog"
      version = "= 3.11.0"
    }
```

### Debug Output

```
Initializing provider plugins...
- Finding datadog/datadog versions matching "3.2.0"...
- Finding latest version of hashicorp/datadog...
- Finding hashicorp/aws versions matching "~> 3.75.0"...
- Installing datadog/datadog v3.2.0...
- Installed datadog/datadog v3.2.0 (signed by a HashiCorp partner, key ID FB70BE941301C3EA)
- Installing hashicorp/aws v3.75.1...
- Installed hashicorp/aws v3.75.1 (signed by HashiCorp)

Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/cli/plugins/signing.html
╷
│ Error: Failed to query available provider packages
│
│ Could not retrieve the list of available versions for provider
│ hashicorp/datadog: provider registry registry.terraform.io does not have a
│ provider named registry.terraform.io/hashicorp/datadog
│
│ Did you intend to use datadog/datadog? If so, you must specify that source
│ address in each module which requires that provider. To see which modules
│ are currently depending on hashicorp/datadog, run the following command:
│     terraform providers
╵

ERRO[0024] 1 error occurred:
	* exit status 1
```

### Panic Output

If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior

The provider is searched for in registry.terraform.io/datadog/datadog

### Actual Behavior

The provider is searched for in registry.terraform.io/hashicorp/datadog

### Steps to Reproduce

`terraform init`

### Important Factoids

Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

### References

Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:

-   GH-1234

**Comment by robmosca-travelperk** [comment]
Realised it was a problem on our side. Sorry for the noise.

**Comment by lorrin** [comment]
For anyone else bumping into this, see https://github.com/DataDog/terraform-provider-datadog/issues/1571#issuecomment-1254706383 for a possible cause.
