### ISSUE TITLE
Not able to find the attribute for Ignore Certificate Error in Terraform for Datadog Synethic Monitoring

### ISSUE THREAD

**Issue by surajtikoo** [DataDog/terraform-provider-datadog#1429]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see https://www.terraform.io/community.html.

### Affected Resource(s)
I am using terraform to build the Datadog Synthetic Monitoring to create the API Resource in Datadog. I am able to create but I need to ignore the certificate part. With the terraform synthetic monitoring documentation I am not able to find the attribute for ignoring Certificate Error in Terraform for Datadog Synthetic Monitoring

### Debug Output

Please provide a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output

If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior

What should have happened?

### Actual Behavior

What actually happened?

### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:

1. `terraform apply`

![image](https://user-images.githubusercontent.com/40026947/165670188-478e2b49-655b-48db-8d60-e14e2ae7440e.png)

**Comment by Drarig29** [comment]
Hi @surajtikoo!

The attribute you are searching is `allow_insecure`.

Here is an example:

```tf
options_list {
  allow_insecure = true
}
```
