### ISSUE TITLE
Error when removing an SLO linked from a dashboard

### ISSUE THREAD

**Issue by lhelman** [DataDog/terraform-provider-datadog#1436]
When removing an SLO which is shown in a dashboard, you get an error:

```
Error: error deleting service level objective from https://api.datadoghq.com/api/v1/slo/abc..... 409 Conflict: {"errors":"slo abc is referenced in dashboard_id: xxx-yyy-zzzj","data":null}
```

The SLO was also removed from the dashboard in terraform, so it is a matter of ordering the operations - graph

Manually removing the dashboard and letting terraform to recreate it, works

**Comment by therve** [comment]
Hi,

I don't think the provider has any mechanism to handle operation dependencies. I think some more recent Terraform versions may have improved the behavior, but I don't know which one you're using. The resource has a `force_delete` to work around that situation, so I'll close that one for now. Thanks.
