### ISSUE TITLE
Allow disabling name resolution in synthetics_test Terraform resource

### ISSUE THREAD

**Issue by ericarellanom** [DataDog/terraform-provider-datadog#1446]
Hello!

### Terraform Version

1.1.9

### Affected Resource(s)

- datadog_synthetics_test

### Terraform Configuration Files

Not sure if this is a missing documentation or feature.  I am able to build Synthetic Tests using the DataDog provider 3.11.0 but I don't see any way to programmatically disable DNS resolution in the responseTime, which is available via the GUI.

Steps to reproduce:  

1. create Synthetic Test (simple, API, or multistep) and select request responseTime **without DNS** is less than __ms in the web GUI

2. Export the synthetic test using Terraformer.  Verify there is no DNS setting in the exported config

3. Attempted using dns_server or dns_server_port set to invalid values to force this with no success.

    `dns_server_port = "0"
     dns_server              = "0"`

### Debug Output

    assertion {
      operator = "lessThan"
      target   = "1000"
      type     = "responseTime"
    }

### Expected Behavior

Specify dns_resolution = False to disable name resolution the assertion responseTime step

### Actual Behavior

This feature does not seem to be available or is not documented in the API and Terraform provider

#### Workaround(s)

Account for DNS in synthetic test latency.  Using http_check for local Datadog Agent based synthetics.

**Comment by pkgit** [comment]
same here!

**Comment by nkzou** [comment]
Resolved by #2101 . This missed our last release window so it will be available in our next release, planned for mid-October.
