### ISSUE TITLE
Unable to use "show_priority" parameter for "manage_status_definition" widget in terraform

### ISSUE THREAD

**Issue by aggarwal-payal** [DataDog/terraform-provider-datadog#1461]
Hi there,

### Terraform Version

Terraform v1.2.2
on windows_386
+ provider registry.terraform.io/datadog/datadog v3.12.0

### Affected Resource(s)

List the resources as a list

-   datadog_dashboard (Resource) "manage_status_definition" widget in a datadog dashboard through terraform

### Terraform Configuration Files

```hcl
manage_status_definition {
      summary_type        = "monitors"
      title               = "Monitors"
      title_size          = 13
      title_align         = "left"
      color_preference    = "text"
      display_format      = "countsAndList"
      hide_zero_counts    = true
      show_last_triggered = true
      **show_priority        = true**
      query = "tag:(component:db)"
      **sort  = "priority,desc"**
    }
```

### Output

![image](https://user-images.githubusercontent.com/95336212/172372300-6be9ddab-93b1-4934-97c5-6950b3859879.png)

### Expected Behavior

It should create a Manage Status widget to dashboard showing the priority column and sort it with priority but its not supported through terraform, also there is no such parameter in terraform datadog_dashboard resource for "manage_status_definition" widget but it is there on UI of Datadog and It should be available for datadog terraform resource. 

Highlight part is the fields those are not supported by datadog terraform resource
![image](https://user-images.githubusercontent.com/95336212/172373118-a03d9e26-79a1-4423-96a1-5a662fcd8335.png)

### Actual Behavior

Throwing error
**"show_priority"** field is also available in dashboards json but not supported by terraform. 
![image](https://user-images.githubusercontent.com/95336212/172373318-1e8cd780-2d57-43e4-960a-7e928607fa1f.png)

**sort = "priority,desc"** should be supported through Datadog terraform resource as it is supported by Datadog UI.
![image](https://user-images.githubusercontent.com/95336212/172373678-8c40915b-2fdb-4918-a748-87e8da7c758f.png)

**Comment by skarimo** [comment]
Closed by #1525. Thanks for the report
