### ISSUE TITLE
Unsupported dashboard widget type "Live" in terraform

### ISSUE THREAD

**Issue by aggarwal-payal** [DataDog/terraform-provider-datadog#1468]
Hi there,

I need to create a "Live stream" widget in dashboard through terraform but this widget type is not supported by terraform.

![image](https://user-images.githubusercontent.com/95336212/174252039-cb337782-4497-4a7d-b666-cf3345d939a1.png)

## Terraform Version
Terraform v1.2.2
on windows_386
provider registry.terraform.io/datadog/datadog v3.12.0

## Affected Resource(s)
List the resources as a list

- datadog_dashboard (Resource)

## Expected Behavior
Support for "Live" list and stream widget type to have logs grouped by patterns.

## Actual Behavior
Unsupported in terraform, no such widget type is available.

## Widget .json 
{
                        "id": xxxxxxx,
                        "definition": {
                            "title": "Top Log Patterns",
                            "title_size": "16",
                            "title_align": "left",
                            "requests": [
                                {
                                    "query": {
                                        "query_string": "",
                                        "data_source": "logs_pattern_stream",
                                        "group_by": [
                                            {
                                                "facet": "service"
                                            }
                                        ],
                                        "indexes": []
                                    },
                                    "response_format": "event_list",
                                    "columns": [
                                        {
                                            "field": "status_line",
                                            "width": "auto"
                                        },
                                        {
                                            "field": "matches",
                                            "width": "auto"
                                        },
                                        {
                                            "field": "volume",
                                            "width": "auto"
                                        },
                                        {
                                            "field": "service",
                                            "width": "auto"
                                        },
                                        {
                                            "field": "message",
                                            "width": "auto"
                                        }
                                    ]
                                }
                            ],
                            "type": "list_stream"
                        },
                        "layout": {
                            "x": 0,
                            "y": 0,
                            "width": 12,
                            "height": 4
                        }
                    }

**Comment by mazamachi** [comment]
I want `logs_pattern_stream` widget too!
It's very useful for finding frequently occurring errors in dashboard.

**Comment by skarimo** [comment]
Support for `list_stream` widget were added by: https://github.com/DataDog/terraform-provider-datadog/pull/1470

@mazamachi your request will be closed by: https://github.com/DataDog/datadog-api-client-go/pull/1633
