### ISSUE TITLE
Feature request: add a data 'restriction query' resource and data source

### ISSUE THREAD

**Issue by robotparty** [DataDog/terraform-provider-datadog#1477]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
This is a provider feature request but I am running v1.2.1

### Affected Resource(s)
I'm requesting that a resource and data source be added for configuring data restriction queries as described here: https://docs.datadoghq.com/logs/guide/logs-rbac/?tabs=api
This feature is exposed in the API but I don't see anything in this provider related to it. 
We need to create quite a few of these restriction queries and it'd be nice to manage them in TF with the rest of our config. Thx!

**Comment by phifre** [comment]
Duplicate of #1217

**Comment by skarimo** [comment]
Closing in favor of #1217
