### ISSUE TITLE
'tick_every' only has limited values (undocumented)

### ISSUE THREAD

**Issue by AshKapow** [DataDog/terraform-provider-datadog#1484]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version

Terraform v1.0.4 on darwin_arm64

### Affected Resource(s)

- datadog_synthetics_test

### Expected Behavior

According to the documentation and the Datadog UI, you can set any integer for the 'tick_every' section for Datadog Synthetics Test

### Actual Behavior

When applying via Terraform, this error is reported 
`SyntheticsTickInterval: valid values are [30 60 300 900 1800 3600 21600 43200 86400 604800]`

### References

https://registry.terraform.io/providers/DataDog/datadog/latest/docs/resources/synthetics_test#tick_every

**Comment by nkzou** [comment]
The API has since been updated and the `tick_every` field can be any integer between 30-604800. (300-604800 for browser tests).
