### ISSUE TITLE
How to specify a synthetics_check_id to a "synthetics alert" monitor?

### ISSUE THREAD

**Issue by irons** [DataDog/terraform-provider-datadog#1492]
I'd like to be able to create a DD monitor in terraform of the supported type `synthetics alert`, preferably as a `datadog_monitor_json`, but if necessary using HCL syntax as a `datadog_monitor`. The "synthetics_check_id" found in the API representation of a synthetics-linked monitor created through the web interface seems to be the essential element, but it's not available as an attribute of the [datadog_monitor](https://registry.terraform.io/providers/DataDog/datadog/latest/docs/resources/monitor) resource. 

### Terraform Version

datadog provider 3.13.1 

### Affected Resource(s)

Please list the resources as a list, for example:

-   datadog_monitor
-   datadog_monitor_json

### Terraform Configuration Files

```hcl
resource "datadog_monitor" "synthetics-monitor-test" {
  name               = "sample synthetics-linked monitor"
  type               = "synthetics alert"
  message            = "test message"
  query              = "no_query"
  include_tags       = true
  tags               = ["env:prod"]
  # synthetics_check_id = "gt7-vmc-k2y"
}
```

### Expected Behavior

This sample should complain that I haven't provided a valid ID for a synthetic, specifying the name of the check_id attribute that I failed to specify.

### Actual Behavior

I haven't found any way to specify the `synthetics alert` type without generating this error:
```
│ Error: error creating monitor from https://api.datadoghq.com/api/v1/monitor: 400 Bad Request: {"errors": ["Cannot directly update a Synthetics Monitor, use Synthetics API instead."]}
```

### Steps to Reproduce

1. `terraform plan`

**Comment by therve** [comment]
Hi,

You shouldn't need to do anything with the synthetics generated monitor. Can you explain what you're trying to achieve? Do you want several monitors associated with the same synthetics test? Thanks.

**Comment by irons** [comment]
The team responsible for monitors wants to manage them in terraform, reasonably. The team responsible for synthetics does not want to manage them in terraform, also reasonably. The existence of the `synthetics alert` monitor type suggested we could divide the responsibilities along those lines, but Datadog support case 862235 recently told us that we can't:

> Engineering has confirmed that synthetics alerts monitors cannot be managed via the datadog_monitor resources. The reference to this being an accepted type is inaccurate in the documentation and I've made the product and engineering teams aware of this inaccuracy and asked that it be updated.

We're going to move away from synthetics for these monitoring scenarios.

**Comment by therve** [comment]
OK, sorry it doesn't fit your need. Closing this issue for now, thanks.

**Comment by sosafe-bastian-bretagne** [comment]
I've recently moved to terraform to manage our monitors, this error also prevent us from using terraform to provision them.
