### ISSUE TITLE
Allow timingsScope in responseTime assertions

### ISSUE THREAD

**Issue by drmaciej** [DataDog/terraform-provider-datadog#1493]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version

1.1.7

### Affected Resource(s)

datadog_synthetics_test

### Terraform Configuration Files

Here's a relevant snippet:
```hcl
  assertion {
    type     = "responseTime"
    operator = "lessThan"
    target   = 100
  }
```

### Expected Behavior

If an assertion is specified for `response time`, it defaults to `including DNS`.

### Actual Behavior

If an assertion is specified for `response time`, it should be possible to specify `including DNS` or `without DNS`. In the API, this is specified as follows:
```
{
  "operator": "lessThan",
  "type": "responseTime",
  "target": 100,
  "timingsScope": "withoutDNS"
}
```

**Comment by briceburg** [comment]
👍 It is important to allow the exclusion of DNS time from time-to-first byte. The DataDog API and UI allows for this;

<img width="736" alt="image" src="https://user-images.githubusercontent.com/490144/225109270-9a0b3e8d-d490-41de-98a2-8a2c8fce9249.png">
