### ISSUE TITLE
Support to enable "calculate_percentiles" on "datadog_logs_metric" resources

### ISSUE THREAD

**Issue by zmotu** [DataDog/terraform-provider-datadog#1510]
### Terraform Version

v1.2.4

### Affected Resource(s)

-   datadog_logs_metric

### Terraform Configuration Files

```hcl
resource "datadog_logs_metric" "latency_metric" {
  count = length(var.slos)
  name = "slo.edge.${lower(var.parent)}.${var.slos[count.index].key}.ttfb_ms"

  compute {
    aggregation_type = "distribution"
    path             = "@EdgeTimeToFirstByteMs"
  }

  filter {
    query = "source:cloudflare ${var.slos[count.index].dd_filter}"
  }
  # calculate_percentiles = true # Unfortunately, this isn't available via terraform just yet.
}
```

![image](https://user-images.githubusercontent.com/2383784/181398436-e27396dc-f428-4ced-9fa2-9705945df7a2.png)

### Expected Behavior

The ability to configure whether percentiles should be calculated for distribution metrics created from logs via the "datadog_logs_metrics" resource in terraform. 

### Actual Behavior

No such attribute to configure this is available on the resource currently. 

### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:

1. Uncomment `calculate_percentiles = true` line from above configuration example
1. `terraform apply`

### Important Factoids

Have tried using the `datadog_metric_metadata` resource instead to enable this but got an error noting the metric was generated from logs. 

### References
 - nil

**Comment by nkzou** [comment]
Hi,
With e7eccd33eec9febc6f5b05a96ec23acd39f9d4d1 this functionality will be available in the next release of the provider, which we expect to happen in the next week.
It's been named `include_percentiles` and can be used via the `compute` block, for example:
```terraform
resource "datadog_logs_metric" "testing_logs_metric" {
	name = "exampleLogsMetric"
	compute {
		aggregation_type    = "distribution"
		path                = "@duration"
		include_percentiles = false
	}
	filter {
		query = "service:test"
	}
	group_by {
		path     = "@my.status"
		tag_name = "status"
	}
	group_by {
		path     = "service"
		tag_name = "service"
	}
}
```
Thanks for your feature request, and feel free to reopen the issue if any problems arise.
