### ISSUE TITLE
Service Catalog

### ISSUE THREAD

**Issue by djtecha** [DataDog/terraform-provider-datadog#1511]
Looks like we can now set service catalog information. It would be really nice to be able to use the provider to set this type of data.

https://docs.datadoghq.com/tracing/service_catalog/service_definition_api/

**Comment by djtecha** [comment]
Awesome, thank you!

**Comment by taltcher** [comment]
Is there anything new regarding this PR? something I'm waiting for as well 😄 anyway we can try and move forward with it?

**Comment by mattcanty-ikigai** [comment]
Think it is close, not sure which will win though!
https://github.com/DataDog/terraform-provider-datadog/pull/1556
https://github.com/DataDog/terraform-provider-datadog/pull/1521

**Comment by AesaKamar** [comment]
Looks like https://github.com/DataDog/terraform-provider-datadog/pull/1556 is freshly merged (:
