### ISSUE TITLE
is there support for Datadog Synthetic Browser test in Terraform?

### ISSUE THREAD

**Issue by geetabodati** [DataDog/terraform-provider-datadog#1514]
Hi there,

We are trying to write Synthetic Browser test using Terraform, But the params are not explained in the document properly. When i am using "runApiTest" for "HTTPTest" it's showing below error.
"""
 Error: error updating synthetics browser test from https://api.datadoghq.com/api/v1/synthetics/tests/browser/duw-zqv-55d: 400 Bad Request: {"errors": ["Invalid steps data: Step 0 has invalid params: None is not of type 'object'"]}
│
│   with datadog_synthetics_test.test_ps_ui_v2_dev,
"""

I tried different params which mentioned in the Terraform standard document. No Params are working for this scenario.
Could you please let me know if i miss anything to add "HTTPTest" under browser test. Could you please provide list of supported params with example if possible.

I am expecting to write below mentioned test case.
![image](https://user-images.githubusercontent.com/72452869/182139171-59de8b88-b0c0-4403-847d-2ddc1afd1dc7.png)

### Terraform Version

$ terraform -v
Terraform v1.2.4
on windows_amd64
+ provider registry.terraform.io/datadog/datadog v3.14.0

Your version of Terraform is out of date! The latest version
is 1.2.6. You can update by downloading from https://www.terraform.io/downloads.html

### Affected Resource(s)

datadog_synthetics_test

### Terraform Configuration Files
resource "datadog_synthetics_test" "test_ps_ui_v2_dev" {
  type = "browser"

  request_definition {
    method = "GET"
    url    = "https://google.com"
  }

  device_ids = ["laptop_large"]
  locations  = ["aws:us-east-2"]

  options_list {
    tick_every = 900
  }

  name    = "A Browser test (DEV)"
  message = "DEV synthetic test failure"

  status = "live"
  browser_step {
    name = "Check current url"
    type = "runApiTest"
    params {
      request =  "https://google.com"
    } 
  }
}

### Debug Output
 Error: error updating synthetics browser test from https://api.datadoghq.com/api/v1/synthetics/tests/browser/duw-zqv-55d: 400 Bad Request: {"errors": ["Invalid steps data: Step 0 has invalid params: None is not of type 'object'"]}
│
│   with datadog_synthetics_test.test_ps_ui_v2_dev,

### Panic Output

No Panic

### Expected Behavior

It should add HTTPTest in Browser test of Datadog.

### Actual Behavior

Getting Error while running terraform apply.

### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:

1. `terraform apply`

**Comment by skarimo** [comment]
Hi, it is supported. Here is an example: https://github.com/DataDog/terraform-provider-datadog/blob/master/datadog/tests/resource_datadog_synthetics_test_test.go#L2838-L2854


```
resource "datadog_synthetics_test" "test_ps_ui_v2_dev" {
  type = "browser"

  request_definition {
    method = "GET"
    url = "https://google.com"
  }

  device_ids = ["laptop_large"]
  locations = ["aws:us-east-2"]

  options_list {
    tick_every = 900
  }

  name = "A Browser test (DEV)"
  message = "DEV synthetic test failure"

  status = "live"
	browser_step {
		name = "api step"
		type = "runApiTest"
		params {
			request = jsonencode({
				"config": {
					"assertions": [],
					"request": {
						"method": "GET",
						"url": "https://example.com"
					}
				},
				"options": {}
        		"subtype": "http",
      		})
		}
	}
}
```

You can look further at the test file for additional examples.
