### ISSUE TITLE
datadog_monitor_json Drift with period block

### ISSUE THREAD

**Issue by smc87** [DataDog/terraform-provider-datadog#1516]
### Terraform Version

gitlab-terraform -v
Terraform v1.1.9
on linux_amd64

### Affected Resource(s)

datadog_monitor_json

####Config
{
	"id": 78467471,
	"name": "My alert",
	"type": "log alert",
	"query": "logs("my query") >= 10",
	"message": "my message",
	"tags": [],
	"options": {
		"thresholds": {
			"critical": 10,
			"period": {
				"digit": 1,
				"name": "1 minute average",
				"no_data_timeframe": 2,
				"seconds": 60,
				"tense": "last",
				"text": "1 minute",
				"unit": "minutes",
				"value": "last_1m",
				"timeString": "1m",
				"unitAbbreviation": "m"
			},
			"timeAggregator": "avg",
			"comparison": ">="
		},
		"enable_logs_sample": true,
		"notify_audit": false,
		"restriction_query": null,
		"on_missing_data": "show_no_data",
		"silenced": {},
		"include_tags": true,
		"groupby_simple_monitor": false,
		"new_group_delay": 60
	},
	"priority": null,
	"restricted_roles": null
}

### Expected Behavior

On second run of terraform, there should be no changes detected

### Actual Behavior

Drift is always detected when there is a period block included in the JSON

### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:

1. terraform plan, terraform apply, terraform plan

**Comment by skarimo** [comment]
👋 I have chatted with the respective team and they have a card in there back log to remove the "period" block from the thresholds when exporting monitor from the edit page. The only required key in the threshold block from your example is 'critical'. 

With that said, you can export a monitor from the monitors page (vs the monitors edit page) and it will not be included in the definition. Im going to close this issue but the respective team has a card in their backlog as this is a UI behavior when exporting a monitor from the edit page. Thanks!
