### ISSUE TITLE
Getting 400 Bad Request: {"errors":["The monitor's restricted roles is expected to be an array of UUID strings."]}

### ISSUE THREAD

**Issue by fredflev** [DataDog/terraform-provider-datadog#1539]
Getting a 400 bad request from Datadog validate API when running terraform plan. 

With error: 

```JSON
Error: error validating monitor from https://api.datadoghq.eu/api/v1/monitor/XXXXXXX/validate: 400 Bad Request: {"errors":["The monitor's restricted roles is expected to be an array of UUID strings."]}
```
Note: `XXXXXXX` is the Redacted monitor number

### Terraform Version

Terraform `v1.2.4` 

Note: Same issue with Terraform `v1.2.8` 

### Provider Version

 datadog/datadog `v3.14.0`

### Affected Resource(s)

- datadog_monitor

### Terraform Configuration Files

```hcl
resource "datadog_monitor" "datadog_agent" {
  
  type               = "service check"
  name               = "Not relevant"
  query              = "Not relevant"
  escalation_message = "Not relevant"
  message            = "Not relevant"
  renotify_interval  = var.datadog_renotify_interval
  restricted_roles   = ["XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"] # Datadog Admin Role
  notify_no_data     = true
  no_data_timeframe  = 20

  tags = []

  monitor_thresholds {
  }
}
```

The UUID in `restricted_roles` has the same format as any standard UUID. 

Such as: 

```console
 uuidgen               
F9692CA4-F87E-4BA3-AAFB-DCECE31262EC
```

It was retrieved using: 

```console
 curl -sX GET "https://api.datadoghq.eu/api/v2/roles" \
-H "Content-Type: application/json" \
-H "DD-API-KEY: ${DATADOG_API_KEY}" \
-H "DD-APPLICATION-KEY: ${DATADOG_APP_KEY}" | jq  '.data[] | select(.attributes.name=="Datadog Admin Role") | .id'
```

### Debug Output

Running plan with `TF_LOG=debug` doesn't give any additional relevant info.

### Expected Behavior

No error from the Datadog API during `validate`.

### Actual Behavior

```console
Error: error validating monitor from https://api.datadoghq.eu/api/v1/monitor/XXXXXXX/validate: 400 Bad Request: {"errors":["The monitor's restricted roles is expected to be an array of UUID strings."]}
```

### Steps to Reproduce

Just create any `datadog_monitor` resource with the `restricted_roles` value set to ` ["XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"]` with `XXX` set to your Datadog admin role UUID. 

Since my code hasn't changed and was working a few days ago I am guessing that this might be due to an API change on Datadog side.

**Comment by therve** [comment]
This is indeed a backend issue, team is working on a fix and it should be deployed quickly. Thanks for your patience.

**Comment by therve** [comment]
This should be resolved, sorry for the trouble.

**Comment by fredflev** [comment]
> This should be resolved, sorry for the trouble.

All good now. Thanks!
