### ISSUE TITLE
state decoding errors upgrading from provider v2.25 to v3.12

### ISSUE THREAD

**Issue by chicks-net** [DataDog/terraform-provider-datadog#1545]
### Terraform Version

```
% terraform -v
Terraform v1.2.8
on darwin_arm64
+ provider registry.terraform.io/datadog/datadog v3.14.0
+ provider registry.terraform.io/hashicorp/vault v3.1.1
```

### Affected Resource(s)

-   datadog_monitor

### Terraform Configuration Files

Too large to include and probably not relevant to this question.

### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior

It would be great if the current provider could read the state from the older providers and fixup whatever is needed.

It would also be great of the process of upgraded providers was documented somewhere.

### Actual Behavior

A series of complaints about tfstate....

The first set of problems that I cleared up was getting rid of the silenced attribute on monitors when it was an empty hash or null. Those were leading to errors like:

```
[ERROR] [STDERR] ╷
[ERROR] [STDERR] │ Error: Failed to decode resource from state
[ERROR] [STDERR] │
[ERROR] [STDERR] │ Error decoding
[ERROR] [STDERR] │ "module.aws_limit_monitoring_979323271173.datadog_monitor.aws_limit_monitor[33]"
[ERROR] [STDERR] │ from previous state: unsupported attribute "silenced"
[ERROR] [STDERR] ╵
```

Now I'm getting:

```
[ERROR] [STDERR] ╷
[ERROR] [STDERR] │ Error: Failed to decode resource from state
[ERROR] [STDERR] │
[ERROR] [STDERR] │ Error decoding
[ERROR] [STDERR] │ "module.aws_limit_monitoring_370025973162.datadog_monitor.aws_limit_monitor[20]"
[ERROR] [STDERR] │ from previous state: unsupported attribute "threshold_windows"
[ERROR] [STDERR] ╵
```

Should these be renamed from `threshold_windows` to `monitor_threshold_windows` in the tfstate as we did in the terraform HCL code?  Should we do the same for `thresholds` to `monitor_thersholds`?

### Steps to Reproduce

1. `terraform plan` with tfstate from v2.25 using provider v3.12.

### Important Factoids

Old tfstate is from provider v2.25, but we'd like to upgrade everything to provider v3.12.

### References

N/A

**Comment by skarimo** [comment]
Hi, with the v3 of the provider, there were several attributes renamed and updated. See full list here: https://github.com/DataDog/terraform-provider-datadog/blob/master/CHANGELOG.md#300-may-27-2021

All of these removed fields will need to be updated to the new format. What you can do is update to latest v2 of the provider, update all deprecated keys to their respective replacement so the state updates properly. And then update to v3.

You can update the state file directly as well but would just need make sure attributes are correct types and format

**Comment by skarimo** [comment]
Closing this, feel free to re-open if need be.
