### ISSUE TITLE
IAM role with path cannot be used with datadog_integration_aws

### ISSUE THREAD

**Issue by dhohengassner** [DataDog/terraform-provider-datadog#1551]
### Terraform Version

Terraform v1.2.8

### Affected Resource(s)

Please list the resources as a list, for example:

-   datadog_integration_aws

### Terraform Configuration Files

```hcl
resource "datadog_integration_aws" "integrate_aws_account" {
  account_id       = data.aws_caller_identity.current.account_id
  role_name        = "test-role"
  excluded_regions = var.excluded_regions
}

```

### Expected Behavior

We do like to use an IAM role which is placed in a path:
https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_identifiers.html#identifiers-friendly-names

The IAM role name needs to be unique in an account so we expected the provider should be able to find the correct ARN with the name.

### Actual Behavior

Datadog is not able to assume the IAM role. Probably this happens because the path is also used in the AWS ARN.

Example without path:
`arn:aws:iam::123456789:role/test-role`

Example with path:
`arn:aws:iam::123456789:role/datadog/test-role`

### Steps to Reproduce

Use an IAM role which uses a path and use this for datadog integration.

This will cause an error:
```
Datadog is not authorized to perform action sts:AssumeRole Accounts affected:
```

In general it is possible this is more a Datadog issue itself than a terraform provider issue.

**Comment by jvanbrie** [comment]
Hi there, here from Datadog. This has to do with how we call sts:AssumeRole on your behalf. We need to generate the role ARN and we generate it by placing your role name after `arn:aws:iam::<YOUR_ACCOUNT_ID>:role/`. So if you pass us the role name with the path (ex: `datadog/test-role`), that should fix your issue. If not feel free to open a support ticket with us and we can take a look, but I agree with you that I don't think this is an issue with the terraform resource itself.
