### ISSUE TITLE
Can we have multiple datadog_users invite by terraform code?

### ISSUE THREAD

**Issue by RaghavK12RK** [DataDog/terraform-provider-datadog#1558]
Hi, I have tried with this `count` pattern for datadog_user to get the multiple invites in `var.tf` given as type= list(string) its only accepting for 2 users, I need more than 2 users invites, Can we have a solution by terraform code.

resource "datadog_user" "dd_user" {
  count    = length(var.user_email_ids)

  email  = var.user_email_ids[count.index]
  roles  = [data.datadog_role.user_role.id]
}

**Comment by skarimo** [comment]
Not sure if I entirely understand the issue here, can you elaborate. If you mean that `count` keyword  is creating only 2 instances of the `datadog_user` then I would double check that the user_email_ids variables define more than 2 values. I tested out the example you sent and it works with more than 2 resource instances.

**Comment by srosenthal-dd** [comment]
I tested this out locally and was able to create 5 Datadog users using this pattern

```
variable "user_email_ids" {
  type = list(string)
  default = [
    "a@datadoghq.com",
    "b@datadoghq.com",
    "c@datadoghq.com",
    "d@datadoghq.com",
    "e@datadoghq.com"
  ]
}

resource "datadog_user" "dd_user" {
  count = length(var.user_email_ids)

  email = var.user_email_ids[count.index]
  roles = [datadog_role.role.id]
}
```

**Comment by RaghavK12RK** [comment]
Thanks for the kind reply!

But, When i run the run for the multiple user invites dd_user with default `Datadog Admin Role` it is failing for provider plugin crashed.

![image](https://user-images.githubusercontent.com/109405973/189330789-451ccc6a-5a02-4951-b625-07ca9de267f9.png)

#reource code
resource "datadog_user" "user_email" {
  count    = length(var.user_email_ids) 

  email  = var.user_email_ids[count.index]
  roles = [data.datadog_role.user_role.id]
}

variable "user_email_ids" {
  type = list(string)
  default = [
              "1@gmail.com",
              "2@gmail.com",
              "3@gmail.com",
              "4@gmail.com",
              "5@gmail.com" 
  ]
}
 Error: The terraform-provider-datadog_v3.15.0.exe plugin crashed!

**Comment by RaghavK12RK** [comment]
Datadog plugin is having the support feature of multiple dd_user invites?

**Comment by RaghavK12RK** [comment]
Issue resolved, Working fine now, Thank you!

**Comment by RaghavK12RK** [comment]
Closing this issue
