### ISSUE TITLE
invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by wojukasz** [DataDog/terraform-provider-datadog#1559]
### Terraform Version

Terraform v1.2.8

### Affected Resource(s)
-  data: datadog_ip_ranges

### Terraform Configuration Files

```hcl
provider "datadog" {
  api_url = "https://api.datadoghq.eu/"
  api_key = var.api_key
  app_key = var.app_key
}

terraform {
  required_providers {
    datadog = {
      source  = "datadog/datadog"
      version = "= 3.15"
    }
  }
}

data "datadog_ip_ranges" "this" {}

output "datadog_ip_ranges" {
  value = data.datadog_ip_ranges.this
}
```

### Debug Output

```
data.datadog_ip_ranges.this: Reading...
╷
│ Error: invalid character '<' looking for beginning of value
│
│   with data.datadog_ip_ranges.this,
│   on datadog.tf line 16, in data "datadog_ip_ranges" "this":
│   16: data "datadog_ip_ranges" "this" {}
│
```

### Expected Behavior

terraform plan to succed and provide IP ranges.

### Actual Behavior

terraform plan failed to provide IP ranges with following error:   
`Error: invalid character '<' looking for beginning of value`  

### Steps to Reproduce

Use above terraform hcl code snippet,
1. populate variables: app_key, api_key
2. terraform init
3. terraform plan

### Important Factoids

This issue doesn't occur with datadog provider 3.14.
Changing ` version = "= 3.15"` to `3.14` results with working plan.
### References

Other issue with same error:
https://github.com/DataDog/terraform-provider-datadog/issues/1065 
https://github.com/DataDog/terraform-provider-datadog/issues/364  
https://github.com/DataDog/terraform-provider-datadog/issues/364

**Comment by skarimo** [comment]
We just released v3.15.1 with the fix included. Thanks for the report!
