### ISSUE TITLE
datadog_security_monitoring_rule always passes the query.metric field to Datadog's API

### ISSUE THREAD

**Issue by sdinay** [DataDog/terraform-provider-datadog#1562]
### Terraform Version

```
terraform -v
Terraform v1.2.9
on darwin_amd64
+ provider registry.terraform.io/datadog/datadog v3.15.1
```

### Affected Resource(s)

-   datadog_security_monitoring_rule

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    datadog = {
      source  = "DataDog/datadog"
      version = "3.15.1"
    }
  }
}

provider "datadog" {
}

# This is the current example from the Terraform Datadog provider documentation.
# I also tried importing a rule and changing all these values to match the rule based on the "terraform state show" output with no success.
resource "datadog_security_monitoring_rule" "myrule" {
  name = "My rule"

  message = "The rule has triggered."
  enabled = true

  query {
    name            = "errors"
    query           = "status:error"
    aggregation     = "count"
    group_by_fields = ["host"]
  }

  query {
    name            = "warnings"
    query           = "status:warning"
    aggregation     = "count"
    group_by_fields = ["host"]
  }

  case {
    status        = "high"
    condition     = "errors > 3 && warnings > 10"
    notifications = ["@user"]
  }

  options {
    evaluation_window   = 300
    keep_alive          = 600
    max_signal_duration = 900
  }

  tags = ["type:dos"]
}
```

### Debug Output

The main part from the debug logs that I think is the issue are the fields being passed to the Datadog API.
Even if the `query.metric` field is not passed in through Terraform, the API request still has it:

```json
  "queries": [
    {
      "aggregation": "count",
      "distinctFields": [],
      "groupByFields": [
        "host"
      ],
      "metric": "",
      "name": "errors",
      "query": "status:error"
    },
```

### Expected Behavior

The `datadog_security_monitoring_rule.myrule` resource is created.

### Actual Behavior

If I don't have `metric` or `metrics` in the query block I see this:

```
│ Error: error creating security monitoring rule from https://api.datadoghq.com/api/v2/security_monitoring/rules: 400 Bad Request: {"errors":["Invalid rule configuration","Metrics fields can't be null or empty"]}
```

If I add `metrics = ["anything"]` to the query block, I see this:

```
│ Error: error creating security monitoring rule from https://api.datadoghq.com/api/v2/security_monitoring/rules: 400 Bad Request: {"errors":["Invalid rule configuration","Metrics and metric cannot both be defined; please only use \"metrics\" as \"metric\" is deprecated"]}
```

I believe this is because the `metric` field is always being passed to the API.

If I add a `metric` field I see this error:
```
Metrics not allowed for this aggregation type
```

Note: The particular rule that I imported and then created the Terraform code for, had `metric = []` set in the Terraform state.

### Steps to Reproduce

Copy the terraform code above to a file and run the following commands against the Terraform:
(You will need a DataDog API key)
1. `terraform init`
2. `terraform apply`

### References

I tried to revert back to the Datadog version 3.14.0, before this issue was released but I get the same behavior.
- https://github.com/DataDog/terraform-provider-datadog/pull/1506

**Comment by therve** [comment]
Hi,

Backend changed behavior, we'll revert back to something that works with terraform. We'll fix terraform then to not pass it when it's empty.

**Comment by therve** [comment]
This has been fixed.
