### ISSUE TITLE
resource datadog_synthetics_test does not support operator "validatesXPath"

### ISSUE THREAD

**Issue by S-Bohn** [DataDog/terraform-provider-datadog#1563]
Hi there,

I tried to import an existing test into Terraform and it failed with
```
│ Error: object contains unparsed element: map[operator:validatesXPath target:map[operator:is targetValue:female xPath://user/results/gender] type:body]
```

The issue should have been fixed with https://github.com/DataDog/terraform-provider-datadog/issues/1173 – but apparently it isn't the case.

### Terraform Version

```
➜  datadog git:(master) ✗ terraform -v
Terraform v1.2.9
on darwin_arm64
+ provider registry.terraform.io/datadog/datadog v3.15.1
```

### Affected Resource(s)

- datadog_synthetics_test

### Terraform Configuration Files

```hcl
resource "datadog_synthetics_test" "bug" {
  name      = "Test"
  type      = "api"
  subtype   = "multi"
  status    = "live"
  locations = []
}
```

### Debug Output

https://gist.github.com/S-Bohn/91027e00c9c93a5f4148a159856fe428

### Expected Behavior

The resource gets imported.

### Actual Behavior

```
│ Error: object contains unparsed element: map[operator:validatesXPath target:map[operator:is targetValue:female xPath://user/results/gender] type:body]
```

### Steps to Reproduce

```
terraform import 'datadog_synthetics_test.bug' mtc-2mk-qzh
```

### Important Factoids

Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

### References

Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:

- GH-1173
- https://github.com/DataDog/datadog-api-client-go/pull/1070

**Comment by skarimo** [comment]
Thanks for the report. This is closed by: https://github.com/DataDog/terraform-provider-datadog/pull/1632
