### ISSUE TITLE
Feature Request: add datadog_integration_confluent_cloud

### ISSUE THREAD

**Issue by miguelaferreira** [DataDog/terraform-provider-datadog#1565]
It would be very useful for my team to terraform the integration between DataDog and Confluent Cloud. Following the [DataDog integration documentation](https://www.datadoghq.com/blog/confluent-cloud-monitoring-datadog/#add-your-api-key-to-datadog), the new resource would need to allow for a Confluent Cloud API key, and a set of managed resources.

### Affected Resource(s)

Please list the resources as a list, for example:

-   `datadog_integration_confluent_cloud`

### Terraform Configuration Files

```hcl
resource "datadog_integration_confluent_cloud" {
  api_key    = confluent_api_key.example.id
  api_secret = confluent_api_key.example.id

  managed_resource {
    id   = confluent_kafka_cluster.example.id
    type = "Cluster"
    tags = ["connect_cluster2"]
  }

  managed_resource {
    id   = confluent_connector.example.id
    type = "Connector"
    tags = ["datagen", "foo:bar"]
  }
}
```

**Comment by linouk23** [comment]
I'll be able to implement it once https://github.com/DataDog/datadog-api-client-go/issues/1677 is ✅ .

**Comment by jcunhafonte** [comment]
@linouk23 Have you started any implementation? Thanks.

**Comment by linouk23** [comment]
@jcunhafonte my focus has shifted to other tasks unfortunately but I can see there's some ongoing work here: https://github.com/DataDog/terraform-provider-datadog/pull/1682

**Comment by Conacious** [comment]
Is there any ongoing work for this? Also, I would like to know if there's any kind of guide to contributing to this project, in case someone else wants to implement this feature.

**Comment by jcunhafonte** [comment]
> Is there any ongoing work for this? Also, I would like to know if there's any kind of guide to contributing to this project, in case someone else wants to implement this feature.
> 
> One last question, is possible to configure the integration using the API? I don't see any example in the docs https://docs.datadoghq.com/api/latest/confluent-cloud/
> 
> Thank you

@Conacious You can use various Datadog API Clients to achieve this or directly with the REST API too:
- https://github.com/DataDog/datadog-api-client-python/blob/master/examples/v2/confluent-cloud/UpdateConfluentResource.py
- https://github.com/DataDog/datadog-api-client-typescript/tree/master/examples/v2/confluent-cloud
- More: https://github.com/orgs/DataDog/repositories?q=datadog+api&type=all&language=&sort=

**Comment by pichouk** [comment]
@Conacious 

I think there is some work in progress from @skarimo on https://github.com/DataDog/terraform-provider-datadog/pull/1734 about this :eyes:

**Comment by Marcus-James-Adams** [comment]
I se that this has now been completed, but when I look at the terraform datadog resource page I can not see a resource for this

**Comment by therve** [comment]
This was merged and needs a release, which will happen soon.

**Comment by linouk23** [comment]
@Marcus-James-Adams as a follow up, I can see these 2 new resources:
* https://registry.terraform.io/providers/DataDog/datadog/latest/docs/resources/integration_confluent_account
* https://registry.terraform.io/providers/DataDog/datadog/latest/docs/resources/integration_confluent_resource

Thanks everyone!
