### ISSUE TITLE
Snowflake custom metrics add into datadog through terraform

### ISSUE THREAD

**Issue by ghouse13** [DataDog/terraform-provider-datadog#1572]
Hi there,

Is there any way to add snowflake custom metrics add into datadog through terraform? If it is possible Could you please provide the docs.

https://docs.datadoghq.com/integrations/snowflake/

**Comment by nkzou** [comment]
Hi there, this is not the intended use case for terraform. Our Terraform provider is intended for managing resources on the Datadog backend using the API.
The agent and its integrations aren't part of the Datadog backend, they send data to the backend for ingesting. As such, configuring the agent and its integrations involves adding a config file to the agent's `conf.d` config directory. You can find more details and guides for your specific OS/platform [here](https://docs.datadoghq.com/agent/basic_agent_usage/?tab=agentv6v7)
In case there is a misunderstanding please feel free to reopen the issue and explain further. Thanks!
