### ISSUE TITLE
Bug with creating datadog_monitor using `error-tracking-rum` in query

### ISSUE THREAD

**Issue by jshort-insights** [DataDog/terraform-provider-datadog#1574]
Hi,

I have been following an issue with creating a datadog error-tracking monitor, which will report any new issues that may of been raised by RUM. I have successfully managed to create the monitor by hand to prove that the functionality is possible. However when I try to apply the change from terraform it consistently fails with :

`Error: error creating monitor from https://api.datadoghq.eu/api/v1/monitor: 400 Bad Request: {"errors":["The value provided for parameter 'query' is invalid: Invalid query: Check for invalid tags or facets in your query."]}`

I have also manually validated the generated json against the actual datadog api, which receives a OK (200) response.

We are currently running with terraform version 1.2.2 and datadog provider 3.15.1

### Affected Resource(s)
-   datadog_monitor

## example hcl
```

resource "datadog_monitor" "rum_new_error_monitors" {
  for_each = toset(["app1","app2"])

  name     = "${var.environment_name} | ${each.value} | error tracking | Error was found at view {{rum.attributes.view.name}}"
  query    = "error-tracking-rum(\"service:${each.value} @issue.age:<=300000\").rollup(\"count\").by(\"@issue.id\").last(\"5m\") > 0"
  type     = "error-tracking alert"
  message  = <<-EOF
              {{#is_alert}}
              New error found at `{{rum.attributes.view.url}}`  @ `{{rum.attributes.error.file}}` using `{{rum.attributes.browser.name}} ({{rum.attributes.browser.version}})`
              [View Error]({{rum.link}})
              Stack Trace:
              ```
              {{rum.attributes.error.handling_stack}}
              ```
              (Triggered via @slack-datadog-alerts integration)
            {{/is_alert}}
            EOF

  include_tags        = false
  require_full_window = true
  timeout_h           = 0 # hours
  priority            = 1 # highest
}

```

**Comment by therve** [comment]
Are you sure you're not seeing another issue? I'm using 3.15.1 and the following examples worked fine:

```hcl
resource "datadog_monitor" "rum_new_error_monitors" {
  for_each = toset(["app1","app2"])

  name     = "${each.value} | error tracking | Error was found at view {{rum.attributes.view.name}}"
  query    = "error-tracking-rum(\"service:${each.value} @issue.age:<=300000\").rollup(\"count\").by(\"@issue.id\").last(\"5m\") > 0"
  type     = "error-tracking alert"
  message  = <<-EOF
              {{#is_alert}}
              New error found at `{{rum.attributes.view.url}}`  @ `{{rum.attributes.error.file}}` using `{{rum.attributes.browser.name}} ({{rum.attributes.browser.version}})`
              [View Error]({{rum.link}})
              Stack Trace:
              ```
              {{rum.attributes.error.handling_stack}}
              ```
              (Triggered via @slack-datadog-alerts integration)
            {{/is_alert}}
            EOF

  include_tags        = false
  require_full_window = true
  timeout_h           = 0 # hours
  priority            = 1 # highest
}
```

**Comment by jshort-insights** [comment]
I can confirm , I am using the same version of provider and I see this issue consistently.

I even tried ignoring the validation through the resource, which actually created the monitor but still failed with that error.

**Comment by therve** [comment]
Can you open a support ticket and attach traces? Thanks.

**Comment by therve** [comment]
Closing for now, let me know if you still see this.

**Comment by jshort-insights** [comment]
I have reinvestigated this error, and have found the issue was one of the environments I was deploying the monitor to actually did not have RUM enabled. 

Not sure if their could be improvements made around this error message - as I now understand the context of why the query was incorrect because RUM is not enabled.
