### ISSUE TITLE
template_variable does not support multiple preselected values

### ISSUE THREAD

**Issue by Okeanos** [DataDog/terraform-provider-datadog#1581]
### Terraform Version

Terraform `v1.2.5`
Datadog Provider `registry.terraform.io/datadog/datadog`: `3.15.1`

### Affected Resource(s)

- `datadog_dashboard.template_variable`
- `datadog_dashboard.template_variable_preset.template_variable`

### Terraform Configuration Files

```hcl
resource "datadog_dashboard" "kubernetes_resources" {
  title       = "Dummy Value"
  widget {
   group_definition {
     # ..
   }
  }

  template_variable {
    name             = "env"
    prefix           = "env"
    default          = "prod"
    available_values = ["dev", "nonprod", "prod"]
  }
  template_variable {
    name    = "service"
    prefix  = "kube_service"
    default = "*" # cannot provide multiple specific values here
    available_values = [
      "foo-service",
      "bar-service",
      "foo-bar-service",
      "some-service",
      "another-service"
    ]
  }

  template_variable_preset {
    name = "Preset Name"
    template_variable {
      name = "service"
      value = "foo-service" # cannot provide multiple specific values here
    }
}
```

### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior

The Datadog Dashboard UI allows creating so called "Saved views" (called `template_variable_preset` in Terraform). These saved views may contain an arbitrary selection of values from the `template_variable` values. For example, in the UI the following saved views are possible (based on the example above):

1. "Preset Name": `env:prod`, `service:(foo-service OR bar-service)`
2. "Another saved view": `service:foo-bar-service`
3. "Further saved view": `service:(foo-bar-service OR some-service OR another-service)`
4. "Last saved view": `env:(nonprod OR prod)`, `service:*`

---

I would expect to be able to specify all four examples in Terraform as well.

### Actual Behavior

Specifying this in Terraform is impossible because the `template_variable` only allows a single `string` for the `value` property.

---

Using the form:

```hcl
  template_variable_preset {
    name = "Preset Name"
    template_variable {
      name = "service"
      value = "foo-service, bar-service"
    }
```

Is not rejected by Terraform but doesn't actually work in the Datadog UI when opening the Dashboard because the value syntax is wrong. After selecting a saved view refreshing a template variable selection within the UI may fix it "magically" but isn't an acceptable solution/workaround. It appears that the UI will re-parse the given values and then send a correct request to the backend.

### Steps to Reproduce

Try any form of:

```hcl
template_variable {
  name = "service"
  value = ??? # multiple distinct preselected values here
}
```

or

```hcl
template_variable {
  name    = "service"
  prefix  = "kube_service"
  default = ??? # multiple distinct preselected values here
  available_values = [
    "foo-service",
    "bar-service",
    "foo-bar-service",
    "some-service",
    "another-service"
  ]
}
```

where `???` represents multiple distinct values allowed by the `available_values` array.

### Important Factoids

N/A

### References

N/A

**Comment by skarimo** [comment]
Thanks for the report. Closed by: https://github.com/DataDog/terraform-provider-datadog/pull/1622
