### ISSUE TITLE
Feature Request:  Audit Trail Settings

### ISSUE THREAD

**Issue by jfreeland** [DataDog/terraform-provider-datadog#1594]
It would be great to see Audit Trail Settings support in the Datadog terraform provider.

# References

* https://docs.datadoghq.com/account_management/audit_trail/
* https://app.datadoghq.com/organization-settings/audit-trail-settings

**Comment by JeanFred** [comment]
Duplicate of #1456?

**Comment by therve** [comment]
Closing in favor of #1456, thanks.
