### ISSUE TITLE
Dashboard URLs change every time

### ISSUE THREAD

**Issue by keeganwitt** [DataDog/terraform-provider-datadog#1596]
### Terraform Version

1.2.8

### Affected Resource(s)

-   dashboard

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    datadog = {
      version = "~> 3.15.1"
      source  = "DataDog/datadog"
    }
  }
}

resource "datadog_dashboard" "tfer--dashboard_gcu-ret-4nk" {
  is_read_only = "false"
  layout_type  = "ordered"
  reflow_type  = "fixed"
  title        = "Keegan's test Terraform dashboard"
  url          = "/dashboard/gcu-ret-4nk/keegans-test-terraform-dashboard"
}
```

### Debug Output

https://gist.github.com/keeganwitt/da4cfb21f9c20033e763452b58d6424b

### Panic Output

None.

### Expected Behavior

Running `terraform plan` with no changes should result in the plan not finding any changes to apply.

### Actual Behavior

Every time `terraform plan`/`terraform apply` is run, dashboard URLs change.

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

None.

### References

None.

**Comment by keeganwitt** [comment]
The URLs aren't changing to a new value every time, they are trying to change to the _same value_ every time, but the URL in the tf file doesn't match the live URL.

[terraformer](https://github.com/GoogleCloudPlatform/terraformer) was used to create this tf file. So the issue is the URL and ID are different than what it was when it was exported. This is because the manually created resource was deleted, then re-created with Terraform. It's not clear to me how this problem can be avoided.

**Comment by keeganwitt** [comment]
Update: I confirmed if you don't set the URL in the tf file, you don't have this issue. So maybe this provider should not accept `url` for `dashboard` resources, since it seems it can't respect it anyway?

**Comment by keeganwitt** [comment]
Thank you!

**Comment by arruw** [comment]
I would be nice if this can get documented, because current docs give an impression that you can create dashboard by predefining its url?

(see https://registry.terraform.io/providers/DataDog/datadog/latest/docs/resources/dashboard#url)
