### ISSUE TITLE
monitors: query format

### ISSUE THREAD

**Issue by zekth** [DataDog/terraform-provider-datadog#1606]
Hello,
It seems that the query validation is a bit too sensitive about the formatting and it makes maintaining queries painfull when those grow up significantly.
### Terraform Version

```
tf -v
Terraform v1.3.2
on darwin_amd64
```
### Affected Resource(s)

-   datadog_monitor (maybe others?)
### Terraform Configuration Files
This is the workaround i came with, which is hacky and not even sure it would work for every kind of query. Wondering if something is doable at the provider side?
```hcl

locals {  
  query               = <<EOT
    avg(last_5m):sum:rollout_info_replicas_available{
        namespace:${var.kube_namespace},
        name:${var.kube_service}
    } by {env,region} < ${var.critical_threshold}
  EOT
  query_fmt           = replace(local.query, "\n", "")
}

resource "datadog_monitor" "this" {
  name    = var.name
  type    = var.type
  message = var.message

  priority = var.priority

  on_missing_data = var.on_missing_data
  query           = var.query

  monitor_thresholds {
    warning  = var.warning_threshold
    critical = var.critical_threshold
  }

  include_tags = true
  tags         = local.tags
}
```

### Panic Output

```
Error: error validating monitor from https://api.datadoghq.com/api/v1/monitor/validate: 400 Bad Request: {"errors":["The value provided for parameter 'query' is invalid"]}
```

### Expected Behavior

I'd expect query to work regardless line feed / space characters

### Actual Behavior

unable to verify the query

### Steps to Reproduce

1. `terraform apply`

**Comment by skarimo** [comment]
Hi, thanks for opening this issue. Looks like the api should now accept white space so no need for changes on terraform side. I am going to close this issue but feel free to re-open if the behavior is still happening for you.

**Comment by zekth** [comment]
@skarimo thanks, confirmed it works
