### ISSUE TITLE
Feature Requests - datadog_synthetics_test - OAuth 2.0 Configuration

### ISSUE THREAD

**Issue by leandroscardua** [DataDog/terraform-provider-datadog#1612]
Hi there,

Could you please add the option on the provider to create a datadog_synthetics_test using OAuth 2.0, we can do it using the UI, but have that option integrated with terrafom will be appreciate.

### Affected Resource(s)

Please list the resources as a list, for example:

-   datadog_synthetics_test

### Expected Behavior

We don't have support to do it with terraform

### Actual Behavior

Be able to create a datadog_synthecis_test with the OAuth 2.0

**Comment by gmiu** [comment]
Yep, we need this!! :)

**Comment by leandroscardua** [comment]
Looks like the version, https://github.com/DataDog/terraform-provider-datadog/releases/tag/v3.19.0, just introduce OAuth 2.0 :dancers:

**Comment by skarimo** [comment]
Thanks for updating the thread here @leandroscardua. Closing this issue.
