### ISSUE TITLE
Support for Datadog template_variable defaults - More than one default value

### ISSUE THREAD

**Issue by vgnanasekaran** [DataDog/terraform-provider-datadog#1621]
### Terraform Version
1.3.3

### Affected Resource(s)
-   datadog dashboard 

### Feature Request 
datadog-api-client-go now supports multiple default values for template_variable.
https://github.com/DataDog/datadog-api-client-go/blob/1c6033006d72db906faef2daeecda0ccd20cb48e/api/datadogV1/model_dashboard_template_variable.go#L22

template_variable default is deprecated - https://github.com/DataDog/datadog-api-client-go/blob/1c6033006d72db906faef2daeecda0ccd20cb48e/api/datadogV1/model_dashboard_template_variable.go#L18

Please find below the PR to enhance datadog dashboard template_variable to include defaults:
https://github.com/DataDog/terraform-provider-datadog/pull/1620

**Comment by skarimo** [comment]
Closed by: https://github.com/DataDog/terraform-provider-datadog/pull/1622
