### ISSUE TITLE
Provider crashing upon use of slo_list_definition

### ISSUE THREAD

**Issue by rileygriffith** [DataDog/terraform-provider-datadog#1623]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version

Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

### Affected Resource(s)

Please list the resources as a list, for example:

-   widget.group_definition.widget.slo_list_definition

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files

```hcl
resource "datadog_dashboard" "api_health_dashboard" {
  title       = "API Gateways - ${local.env}"
  description = "Created using the Datadog provider in Terraform"
  layout_type = "ordered"

  widget {
    group_definition {
      title            = "Synthetic Testing for Cyndx APIs"
      background_color = "vivid_blue"
      layout_type      = "ordered"

      widget {
        slo_list_definition {
          request {
            request_type = "slo_list"
            query {
              query_string = ""
              limit        = 100
            }
          }
        }
        widget_layout {
          height = 3
          width  = 4
          x      = 4
          y      = 0
        }
      }

    }
  }
}
```

### Debug Output

Stack trace from the terraform-provider-datadog_v3.17.0 plugin:

panic: [widget 0 group_definition 0 widget 2 slo_list_definition 0] doesn't end with [widget 2]

goroutine 31 [running]:
github.com/terraform-providers/terraform-provider-datadog/datadog/internal/utils.(*ResourceDataKey).Remove(0xc000d2ef10, {0x11ea580, 0xc000e9dc40})
github.com/terraform-providers/terraform-provider-datadog/datadog/internal/utils/key.go:63 +0x214
github.com/terraform-providers/terraform-provider-datadog/datadog.buildTerraformGroupDefinition({0xc000f6ece0, 0x0, {0xc00082e2f8, 0x7}, 0xc0009a26f8, 0xc000f6ecd0, 0x0, {0xc00082e310, 0x5}, {0xc000408000, ...}, ...}, ...)
github.com/terraform-providers/terraform-provider-datadog/datadog/resource_datadog_dashboard.go:1353 +0x54a
github.com/terraform-providers/terraform-provider-datadog/datadog.buildTerraformWidget({{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc0001c5260, ...}, ...}, ...)
github.com/terraform-providers/terraform-provider-datadog/datadog/resource_datadog_dashboard.go:1110 +0x29a5
github.com/terraform-providers/terraform-provider-datadog/datadog.buildTerraformWidgets(0xc000d2f2f8, 0xc00004dc80)
github.com/terraform-providers/terraform-provider-datadog/datadog/resource_datadog_dashboard.go:1077 +0x225
github.com/terraform-providers/terraform-provider-datadog/datadog.updateDashboardState(0x142a0e0, 0xc000d2f220)
github.com/terraform-providers/terraform-provider-datadog/datadog/resource_datadog_dashboard.go:266 +0x31e
github.com/terraform-providers/terraform-provider-datadog/datadog.resourceDatadogDashboardRead({0x1690640, 0xc00101e780}, 0xc00004dc80, {0x1175000, 0xc000910870})
github.com/terraform-providers/terraform-provider-datadog/datadog/resource_datadog_dashboard.go:312 +0x397
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc0001eb880, {0x1690640, 0xc00101e780}, 0xd, {0x1175000, 0xc000910870})
github.com/hashicorp/terraform-plugin-sdk/v2@v2.16.0/helper/schema/resource.go:724 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0001eb880, {0x1690640, 0xc00101e780}, 0xc000b9ab60, {0x1175000, 0xc000910870})
github.com/hashicorp/terraform-plugin-sdk/v2@v2.16.0/helper/schema/resource.go:1015 +0x585
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc000466000, {0x1690598, 0xc00036a9c0}, 0xc00036aa40)
github.com/hashicorp/terraform-plugin-sdk/v2@v2.16.0/helper/schema/grpc_provider.go:613 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc00042ed20, {0x1690640, 0xc00101e1b0}, 0xc0007980c0)
github.com/hashicorp/terraform-plugin-go@v0.9.0/tfprotov5/tf5server/server.go:746 +0x48c
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x13df740, 0xc00042ed20}, {0x1690640, 0xc00101e1b0}, 0xc000798060, 0x0)
github.com/hashicorp/terraform-plugin-go@v0.9.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000232c40, {0x169f8e0, 0xc0002341a0}, 0xc001020000, 0xc000281230, 0x21e2750, 0x0)
google.golang.org/grpc@v1.45.0/server.go:1282 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc000232c40, {0x169f8e0, 0xc0002341a0}, 0xc001020000, 0x0)
google.golang.org/grpc@v1.45.0/server.go:1619 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
google.golang.org/grpc@v1.45.0/server.go:921 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
google.golang.org/grpc@v1.45.0/server.go:919 +0x294

Error: The terraform-provider-datadog_v3.17.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

### Expected Behavior

SLO List applied to dashboard group

### Actual Behavior

SLO List widget was in fact added to the dashboard upon apply, but any future terraform plans cause the above error to persist maybe it impossible to add more resources. Another thing I noted is that `slo_list_definition` does not come up as an autofill option on vscode while other widget types do

**Comment by rileygriffith** [comment]
This did not fix the issue

**Comment by rileygriffith** [comment]
@skarimo

**Comment by skarimo** [comment]
@rileygriffith did you build the latest master and override the provider properly?  Your configuration was created successfully in my testing

```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the
following symbols:
  + create

Terraform will perform the following actions:

  # datadog_dashboard.api_health_dashboard will be created
  + resource "datadog_dashboard" "api_health_dashboard" {
      + dashboard_lists_removed = (known after apply)
      + description             = "Created using the Datadog provider in Terraform"
      + id                      = (known after apply)
      + is_read_only            = false
      + layout_type             = "ordered"
      + title                   = "API Gateways - rand"
      + url                     = (known after apply)

      + widget {
          + id = (known after apply)

          + group_definition {
              + background_color = "vivid_blue"
              + layout_type      = "ordered"
              + show_title       = true
              + title            = "Synthetic Testing for Cyndx APIs"

              + widget {
                  + id = (known after apply)

                  + slo_list_definition {
                      + request {
                          + request_type = "slo_list"

                          + query {
                              + limit = 100
                            }
                        }
                    }

                  + widget_layout {
                      + height = 3
                      + width  = 4
                      + x      = 4
                      + y      = 0
                    }
                }
            }
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

datadog_dashboard.api_health_dashboard: Creating...
datadog_dashboard.api_health_dashboard: Creation complete after 1s [id=e76-qbu-8b2]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```
