### ISSUE TITLE
datadog_logs_archive - panic: runtime error

### ISSUE THREAD

**Issue by jakub-qg** [DataDog/terraform-provider-datadog#1643]
### Terraform Version

```
$ tf -v
Terraform v1.1.8
```

### Affected Resource(s)

-   `datadog_logs_archive`

### Terraform Configuration Files

```hcl
resource "datadog_logs_archive" "browser_archive" {
  name             = "Logs Archive"
  query             = "source:browser"
  include_tags = true

  s3 = {
    bucket        = var.archive_bucket
    path            = "/browser"
    account_id = var.archive_aws_account_id
    role_name  = var.archive_aws_role_name
  }
}
```

### Debug Output

https://gist.github.com/jakub-qg/15efe59530514be861372a09cb33caf9#file-debug-log

### Panic Output

https://gist.github.com/jakub-qg/15efe59530514be861372a09cb33caf9#file-panic-log

### Expected Behavior

Resource should be created and terraform should finish with a success. 

### Actual Behavior

Resource gets created but terraform crashes.

### Steps to Reproduce

1. `terraform apply`

OR

1. `tf import datadog_logs_archive.browser_archive <id>`

**Comment by therve** [comment]
Thanks, we'll look into the panic. But even if we fix it, I think terraform will still fail as the destination is null im your API reply. Do you know how you got that? Thanks.

**Comment by therve** [comment]
At the very least, your resource definition should say `s3_archive {` not `s3 = {`.

**Comment by therve** [comment]
Closing for now, feel free to reopen with more information, thanks.
