### ISSUE TITLE
[datadog_service_definition_yaml] Flaky recreates because of case sensitive service name

### ISSUE THREAD

**Issue by marceloboeira** [DataDog/terraform-provider-datadog#1651]
### Terraform Version

```
Terraform v1.3.5
on darwin_amd64
```

### Affected Resource(s)

Please list the resources as a list, for example:

-   datadog_service_definition_yaml

### Terraform Configuration Files

```hcl
resource "datadog_service_definition_yaml" "foo" {
  service_definition = <<-EOT
  schema-version: v2
  dd-service: Foo
  integrations:
    pagerduty: https://XXX.pagerduty.com/service-directory/XXX
  tags:
  - managed-by:terraform
  team: data-platform
EOT
}
```

### Debug Output

Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Expected Behavior

What should have happened?

### Actual Behavior

```diff
-/+ resource "datadog_service_definition_yaml" "foo" {
      ~ id                 = "foo" -> (known after apply)
      ~ service_definition = <<-EOT # forces replacement
          - dd-service: foo
          + dd-service: Foo
            integrations:
                pagerduty: https://XXX.pagerduty.com/service-directory/XXX
            schema-version: v2
            tags:
                - managed-by:terraform
            team: data-platform
        EOT
    }
```

### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:

1. Use the mentioned code
1. `terraform apply`
1.  Resources get created
1. `terraform plan`
1. See the diff with recreation of the service in the catalog

### Important Factoids

* We can work around this in the provider by comparing lowercased versions of the definition and avoid replacing the resource every single time; however, if the API doesn't handle those properly, then it will still be a problem (since case changes won't take effect). The question remains for the datadog folks, is the service name case-sensitive? does it force lower case?

**Comment by nkzou** [comment]
We've looked into it and found that the field conforms to Datadog's universal service tagging rules, found at https://docs.datadoghq.com/getting_started/tagging/#define-tags. This means it not only converts to lowercase, but replaces most special characters as well. We're currently discussing how best to handle/document this - thanks for bringing this to our attention.
