### ISSUE TITLE
datadog_service_level_objective tags not respecting capitalization constraint in Datadog

### ISSUE THREAD

**Issue by josh-mcq** [DataDog/terraform-provider-datadog#1675]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version

Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.
$ terraform -v
Terraform v1.1.5
### Affected Resource(s)

Please list the resources as a list, for example:

-   datadog_service_level_objective

### Terraform Configuration Files

```hcl
resource "datadog_service_level_objective" "custom_monitor_slos" {
  for_each    = { for i in local.monitor_slos : i.slo_name => i }
  name        = format("%s-%s-%s", local.stack_name, each.value.slo_name, var.environment)
  type        = "monitor"
  description = each.value.slo_desc
  monitor_ids = [datadog_monitor.custom_monitors[each.value.slo_monitor].id]
  thresholds {
    timeframe = each.value.timeframe
    target    = each.value.target_percentage
  }
  tags = concat(try(each.value.tags, []), ["owner: Eos")
}
```

### Expected Behavior
The deployed resource in datadog should match what I have specified in terraform.

### Actual Behavior
adding a tag with a Capitalized value, like "owner: Eos" to a datadog_service_level_objective resource will end up with a lowercased value - "owner: eos" - as the tag on actual SLO in Datadog.  Every subsequent plan/apply will state the following change:
```
      ~ tags        = [
          + "owner:Eos",
          - "owner:eos",
```
This change will never actually happen, even though the apply "succeeds".  

If Datadog has a constraint on the values for this resource, this resource should abide by the same constraint and write the normalized representation to the state (or possibly err) to prevent this misalignment.

**Comment by nkzou** [comment]
Hi, thanks for the report. We're currently handling this together with a similar issue in the service_definition_yaml resource. You can follow progress in https://github.com/DataDog/terraform-provider-datadog/pull/1686
