### ISSUE TITLE
Feature request: logs restriction queries

### ISSUE THREAD

**Issue by axl89** [DataDog/terraform-provider-datadog#1680]
We're currently provisioning our roles via terraform with the [datadog_role resource](https://registry.terraform.io/providers/DataDog/datadog/latest/docs/resources/role) in a similar way to this:

```tf
resource "datadog_role" "team_a_developer" {
  name = "Team A - Developer"
  permission {
    id = data.datadog_permissions.bar.permissions.logs_read_data
  }
  permission {
    id = data.datadog_permissions.bar.permissions.logs_read_index_data
  }
}
```

To fully implement log RBAC with Terraform we would love to be able to terraform said role's access to its own index subset of logs via [restriction queries](https://docs.datadoghq.com/api/latest/logs-restriction-queries/) with some sort of new resources such as `datadog_restriction_query` and `datadog_restriction_query_association`. Something like:

```tf
resource "datadog_restriction_query" "team_a" {
  restriction_query = "source:team-a-stuff"
}

resource "datadog_restriction_query_association" "team_a" {
  restriction_query = datadog_restriction_query.team_a.id
  roles = [
    datadog_role.team_a_developer.id
  ]
}
```

Extra points would be for data sources as well as resources, of course :smile:

**Comment by therve** [comment]
Thanks, it's already tracked on #1217
