### ISSUE TITLE
Add support for Cloudflare integration

### ISSUE THREAD

**Issue by antoinetielbeke** [DataDog/terraform-provider-datadog#1700]
This feature request is for a datadog_integration_cloudflare resource. It would be useful to configure the Cloudflare Datadog integration in Terraform code. Would make it more manageable for us to renew our API tokens.

https://docs.datadoghq.com/integrations/cloudflare/

Thanks in advance!

**Comment by antoinetielbeke** [comment]
Similar to: https://github.com/DataDog/terraform-provider-datadog/issues/195

**Comment by LanceSandino** [comment]
fwiw you can already do this via [cloudflare’s terraform provider](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/logpush_job)

**Comment by antoinetielbeke** [comment]
AFAIK is Cloudflare Logpush different from the Datadog integration. So my request is still valid :)

**Comment by LanceSandino** [comment]
It’s not different. 
the cloudflare terraform would be the same as if datadog implemented it. Currently they ask you to setup log push via API or GUI. 

The integration just takes care of creating the dashboard and setting up metrics.
