### ISSUE TITLE
Support the datadog_dashboard widget query data_source `logs_issue_stream`

### ISSUE THREAD

**Issue by Inkdpixels** [DataDog/terraform-provider-datadog#1720]
### Terraform Version

1.3.6

### Affected Resource(s)

-   [datadog_dashboard](https://registry.terraform.io/providers/DataDog/datadog/latest/docs/resources/dashboard)

### Expected Behavior

The provider should support the query data_source `logs_issue_stream`

### Actual Behavior

The provider throws `invalid value 'logs_issue_stream' for ListStreamSource: valid values are [logs_stream audit_stream rum_issue_stream apm_issue_stream
│ logs_pattern_stream]`

### HCL

```
resource "datadog_dashboard" "ordered_dashboard" {
  title        = "Ordered Layout Dashboard"
  description  = "Created using the Datadog provider in Terraform"
  layout_type  = "ordered"
  is_read_only = true

  widget {
    list_stream_definition {
      response_format  = "event_list"
      query  {
        data_source = "logs_issue_stream"
        query_string = "*"
      }
      title     = "Widget Title"
    }
  }
}
```

![Bildschirm­foto 2023-01-13 um 10 05 01](https://user-images.githubusercontent.com/1557092/212281252-12da4ebc-2074-4212-9d48-6203772aee52.png)

**Comment by skarimo** [comment]
Thanks for the report. This is closed by: https://github.com/DataDog/datadog-api-client-go/pull/1895
