### ISSUE TITLE
Feature Request: Copy multiple cells and paste all at once and/or be able to add a template at the bottom of a Notebook

### ISSUE THREAD

**Issue by lielee** [DataDog/terraform-provider-datadog#1732]
Hi there!

### Affected Resource(s)

-   Notebooks

### Expected Behavior

We use Notebooks to keep track of test runs, but often will have to add the same 9 cells over and over when doing more runs than usual in a day, or have to delete the same 9 cells when it's a lighter test day than normal. It would be great to be able to copy an entire section from a heading and paste at the bottom, or possibly even better, in the Add New Cell section at the bottom, be able to add an entire Template to the bottom. That way we could have a Template for our 9 cells and be able to add them in as needed with a single click rather than have one template with ~4 runs that often needs to be added to or have some cells removed from depending on the number of test runs in a day.

**Comment by nkzou** [comment]
Apologies if I'm misunderstanding, but it seems like this is a feature request for the web app, not the terraform provider. I suggest you open a support ticket for this feature request, as the notebooks team doesn't check here.
