### ISSUE TITLE
New fields in datadog JSON from UI cause constant drift in monitors

### ISSUE THREAD

**Issue by smc87** [DataDog/terraform-provider-datadog#1739]
### Terraform Version

1.3.6

### Affected Resource(s)

datadog_monitor_json

	"options": {
		"notify_audit": false,
		"enable_logs_sample": true,
		"thresholds": {
			"critical": 10
		},
		"on_missing_data": "show_and_notify_no_data",
		"include_tags": true,
		"groupby_simple_monitor": false,
		"new_group_delay": 60,
		"restriction_query": null,
		"silenced": {
			"*": null
		}
	},
```hcl


### Debug Output

Error: error updating monitor from https://api.datadoghq.com/api/v1/monitor/108877691: 400 Bad Request: {"errors":["Duplicate of an existing monitor_id:xxxx org_id:xxxx"]}



### Expected Behavior

On a rerun of terraform plan / apply. No changes should be planned for the monitor, and no changes attempted.


### Actual Behavior

We see the options block constantly drift, and cause a 400 error when TF tries to update the datadog entity. 

### Steps to Reproduce

Export a monitor from the UI in JSON format and use it with terraform. 
The monitor will be created.
Rerun your plan and apply, you will see the error:

Error: error updating monitor from https://api.datadoghq.com/api/v1/monitor/xxxx : 400 Bad Request: {"errors":["Duplicate of an existing monitor_id:xxxx org_id:xxxx"]}

**Comment by skarimo** [comment]
Hello, I tested this out with a few different options and can't reproduce any drift. Additionally, the output you have shared suggests you are trying to re-create a duplicate monitor rather than a resource drift.
```
...
Error: error updating monitor from https://api.datadoghq.com/api/v1/monitor/xxxx : 400 Bad Request: {"errors":["Duplicate of an existing monitor_id:xxxx org_id:xxxx"]}
...
```
Terraform is trying to recreate the monitor suggesting it is not in your state and needs to be imported.

**Comment by smc87** [comment]
Running apply the first time works fine.
Running the exact same config for a second time, in the plan I can see this drift:

` ~ resource "datadog_monitor_json" "monitor_json" {
        id      = "108877691"
      ~ monitor = jsonencode(
          ~ {
                name     = "Apollo - Redirect Config Rules API call has failed"
              ~ options  = {
                  ~ thresholds             = {
                      + comparison     = ">="
                      + period         = {
                          + digit             = 10
                          + name              = "10 minute average"
                          + no_data_timeframe = 20
                          + seconds           = 600
                          + tense             = "last"
                          + text              = "10 minutes"
                          + timeString        = "10m"
                          + unit              = "minutes"
                          + unitAbbreviation  = "m"
                          + value             = "last_10m"
                        }
                      + timeAggregator = "avg"
                        # (1 unchanged element hidden)
                    }
                    # (7 unchanged elements hidden)
                }
                tags     = [
                    "team:xxxx",
                    "managed_by:xx-terraform",
                    "service:xx-ui",
                ]
                # (4 unchanged elements hidden)
            }
        )
    }`
    
    When trying to apply with this plan I then get:
    
    `Error: error updating monitor from https://api.datadoghq.com/api/v1/monitor/108877691: 400 Bad Request: {"errors":["Duplicate of an existing monitor_id:108877691 org_id:xxxx"]}
│ 
│   with module.monitors.datadog_monitor_json.monitor_json["XXMonitor NameXX"],
│   on terraform/monitors/monitors.tf line 23, in resource "datadog_monitor_json" "monitor_json":
│   23: resource "datadog_monitor_json" "monitor_json" {`
    
    
 This only seems to impact monitors where the JSON was exported in the last week or so, all others still work as expected.

**Comment by smc87** [comment]
This was due to exporting from the edit page, rather than the status page. Sorry

**Comment by ento** [comment]
This tripped me up too. I created a `datadog_monitor_json` resource based on a JSON export of the edit page of a new, unsaved monitor. I was able to apply it but subsequent `terraform plan` resulted in diffs like this:

```tf
  ~ resource "datadog_monitor_json" "rds_free_storage_space_warning" {
        id      = "..."
      ~ monitor = jsonencode(
          ~ {
                name     = "RDS storage space will run out soon"
              - priority = null -> null
                tags     = []
                # (4 unchanged elements hidden)
            }
        )
    }
```

This GitHub issue pointed me to the right path (thanks!): the JSON representation of the monitor exported from its status page had a few extra keys (`options.silenced`, `priority`, `restricted_roles`) and adding them to TF code did away with the drift.
