### ISSUE TITLE
Datadog provider - widget.timeseries_definition.request.formula.style block cannot be created.

### ISSUE THREAD

**Issue by jablon1989** [DataDog/terraform-provider-datadog#1742]
### Terraform Version

Terraform v.1.3.7

### Affected Resource(s)

-   datadog provider - datadog dashboard resource

### Terraform Configuration Files

```hcl
widget {
        timeseries_definition {
          title          = "Resource"
          title_size     = "16"
          title_align    = "left"
          show_legend    = false
          legend_layout  = "auto"
          legend_columns = ["avg", "min", "max", "value", "sum"]
          request {
            formula {
              alias              = "Alias 1"
              formula_expression = "query5"
              style {
                palette = "classic"
                palette_index = "3"
              }
            }
            formula {
              alias              = "Alias 2"
              formula_expression = "(query1 + query2) * 8"
            }
            query {
              metric_query {
                name  = "query5"
                query = "some_query"
              }
            }
            }
            style {
              palette    = "dog_classic"
              line_type  = "solid"
              line_width = "normal"
            }
            display_type = "area"
          }
          yaxis {
            include_zero = "true"
            scale        = "linear"
            min          = "auto"
            max          = "auto"
          }
        }
        widget_layout {
          x      = "0"
          y      = "5"
          width  = "12"
          height = "5"
        }
      }
```

### Debug Output

https://registry.terraform.io/providers/DataDog/datadog/latest/docs/resources/dashboard#nested-schema-for-widgetgroup_definitionwidgettimeseries_definitionrequestformulastyle

**NOTE:** Remember to review debug output before posting, and redact any sensitive data.

### Expected Behavior

Widget created would have a two style for each formula.

### Actual Behavior

Threw an error that style block does not have a place there - but the documentation [and the JSON file I got from existing dashboards] says otherwise.

### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:

1. terraform plan
2. terraform validate

**Comment by nkzou** [comment]
Looks like you have an extra `}` closing bracket on line 27/28 right before the style block that closes the request block.

**Comment by jablon1989** [comment]
I copied the code without style block and just entered it in the slot above. The real code didn't have an extra bracket.
Screenshot below with the error provided by Terraform.
![Screenshot from 2023-01-27 20-36-55](https://user-images.githubusercontent.com/89132335/215181587-1b586bf0-c109-497e-b4bd-4e3261be0fc9.png)
![Screenshot from 2023-01-27 20-37-17](https://user-images.githubusercontent.com/89132335/215181651-04ebb21b-37cd-44c7-ba6f-fe9f92107d09.png)
![Screenshot from 2023-01-27 20-37-17](https://user-images.githubusercontent.com/89132335/215181664-28b9935b-7e57-4109-9a63-228fe524740a.png)
![Screenshot from 2023-01-27 20-36-55](https://user-images.githubusercontent.com/89132335/215181666-96dbb912-bc84-4251-967f-7c1b8e101f44.png)

**Comment by nkzou** [comment]
Which version of the DataDog provider are you using? I'm unable to reproduce this on v3.20 with your widget definition.

**Comment by jablon1989** [comment]
Ok, the problem was with the older version. Thank you. Also fixed another issue, I created 2 group definition widgets and only 1 group was shown. Not it works for both.
Thanks!

**Comment by jablon1989** [comment]
I was using 3.18
