### ISSUE TITLE
Create datadog_service_account with app_keys resource with latest version of datadog with terraform

### ISSUE THREAD

**Issue by RaghavK12RK** [DataDog/terraform-provider-datadog#1787]
Hi, I cannot able to create `app_keys` for the particular datadog_service_account, May i know this feature is enable or not.

I Want to create datadog_service_account with app_keys where the service account will be the owner of the keys generated.

Need your support on this!!

**Comment by jsthibault** [comment]
Same issue here, support will be higly appreciate
