### ISSUE TITLE
datadog_security_monitoring_rule | panic: interface conversion: interface {} is nil, not string

### ISSUE THREAD

**Issue by marcossv9** [DataDog/terraform-provider-datadog#1795]
### Terraform Version

```
Terraform v1.3.9
on linux_amd64
+ provider registry.terraform.io/datadog/datadog v3.21.0
```

### Affected Resource(s)

Please list the resources as a list, for example:

-   datadog_security_monitoring_rule

### Terraform Configuration Files

I've created my own module to create `datadog_security_monitoring_rule`, here is the `main.tf` for the module:

```hcl
resource "datadog_security_monitoring_rule" "rule" {
  enabled            = var.rule_enabled
  name               = var.rule_name
  message            = var.rule_message
  has_extended_title = var.rule_has_extended_title

  dynamic "query" {
    for_each = var.rule_queries

    content {
      name  = query.key
      query = query.value.query

      aggregation     = query.value.aggregation != null ? query.value.aggregation : null
      group_by_fields = query.value.group_by_fields != null ? query.value.group_by_fields : null
    }
  }

  dynamic "case" {
    for_each = var.rule_cases

    content {
      name          = case.key
      status        = case.value.status
      condition     = case.value.condition
      notifications = case.value.notifications
    }
  }

  options {
    evaluation_window   = var.rule_options_evaluation_window
    keep_alive          = var.rule_options_keep_alive
    max_signal_duration = var.rule_options_max_signal_duration
  }

  tags = var.rule_tags
}
```
And here is how I'm using the module to create a security rule:

```hcl

module "my-rule" {
  source = "git::ssh://git@my_module_repo"

  rule_enabled            = var.rule_enabled
  rule_name               = var.rule_name
  rule_message            = var.rule_message
  rule_has_extended_title = var.rule_has_extended_title

  rule_queries = var.rule_queries

  rule_cases = var.rule_cases

  rule_options_evaluation_window   = var.rule_options_evaluation_window
  rule_options_keep_alive          = var.rule_options_keep_alive
  rule_options_max_signal_duration = var.rule_options_max_signal_duration

  rule_tags = var.rule_tags

  datadog_api_key = var.datadog_api_key
  datadog_app_key = var.datadog_app_key
}
```

### Panic Output
https://gist.github.com/marcossv9/a29f7cb211e7d119cd90f3c1c90a38ef

### Expected Behavior

a security monitoring rule should be created.

### Actual Behavior

A panic in the terraform plugin

### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:

1. `terraform apply -var-file="secret.tfvars" -var-file="terraform.tfvars"`

**Comment by marcossv9** [comment]
Please let me know if you need more details. Thanks!

**Comment by nkzou** [comment]
Hi there, thanks for reporting this issue. I've started a PR to fix this, but I noticed that your query blocks get created with an empty string in the group by list -
```
      + query {
          + aggregation     = "count"
          + group_by_fields = [
              + "",
            ]
          + metrics         = (known after apply)
          + name            = "created"
          + query           = "source:cloudtrail @eventSource:waf*.amazonaws.com @evt.name:Create*"
        }
```
Empty strings in `group_by_fields` and `distinct_fields` aren't valid, and the backend API won't accept it. The PR I opened that fixes the panic will also include string validation to raise errors on empty strings in those fields, so please keep that in mind. Thanks!

**Comment by marcossv9** [comment]
Hi @nkzou, good catch! I'm passing an empty string instead of a `null` value to the module, that was my mistake.
Thank you very much!

**Comment by nkzou** [comment]
Fix has been merged, will be in the next release (most likely in the next week or so). Thanks again for reporting.
