### ISSUE TITLE
Feature Request: add data source for hosts/infrastructure list

### ISSUE THREAD

**Issue by babispo79** [DataDog/terraform-provider-datadog#1816]
Hi there,

Would be nice to have a data source that would list all the hosts in the infrastructure list.

Datadog API - https://docs.datadoghq.com/api/latest/hosts/

**Comment by nkzou** [comment]
Thanks for your feature request, the data source has been merged and will be available in the next release (v3.24.0)

**Comment by babispo79** [comment]
Thank you for implementing it
