### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference on terraform-provider-datadog_v3.23.0 plugin

### ISSUE THREAD

**Issue by Sarath3395** [DataDog/terraform-provider-datadog#1836]
Hi All,

### Terraform Version
hashicorp/terraform:1.2.7

### Affected Resource(s)
Dashboards (error: Plugin did not respond)
Synthetics (Error: Request cancelled)

### Actual Behavior
No changes applied

### Expected Behavior
Dashboard and Synthetics update

### Steps to Reproduce
terraform init -upgrade
terraform apply -var-file="terraform.tfvars" -auto-approve

### Panic Output

  Stack trace from the terraform-provider-datadog_v3.23.0 plugin:
   
  panic: runtime error: invalid memory address or nil pointer dereference
  [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x114ea1d]

### References
https://github.com/DataDog/terraform-provider-datadog/issues/656

https://github.com/DataDog/terraform-provider-datadog/issues/1830

**Comment by therve** [comment]
Hi,

Can you get more details about the trace in particular? Having the synthetics test would help too. Thanks.

**Comment by Sarath3395** [comment]
Hi Therve,

Basically, I am trying to update the synthetics with basicAuth's type with "oauth-rop". I have attached the trace for reference.

  14:16:42   Stack trace from the terraform-provider-datadog_v3.23.0 plugin:
14:16:42   
14:16:42   panic: runtime error: invalid memory address or nil pointer dereference
14:16:42   [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x114ea1d]
14:16:42   
14:16:42   goroutine 54 [running]:
14:16:42   github.com/terraform-providers/terraform-provider-datadog/datadog.completeSyntheticsTestRequest({0x0, 0x0, 0x0, 0x0, 0x0, 0x0, {0x0, 0x0, 0x0}, 0x0, ...}, ...)
14:16:42     github.com/terraform-providers/terraform-provider-datadog/datadog/resource_datadog_synthetics_test_.go:1731 +0x127d
14:16:42   github.com/terraform-providers/terraform-provider-datadog/datadog.buildSyntheticsAPITestStruct(0xc00082a680)
14:16:42     github.com/terraform-providers/terraform-provider-datadog/datadog/resource_datadog_synthetics_test_.go:1436 +0xc98
14:16:42   github.com/terraform-providers/terraform-provider-datadog/datadog.resourceDatadogSyntheticsTestCreate({0x17a0dc8, 0xc000ac4240}, 0x0?, {0x12206e0?, 0xc00056e510?})
14:16:42     github.com/terraform-providers/terraform-provider-datadog/datadog/resource_datadog_synthetics_test_.go:1167 +0xf3
14:16:42   github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc000403c00, {0x17a0e00, 0xc0001403f0}, 0xd?, {0x12206e0, 0xc00056e510})
14:16:42     github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:707 +0x12e
14:16:42   github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000403c00, {0x17a0e00, 0xc0001403f0}, 0xc00081ea90, 0xc00082a500, {0x12206e0, 0xc00056e510})
14:16:42     github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:837 +0xa7a
14:16:42   github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0002960f0, {0x17a0e00?, 0xc000140240?}, 0xc000530280)
14:16:42     github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/grpc_provider.go:1021 +0xe3c
14:16:42   github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0000adf40, {0x17a0e00?, 0xc000630ab0?}, 0xc0003dc1c0)
14:16:42     github.com/hashicorp/terraform-plugin-go@v0.14.1/tfprotov5/tf5server/server.go:818 +0x574
14:16:42   github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x14c1460?, 0xc0000adf40}, {0x17a0e00, 0xc000630ab0}, 0xc0003dc150, 0x0)
14:16:42     github.com/hashicorp/terraform-plugin-go@v0.14.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
14:16:42   google.golang.org/grpc.(*Server).processUnaryRPC(0xc00043a000, {0x17a3b80, 0xc0000c8b60}, 0xc000c22000, 0xc0007125d0, 0x2290620, 0x0)
14:16:42     google.golang.org/grpc@v1.50.1/server.go:1340 +0xd13
14:16:42   google.golang.org/grpc.(*Server).handleStream(0xc00043a000, {0x17a3b80, 0xc0000c8b60}, 0xc000c22000, 0x0)
14:16:42     google.golang.org/grpc@v1.50.1/server.go:1713 +0xa1b
14:16:42   google.golang.org/grpc.(*Server).serveStreams.func1.2()
14:16:42     google.golang.org/grpc@v1.50.1/server.go:965 +0x98
14:16:42   created by google.golang.org/grpc.(*Server).serveStreams.func1
14:16:42     google.golang.org/grpc@v1.50.1/server.go:963 +0x28a
14:16:42   
14:16:42   Error: The terraform-provider-datadog_v3.23.0 plugin crashed!
14:16:42   
14:16:42   This is always indicative of a bug within the plugin. It would be immensely
14:16:42   helpful if you could report the crash with the plugin's maintainers so that it
14:16:42   can be fixed. The output above should help diagnose the issue.


Thank you!

**Comment by therve** [comment]
The panic should be fixed in #1837, but your TF file is probably invalid and missing a value for `token_api_authentication` in `request_basicauth`. Can you double check? Thanks.

**Comment by Sarath3395** [comment]
Hi Therve,

Thank you so much for the quick response. I appreciate that. I have tokenApiAuthentication in the configuration file but for some reason, I do not see tokenApiAuthentication in the API request(terrafrom logs).  

Once your PR is merged this fix should be available in the next version(3.24) or should be available in this version(3.23) itself?

Thanks again :)

**Comment by therve** [comment]
AFAIU, the fix should prevent the crash but not make the test creation succeeds. Can you paste just the relevant section of our tf file containing `token_api_authentication` if it doesn't contain any secret?

**Comment by Sarath3395** [comment]
Hi Therve,

Terraform plan produces the following block on synthetic creation.

+ request_basicauth {
             + access_token_url         = "https://XXXXXXXXXXX
             + audience                 = "audience"
             + client_id                = "{{ client }}"
             + client_secret            = (sensitive value)
             + password                 = (sensitive value)
             + resource                 = "resource"
             + scope                    = "scope"
             + token_api_authentication = "body"
             + type                     = "oauth-rop"
             + username                 = "XXX"
           }

I have masked sensitive data. 
Will this fix be part of datadog_provisioner 3.23?

Thank you!

**Comment by therve** [comment]
It will not be part of 3.23 because it has been released already.
That block should work, I don't know if the fix would change anything.

**Comment by Sarath3395** [comment]
thank you so much for your help on this Therve. I am able to create the synthetics after passing the token_api_authentication(though it was an optional field in UI)
