### ISSUE TITLE
Validation error on ci-pipelines monitor that uses a formula

### ISSUE THREAD

**Issue by jfirebaugh** [DataDog/terraform-provider-datadog#1846]
### Steps to Reproduce

Create a CI pipeline monitor in the Datadog UI that uses the following configuration:

<img width="537" alt="Screen Shot 2023-04-03 at 1 07 22 PM" src="https://user-images.githubusercontent.com/98601/229615751-73a16015-af5d-4f5a-a1f2-417e7b614a39.png">

`terraform import` to import it into a terraform configuration. Set the `query` attribute to the value shown in the Datadog UI:

```
ci-pipelines("(count[ci_level:job @ci.job.retry_count:>=1 @buildkite.queue:production-*] / count[ci_level:job @buildkite.queue:production-*]) * 100").last("5m") > 5
```

Run `terraform apply`.

### Expected Behavior

Apply succeeds.

### Actual Behavior

Validation error.

### Terraform Version

Terraform v1.1.3
on darwin_arm64
+ provider registry.terraform.io/datadog/datadog v3.21.0

### Affected Resource(s)

-   datadog_monitor

### Terraform Configuration Files

```hcl
resource "datadog_monitor" "monitor" {
  name = "test"
  type = "ci-pipelines alert"
  query = <<-EOF
    ci-pipelines("(count[ci_level:job @ci.job.retry_count:>=1 @buildkite.queue:production-*] / count[ci_level:job @buildkite.queue:production-*]) * 100").last("5m") > 5
  EOF
}
```

### Debug Output

> Error: error validating monitor from https://api.datadoghq.com/api/v1/monitor/115420349/validate: 400 Bad Request: {"errors":["The value provided for parameter 'query' is invalid: invalid operator specified: "]}

**Comment by therve** [comment]
Hi,

I believe you need to use the formula support to express that monitor. If you click on `Export` in the UI it should give you the proper format. It should look something like that:

```hcl
resource "datadog_monitor" "monitor" {
  name    = "test"
  message = "message"
  type    = "ci-pipelines alert"
  query   = "formula(\"(query1 / query2) * 100\").last(\"5m\") > 5"

  variables {       
    event_query {
      data_source = "ci_pipelines"
      name        = "query1"
      indexes     = ["*"]   
      compute {
        aggregation = "count"
      }         
      search {
        query = "ci_level:job @ci.job.retry_count:>=1 @buildkite.queue:production-*"
      }
    }
    event_query {
      data_source = "ci_pipelines"
      name        = "query2"
      indexes     = ["*"]   
      compute {
        aggregation = "count"
      }
      search {
        query = "ci_level:job @buildkite.queue:production-*"
      }         
    }   
  }
}
```

Let us know if that works for you, thanks.

**Comment by jfirebaugh** [comment]
Yes, that works, thanks!
