### ISSUE TITLE
Unable to update target and warning values on SLO

### ISSUE THREAD

**Issue by emmaLP** [DataDog/terraform-provider-datadog#1849]
Hi there,

### Terraform Version
Terraform v1.2.6 
DataDog Provider version v3.21.0 

### Affected Resource(s)

Please list the resources as a list, for example:

-   datadog_service_level_objective

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files

Original Configuration
```hcl
resource "datadog_service_level_objective" "success_failed_logins" {
  name        = "Successful Logins"
  description = "Tracking Successful Logins"
  type        = "metric"
  query {
    numerator   = "sum:account.login.success"
    denominator = "(sum:account.login.success + sum:account.login.failed)"
  }
  thresholds {
    timeframe = "7d"
    target    = "95.9"
    warning   = "97.0"
  }
  tags = local.datadog_tags
}
```

Updated Configuration
```hcl
resource "datadog_service_level_objective" "success_failed_logins" {
  name        = "Successful Logins"
  description = "Tracking Successful Logins"
  type        = "metric"
  query {
    numerator   = "sum:account.login.success"
    denominator = "(sum:account.login.success + sum:account.login.failed)"
  }
  thresholds {
    timeframe = "7d"
    target    = "80.0"
    warning   = "85.0"
  }
  tags = local.datadog_tags
}
```

### Debug Output
Diff of change:

![Screenshot](https://user-images.githubusercontent.com/10513197/229753130-0e7469ff-4824-4e97-a523-d9e69cbd6af0.png)

Result
![Screenshot](https://user-images.githubusercontent.com/10513197/229752917-8902cd54-f203-44ab-9bd2-13d03174fc14.png)

### Expected Behavior
The SLO target and warning should be updated accordingly.

### Actual Behavior
The underlying API throws an error about the payload been invalid due to the target_threshold and target not matching

![Screenshot](https://user-images.githubusercontent.com/10513197/229753904-32d2a73c-2bd0-4ab3-b3d8-fb7a07ab719d.png)

### Steps to Reproduce

Issue only occurs on apply and not on plan
1. `terraform apply`

### Important Factoids
When updating an SLO via the DataDog console, the target_threshold is set to the same as the target within the thresholds array in the api call
![Screenshot 2023-04-04 at 10 55 09](https://user-images.githubusercontent.com/10513197/229756837-87a32fd7-83f3-4550-bd95-3d8b625c7d8f.png)

**Comment by therve** [comment]
Hi,

You should add the following in your definition:

```hcl
  target_threshold = 80
  warning_threshold = 85
```

Otherwise default values are used and you get the error. Let us know if that works for you, thanks.

**Comment by therve** [comment]
Closing for now, feel free to reopen if you still have an issue.

**Comment by grimm26** [comment]
> Hi,
> 
> You should add the following in your definition:
> 
> ```terraform
>   target_threshold = 80
>   warning_threshold = 85
> ```
> 
> Otherwise default values are used and you get the error. Let us know if that works for you, thanks.

@therve   This is a documentation failure, then, because target_threshold and warning_threshold are marked as optional.

**Comment by emmaLP** [comment]
@smacktoid if you're changing the values in the thresholds block you need to set the likes of `warning_threshold` and so on. If they are unchanged then you don't need to set the "optional" values

**Comment by smacktoid** [comment]
> @smacktoid if you're changing the values in the thresholds block you need to set the likes of `warning_threshold` and so on. If they are unchanged then you don't need to set the "optional" values

@emmaLP, I am setting both the `target_threshold` and `warning_threshold` values. They're aligned with the contents of the relevant `thresholds` block.

But the provider seems to be picking up a default value for `warning_threshold` from _somewhere_, hence the error indicating that it's not matching the warning value in the relevant threshold.

**Comment by grimm26** [comment]
> > @smacktoid if you're changing the values in the thresholds block you need to set the likes of `warning_threshold` and so on. If they are unchanged then you don't need to set the "optional" values
> 
> @emmaLP, I am setting both the `target_threshold` and `warning_threshold` values. They're aligned with the contents of the relevant `thresholds` block.
> 
> But the provider seems to be picking up a default value for `warning_threshold` from _somewhere_, hence the error indicating that it's not matching the warning value in the relevant threshold.

I think terraform is ignoring your setting to warning_threshold because it is null instead of wiping it out?

**Comment by smacktoid** [comment]
I've tested completely removing the `warning_threshold` from the slo resources alongside the changes to remove the `warning` from the primary interval.

The effect seems to be the same as if the `warning_threshold` was set to `null`

```
│ Error: error updating service level objective from https://api.datadoghq.com/api/v1/slo/c1dd259e6c5355c5849bf0461c0e67b5: 400 Bad Request: {"errors":["Invalid payload: warning_threshold (99.99) and warning (undefined) for the same timeframe (30d) in the threshold list must match"]}
```
