### ISSUE TITLE
Browser Tests Advanced scheduling doesn't work at all

### ISSUE THREAD

**Issue by VladimirGladkyTR** [DataDog/terraform-provider-datadog#1855]
### Terraform Version
Terraform v1.4.2

### Affected Resource(s)
-   datadog_synthetics_test

### Terraform Configuration Files

```hcl
    scheduling {
        timeframes {
            day  = "1"
            from = "07:00"
            to   = "16:00"
        }
        timezone = "UTC"
    }
```

### Debug Output
```
          + scheduling {
              + timezone = "UTC"
              + timeframes {
                  + day  = 1
                  + from = "07:00"
                  + to   = "16:00"
                }
            }
```

### Panic Output

N/A

### Expected Behavior

Advanced schedule configured for browser test and only Monday is enabled

### Actual Behavior

Advanced schedule is not configured but Basic schedule is set instead 

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

It looks like scheduling section in config for browser test is completely ignored

### References

**Comment by therve** [comment]
Hi,

You're right, looks like there is a mismatch on options handling between API and browser tests. We'll come up with a fix, sorry for the troubles.
