### ISSUE TITLE
Resource datadog_synthetics_test change every time

### ISSUE THREAD

**Issue by IanMoroney** [DataDog/terraform-provider-datadog#1862]
It seems that the `datadog_synthetics_test` resource wants to change every time you plan, because it thinks the `browser_step.params.check` seems to be missing and wants to add it.

### Terraform Version
Terraform 1.4.4
Provider version 3.23.0

### Affected Resource(s)

Please list the resources as a list, for example:

-   datadog_synthetics_test

### Terraform Configuration Files

```hcl
resource "datadog_synthetics_test" "browser" {
  type = "browser"

  request_definition {
    method = "GET"
    url    = "https://www.github.com/"
  }

  device_ids = ["chrome.laptop_large", "firefox.laptop_large"]
  locations  = ["aws:eu-central-1", "aws:eu-west-2", "aws:eu-north-1", "aws:us-east-1"]

  options_list {
    tick_every = "300"
    retry {
      count    = "2"
      interval = "300"
    }
  }

  name    = "Github Website Homepage test"
  message = "@slack-devops_alerting"
  tags    = ["env:prd", "isTerraform:true", "owner: DevOps", "createdBy: DevOps Team"]

  status = "live"

  browser_step {
    name = "Check current url"
    type = "assertPageContains"
    params {
      check = "contains"
      value = "github"
    }
  }
}
```

### Plan Output

```
datadog_synthetics_test.browser: Refreshing state... [id=xvz-wiw-zic]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the      
following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # datadog_synthetics_test.browser will be updated in-place
  ~ resource "datadog_synthetics_test" "browser" {
        id              = "xvz-wiw-zic"
        name            = "Github Website Homepage test"
        tags            = [
            "env:prd",
            "isTerraform:true",
            "owner: DevOps",
            "createdBy: DevOps Team",
        ]
        # (8 unchanged attributes hidden)

      ~ browser_step {
            name                 = "Check current url"
            # (5 unchanged attributes hidden)

          ~ params {
              + check      = "contains"
                # (6 unchanged attributes hidden)
            }
        }

        # (2 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

### Debug Output

--

### Expected Behavior

The terraform plan should have detected no changes

### Actual Behavior

It wants to add the `check` param every time for every synthetics test.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?
No.

### References

None

**Comment by nkzou** [comment]
If you're trying to assert on the URL of the page, using `type = "assertCurrentUrl"` would be the correct assertion, and also fix the drift because that assertion type also takes the `check` parameter.

**Comment by IanMoroney** [comment]
Perfect! that's done the trick. Thank you @therve .
@nkzou , i am actually trying to assert for specific text in the page, so the `value` is needed, but you raise a good point about me correcting the `name` to make it clear that I'm asserting the page contents, and not the url.

Thank you both for your excellent help and suggestions, and i'll take both forward into my code :)

Case closed!
