### ISSUE TITLE
value "0" should be a valid one for monitor_priority

### ISSUE THREAD

**Issue by VladimirGladkyTR** [DataDog/terraform-provider-datadog#1865]
### Terraform Version

Terraform v1.4.4

### Affected Resource(s)

Please list the resources as a list, for example:

-   datadog_synthetics_test

### Terraform Configuration Files

```hcl
resource "datadog_synthetics_test" "my_browser_test" {
  ...
  options_list {
    ...
    monitor_priority = "0"
    ...
  }
  ...
}
```

### Debug Output

Error: expected options_list.0.monitor_priority to be in the range (1 - 5), got 0

### Panic Output

NA

### Expected Behavior

value "0" should be valid one for Monitor Priority = Not Defined

### Actual Behavior

Terraform Validate fails with error: "Error: expected options_list.0.monitor_priority to be in the range (1 - 5), got 0"

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

NA

### References

NA

**Comment by nkzou** [comment]
Hi,
A monitor with value 0 is invalid, which is why it's not supported. To have a monitor with no priority, you should omit the field entirely. #1617 has some more details on this.
Feel free to reopen the issue if you have further questions.
