### ISSUE TITLE
Step in Datadog GUI "Edit recording" screen cannot be copy/pasted when using "element_user_locator" alone

### ISSUE THREAD

**Issue by VladimirGladkyTR** [DataDog/terraform-provider-datadog#1870]
### Terraform Version

Terraform v1.4.4
on linux_amd64

### Affected Resource(s)

-   datadog_synthetics_test

### Terraform Configuration Files

config (1) which makes step impossible to copy/paste in Datadog GUI:
```hcl
  browser_step {
    name          = "Enter Username"
    type          = "typeText"
    timeout       = "60"
    allow_failure = "false"
    params {
      element_user_locator {
        fail_test_on_cannot_locate = "true"
        value {
          type  = "css"
          value = "#Username"
        }
      }
      value   = var.test_user
    }
  }
```
below are couple of config examples which do not have this issue:
config (2):
```hcl
  browser_step {
    name          = "Enter Username"
    type          = "typeText"
    timeout       = "60"
    allow_failure = "false"
    params {
      element= jsonencode(
        {
          "multiLocator" : {
            "ab": "",
            "at": "",
            "cl": "",
            "co": "",
            "ro": "",
            "clt": ""
          }
        }
      )
      element_user_locator {
        fail_test_on_cannot_locate = "true"
        value {
          type  = "css"
          value = "#Username"
        }
      }
      value   = var.test_user
    }
  }
```
or config (3):
```hcl
  browser_step {
    name          = "Enter Username"
    type          = "typeText"
    timeout       = "60"
    allow_failure = "false"
    params {
      element = jsonencode(
          {
            multiLocator = {},
            userLocator  = {
                failTestOnCannotLocate = true,
                values = [
                    {
                        type = "css",
                        value = "#Username"
                    }
                ]
            }
          }
      )
      value   = var.test_user
    }
  }
```

### Debug Output
output for config (1):
```hcl
      + browser_step {
          + allow_failure = false
          + name          = "Enter Username"
          + timeout       = 60
          + type          = "typeText"

          + params {
              + value   = "<removed>"

              + element_user_locator {
                  + fail_test_on_cannot_locate = true

                  + value {
                      + type  = "css"
                      + value = "#Username"
                    }
                }
            }
        }
```

### Panic Output

NA

### Expected Behavior

When using "element_user_locator" alone inside "browser_step" it should create a valid test step in Datadog which allows user to later copy/paste step in Datadog GUI "Edit recording" screen.

### Actual Behavior

When using "element_user_locator" alone inside "browser_step" (config number 1) it will create a step which is unable to copy/paste in Datadog GUI "Edit recording" screen.

### Steps to Reproduce

1. `terraform apply` using config (1)

### Important Factoids

It is possible to workaround this issue by using config (2) or config (3) by explicitly including empty "multiLocator" block into browser step config which uses "element_user_locator". Configuration become flooded with useless "multiLocator" blocks (config 2) or force to use "non-native" json blocks instead of hcl blocks (config 3).

Empty "multiLocator" block has to be included by default into Datadog config during apply when using "element_user_locator" alone inside "browser_step" so that in Datadog GUI "Edit recording" screen copy/paste step functionality works normally.

### References

NA

**Comment by romainberger** [comment]
Hi, thanks for reporting this issue, we've identified the issue and we're working on releasing a fix very soon.

**Comment by VladimirGladkyTR** [comment]
Thanks. I think it may also be the reason which prevents test from being cloned in DD GUI. It constantly gives an error "Could not clone the test, retry in few seconds" when you click on "Save & Edit Recording ->" during the clone process.

**Comment by nkzou** [comment]
Closing this issue as the backend fix was deployed. Please reopen if the issue persists, thanks!
