### ISSUE TITLE
datadog_service_level_objective: target_threshold and warning_threshold are not always optional

### ISSUE THREAD

**Issue by grimm26** [DataDog/terraform-provider-datadog#1872]
https://github.com/DataDog/terraform-provider-datadog/issues/1849 exposed the fact that `target_threshold` and `warning_threshold`, while listed in the documentation as optional, are not optional.

### Terraform Version

1.4.4

### Affected Resource(s)

-   datadog_service_level_objective

### Terraform Configuration Files

See https://github.com/DataDog/terraform-provider-datadog/issues/1849 for all other details.

### Expected Behavior

Either change the documentation to not list these attributes as optional or make the provider/resource treat them as optional.

### References

Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:

-   [1849](https://github.com/DataDog/terraform-provider-datadog/issues/1849)

**Comment by therve** [comment]
This has been fixed in #1879 which will be in next release, thanks.
