### ISSUE TITLE
bug: `datadog_synthetics_test` when passing `operator = isUndefined` 

### ISSUE THREAD

**Issue by augustomelo** [DataDog/terraform-provider-datadog#1876]
### Terraform Version

```bash
terraform -v
Terraform v1.4.4
on darwin_arm64
+ provider registry.terraform.io/datadog/datadog v3.23.0
```
### Affected Resource(s)

Please list the resources as a list, for example:

-   datadog_synthetics_test

### Terraform Configuration Files

```hcl
resource "datadog_synthetics_test" "example_synthetic_test" {
  name      = "monitor-name"
  tags      = "tag:example"
  message   = "message"
  locations = ["aws:eu-central-1"]
  status    = "live"
  subtype   = "multi"
  type      = "api"

  api_step {
    name    = "Generic name"
    subtype = "http"

    request_definition {
      method = "GET"
      url    = "http://mockserver:8080/api/rest/status"
    }

    assertion {
      operator = "lessThan"
      target   = "10000"
      type     = "responseTime"
    }

    assertion {
      operator = "is"
      target   = "200"
      type     = "statusCode"
    }

    assertion {
      operator = "validatesJSONPath"
      type     = "body"
      targetjsonpath {
        jsonpath    = "$.mesage"
        operator    = "isUndefined"
        targetvalue = ""
      }
    }

  options_list {
    tick_every = 900

    retry {
      count    = 2
      interval = 300
    }

    monitor_options {
      renotify_interval = 120
    }
  }
}
```

### Debug Output

`error updating synthetics API test from https://api.datadoghq.eu/api/v1/synthetics/tests/api/XXXXXXXX: 400 Bad Request: {"errors":["0.type: '' is not of type 'number'\n\nFailed validating 'type' in schema[0]:\n    {'type': 'number'}\n\nOn instance:\n    ''"]}`

### Expected Behavior

I expected the synthetic test to be created/updated, since the `operator = "isUndefined"` is a valid value, moreover since the `targetvalue` is not used on this case, I didn't expected it to be required.

### Actual Behavior

I was unable to create/updated the synthetic test.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

When I did the updated using the web app the field `targetvalue` was not set as you can see bellow:

```json
        "assertions": [
          {
            "operator": "lessThan",
            "target": 10000,
            "type": "responseTime"
          },
          {
            "operator": "is",
            "target": 200,
            "type": "statusCode"
          },
          {
            "operator": "validatesJSONPath",
            "target": {
              "jsonPath": "$.message",
              "operator": "isUndefined"
            },
            "type": "body"
          }
        ],
```

But upon looking at the code is the field targetValue is required: https://github.com/DataDog/terraform-provider-datadog/blob/c2f777c6a3e2b6f0b6535c6ca051df11f7b18acc/datadog/resource_datadog_synthetics_test_.go#L461

Also looking at the synthetic test API it doesn't specify the type for the `targetvalue` [create-an-api-test config](https://docs.datadoghq.com/api/latest/synthetics/#create-an-api-test config) > steps > assertions > Option 2 > target

Edit: Accidentally hit the `Enter` when I was editing the title, so I had almost no information filled.

**Comment by nkzou** [comment]
This has been closed by #1880. Will be a part of the next release, which is planned for by end of week. Thank you for the report!
