### ISSUE TITLE
Cannot remove the warning value from a primary threshold on a service level correction

### ISSUE THREAD

**Issue by smacktoid** [DataDog/terraform-provider-datadog#1877]
### Terraform Version

1.1.3

### Affected Resource(s)

-   datadog_service_level_objective

### Terraform Configuration Files
Original:

```hcl
resource "datadog_service_level_objective" "agent_desktop_availability" {
  name        = "Agent Desktop Availability"
  type        = "monitor"
  monitor_ids = [... omitted]
  thresholds {
    timeframe = "30d"
    target    = "99.9"
    warning   = "99.95"
  }
  timeframe = "30d"
  target_threshold = "99.9"
  warning_threshold = "99.95"
  tags = local.datadog_tags
}
```

Updated - note the goal is to increase the target to 99.9%, rendering a warning impossible. So it is removed.
```hcl
resource "datadog_service_level_objective" "agent_desktop_availability" {
  name        = "Agent Desktop Availability"
  type        = "monitor"
  monitor_ids = [... omitted]
  thresholds {
    timeframe = "30d"
    target    = "99.99"
    warning = null
  }
  timeframe = "30d"
  target_threshold = "99.99"
  warning_threshold = null
  tags = local.datadog_tags
}
```

### Debug Output

plan:
Note the absence of the `warning_threshold`, even though it was explicitly set to `null` in the script.

```
        ]
      ~ target_threshold  = 99.9 -> 99.99
        # (6 unchanged attributes hidden)
      ~ thresholds {
          ~ target          = 99.9 -> 99.99
          - warning         = 99.99 -> null
            # (3 unchanged attributes hidden)
        }
        # (1 unchanged block hidden)
    }
```

### Expected Behavior

The primary threshold should have been updated to a 99.9% target, and the warning removed.

### Actual Behavior

```
│ Error: error updating service level objective from https://api.datadoghq.com/api/v1/slo/6f077133bca056a590f899a92bf53107: 400 Bad Request: {"errors":["Invalid payload: warning_threshold (99.95) and warning (undefined) for the same timeframe (30d) in the threshold list must match"]}
│ 
│   with module.****.datadog_service_level_objective.all["*****_availability"],
│   on .terraform/modules/*****/datadog_slos.tf line 1, in resource "datadog_service_level_objective" "all":
│    1: resource "datadog_service_level_objective" "all" {
```

### Steps to Reproduce

1. `terraform plan`
2. `terraform apply`

### Important Factoids

Running the terraform script in harness.io

The scripting above is paraphrasing what's actually being used. A TF module is doing the job of creating all DataDog resources at runtime, based on descriptors held in seprate YAML files. It seems easiest to express the issue in terms of the raw TF resources being created by that module.

### References

Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:

-   [Unable to update target and warning values on SLO #1849](https://github.com/DataDog/terraform-provider-datadog/issues/1849)

**Comment by nkzou** [comment]
Reproduced. From my understanding, the old value for `warning_threshold` gets kept because it's a computed field. As a result the plan only shows `thresholds.warning -> null`, as it thinks `warning_threshold` was computed, causing the conflict when both get sent to the backend.
Looking into a fix, thanks for raising the issue.

**Comment by smacktoid** [comment]
Thanks for the explanation @nkzou 

I can test out a fix whenever it's available. For now I have simply set my target a little lower to leave headroom for the warning.
