### ISSUE TITLE
datadog_security_monitoring_default_rule changes to case on datadog backend cause TF errors

### ISSUE THREAD

**Issue by granular-ryanbonham** [DataDog/terraform-provider-datadog#1911]
Hi,

The datadog_security_monitoring_default_rule resource doesn't correctly handle case changes that happen on the backend. For example Datadog recently updated the CSPM rule "IAM password policy prevents password reuse" rule id 9f5_4or_5ni from having a case of status "low" to a status of "info.  

We have this resource managed via TF, and previously imported into our tf state. Our existing TF file contains this resource.

```hcl
```hcl
resource "datadog_security_monitoring_default_rule" "rule_9f5_4or_5ni" {
  # IAM password policy prevents password reuse
  enabled = true

  case {
    status        = "low"
    notifications = []
  }

}
```
```

When we update the tf to match the new rule configuration as such

```hcl
resource "datadog_security_monitoring_default_rule" "rule_9f5_4or_5ni" {
  # IAM password policy prevents password reuse
  enabled = true

  case {
    status        = "info"
    notifications = []
  }

}
```

The terraform plan fails with 

```
 Error: error: no rule case with status low
│ 
│   with module.built-in-cloud_configuration.datadog_security_monitoring_default_rule.rule_9f5_4or_5ni,
│   on modules/built-in/cloud_configuration/aws.tf line 138, in resource "datadog_security_monitoring_default_rule" "rule_9f5_4or_5ni":
│  138: resource "datadog_security_monitoring_default_rule" "rule_9f5_4or_5ni" {
```

### Terraform Version

Terraform v1.3.7. DataDog Provider 3.23.0

### Affected Resource(s)

Please list the resources as a list, for example:

-   datadog_security_monitoring_default_rule

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Expected Behavior

Terraform plan should be successful.

### Actual Behavior

What actually happened?

```
│ Error: error: no rule case with status critical
│ 
│   with module.built-in-cloud_configuration.datadog_security_monitoring_default_rule.rule_rps_fi3_zbw,
│   on modules/built-in/cloud_configuration/aws.tf line 1055, in resource "datadog_security_monitoring_default_rule" "rule_rps_fi3_zbw":
│ 1055: resource "datadog_security_monitoring_default_rule" "rule_rps_fi3_zbw" {

**Comment by nkzou** [comment]
Hi, thanks for reporting this. We'll looking into improving the logic. In the meantime, as a workaround can you try removing the resource from state with `terraform state rm <resource>` and re-importing it? Let us know if the workaround works for you.
