### ISSUE TITLE
datadog_logs_custom_pipeline provider can not process grok match rule with regex

### ISSUE THREAD

**Issue by feiy-sportsbet** [DataDog/terraform-provider-datadog#1914]
Hi there,
datadog_logs_custom_pipeline can not process below processor 
```
processor {
    grok_parser {
      samples = [""]
      source  = "message"
      grok {
        support_rules = ""
        match_rules   = "parse_rule %%{regex(\".*correlationId=\")}%%{word:correlation-id}%%{regex(\".*\")}"
      }
      name       = "parse java correlation id"
      is_enabled = true
    }
  }
```
always end with error
```
datadog_logs_custom_pipeline.tf_smf_nhl_feed_log_process: Modifying... [id=IIrxOfYuQBi9A-fCToKyZg]
╷
│ Error: Plugin did not respond
│
│   with datadog_logs_custom_pipeline.tf_smf_nhl_feed_log_process,
│   on smf-nhl-feed-log-pipeline.tf line 1, in resource "datadog_logs_custom_pipeline" "tf_smf_nhl_feed_log_process":
│    1: resource "datadog_logs_custom_pipeline" "tf_smf_nhl_feed_log_process" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-datadog_v3.25.0 plugin:


```

### Terraform Version

Terraform v1.1.6
on linux_amd64
+ provider registry.terraform.io/datadog/datadog v3.25.0

### Affected Resource(s)

-   logs_custom_pipeline

### Terraform Configuration Files

```hcl
# This file is maintained automatically by "terraform init".
# Manual edits may be lost in future updates.

resource "datadog_logs_custom_pipeline" "tf_feed_log_process" {
  filter {
    query = "service:*smf*"
  }
  name       = "tf_feed_log_process"
  is_enabled = false
  processor {
    grok_parser {
      samples = [""]
      source  = "message"
      grok {
        support_rules = ""
        match_rules   = "parse_rule %%{regex(\".*correlationId=\")}%%{word:smf-nhl-correlation-id}%%{regex(\".*\")}"
      }
      name       = "parse java correlation id"
      is_enabled = true
    }
  }
  processor {
    service_remapper {
      sources    = ["smf-service"]
      name       = "service remapper"
      is_enabled = false
    }
  }
}

```

### Debug Output

Please provide a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

**NOTE:** Remember to review debug output before posting, and redact any sensitive data.

### Panic Output
panic: interface conversion: interface {} is nil, not string

goroutine 15 [running]:
github.com/terraform-providers/terraform-provider-datadog/datadog.buildDatadogGrokParser(0x142bbe0?)
        github.com/terraform-providers/terraform-provider-datadog/datadog/resource_datadog_logs_custom_pipeline.go:995 +0x538
github.com/terraform-providers/terraform-provider-datadog/datadog.buildDatadogProcessor({0x1790378, 0xb}, 0xc0008a1ab8?)
        github.com/terraform-providers/terraform-provider-datadog/datadog/resource_datadog_logs_custom_pipeline.go:810 +0x1d8
github.com/terraform-providers/terraform-provider-datadog/datadog.buildDatadogProcessors({0xc0009c9ec0, 0x2, 0x17896a7?})
        github.com/terraform-providers/terraform-provider-datadog/datadog/resource_datadog_logs_custom_pipeline.go:775 +0x19f
github.com/terraform-providers/terraform-provider-datadog/datadog.buildDatadogPipeline(0x0?)
        github.com/terraform-providers/terraform-provider-datadog/datadog/resource_datadog_logs_custom_pipeline.go:761 +0x2f8
github.com/terraform-providers/terraform-provider-datadog/datadog.resourceDatadogLogsPipelineUpdate({0x19eec40?, 0xc0006813b0?}, 0xc0007c2480, {0x13f1260?, 0xc0000c8780?}) 
        github.com/terraform-providers/terraform-provider-datadog/datadog/resource_datadog_logs_custom_pipeline.go:454 +0x11a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0xc0002e09a0, {0x19eec40, 0xc0006813b0}, 0xd?, {0x13f1260, 0xc0000c8780})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:741 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0002e09a0, {0x19eec40, 0xc0006813b0}, 0xc0000e7380, 0xc0007c2280, {0x13f1260, 0xc0000c8780})        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:847 +0x83a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0002178c0, {0x19eec40?, 0xc000681260?}, 0xc00074e780)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/grpc_provider.go:1021 +0xe8d
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.muxServer.ApplyResourceChange({0xc00039a150, 0xc00039a1b0, {0xc0005420a0, 0x2, 0x2}, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...)
        github.com/hashicorp/terraform-plugin-mux@v0.8.0/tf5muxserver/mux_server_ApplyResourceChange.go:27 +0x102
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0000015e0, {0x19eec40?, 0xc000680240?}, 0xc00041e0e0)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:818 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x16cbd20?, 0xc0000015e0}, {0x19eec40, 0xc000680240}, 0xc00041e000, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0008aa000, {0x19f39e0, 0xc00072d860}, 0xc00064a000, 0xc00074b3e0, 0x25cd140, 0x0)
        google.golang.org/grpc@v1.51.0/server.go:1340 +0xd23
google.golang.org/grpc.(*Server).handleStream(0xc0008aa000, {0x19f39e0, 0xc00072d860}, 0xc00064a000, 0x0)
        google.golang.org/grpc@v1.51.0/server.go:1713 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.51.0/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.51.0/server.go:963 +0x28a

Error: The terraform-provider-datadog_v3.25.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

### Expected Behavior

can use regex in this processor

### Actual Behavior

always fail

### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:

1. `terraform apply`

### References
No

**Comment by nkzou** [comment]
Reproduced, we'll have a fix for it in the next release. In the meantime you can avoid the issue by making sure there is no empty string in `samples` like so -
```
processor {
    grok_parser {
      samples = []
      source  = "message"
      grok {
        support_rules = ""
        match_rules   = "parse_rule %%{regex(\".*correlationId=\")}%%{word:correlation-id}%%{regex(\".*\")}"
      }
      name       = "parse java correlation id"
      is_enabled = true
    }
  }

```
