### ISSUE TITLE
Feature Request: Add more namespaces to datadog_integration_aws_tag_filter resource

### ISSUE THREAD

**Issue by colbyall** [DataDog/terraform-provider-datadog#1934]
Team,

Would it be possible to provide add support for more namespaces for `datadog_integration_aws_tag_filter{}` resource? I wanted to filter metrics for `dynamodb`, `s3` etc... based on specific tags but it's not currently supported.

Thanks

**Comment by nkzou** [comment]
This looks like a limitation of the backend AWS integration itself, rather than our terraform provider. I'd suggest [opening a support ticket](https://help.datadoghq.com/hc/en-us) to submit a feature request for the AWS Integration's Metric Collection Tag Filter to support more AWS resources.
