### ISSUE TITLE
Seems there is something wrong with config_variable type in datadog_synthetics_test

### ISSUE THREAD

**Issue by mimiz** [DataDog/terraform-provider-datadog#1935]
Hi there,

I am trying to create synthetic tests through terraform.
When I am using *config_variariable* I have got an error on `terraform apply` (see below)

### Terraform Version

Using terraform version : 1.4.6
Datadog provider : 3.25.0

### Affected Resource(s)

Please list the resources as a list, for example:

- [datadog_synthetics_test](https://registry.terraform.io/providers/DataDog/datadog/latest/docs/resources/synthetics_test)  
- [config_variable](https://registry.terraform.io/providers/DataDog/datadog/latest/docs/resources/synthetics_test#nested-schema-for-config_variable)
- 
### Terraform Configuration Files

Here is the *config_variable* code : 

```hcl
 config_variable {
    type = "global"
    name = "DEMO"
    id   = datadog_synthetics_global_variable.infra_access_token_url.id
  }
```

### Debug Output
The error is : 

```
Error: error updating synthetics API test from https://api.datadoghq.eu/api/v1/synthetics/tests/api/xap-897-nxv: 400 Bad Request: {"errors":["0.properties.type.enum: 'text' is not one of ['email']\n\nFailed validating 'enum' in schema[0]['properties']['type']:\n    {'enum': ['email'], 'type': 'string'}\n\nOn instance['type']:\n    'text'"]}
│ 
│   with datadog_synthetics_test.pearl_merch_api_synthetic,
│   on main.tf line 24, in resource "datadog_synthetics_test" "pearl_merch_api_synthetic":
│   24: resource "datadog_synthetics_test" "pearl_merch_api_synthetic" {
```

It seems that the *"type"* of the variable must be *email*, but if I use email, the `terraform plan` will fail saying, *type* must be either *global* or *text*.

If I remove the *config_variable* (for try) `terraform apply` will succeed ... 

Any ideas ? 

Maybe backend api issue ? 

regards

Rémi

**Comment by therve** [comment]
Hi,

I can't seem to be able to reproduce. Can you share more details about the test and the variable? If it contains private info please open a support ticket. Thanks.

**Comment by mimiz** [comment]
Hi I tried again tonight, and it seems to be ok now.
I did not change anything on my TF code .
I will close this issue, sorry :(
