### ISSUE TITLE
request_basicauth config is not being applied to the DD test

### ISSUE THREAD

**Issue by Dinky7NZ** [DataDog/terraform-provider-datadog#1942]
Hi,

### Terraform Version
Terraform v1.4.6
on darwin_amd64
+ provider registry.terraform.io/datadog/datadog v3.25.0
+ provider registry.terraform.io/hashicorp/azurerm v3.51.0

### Affected Resource(s)

Please list the resources as a list, for example:

datadog_synthetics_test

### Terraform Configuration Files
Note: this is in a module

```hcl
resource "datadog_synthetics_test" "ApiTest" {
  name    = local.name
  status  = var.enable ? "live" : "paused"
  type    = "api"
  subtype = "http"
  locations = ["aws:ap-southeast-2"]

  request_definition {
    method = "GET"
    url    = "https://${var.subdomain}.${var.env_config.hostname}/${var.path}"
  }

  dynamic "request_basicauth" {
    for_each = var.request_basicauth[*]
    content {
      access_token_url = request_basicauth.value["access_token_url"]
      client_id        = request_basicauth.value["client_id"]
      client_secret    = request_basicauth.value["client_secret"]
      scope            = request_basicauth.value["scope"]
    }
  }

  dynamic "assertion" {
    for_each = var.SuccessCriteria
    content {
      type     = assertion.value["type"]
      operator = assertion.value["operator"]
      target   = assertion.value["target"]
      property = lookup(assertion, "property", null) # Optional
    }
  }

  options_list {
    monitor_name     = local.name
    monitor_priority = 3
    http_version     = var.http_version
    tick_every       = local.CheckFrequencyInSeconds
  }

  message = <<-EOT
    blahblah
  EOT
}
```

### Expected Behavior

The plan is applied and I can see the auth settings in the DD portal and it works.

### Actual Behavior

The plan is applied successfully but the changes don't appear on the DD portal when I view the test details.
The tf state file has the changes for the `request_basicauth` block configured.

![image](https://github.com/DataDog/terraform-provider-datadog/assets/28836138/a7ab3162-9f8e-4d4e-ad92-c45f4bbdcf91)

![image](https://github.com/DataDog/terraform-provider-datadog/assets/28836138/3086d976-7147-46e6-89ef-3ce9870d458f)

### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:

1. `terraform apply`

### Important Factoids

I updated other aspects of the detail i.e. the http_version and it shows on the DD portal.

**Comment by nkzou** [comment]
I believe setting `type = "oauth-client"` in the `request_basicauth` should fix this. It defaults to `web`, so your other options are getting ignored.

**Comment by Dinky7NZ** [comment]
Damn, I thought `oauth-rop` was the one instead but same error as `oauth-client`

```
module.ApiTests["Powerchainsvc"].datadog_synthetics_test.ApiTest: Modifying... [id=hci-f7x-mu2]
╷
│ Error: error updating synthetics API test from https://api.us3.datadoghq.com/api/v1/synthetics/tests/api/hci-f7x-mu2: 400 Bad Request: {"errors":["0.properties.type.const: 'web' was expected\n\nFailed validating 'const' in schema[0]['properties']['type']:\n    {'const': 'web'}\n\nOn instance['type']:\n    'oauth-rop'"]}
│
│   with module.ApiTests["Powerchainsvc"].datadog_synthetics_test.ApiTest,
│   on modules/UxMonitoring/SyntheticTests/ApiTest/main.tf line 5, in resource "datadog_synthetics_test" "ApiTest":
│    5: resource "datadog_synthetics_test" "ApiTest" {
```

**Comment by nkzou** [comment]
After some testing I found that I needed both `type = "oauth-client"` and `token_api_authentication = "header"` to properly apply the auth settings. However, I also ran into a segfault that sometimes occurs when setting basicauth settings, for which I'm putting up a PR shortly to fix, so if you run into that I'll merge a fix shortly (with the next provider release early next week).

**Comment by Dinky7NZ** [comment]
Thanks @nkzou. Adding `token_api_authentication = "header"` has allowed my tf to run and apply.

When I run a test of the synthetic test setup, I'm getting this error :

![image](https://github.com/DataDog/terraform-provider-datadog/assets/28836138/c8e51859-ebd8-415a-853e-f32a062d5ffe)

I haven't set the `request` parameter
![image](https://github.com/DataDog/terraform-provider-datadog/assets/28836138/61692472-35c2-4141-adb4-ba287d7744ea)

The tf state shows the same:
![image](https://github.com/DataDog/terraform-provider-datadog/assets/28836138/e9bbd687-4f48-450b-84de-a9c25355a1fe)

I wondered if Datadog needs the value to be null instead of `""` but I can't set it to null as the default is `""`
Is that the problem or is it the segfault issue you mentioned which has been fixed and just need to wait till the next version comes out?
![image](https://github.com/DataDog/terraform-provider-datadog/assets/28836138/18addd65-dc31-4aaf-85d8-dbebf44d0717)

**Comment by nkzou** [comment]
I don't believe the issue here is related to the segfault. Does the test work if you manually create it via the web app? If so, I suspect the issue is with `""` vs null as you mentioned. Working on confirming that with the relevant team.

**Comment by Dinky7NZ** [comment]
@nkzou Yes, it works when i set the config manually
