### ISSUE TITLE
Add support for Fastly integration

### ISSUE THREAD

**Issue by eheydrick** [DataDog/terraform-provider-datadog#195]
This feature request is for a `datadog_integration_fastly` resource. It would be useful to configure the Fastly Datadog integration in Terraform code.

Datadog docs: https://docs.datadoghq.com/integrations/fastly/

**Comment by moogzy** [comment]
Any thoughts/progress on making this happen? I'm now exploring a migration from Cloudflare to Fastly and looking at getting this integration setup happening.

**Comment by danbf** [comment]
As well here.  While we terraform our Fastly setups, since adding the Fastly services to DataDog is manual we often forget.  If  configuring the Faslty Integration config was in Terraform, then we could just have it as part of our template and not forget.
