### ISSUE TITLE
Terraform is failing with https://api.datadoghq.com/api/v1/synthetics/tests/api: 400 Bad Request, Global variable invalid names errors

### ISSUE THREAD

**Issue by shwetaarshad** [DataDog/terraform-provider-datadog#1964]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version

Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

### Affected Resource(s)

Please list the resources as a list, for example:

-   opc_instance
-   opc_storage_volume

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### Debug Output

Please provide a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

**NOTE:** Remember to review debug output before posting, and redact any sensitive data.

### Panic Output

If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

**NOTE:** Remember to review panic log file before posting, and redact any sensitive data.

### Expected Behavior

What should have happened?

### Actual Behavior

What actually happened?

### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:

1. `terraform apply`

### Important Factoids

Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

### References

Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:

-   GH-1234

**Comment by therve** [comment]
Hi,

It's a bit hard to tell without more information, but this error should mean that the name you associated in your test doesn't match the name associated with the global variable. Maybe it got renamed?

**Comment by bryanjknight** [comment]
I'm also having the same issue. I've confirmed that the requested global variable in the error message:
```
│ Error: error updating synthetics API test from https://api.datadoghq.com/api/v1/synthetics/tests/api/pdc-55y-854: 400 Bad Request: {"errors":["Global variable invalid names: DEV_ENRICHMENT_TEST_CLIENT_TOKEN"]}
│ 
│   with module.dev_enrich_checks.datadog_synthetics_test.test_conditions_enrich,
│   on modules/checks/enrichment_health_checks/conditions.tf line 1, in resource "datadog_synthetics_test" "test_conditions_enrich":
│    1: resource "datadog_synthetics_test" "test_conditions_enrich" {
│ 
╵
``` 

matches what's in the UI

![image](https://github.com/DataDog/terraform-provider-datadog/assets/1211418/9d413346-1e92-4615-bb8c-007f98c15326)

**Comment by bryanjknight** [comment]
We're also using `3.19.1` of the provider. Will try to upgrade to the latest `3.26.0` and see if that helps

**Comment by therve** [comment]
You config uses terraform variables, but not synthetics ones? Curious about the bits that references `DEV_ENRICHMENT_TEST_CLIENT_TOKEN`,

**Comment by therve** [comment]
Thanks for check it. I'll close that one for now, let us know if it happens again with 3.26 or above.
