### ISSUE TITLE
Issue with AWS Core Integration

### ISSUE THREAD

**Issue by naveenkumarer** [DataDog/terraform-provider-datadog#1978]
Hi there,

Issue Description:

Datadog provider version 3.25.0 and 3.26.0. It worked fine until 2 weeks ago with 3.25.0.

│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to module.dab-datadog.module.dab-datadog.datadog_integration_aws.core[0], provider "module.dab-datadog.module.dab-datadog.provider[\"registry.terraform.io/datadog/datadog\"]" produced an unexpected new value: Root resource was present, but now
│ absent.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.

### Terraform Version

Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

terraform version 1.3.4

### Affected Resource(s)

Please list the resources as a list, for example:

AWS Core Integration - datadog_integration_aws

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### Debug Output

Please provide a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

**NOTE:** Remember to review debug output before posting, and redact any sensitive data.

### Panic Output

If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

**NOTE:** Remember to review panic log file before posting, and redact any sensitive data.

### Expected Behavior

What should have happened?

### Actual Behavior

AWS integration should have been created in datadog and associated IAM Roles and Policies should have been created in AWS account.

What actually happened?

### Steps to Reproduce

terraform apply

Please list the steps required to reproduce the issue, for example:

1. `terraform apply`

### Important Factoids

Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

### References

Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:

-   GH-1234

**Comment by nkzou** [comment]
Hi, could you share some more details about your configuration? Is this happening on create, read, destroy, etc, are you using `access_key_id`/`secret_access_key` or the standard `account_id`, etc? Also, do you know if the integration account being changed was re-created? for example if the aws integration for a specific account gets deleted and then the same account_id got created again within the minute? Trying to narrow down the suspect code paths. Thanks!

**Comment by naveenkumarer** [comment]
I am using standard account_id and it is happening on create for now. I have been struggling with this since last week, hence do not remember if it happened on modify.

## This tf file will setup Datadog AWS integration
resource "datadog_integration_aws" "core" {
  count      = var.enable_datadog_aws_integration ? 1 : 0
  account_id = var.aws_account_id
  role_name  = "datadog-integration-role"

  host_tags = [
    "Namespace:${var.namespace}",
    "env:${var.env}"
  ]

  account_specific_namespace_rules = var.account_specific_namespace_rules
  excluded_regions                 = var.excluded_regions
  filter_tags                      = var.filter_tags
}

resource "aws_iam_role" "datadog-integration" {
  count = var.enable_datadog_aws_integration ? 1 : 0
  name  = "datadog-integration-role"

  assume_role_policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "AWS": "arn:aws:iam::464622532012:root"
      },
      "Action": "sts:AssumeRole",
      "Condition": {
        "StringEquals": {
          "sts:ExternalId": "${datadog_integration_aws.core[0].external_id}"
        }
      }
    }
  ]
}
EOF

  tags = merge(var.default_tags, {
    description = "This role allows the datadog AWS account to access this account for metrics collection"
  })
}

resource "aws_iam_policy" "datadog-core" {
  count       = var.enable_datadog_aws_integration ? 1 : 0
  name        = "datadog-core-integration"
  path        = "/"
  description = "This IAM policy allows for core datadog integration permissions"

  policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": [
        "apigateway:GET",
        "autoscaling:Describe*",
        "budgets:ViewBudget",
        "cloudformation:DetectStack*",
        "cloudfront:GetDistributionConfig",
        "cloudfront:ListDistributions",
        "cloudtrail:LookupEvents",
        "cloudtrail:DescribeTrails",
        "cloudtrail:GetTrailStatus",
        "cloudwatch:Describe*",
        "cloudwatch:Get*",
        "cloudwatch:List*",
        "codedeploy:List*",
        "codedeploy:BatchGet*",
        "directconnect:Describe*",
        "dynamodb:List*",
        "dynamodb:Describe*",
        "ec2:Describe*",
        "ecs:Describe*",
        "ecs:List*",
        "elasticache:Describe*",
        "elasticache:List*",
        "elasticfilesystem:DescribeAccessPoints",
        "elasticfilesystem:DescribeFileSystems",
        "elasticfilesystem:DescribeTags",
        "elasticloadbalancing:Describe*",
        "elasticmapreduce:List*",
        "elasticmapreduce:Describe*",
        "es:ListTags",
        "es:ListDomainNames",
        "es:DescribeElasticsearchDomains",
        "fsx:DescribeFileSystems",
        "health:DescribeEvents",
        "health:DescribeEventDetails",
        "health:DescribeAffectedEntities",
        "kinesis:List*",
        "kinesis:Describe*",
        "lambda:AddPermission",
        "lambda:GetPolicy",
        "lambda:List*",
        "lambda:RemovePermission",
        "logs:Get*",
        "logs:Describe*",
        "logs:FilterLogEvents",
        "logs:TestMetricFilter",
        "logs:PutSubscriptionFilter",
        "logs:DeleteSubscriptionFilter",
        "logs:DescribeSubscriptionFilters",
        "organizations:DescribeOrganization",
        "rds:Describe*",
        "rds:List*",
        "redshift:DescribeClusters",
        "redshift:DescribeLoggingStatus",
        "route53:List*",
        "s3:GetBucketLogging",
        "s3:GetBucketLocation",
        "s3:GetBucketNotification",
        "s3:GetBucketTagging",
        "s3:ListAllMyBuckets",
        "s3:PutBucketNotification",
        "ses:Get*",
        "sns:List*",
        "sns:Publish",
        "states:ListStateMachines",
        "states:DescribeStateMachine",
        "sqs:ListQueues",
        "support:*",
        "tag:GetResources",
        "tag:GetTagKeys",
        "tag:GetTagValues",
        "xray:BatchGetTraces",
        "xray:GetTraceSummaries"
      ],
      "Effect": "Allow",
      "Resource": "*"
    }
  ]
}
EOF
}

resource "aws_iam_role_policy_attachment" "datadog-core-attach" {
  count      = var.enable_datadog_aws_integration ? 1 : 0
  role       = aws_iam_role.datadog-integration[0].name
  policy_arn = aws_iam_policy.datadog-core[0].arn
}

resource "aws_iam_role_policy_attachment" "datadog-core-attach-extras" {
  for_each   = toset(var.extra_policy_arns)
  role       = aws_iam_role.datadog-integration[0].name
  policy_arn = each.value
}

**Comment by naveenkumarer** [comment]
AWS Core integration with integration account was created successfully earlier and then deleted. we have been trying to re-create it and getting this error.

Same error is coming in both scenarios,
1) AWS integration for a specific account gets deleted and then the same account_id got created again within the minute.
2) AWS integration for a specific account gets deleted and then the same account_id got created again after some time.

**Comment by zhengguang-finix** [comment]
facing to the same issue, which becomes a hard blocker for our AWS integration.

**Comment by dhnokia** [comment]
same issue with aws integration

**Comment by naveenkumarer** [comment]
I have moved away from using terraform resource to aws CloudFormation as workaround for now.

resource "aws_cloudformation_stack" "datadog-core" {
  name         = "datadog-core-integration"
  capabilities = ["CAPABILITY_IAM", "CAPABILITY_NAMED_IAM", "CAPABILITY_AUTO_EXPAND"]
  parameters = {
    APIKey                    = var.datadog_api_key
    APPKey                    = var.datadog_app_key
    DatadogSite               = var.dd_forwarder_dd_site
    InstallLambdaLogForwarder = true
    IAMRoleName               = "DatadogIntegrationRole"
    DisableMetricCollection   = false
  }
  template_url = "https://datadog-cloudformation-template-quickstart.s3.amazonaws.com/aws/main_v2.yaml"

  lifecycle {
    ignore_changes = [
      parameters["DatadogApiKey"]
    ]
  }
}
 
Please note this stack deploys aws core integration and logs forwarder lambda as well.

**Comment by nkzou** [comment]
Could those of you running into this issue confirm whether or not this is happening when deleting and re-creating the last remaining aws integration in the datadog org? for example if there is only 1 aws integration account, which gets deleted, bringing the count to 0, and then re-created, triggering this error? Or does this also happen if there are multiple existing aws integration accounts and the total count of integration accounts never drops to 0?

**Comment by zhengguang-finix** [comment]
> Could those of you running into this issue confirm whether or not this is happening when deleting and re-creating the last remaining aws integration in the datadog org? for example if there is only 1 aws integration account, which gets deleted, bringing the count to 0, and then re-created, triggering this error? Or does this also happen if there are multiple existing aws integration accounts and the total count of integration accounts never drops to 0?

Like mentioned by @naveenkumarer, the error occurs in both fresh new AWS account and after existing account delete. For fresh new AWS account, when terraform error out, the aws account does show up in Datadog dashboard (and shows in error status). That means terraform does successfully call Datadog API to create an AWS account integration with token generated, but the datadog provider failed to understand the response Datadog sends back.

If we apply terraform again without delete the existing AWS account from Datadog, terraform will complain about the account already exists, which is reasonable, but also means the Datadog API is not idempotent.

After delete the existing AWS account from Datadog, wait for a while (about 1 hour), apply terraform again, the same error ("Root resource was present, but now absent") appears.

**Comment by emeraldsanto** [comment]
We've also been running into this issue since last Friday, even using the `3.18` provider version which we've used to create the integration in the past (we have a handy module for it that remained unchanged).

I've retried the run several times with different versions and `TF_LOG=debug` which yielded these interesting HTTP request logs

```
2023-06-26T16:32:00.392Z [INFO]  provider.terraform-provider-datadog_v3.18.0: 2023/06/26 16:32:00
POST /api/v1/integration/aws HTTP/1.1
Host: api.datadoghq.com
User-Agent: terraform-provider-datadog/3.18.0 (terraform 2.10.1; terraform-cli 1.1.9) datadog-api-client-go/2.5.0 (go go1.18.7; os linux; arch amd64)
Content-Length: 291
Accept: application/json
Content-Type: application/json
Dd-Api-Key: REDACTED
Dd-Application-Key: REDACTED
Accept-Encoding: gzip

{"account_id":"REDACTED","account_specific_namespace_rules":{"step_functions":true},"cspm_resource_collection_enabled":false,"excluded_regions":[],"filter_tags":[],"host_tags":[],"metrics_collection_enabled":true,"resource_collection_enabled":false,"role_name":"DatadogIntegrationRole"}: timestamp=2023-06-26T16:32:00.392Z

2023-06-26T16:32:00.955Z [INFO]  provider.terraform-provider-datadog_v3.18.0: 2023/06/26 16:32:00
HTTP/1.1 200 OK
Transfer-Encoding: chunked
Connection: keep-alive
Content-Security-Policy: frame-ancestors 'self'; report-uri https://logs.browser-intake-datadoghq.com/api/v2/logs?dd-api-key=REDACTED&dd-evp-origin=content-security-policy&ddsource=csp-report&ddtags=site%3Adatadoghq.com
Content-Type: application/json
Date: Mon, 26 Jun 2023 16:32:00 GMT
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
Vary: Accept-Encoding
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
```

which is immediately followed by

```
2023-06-26T16:32:00.956Z [INFO]  provider.terraform-provider-datadog_v3.18.0: 2023/06/26 16:32:00
GET /api/v1/integration/aws HTTP/1.1
Host: api.datadoghq.com
User-Agent: terraform-provider-datadog/3.18.0 (terraform 2.10.1; terraform-cli 1.1.9) datadog-api-client-go/2.5.0 (go go1.18.7; os linux; arch amd64)
Accept: application/json
Dd-Api-Key: REDACTED
Dd-Application-Key: REDACTED
Accept-Encoding: gzip

2023-06-26T16:32:01.026Z [INFO]  provider.terraform-provider-datadog_v3.18.0: 2023/06/26 16:32:01
HTTP/1.1 200 OK
Content-Length: 16
Connection: keep-alive
Content-Security-Policy: frame-ancestors 'self'; report-uri https://logs.browser-intake-datadoghq.com/api/v2/logs?dd-api-key=REDACTED&dd-evp-origin=content-security-policy&ddsource=csp-report&ddtags=site%3Adatadoghq.com
Content-Type: application/json
Date: Mon, 26 Jun 2023 16:32:01 GMT
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN

{"accounts":[]}: timestamp=2023-06-26T16:32:01.026Z
```

My understanding of the above is that a first call is made to Datadog (`POST /api/v1/integrations/aws`) in order to create the integration which succeeds, as indicated by the response status code of `HTTP 200`. A second call is then made to retrieve the list of AWS integrations (`GET /api/v1/integrations/aws`) which behaves as if no integrations had been created, as per the empty `accounts` array in the response body.

This is odd because when visiting the Datadog dashboard, the AWS account is present and marked as configured (except there is one error message stating that Datadog is not authorized to perform `sts:AssumeRole`, presumably because the Terraform apply failed before creating the necessary role).

**Comment by emeraldsanto** [comment]
I just re-ran a failing plan and apply without any problems, thanks 😎

**Comment by nkzou** [comment]
@ArunSisodiya The backend fix for the 500 error was pushed out within the last hour.
I'm going to go ahead and close this issue. If you're still running into errors with `inconsistent result after apply` feel free to re-open. Otherwise please open a new issue, thanks!
