### ISSUE TITLE
[datadog_downtime] Scheduled downtime start cannot be in the past

### ISSUE THREAD

**Issue by orlandothoeny** [DataDog/terraform-provider-datadog#1983]
It is not possible to create a downtime that starts in the past. When trying to create one, I get the error "Scheduled downtime start cannot be in the past".

I also tried creating a downtime, where the `start` is in the past, and the `end` is in the future. Getting the same error.

### Terraform Version
1.5.1

### Provider Version
3.25.0

### Affected Resource
-   datadog_downtime

### Terraform Configuration Files

Timestamp at time of `terraform apply`: 1687853504 (Tue Jun 27 2023 10:11:44 GMT+0200)
```hcl
resource "datadog_downtime" "downtime" {
  scope      = ["*"]
  monitor_id = var.monitor_id

  start    = 1687853658 # Mon Jun 26 2023 00:00:00 GMT+0200
  end      = 1687816800 # Tue Jun 27 2023 00:00:00 GMT+0200
  timezone = "Europe/Zurich"

  recurrence {
    type      = "weeks"
    week_days = ["Sat", "Sun"]
    period    = 1
  }
}
```

### Output

```
╷
│ Error: error creating downtime from https://api.datadoghq.eu/api/v1/downtime: 400 Bad Request: {"errors":["Scheduled downtime start cannot be in the past"]}
│ 
│   with module.XXXXXX,
│   on ../modules/monitoring/datadog/recurring_downtime/main.tf line 43, in resource "datadog_downtime" "downtime":
│   43: resource "datadog_downtime" "downtime" {
│ 
╵
```

### Expected Behavior
Downtime is created.

### References
-   [GH-1234](https://github.com/DataDog/terraform-provider-datadog/issues/1169)

**Comment by therve** [comment]
Thanks for the report.

That's expected behavior. You need to set start in the future to be able to create a downtime. This is coming from the API so there is nothing in the provider that we can do about it. You can use terraform time [resources](https://registry.terraform.io/providers/hashicorp/time/latest/docs/resources/static) if you want to have some dynamism in your resource creation.

**Comment by orlandothoeny** [comment]
Ah okay. Is there any way to prevent this problem?

We create a monitor & downtime for that monitor via Terraform. The first recurrence of the downtime starts tomorrow. 
The monitor checks whether an application is available. It is shut down during the night. This is what the downtime is for.
On the day when we create the monitor & downtime via Terraform, alerts are triggered (which go to our on-call SRE) in the night if the monitor that was created is not muted manually for 1 day.

There are n instances of this monitor + downtime pair. Which is why we want to avoid this.

**Comment by therve** [comment]
You need to set the start date after the downtime creation, that's all. If your downtime starts during the night, set the start during the night? It shouldn't prevent you from doing any particular logic.
