### ISSUE TITLE
Provide dashboard URL as exported attribute

### ISSUE THREAD

**Issue by riisi** [DataDog/terraform-provider-datadog#1990]
### Terraform Version
1.0.46

### Affected Resource(s)

-   datadog_dashboard_json

### Feature Request

Would it be possible to provide the Dashboard URL as an exported attribute on the dashboard resources? 

Our use case is that we want to include the URL in related monitors, to help SRE resolve issues. To do that currently, we can use a `data` resource to retrieve the URL. However, the plan fails for new environments, because the dashboard doesn't exist yet. 

```
 │ Error: couldn't find a dashboard named Spark
│ 
│   with data.datadog_dashboard.spark_dashboard,
│   on eks-monitors.tf line 1, in data "datadog_dashboard" "spark_dashboard":
│    1: data "datadog_dashboard" "spark_dashboard" {
```

If the URL was exported, we wouldn't need the data resource and Terraform should handle dependencies correctly.

**Comment by skarimo** [comment]
Hello this is already supported. The dashboard is exposed via `url` attribute see https://registry.terraform.io/providers/DataDog/datadog/latest/docs/resources/dashboard_json#url

```
resource "datadog_dashboard_json" "dashboard_json" {
  dashboard = <<EOF
{
   "title":"Ordered Layout Dashboard",
   "description":"Created using the Datadog provider in Terraform",
   "widgets":[],
   "layout_type":"ordered",
   "is_read_only":true,
   "notify_list":[],
   "template_variables":null
}
EOF
}

output "dashboard_url" {
  value = datadog_dashboard_json.dashboard_json.url
}
```

```
➜  terraform terraform output
dashboard_url = "/dashboard/juz-5qe-a7s/ordered-layout-dashboard"
```
