### ISSUE TITLE
400 Bad Request: {"errors":["The `locked` monitor option has been replaced with role-based access 

### ISSUE THREAD

**Issue by Ramvi12** [DataDog/terraform-provider-datadog#1996]
Hi there,

Terraform Version

Terraform v0.13.7

provider registry.terraform.io/datadog/datadog v2.25.0

When deploying monitors to datadog, we encounted an issue to replace 'locked' monitoring option with role-bases access, however  the 'locked' monitor option is deprecated staring from v.3.11.0 and we using an older version(v2.25.0).In addition we are seeing this behaviour when trying to deploy newer monitors, and older ones are working without any issue.  

Error: error validating monitor: 400 Bad Request: {"errors":["The `locked` monitor option has been replaced with role-based access control: https://docs.datadoghq.com/monitors/guide/how-to-set-up-rbac-for-monitors/?tab=ui#migrate-monitors-from-locked-to-restricted-roles"]}
  on main.tf line 1, in resource "datadog_monitor" "datadog-monitor":
  1: resource "datadog_monitor" "datadog-monitor"

**Comment by therve** [comment]
Hi,

The locked option has been deprecated in the 3.11 version of the resource, but has since then been removed from our backend. You need to upgrade the resource and use restricted roles. Thanks.

**Comment by nkzou** [comment]
@Ramvi12 Hi, if the `locked` monitor option previously worked for you/your org, please open a ticket at https://help.datadoghq.com/ and let them know that the `locked` monitor field has stopped working for you - they'll assess why/how your Datadog organization stopped allowing the usage of that option, and whether or not it should be re-enabled. Thanks!
