### ISSUE TITLE
Add support for Trigger when the evaluated setting

### ISSUE THREAD

**Issue by chad-whelan-kr** [DataDog/terraform-provider-datadog#2001]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version

Terraform v1.4.6

### Affected Resource(s)
datadog_monitor

### Expected Behavior
Please add support for the "Trigger when the evaluated value" Monitor drop down so that the evaluated thresholds can be set to trigger at the same "above" / "above or equal to" / "below" / "below or equal to" options as the Datadog UI.

### Actual Behavior
The threshold defaults to "above" without the ability to change the behavior

### Steps to Reproduce
New feature request, or documentation clarification if I missed an existing option

### Important Factoids
Nothing, really.  Just creating log monitors through tf.

**Comment by therve** [comment]
Hi,

This information in the UI is encoded in the `query` parameter. You can translate `above` to `>` and below to `<`, with the equal part if needed. Let us know if that doesn't make sense, thanks.

**Comment by chad-whelan-kr** [comment]
> Hi,
> 
> This information in the UI is encoded in the `query` parameter. You can translate `above` to `>` and below to `<`, with the equal part if needed. Let us know if that doesn't make sense, thanks.

Nope, makes perfect sense.  Thanks!
