### ISSUE TITLE
Terraform plan issue

### ISSUE THREAD

**Issue by dmitriy-pisarevskiy** [DataDog/terraform-provider-datadog#2002]
Hi there,

I have terraform plan issue:

Error: failed to read provider configuration schema for registry.terraform.io/hashicorp/datadog: failed to instantiate provider "registry.terraform.io/hashicorp/datadog" to obtain schema: unavailable provider "registry.terraform.io/hashicorp/datadog"

How can I fix it?

``` 

terraform {
  backend "s3" {
    region         = "eu-west-1"
    bucket         = "terraform-state"
    key            = "kubernetes"
    dynamodb_table = "terraform-state-locks"
    encrypt        = true
  }
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 4.0"
    }
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = ">= 2.6.1"
    }
    helm = {
      source  = "hashicorp/helm"
      version = ">= 2.4.1"
    }
    kubectl = {
      source  = "gavinbunney/kubectl"
      version = ">= 1.7.0"
    }
    datadog = {
      source  = "DataDog/datadog"
      version = "3.27.0"
    }
  }
}
provider "datadog" {
  api_key = var.datadog_api_key
  app_key = var.datadog_app_key
  api_url = var.datadog_api_url
}
```

**Comment by therve** [comment]
Hi,

Do you use modules? You need to define the `required_providers` section in all of them, to reference the correct source. Thanks.

**Comment by dmitriy-pisarevskiy** [comment]
@therve yes, required_providers is defined above.  ~3 days ago, it was working fine with current setup, but I need to install helm on EKS, plus I want to use EB module for agents and this error prevent me to any action, I have no idea what to do, I tried to remove "DataDog/datadog" got the same error.

**Comment by dmitriy-pisarevskiy** [comment]
@therve ok, seems it depended on namespace "datadog" on eks, if I do not remove namespace then all is fine.

how can I remove provider if I want in future?
just remove datadog provider not working.

**Comment by therve** [comment]
Sorry I don't know about EKS. The error you're getting is because of the original migration to Datadog/datadog, which means all the references need to be correct. Can you detail your issue a bit more?

**Comment by therve** [comment]
Closing this one for now, please open a ticket with our support team if you're still having issues. Thanks.
