### ISSUE TITLE
Confluent cloud resources reporting deleted but are not actually deleted

### ISSUE THREAD

**Issue by syntastical** [DataDog/terraform-provider-datadog#2005]
### Terraform Version

Terraform CLI: 1.3.9 but tested with the latest(1.5.3) to test, same result.
Datadog Provider: 3.24.1 but tested with latest(3.27.0) to test, same result.

### Affected Resource(s)

Please list the resources as a list, for example:

-   datadog_integration_confluent_resource

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files

This is a simplified version of our hcl that still represents the problem.
```hcl
terraform {
  required_providers {
    datadog = {
      source = "DataDog/datadog"
    }
  }
}

provider "datadog" {
  api_key = "REMOVED"
  app_key = "REMOVED"
}

resource "datadog_integration_confluent_resource" "foo30" {
  account_id    = "REMOVED"
  resource_id   = "lkc-mkp30w"
  resource_type = "kafka"
  tags          = ["env:nonprd", "cluster:pro-testing-gha"]
}
resource "datadog_integration_confluent_resource" "foo31" {
  account_id    = "REMOVED"
  resource_id   = "lkc-mkp31w"
  resource_type = "kafka"
  tags          = ["env:nonprd", "cluster:pro-testing-gha"]
}
resource "datadog_integration_confluent_resource" "foo32" {
  account_id    = "REMOVED"
  resource_id   = "lkc-mkp32w"
  resource_type = "kafka"
  tags          = ["env:nonprd", "cluster:pro-testing-gha"]
}
resource "datadog_integration_confluent_resource" "foo33" {
  account_id    = "e451cecd8ed93b070aec183c29e8ed6e"
  resource_id   = "lkc-mkp33w"
  resource_type = "kafka"
  tags          = ["env:nonprd", "cluster:pro-testing-gha"]
}
resource "datadog_integration_confluent_resource" "foo34" {
  account_id    = "REMOVED"
  resource_id   = "lkc-mkp34w"
  resource_type = "kafka"
  tags          = ["env:nonprd", "cluster:pro-testing-gha"]
}
resource "datadog_integration_confluent_resource" "foo35" {
  account_id    = "REMOVED"
  resource_id   = "lkc-mkp35w"
  resource_type = "kafka"
  tags          = ["env:nonprd", "cluster:pro-testing-gha"]
}
resource "datadog_integration_confluent_resource" "foo36" {
  account_id    = "REMOVED"
  resource_id   = "lkc-mkp36w"
  resource_type = "kafka"
  tags          = ["env:nonprd", "cluster:pro-testing-gha"]
}
resource "datadog_integration_confluent_resource" "foo37" {
  account_id    = "REMOVED"
  resource_id   = "lkc-mkp37w"
  resource_type = "kafka"
  tags          = ["env:nonprd", "cluster:pro-testing-gha"]
}
resource "datadog_integration_confluent_resource" "foo38" {
  account_id    = "REMOVED"
  resource_id   = "lkc-mkp38w"
  resource_type = "kafka"
  tags          = ["env:nonprd", "cluster:pro-testing-gha"]
}
resource "datadog_integration_confluent_resource" "foo39" {
  account_id    = "REMOVED"
  resource_id   = "lkc-mkp39w"
  resource_type = "kafka"
  tags          = ["env:nonprd", "cluster:pro-testing-gha"]
}
resource "datadog_integration_confluent_resource" "foo44" {
  account_id    = "REMOVED"
  resource_id   = "lkc-mkp44w"
  resource_type = "kafka"
  tags          = ["env:nonprd", "cluster:pro-testing-gha"]
}

```

### Debug Output

https://gist.github.com/syntastical/77199da7e541fb087912c378e25ed0d4

### Panic Output

No crash data.

### Expected Behavior

What should have happened?
Calling terraform destroy should destroy the resources listed in the plan.

### Actual Behavior

What actually happened?
Half the resources listed in the destroy plan are reported as destroyed by terraform but continue to exist.  Running the destroy a second time reports that there are no changes.

### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:

1. `terraform apply`
2. `terraform destory`

### Important Factoids

There appears to be problems when an update is needed too.  Terraform reports the update but doesn't actually do it.  

### References

N/A

**Comment by syntastical** [comment]
Hey all, I've been patiently waiting for a release that fixes this issue and I was circling around to this again today, but when I looked a little deeper, I was unable to tell what PR fixed this issue.  Would someone happen to know?

**Comment by therve** [comment]
This has been fixed in our backend, so you shouldn't need any release to have things working. Are you still encountering issues? Thanks.
