### ISSUE TITLE
Depends_on being ignored between resources

### ISSUE THREAD

**Issue by amartopoulos** [DataDog/terraform-provider-datadog#2024]
### Datadog Terraform Provider Version

3.27.0

### Terraform Version

1.3.3

### What resources or data sources are affected?

datadog_logs_archive
datadog_monitor
datadog_logs_index

### Terraform Configuration Files

```hcl
resource "datadog_monitor" "datadog_index_usage_monitor" {
   depends_on = [datadog_logs_index.account_index]
   validate = false
   ...
}

resource "datadog_logs_archive" "s3_archives" {
  depends_on = [aws_iam_role.datadog_s3_archive_logs]
  ...
}

resource "datadog_logs_index" "account_index" {
  ...
}
```

### Relevant debug or panic output

module.datadog_log_index.datadog_monitor.datadog_index_log_daily_quota_monitor: Creating...
module.datadog_log_index.datadog_logs_archive.s3_archives: Creating...
module.datadog_log_index.datadog_logs_index.account_index: Creating...
module.datadog_log_index.datadog_monitor.datadog_index_usage_monitor: Creating...
module.datadog_log_index.datadog_logs_index.account_index: Creation complete after 1s [id=network]
module.datadog_log_index.datadog_monitor.datadog_index_usage_monitor: Creation complete after 1s [id=XXXXXXX]
╷
│ Error: failed to create logs archive using Datadog API from https://api.datadoghq.com/api/v2/logs/config/archives: 400 Bad Request: {"errors":["The specified S3 account id and role name or access key have not been configured."]}
│ 
│   with module.datadog_log_index.datadog_logs_archive.s3_archives,
│   on ../../modules/datadog-log-index/archives.tf line 1, in resource "datadog_logs_archive" "s3_archives":
│    1: resource "datadog_logs_archive" "s3_archives" {
│ 
╵
╷
│ Error: error creating monitor from https://api.datadoghq.com/api/v1/monitor: 400 Bad Request: {"errors":["The value provided for parameter 'query' is invalid: index network not found"]}
│ 
│   with module.datadog_log_index.datadog_monitor.datadog_index_log_daily_quota_monitor,
│   on ../../modules/datadog-log-index/index-log-daily-quota.tf line 26, in resource "datadog_monitor" "datadog_index_log_daily_quota_monitor":
│   26: resource "datadog_monitor" "datadog_index_log_daily_quota_monitor" {
│ 

### Expected Behavior

No matter what combination of options I try, the terraform datadog provider (?) ignores explicit/implicit dependencies between resources.  I can't create an index and resources that depend on it (e.g. a monitor) in the same repo without both being created concurrently and failing.  Similarly, the datadog_logs_archive needs an aws iam role, which isn't created beforehand even with a depends_on clause.

Setting validate = false where the option is available allows the plan to pass, but during the apply step, terraform then concurrently provisions the resources.

### Actual Behavior

The dependency tree should be followed and resources created in the correct order.

### Steps to Reproduce

1. Create a configuration with resources (e.g. a monitor) that depends on an index for its query.  Create the index in the same terraform project.
2. terraform plan (fails without validate = false, passes with validate = false)
3. terraform apply (fails due to concurrency issues)

**Comment by therve** [comment]
I believe the plan with validate error is expected, as even with depends_on validation needs to happen. Regarding creation, there is nothing is the provider which would bypass those internals so I don't know what happens here. It's possible that even if they are created sequentially, there is a delay which means that the monitor validation doesn't yet see the index when it tries to create it.
