### ISSUE TITLE
datadog_integration_aws - new region `il-central-1` can't be added to `excluded_regions` 

### ISSUE THREAD

**Issue by FabianPi** [DataDog/terraform-provider-datadog#2044]
### Datadog Terraform Provider Version

v3.28.0

### Terraform Version

v1.5.4

### What resources or data sources are affected?

`datadog_integration_aws`

### Terraform Configuration Files

```hcl
data "aws_caller_identity" "current" {}
data "aws_regions" "current" {
  all_regions = true
}

locals {
  regions = setsubtract(data.aws_regions.current.names, ["us-east-1", "us-west-1"])
}

resource "datadog_integration_aws" "environment" {
  account_id       = data.aws_caller_identity.current.account_id
  role_name        = "datadog-role"
  excluded_regions = local.regions
}
```

### Expected Behavior

No changes after first `terraform apply`

### Actual Behavior

Every `terraform apply`, `il-central-1` wants to keep on being added.

```
  # datadog_integration_aws.datadog will be updated in-place
  ~ resource "datadog_integration_aws" "datadog" {
      ~ excluded_regions                 = [
          + "il-central-1",
            # (25 unchanged elements hidden)
        ]
        id                               = "xxxxxxxxxxxxx:datadog-role"
        # (9 unchanged attributes hidden)
    }

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes
  
datadog_integration_aws.datadog: Modifying... [id=xxxxxxxxxxxxx:datadog-role]
datadog_integration_aws.datadog: Modifications complete after 1s [id=xxxxxxxxxxxxx:datadog-role]
```

### Steps to Reproduce

`terraform apply`
`terraform apply`

### Important Factoids

New region `il-central-1` can't be added to `excluded_regions`

**Comment by therve** [comment]
Hi,

This will fixed in our backend soon, thanks for your patience.

**Comment by FabianPi** [comment]
Thank you!

**Comment by amonshiz** [comment]
@therve any update on when this will be addressed by DataDog?

**Comment by sgriff44** [comment]
@therve any update on when this might be fixed? We're getting the same issue mentioned above in the original description, even after upgrading to Datadog provider [3.30.0](https://github.com/DataDog/terraform-provider-datadog/releases/tag/v3.30.0).

**Comment by therve** [comment]
Hi, this is being taken care of by our AWS integration team, but I don't have a date just yet.

**Comment by therve** [comment]
This has been handed alongside other missing regions. Let us know if you're still encountering issues, thanks.
