### ISSUE TITLE
Why does require_full_window default to true?

### ISSUE THREAD

**Issue by aashery-square** [DataDog/terraform-provider-datadog#2047]
### Datadog Terraform Provider Version

v3.28.0

### Terraform Version

v1.2.3

### What resources or data sources are affected?

resource_datadog_monitor

### Terraform Configuration Files

```hcl
N/A
```

### Relevant debug or panic output

N/A

### Expected Behavior

The DataDog UI creates new monitors using `require_full_window:false` for this parameter, which means the programatic and UI behavior are incongruent with each other.

### Actual Behavior

Monitors created with Terraform use `require_full_window:true`

### Steps to Reproduce

N/A

### Important Factoids

N/A

### References

N/A

**Comment by nkzou** [comment]
Hi, thanks for the report.
I was able to confirm this inconsistency, but unfortunately we don't expect to be able to change it. This default behavior in the terraform provider has been around for nearly 7 years, so removing the default would be a significant breaking change. We'll keep it in mind in case we ever do another major release.

**Comment by mjiderhamn** [comment]
Reference to the documentation: https://docs.datadoghq.com/monitors/types/metric/?tab=threshold#data-window
> **Do not require** (Default)
