### ISSUE TITLE
datadog_application_key: Sporadically recreated

### ISSUE THREAD

**Issue by orlandothoeny** [DataDog/terraform-provider-datadog#2048]
### Datadog Terraform Provider Version

3.28.0

### Terraform Version

1.5.3

### What resources or data sources are affected?

* datadog_application_key

### Terraform Configuration Files

```hcl
resource "datadog_application_key" "gitlab_ci" {
  name = "[TF-${var.environment}] DataDog - GitLab CI integration"
}
```

### Relevant debug or panic output

```
Terraform detected the following changes made outside of Terraform since the last "terraform apply" which may have affected this plan:

  # module.datadog_ci.datadog_application_key.gitlab_ci has been deleted
  - resource "datadog_application_key" "gitlab_ci" {
        id   = "XXXXXX"
      - key  = (sensitive value) -> null
        name = "[TF-dev] DataDog - GitLab CI integration"
    }

Unless you have made equivalent changes to your configuration, or ignored the relevant attributes using ignore_changes, the following plan may include actions to undo or respond to these changes.

─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create
  ~ update in-place

Terraform will perform the following actions:

  # module.datadog_ci.datadog_application_key.gitlab_ci will be created
  + resource "datadog_application_key" "gitlab_ci" {
      + id   = (known after apply)
      + key  = (sensitive value)
      + name = "[TF-dev] DataDog - GitLab CI integration"
    }
```

![Screenshot from 2023-08-07 09-17-22](https://github.com/DataDog/terraform-provider-datadog/assets/17168783/840eacf3-febf-4320-99d7-2437f22dbf8d)

### Expected Behavior

Existing application key is used when nothing changed.

### Actual Behavior

Terraform sporadically creates a new application key.

### Important Factoids

From time to time (not clear how to reproduce) Terraform thinks that we deleted our existing application key. And thus wants to create a new one. However, the application key still exists at DataDog when I have a look at https://app.datadoghq.eu/organization-settings/application-keys.
It seems like it somehow was not persisted to the state properly.
This is the only resource we have where this happens.

**Comment by therve** [comment]
Hi,

I looked at our server logs and from I can tell you're using a different user in Terraform than in the UI, so the user in Terraform sees a 404 because he can't access the key (security measure of not getting a 403 on something he can't access to avoid fishing). Did you change the user running Terraform by any chance? Thanks.

**Comment by orlandothoeny** [comment]
We use the `DD_APP_KEY` and `TF_VAR_datadog_api_key` environment variables to configure the provider. It is possible that `terraform apply` was run with a different App Key / API Key

**Comment by orlandothoeny** [comment]
It seems like this was the problem. Thanks
