### ISSUE TITLE
Can't create browser_steps of type=typeText

### ISSUE THREAD

**Issue by russwion** [DataDog/terraform-provider-datadog#2054]
### Datadog Terraform Provider Version

3.28.0

### Terraform Version

1.3.2

### What resources or data sources are affected?

resource "datadog_synthetics_test"

### Terraform Configuration Files

```hcl
browser_step {
    name = "Type text on input signin-username"
    type = "typeText"
    params {
      delay = 25
      element_user_locator {
        value {
          value = "<input type='text' placeholder='' name='username' id='redacted' value='' aria-label='' autocomplete='username' required='' data-nlok-ref-guid='redacted'>"
        }
      }
      value = "redacted"
    }
  }
```

### Actual Behavior

The problem is that when this step is created in Datadog it doesn't have a value for the Target Element and there isn't a terraform field to populate that required field.

**Comment by therve** [comment]
Hi,

I believe you need to use the `element` property in that case. I imported a test with a typeText and this is what I got:

```hcl
  browser_step {
    name                 = "Type text on input"
    type                 = "typeText"
    params {
      element           = "{\"multiLocator\":{...},\"targetOuterHTML\":...}"
      value             = "value"
    }
  }
```

Does this work for you? Thanks.

**Comment by russwion** [comment]
I'll give that a shot.  thank you.

**Comment by nkzou** [comment]
Closing issue due to lack of follow up, feel free to re-open if the issue persists.
