### ISSUE TITLE
Support for PieChart Widget in Dashboards

### ISSUE THREAD

**Issue by johansjoberg** [DataDog/terraform-provider-datadog#2061]
### What resources or data sources are affected?

- datadog_dashboard

### Feature Request

Support the existing [PieChart Widget](https://docs.datadoghq.com/dashboards/widgets/pie_chart/) for datadog dashboards. There is [support for multiple widget types](https://registry.terraform.io/providers/DataDog/datadog/latest/docs/resources/dashboard#nested-schema-for-widget) today but pie chart widget is missing. 

This widget is very useful for showing distributions e.g. distributions of queued message for RabbitMQ per host, memory usage per host etc. This easily visualises when there is unequal distribution between entities, which is helpful when this is important to ensure good performance etc.

**Comment by nkzou** [comment]
Looks like Pie Chart widgets are called a `Sunburst` widget by the Datadog API - [widget.group_definition.widget.sunburst_definition](https://registry.terraform.io/providers/DataDog/datadog/latest/docs/resources/dashboard#nested-schema-for-widgetgroup_definitionwidgetsunburst_definition). Please reopen the issue if this wasn't what you were looking for.

**Comment by JonNorman** [comment]
@nkzou it looks like that anchor tag doesn't lead anywhere – has sunburst_definition been removed from the docs? Or is it defined anywhere else?

**Comment by nkzou** [comment]
The terraform docs got truncated due to length, you can find the markdown at https://github.com/DataDog/terraform-provider-datadog/blob/v3.39.0/docs/resources/dashboard.md#nested-schema-for-widgetsunburst_definition

**Comment by JonNorman** [comment]
Ah thanks!
