### ISSUE TITLE
Error: Provider produced inconsistent result after apply

### ISSUE THREAD

**Issue by robinbihun** [DataDog/terraform-provider-datadog#2062]
### Datadog Terraform Provider Version

v3.28.2

### Terraform Version

v1.5.3

### What resources or data sources are affected?

* datadog_integration_cloudflare_account

### Terraform Configuration Files

```hcl
provider "datadog" {
  api_key = var.dd_api_key
  app_key = var.dd_app_key
}

resource "datadog_integration_cloudflare_account" "cf_dd" {
  api_key = var.cloudflare_token
  name    = "Cloudflare Name"
}
```

### Relevant debug or panic output

╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to datadog_integration_cloudflare_account.cf_dd,
│ provider "provider[\"registry.terraform.io/datadog/datadog\"]" produced an
│ unexpected new value: .email: was null, but now cty.StringVal("").
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
╵

### Expected Behavior

Apply should be successful

### Actual Behavior

Apply fails with provided error when no email provided.

### Steps to Reproduce

terraform apply

### Important Factoids

Workaround by including in the resource lifecycle works

`ignore_changes = [ email ]`

**Comment by nkzou** [comment]
I tested this locally and the Datadog backend replied with `400 Bad Request: {"errors":["{'_schema': ['Email address is required if providing an api key and not an api token.']}"]}`. Did omitting the email work in the past? If so, some requirements might have changed in the backend, so you likely have to supply an email now.
