### ISSUE TITLE
Need a data source for datadog_user

### ISSUE THREAD

**Issue by russwion** [DataDog/terraform-provider-datadog#2064]
### What resources or data sources are affected?

data_datadog_user

### Feature Request

There should be a datasource for datadog_users.  
I want to create teams using TF but my users already exist in Datadog.  
I need a way to retrieve the datadog_user.id without creating the user through TF.

**Comment by nkzou** [comment]
This exists already, the docs are [here](https://registry.terraform.io/providers/DataDog/datadog/latest/docs/data-sources/user). Is there some functionality you need that this doesn't support?

**Comment by russwion** [comment]
I don't know why I couldn't find that on Friday.  You may close this request.  My apologies.

Russell
________________________________
