### ISSUE TITLE
Error: object contains unparsed element in `datadog_logs_archive`

### ISSUE THREAD

**Issue by aleks-andr** [DataDog/terraform-provider-datadog#2065]
### Datadog Terraform Provider Version

v3.28.0

### Terraform Version

v1.3.5

### What resources or data sources are affected?

resource_datadog_logs_archive

### Terraform Configuration Files

```hcl
resource "datadog_logs_archive" "request_logs_archive" {
  name         = "Request logs archive"
  query        = "<Datadog log query>"
  include_tags = true
  gcs_archive {
    bucket       = google_storage_bucket.datadog_archive.name
    client_email = local.datadog_metrics.client_email
    path         = "/request-logs"
    project_id   = data.google_project.project.project_id
  }
}
```

### Relevant debug or panic output

```
│ Error: object contains unparsed element: map[bucket:prod-econo-cm_datadog_archive integration:map[] path:/request-logs type:gcs]
│ 
│   with datadog_logs_archive.request_logs_archive,
│   on datadog.tf line 81, in resource "datadog_logs_archive" "request_logs_archive":
│   81: resource "datadog_logs_archive" "request_logs_archive" {
```

### Expected Behavior

Terraform plan completes without failing.

### Actual Behavior

Running a terraform plan (on completely unrelated resources) in the same project causes the aforementioned failure.

### Steps to Reproduce

1. `terraform plan` in a project containing the resource `datadog_logs_archive`

### Important Factoids

Another user on the Terraform Provider forums [reported an identical issue recently](https://discuss.hashicorp.com/t/error-object-contains-unparsed-element/55190).

**Comment by nkzou** [comment]
Seems like for some reason the Datadog backend stopped returning the integration details with the logs archive. Could you check on the datadog web app if the log archive being managed by terraform has a valid cloud integration set? You can find this info on the web app by editing the log archive in question and checking the "Configure Bucket" section, in this case the service account and project fields.

**Comment by aleks-andr** [comment]
Thank you for pointing this out! It appears that our GCP integration for this project was migrated a week or so ago to the new SA-based authentication, and we had partially misconfigured it. This caused the Log Archive configuration to go into an error state until I manually corrected the integration SA and then the Log Archiving configuration. Plans are now successful again! ❤️
