### ISSUE TITLE
OpenTF support

### ISSUE THREAD

**Issue by skyzyx** [DataDog/terraform-provider-datadog#2087]
### What resources or data sources are affected?

N/A

### Feature Request

https://opentf.org/announcement

We want to understand how this provider is affected by the OpenTF announcement, and what the plans for support are moving forward.

### References

N/A

**Comment by jeremy-lq** [comment]
Hello, the Datadog Terraform provider is not impacted by the license change. This is called out explicitly in the [FAQ](https://www.hashicorp.com/license-faq#impact-on-terraform-providers) by Hashicorp. Additionally, OpenTF explicitly states all existing providers will be compatible in the announcement you linked to.

**Comment by skyzyx** [comment]
From a technical perspective, I expect that it will be a no-op for the time being as OpenTF anticipates maintaining compat/interop for the foreseeable future. (However, OpenTF has stated that _some_ functionality may be added to OpenTF that is a _superset_ of what's in base Terraform.)

From a process perspective:

1. If there is a bug in OpenTF that does not exist in Terraform (or vice-versa), will bug reports (as they pertain to this provider) be treated equally on both platforms?

1. Will testing be performed with code targeting both platforms?

1. For OpenTF's potential future "superset" functionality, will that be treated as a first-class citizen by this provider?

**Comment by therve** [comment]
Hi,

**Comment by skyzyx** [comment]
This is the information I'm looking for. Thank you.

I certainly don't expect you to resolve upstream bugs, but knowing that OpenTF is part of your testing/validation process, and that you would file bug reports upstream when you encounter issues is the level of commitment from Datadog that I'm looking for at the moment. (Also noting any known compat/interop issues in the release notes would be helpful.)

We leverage a lot of tools in the Terraform ecosystem, from open-source tools, to SaaS providers who are firmly in the OpenTF camp due to being "competitive" with HashiCorp. I'm trying to understand not only the position of our internal legal team on the license change, but also the technical impact of OpenTF _existing_ and all of us having to do this dance.

Hoping for the best from all this, but pro-actively planning/communicating for the worst.

Your answers are greatly appreciated. Thank you.
