### ISSUE TITLE
Palette `dog_classic` found but not accepted

### ISSUE THREAD

**Issue by viraptor** [DataDog/terraform-provider-datadog#2095]
### Datadog Terraform Provider Version

3.29.0

### Terraform Version

1.5.7

### What resources or data sources are affected?

datadog_dashboard

### Terraform Configuration Files

constructed from `terraform plan` after resource import:

```hcl
        widget {
            timeseries_definition {
                ...
                request {
                    display_type   = "line" 
                    on_right_yaxis = false 

                    formula {
                        formula_expression = "query1" 
                    }

                    query {
                         ...
                    }

                    style {
                        line_type  = "solid" 
                        line_width = "normal" 
                        palette    = "dog_classic" 
                    }
                }
```

### Relevant debug or panic output

```
│ Error: error updating dashboard from https://api.datadoghq.com/api/v1/dashboard/the-dashboard-id: 400 Bad Request: {"errors":["Invalid widget definition at position 1 of type heatmap. Error: [{'style': {'palette': 'dog_classic'}}] is not valid under any of the given schemas."]}
```

### Expected Behavior

This palette came as a value from an existing dashboard when looking at `terraform plan`. It should be accepted for `terraform apply`.

**Comment by nkzou** [comment]
Is this for a heatmap definition as the backend error implies, or is there only a timeseries definition in your terraform config? Would it be possible to provide a more complete example config that causes this error? I tested "dog_classic" on a minimal heatmap and timeseries widget, and it succeeded normally.
