### ISSUE TITLE
Notify by all query's group keys error

### ISSUE THREAD

**Issue by Lethgir** [DataDog/terraform-provider-datadog#2102]
### Datadog Terraform Provider Version

3.30.0

### Terraform Version

1.5.7

### What resources or data sources are affected?

datadog_monitor

### Terraform Configuration Files

```hcl
resource "datadog_monitor" "this" {
  name = "test"
  type = "metric alert"

  query                = "max(last_1h):max:system.linux.DiskSpaceUtilization{*} by {autoscalinggroupname,env} > 85"
  renotify_interval    = 30
  renotify_occurrences = 1
  priority             = 3

  message            = local.message
  notify_by          = ["autoscalinggroupname", "env"]

  monitor_thresholds {
    critical = 85
  }
}
```

### Relevant debug or panic output

```
Error: error validating monitor from https://api.datadoghq.eu/api/v1/monitor/[REDACTED]/validate: 400 Bad Request: {"errors":["The notify_by list may not include all of the query's group keys."]}
```

### Expected Behavior

No errors because from the UI we are able to use all the _group by_ keys as notify keys.

I don't use `["*"]` for the notify_by setting because according to the [documentation](https://registry.terraform.io/providers/DataDog/datadog/latest/docs/resources/monitor#notify_by) it must be used to configured simple-alert only and not multi-alerts.

### Actual Behavior

An error is displayed when all the _group by_ keys are used as notify keys.

### Steps to Reproduce

1. use the given terraform
2. `terraform apply`

**Comment by skarimo** [comment]
Hi, this seems to be a behavior enforced by the api. It seems that although UI allows for providing all of the tags, it would still be treated as a simple alert as mentioned in the documentation. However, could you open a ticket with our support team so it is tracked by the appropriate team. 

This page has the information on how to contact support https://www.datadoghq.com/support/

Feel free to re-open if you have further questions/issues. Thanks!

**Comment by davidxia** [comment]
> It seems that although UI allows for providing all of the tags, it would still be treated as a simple alert as mentioned in the documentation.

@skarimo Hi, thanks for the clarification. Are you referring to the [notify_by docs here](https://registry.terraform.io/providers/DataDog/datadog/latest/docs/resources/monitor#notify_by-1)? I don't see those docs explicitly saying that if all the grouping tags are used in `notify_by` that the result is the same as using `[*]`. Should these docs be clarified? If so, are you open to a PR?
