### ISSUE TITLE
datadog_integration_confluent_account resource import not supported?

### ISSUE THREAD

**Issue by janningyoshihara** [DataDog/terraform-provider-datadog#2105]
### Datadog Terraform Provider Version

v3.30.0

### Terraform Version

v1.5.7

### What resources or data sources are affected?

datadog_integration_confluent_account

### Expected Behavior

Documentation should be clear on how to import the [datadog_integration_confluent_account](https://registry.terraform.io/providers/DataDog/datadog/latest/docs/resources/integration_confluent_account#import) resource

### Important Factoids

the documentation for the [datadog_integration_confluent_account](https://registry.terraform.io/providers/DataDog/datadog/latest/docs/resources/integration_confluent_account#import) resource says import is supported using the following syntax:
`terraform import datadog_integration_confluent_account.new_list "foobar"`

This command does not work and the syntax is not clear in terms of what is needed to import a confluent cloud account resource that already exists in a confluent cloud datadog integration.

**Comment by skarimo** [comment]
Hello, this is supported. Confluent account can be imported using its ID:
```
terraform import datadog_integration_confluent_account.new_list "<ID>"
```

ID can be retrieved using the ListConfluentAccounts endpoint. See: https://docs.datadoghq.com/api/latest/confluent-cloud/#list-confluent-accounts

Put up PR #2109 to add this information in our docs as well. Feel free to re-open if you have further questions. Thanks.
