### ISSUE TITLE
Add support for SyntheticTesting jsonschema assertions

### ISSUE THREAD

**Issue by romansil** [DataDog/terraform-provider-datadog#2111]
### What resources or data sources are affected?

datadog_synthetics_test

### Feature Request

Datadog allows to define assertions on jsonschema for synthetic tests.

![image](https://github.com/DataDog/terraform-provider-datadog/assets/7067658/1eaedad5-3602-4111-b8fc-03b4015e9b79)

Configuring a terraform-created resource to use the jsonschema assertion leads to an error on the next plan:
```
│ Error: object contains unparsed element: map[operator:validatesJSONSchema target:map[jsonSchema:{
│       "type": "object",
│       "properties": {
│         "status": {
│           "enum": [
│             "UP"
│           ]
│         }
│       }
│     } metaSchema:draft-07] type:body]
```

Please support `jsonschema` as an assertion setting for synthetic tests.

**Comment by vytas-maciulskis** [comment]
We are interested in this functionality as well

**Comment by etnbrd** [comment]
Hey folks 👋 
We just merged this, it should be available in the next release!
Thanks for your patience 🙏
