### ISSUE TITLE
[datadog_monitor] New Group Delay not overrides the New Host Delay (Deprecated)

### ISSUE THREAD

**Issue by weyderfs** [DataDog/terraform-provider-datadog#2115]
### Datadog Terraform Provider Version

v3.30.0

### Terraform Version

v1.5.7

### What resources or data sources are affected?

- datadog_monitor > `new_group_delay`  instead `new_host_delay`
- Terragrunt version: `v0.50.15`

### Terraform Configuration Files

```hcl
# TF Module

`main.tf`


resource "datadog_monitor" "dm" {
  name                = var.name
  type                = var.type
  message             = var.message
  priority            = var.priority
  require_full_window = var.require_full_window
  notify_audit        = var.notify_audit
  restricted_roles    = var.restricted_roles
  query               = var.query
  new_group_delay     = var.new_group_delay

  monitor_thresholds {
    critical = var.monitor_thresholds_critical
  }

  include_tags = var.include_tags
  tags         = var.tags
}
```
---

`vars.tf`

```
variable "new_group_delay" {
  type        = number
  description = "(Number) The time (in seconds) to skip evaluations for new groups."
}
```

### Expected Behavior

When use the `new_group_delay` there's no drift about DD trying input the `new_host_delay`.

### Actual Behavior

After imported using Terragrunt a DD Monitor previously configured via web console and run the `terragrunt plan`, the output show me a drift update in place: `+ new_host_delay = 300`.

But in my Terraform Module and my Terragrunt manifest I'm using the `new_group_delay`. If I change the Terraform module, remove the _new_group_deplay_ and add the _new_host_delay_, the Terragrunt output changes where the update in place becomes `new_group_delay=60`

I've checked the JSON document in the DD web console and there is using the `new_group_delay`, there's no mention in `new_host_delay`...

### Steps to Reproduce

- terragrunt import
- terragrunt plan

### References

https://registry.terraform.io/providers/DataDog/datadog/latest/docs/resources/monitor#new_host_delay

**Comment by nkzou** [comment]
Hi, this is due to a conflicting default value that we unfortunately cannot remove without introducing breaking changes to the resource.
You can safely ignore the `+ new_host_delay = 300` drift if you are setting `new_group_delay` to any non-zero value, as the backend api will ignore `new_host_delay` if `new_group_delay` is being used.
Let us know if this doesn't seem to be the case - I tested this locally and `new_group_delay` seemed to be taking priority over `new_host_delay` properly (checking on the web app and api, not terraform state).

**Comment by weyderfs** [comment]
> Hi, this is due to a conflicting default value that we unfortunately cannot remove without introducing breaking changes to the resource. You can safely ignore the `+ new_host_delay = 300` drift if you are setting `new_group_delay` to any non-zero value, as the backend api will ignore `new_host_delay` if `new_group_delay` is being used. Let us know if this doesn't seem to be the case - I tested this locally and `new_group_delay` seemed to be taking priority over `new_host_delay` properly (checking on the web app and api, not terraform state).

Thanks for support, I'll test again and reply here.

**Comment by nkzou** [comment]
Closing this issue, please reopen if the problem persists.
