### ISSUE TITLE
Error: Provider produced inconsistent result after apply

### ISSUE THREAD

**Issue by janningyoshihara** [DataDog/terraform-provider-datadog#2119]
### Datadog Terraform Provider Version

v3.30.0

### Terraform Version

v1.5.7

### What resources or data sources are affected?

datadog_integration_confluent_resource

### Terraform Configuration Files

```hcl
resource "datadog_integration_confluent_account" "integration" {
  api_key    = var.dd_integration_key
  api_secret = var.dd_integration_secret
}
resource "datadog_integration_confluent_resource" "cluster-resource-sandbox" {
  for_each              = toset(data.terraform_remote_state.state["sandbox"].outputs.cluster-ids)
  account_id            = datadog_integration_confluent_account.integration.id
  resource_id           = each.value
  resource_type         = "kafka"
  enable_custom_metrics = true
  tags                  = ["env:sandbox", "service:confluent_cloud"]
}
```

### Relevant debug or panic output

Error: Provider produced inconsistent result after apply
When applying changes to module.datadog_module.datadog_integration_confluent_resource.cluster-resource-sandbox["***"], provider "provider[\"registry.terraform.io/datadog/datadog\"]" produced an unexpected new value: .enable_custom_metrics: was cty.True, but now cty.False.

This is a bug in the provider, which should be reported in the provider's own issue tracker.

### Expected Behavior

Apply should succeed and resource should be created with `enable_custom_metrics` set to true.

### Actual Behavior

Apply fails. 

### Steps to Reproduce

Create resource and set `enable_custom_metrics` to true
terraform apply

### Important Factoids

Our workflow consists of retrieving cluster-ids from our terraform workspace outputs and creating a resource for each of those cluster ids.

**Comment by skarimo** [comment]
Thanks for the report. I was able to reproduce and will follow up with a fix soon.

**Comment by skarimo** [comment]
A fix was merged in our backend and changes are out. Thanks for the report, this is now resolved.
