### ISSUE TITLE
`require_full_window` property has a different behavior than written in the documentation

### ISSUE THREAD

**Issue by dmavrotas** [DataDog/terraform-provider-datadog#2122]
### Datadog Terraform Provider Version

3.30.0

### Terraform Version

1.5.6

## Context

We created a monitor via terraform in order to be notified or a sparse metric (the data points have a rate of around 1/hour), which was not triggered even though it should have. We created the monitor manually and it was actually working, the difference being that the manual monitor had the value corresponding to `require_full_window` to `false`, while the one created by terraform had the value set to `true`. 

## Problem

After taking a look at the [doc](https://registry.terraform.io/providers/DataDog/datadog/latest/docs/resources/monitor#require_full_window), we realize that the existing behavior should have the `false` by default. It would be useful to know if this is a bug or an intended behavior. 

### Terraform Configuration Files

```hcl
resource "datadog_monitor" "awesome_monitor" {
  name    = "Awesome name"
  type    = "metric alert"
  message = "{{#is_alert}} Something is terribly wrong {{/is_alert}}"
  query = "max(last_1h):sum:metric.metric_property{env:${local.environment}} >= 1500"

  monitor_thresholds {
    critical = 1500
    warning = 1350
  }

  notify_no_data    = false
  renotify_interval = 3600

  tags = flatten(["tag1", "tag2"])
}
```

**Comment by nkzou** [comment]
Hi, thanks for reporting this. Indeed, the `require_full_window` should default to false, but unfortunately it's been defaulting to true for 6 years now - removing the default would be a pretty huge breaking change, so we're stuck with recommending to explicitly set it to false for now. We'll edit the documentation to be more clear - it seems like there's an awkward line break in the middle of the description that's a bit misleading.
