### ISSUE TITLE
Destroying datadog_integration_aws_tag_filter results in 500 internal error

### ISSUE THREAD

**Issue by JeanFred** [DataDog/terraform-provider-datadog#2135]
### Datadog Terraform Provider Version

v3.29.0

### Terraform Version

v1.3.9

### What resources or data sources are affected?

datadog_integration_aws_tag_filter

### Terraform Configuration Files

```hcl
resource "datadog_integration_aws" "main" {
  account_id = var.aws_account_id
  role_name  = local.role_name
  host_tags = [
    "aws_account:${var.aws_account_id}",
    "stage:${var.account_alias}"
  ]
  excluded_regions                 = local.excluded_regions
  account_specific_namespace_rules = local.account_specific_namespace_rules
  metrics_collection_enabled       = var.metrics_collection_enabled
  resource_collection_enabled      = var.resource_collection_enabled
  cspm_resource_collection_enabled = var.cspm_resource_collection_enabled
}

resource "datadog_integration_aws_tag_filter" "filter" {
  count          = length(local.account_specific_namespace_rules) == 0 || contains(var.allowlisted_datadog_namespaces, "collect_custom_metrics") ? 1 : 0
  account_id     = var.aws_account_id
  namespace      = "custom"
  tag_filter_str = "!metric_agent:amazon-cloudwatch-agent"

  depends_on = [datadog_integration_aws.main]
}
```

### Relevant debug or panic output

Error: error deleting aws tag filter from https://api.datadoghq.com/api/v1/integration/aws/filtering: 500 Internal Server Error: {"errors":["500 INTERNAL SERVER ERROR"]}

### Expected Behavior

Resource destruction works

### Actual Behavior

Deletion fails, 500 Internal Server Error

**Comment by skarimo** [comment]
Thanks for the report. We have identified the issue and are working on putting fix in place. Will follow once the changes are in.

**Comment by skarimo** [comment]
Fix has been put in place on our backends. Closing this as complete, thanks!

**Comment by JeanFred** [comment]
Thanks!
