### ISSUE TITLE
Provider produced inconsistent result after apply

### ISSUE THREAD

**Issue by zhangHe58** [DataDog/terraform-provider-datadog#2146]
Dear team,

I encountered an error when deploying the Datadog integrated AWS China account using terraform.

Background Information：
- Datadog uses the eu site
- The aws account is the China account
- The integration mode is access keys

My purpose：
Transfer of relevant access logs of our AWS account in China to Datadog through Datadog Forwarder Lambda function.
I want to implement this process through terraform, including integrating AWS account through Access Keys and creating Datadog Forwarder Lambda function through cloud formation(DataDog Official Best Practices).

Problem:
When I execute the terraform apply command, I get an error：
---
```
Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to module.cn-dev.datadog_integration_aws_lambda_arn.main, provider "provider[\"registry.terraform.io/datadog/datadog\"]" produced
│ an unexpected new value: Root resource was present, but now absent.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to module.cn-dev.datadog_integration_aws_log_collection.main, provider "provider[\"registry.terraform.io/datadog/datadog\"]"
│ produced an unexpected new value: Root resource was present, but now absent.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
```
---

It is worth mentioning that datadog successfully integrated aws, lambda was successfully created, Failed to run the "datadog_integration_aws_lambda_arn" and "datadog_integration_aws_log_collection" terraform resources.

My code:
```
resource "aws_iam_user" "main" {
name = "datadog_integration_user"

path = "/"
}

resource "aws_iam_user_policy" "main" {
name = "datadog_integration_policy"

user = aws_iam_user.main.name
policy = data.aws_iam_policy_document.datadog_integration_policy.json
}

resource "aws_iam_access_key" "main" {
user = aws_iam_user.main.name
}

resource "datadog_integration_aws" "main" {
access_key_id = aws_iam_access_key.main.id
secret_access_key = aws_iam_access_key.main.secret
host_tags = var.host_tags
account_specific_namespace_rules = var.metric_collection
}

resource "aws_cloudformation_stack" "main" {
count = var.enalbe_log_collection ? 1 : 0

name = "datadog-forward-lambda-stack"
capabilities = ["CAPABILITY_IAM", "CAPABILITY_NAMED_IAM", "CAPABILITY_AUTO_EXPAND"]
parameters = {
DdApiKeySecretArn = var.dd_apiKey_secretArn
DdSite = var.dd_site
FunctionName = var.function_name
}
template_url = var.datadog_forward_template_url
}

resource "datadog_integration_aws_lambda_arn" "main" {
account_id = aws_iam_access_key.main.id
lambda_arn = aws_cloudformation_stack.main[0].outputs["DatadogForwarderArn"]
}

resource "datadog_integration_aws_log_collection" "main" {
account_id = aws_iam_access_key.main.id
services = ["s3","lambda"]
}```

**Comment by zhangHe58** [comment]
Interestingly, the execution failed, but on the Datadog dashboard it appears that the configuration succeeded. Is this a bug?

**Comment by zhangHe58** [comment]
![WX20231016-112515](https://github.com/DataDog/terraform-provider-datadog/assets/31123099/234c32c2-768c-40d2-b959-29d727624235)

**Comment by nkzou** [comment]
Yes, this is a bug. I haven't been able to reproduce it locally, but I believe the issue is due to api delay between successful creation and read availability. Will look into a fix.

**Comment by zhangHe58** [comment]
Hi nkzon,

thanks for your help, 
This problem troubles me a lot. Is it caused by the special reasons of the AWS account in China?

**Comment by zhangHe58** [comment]
If I insist on using datadog_integration_aws_lambda_arn and datadog_integration_aws_log_collection, is there any workaround that does not report errors?

**Comment by nkzou** [comment]
Hi, we are working on a fix. The main issue lies in the lack of `account_id` when creating the base aws integration with access keys, rather than account id. There will be an api backend and terraform provider change to fix this - we plan to allow `account_id` to be set alongside the account keys. Will keep this thread updated as the fix is worked on.

As far as workarounds go, since the integration was properly set up, you can try to import the `datadog_integration_aws_log_collection` and `datadog_integration_aws_lambda_arn` resources following the docs on the [terraform registry](https://registry.terraform.io/providers/DataDog/datadog/latest/docs/resources/integration_aws_lambda_arn#import)

**Comment by zhangHe58** [comment]
I found other problems with these two resources, so I created for another ticket
https://github.com/DataDog/terraform-provider-datadog/issues/2149

**Comment by nkzou** [comment]
Hey, thanks for raising this issue. I've merged a workaround, and we plan on releasing a hotfix version early next week that will include the fix.
Once the hotfix is released, you can use the workaround by including your `account_id` in the `datadog_integration_aws` resource. This should allow you to create the `datadog_integration_aws_log_collection` and `datadog_integration_aws_lambda_arn` resources successfully. Please re-open this issue if you run into any issues with this, thanks!
