### ISSUE TITLE
Manage Team SAML Mappings

### ISSUE THREAD

**Issue by SharpEdgeMarshall** [DataDog/terraform-provider-datadog#2148]
### What resources or data sources are affected?

Create a `datadog_team_mapping` resource

### Feature Request

Teams' assignments can be managed by SAML mappings in the UI but the terraform resource doesn't exist.

**Comment by wsellars-bw** [comment]
Looks like this is currently blocked(?) by the DD API not having an endpoint to do so or functionality under the existing AuthN mapping - https://docs.datadoghq.com/api/latest/authn-mappings/

**Comment by Var091** [comment]
This resources would also be very useful for us

**Comment by andersro93** [comment]
This is something that our organization would really appriciate, atm we have lots of teams and to manually manage these mappings would be a really painful. Does the api support doing this atm? To me that isn't really clear from the [docs](https://docs.datadoghq.com/api/latest/authn-mappings/), as @wsellars-bw points out as well

**Comment by wsellars-bw** [comment]
Yea, still hoping to see the api extended to allow this as a feature. Haven't seen a change on DD side yet, but if you've got a contract/subscription make sure to hit support up with a feature request

**Comment by andersro93** [comment]
Seems like this was added with https://github.com/DataDog/terraform-provider-datadog/releases/tag/v3.39.0 by @eric-wood in https://github.com/DataDog/terraform-provider-datadog/pull/2363. 
However, it doesn't seem that this is actually taking effect inside datadog. Maybe there is an issue with sdk that it is not sending the request? Anybody else having the same issue?

**Comment by eric-wood** [comment]
Hey @andersro93! I'd love to help look into this but it will require some more information; if you [reach out to support(https://www.datadoghq.com/support/) they'll be able to connect us in a way I can dig in deeper.

**Comment by JonasBak** [comment]
From what I can tell, it looks like the resource works, but our issue was that we used both the `team` and `role` fields in the same resource (which the provider allows us to do). When we provide both, only the `role` is shown in DD, but when we split it into two resources (one with `team` and one with `role`), both are shown in DD, and the team-mapping seems to work. The resource and docs should probably be updated to reflect this.

**Comment by andersro93** [comment]
Nice @JonasBak you beat me to it. Seems that it works for us now @eric-wood! 🚀

**Comment by eric-wood** [comment]
Thank you @JonasBak! The relationship is mutually exclusive, but this is somewhat difficult to express with the tools available to us. I'll see about clarifying this better in the documentation. Teams and IDP are becoming more and more important and I'm hoping we can provide more flexible interfaces for this in the future.

**Comment by SharpEdgeMarshall** [comment]
@eric-wood I confirm it's working for us now. 
Should I close the issue, or will you take care of it?

**Comment by eric-wood** [comment]
Really happy to hear things are working great; will close it out. Let us know if anything comes up in the future and we'll jump on it. Thanks everyone!
