### ISSUE TITLE
Synthetics Test missing metadata input for multi-step API test

### ISSUE THREAD

**Issue by Nuru** [DataDog/terraform-provider-datadog#2155]
### Datadog Terraform Provider Version

3.30.0

### Terraform Version

1.3.9

### What resources or data sources are affected?

datadog_synthetics_test

### Terraform Configuration Files

<details><summary>bug.tf (click to reveal)</summary>

Note, this was copied from the [Terraform resource documentation](https://registry.terraform.io/providers/DataDog/datadog/latest/docs/resources/synthetics_test#example-usage). The only change was to add `request_metadata`.

```hcl
resource "datadog_synthetics_test" "test_multi_step" {
  name      = "Multistep API test"
  type      = "api"
  subtype   = "multi"
  status    = "live"
  locations = ["aws:eu-central-1"]
  tags      = ["foo:bar", "foo", "env:test"]

  api_step {
    name    = "An API test on example.org"
    subtype = "http"

    assertion {
      type     = "statusCode"
      operator = "is"
      target   = "200"
    }

    request_metadata = {}

    request_definition {
      method = "GET"
      url    = "https://example.org"
    }

    request_headers = {
      Content-Type   = "application/json"
      Authentication = "Token: 1234566789"
    }
  }

  api_step {
    name    = "An API test on example.org"
    subtype = "http"

    assertion {
      type     = "statusCode"
      operator = "is"
      target   = "200"
    }

    request_definition {
      method = "GET"
      url    = "http://example.org"
    }
  }

  options_list {
    tick_every         = 900
    accept_self_signed = true
  }
}
```

</details>

### Relevant debug or panic output

```
│ Error: Unsupported argument
│ 
│   on bug.tf line 19, in resource "datadog_synthetics_test" "test_multi_step":
│   19:     request_metadata = {}
│ 
│ An argument named "request_metadata" is not expected here.
```

### Expected Behavior

The `api_step` block should accept a `metadata` or `request_metadata` input, to match the [REST API](https://docs.datadoghq.com/api/latest/synthetics/#create-an-api-test) input `config.steps[].request.metadata` input.

### Actual Behavior

Neither `metadata` nor `request_metadata` inputs are accepted in `api_step` blocks.

### Steps to Reproduce

`terraform plan`

**Comment by nkzou** [comment]
From my understanding, the `metadata` field is only used for gRPC tests. The description in the docs says `Metadata to include when performing the gRPC test.`, while multi-step synthetic tests only support http requests at this time. As such I don't think there's a need to implement this now, but we will revisit this if multi-step tests ever do support gRPC.
Closing this for now but please reopen if I'm mistaken about anything, thanks!

**Comment by Joapfel** [comment]
Hi @nkzou , it seems that Datadog itself already supports grpc in multistep api tests. Are you planning to provide support from Terraform side anytime soon? Where can I place a feature request?

![image](https://github.com/DataDog/terraform-provider-datadog/assets/23312031/e069ec15-a910-4b93-a973-62ee7ba6437b)
