### ISSUE TITLE
Problem with "assertFileDownload" browser step

### ISSUE THREAD

**Issue by TenKenZero** [DataDog/terraform-provider-datadog#2174]
### Datadog Terraform Provider Version

v3.30.0

### Terraform Version

v3.30.0

### What resources or data sources are affected?

datadog_synthetics_test, type: browser

### Relevant debug or panic output

`Error: error updating synthetics browser test from https://api.datadoghq.com/api/v1/synthetics/tests/browser/3be-adr-kc8: 400 Bad Request: {"errors":["Invalid steps data: Step 15 has invalid params: None is not of type 'object'"]}`

### Expected Behavior

Create the test in Terraform.

I'm trying to add a browser_step (in a browser test) for asserting the download of a file.

**This was my last attempt:**
```
browser_step {
    name = "Check the downloaded file name"
    type = "assertFileDownload"    
    params {
      attribute = "name"
      check = "contains"
      file = ".xls"      
    }
  }
```
  
  
 **Also tried with these options:**
```
 browser_step {
    name = "Check the downloaded file name"
    type = "assertFileDownload"    
    params {
      check = "contains"
      file = ".xls"
      value = ".xls"
    }
  }
```
  
```
  browser_step {
    name = "Check the downloaded file name"
    type = "assertFileDownload"    
    params {
      check = "contains"
      file = ".xls"      
      element_user_locator {
        fail_test_on_cannot_locate = "true"
        value {
          type  = "css"
          value = "#lblExportExcel"
        }
      }
    }
  }
```

### Actual Behavior

Creation fails due to the error.

The attempts without "element_user_locator", gave me the same error:

`Error: error updating synthetics browser test from https://api.datadoghq.com/api/v1/synthetics/tests/browser/3be-adr-kc8: 400 Bad Request: {"errors":["Invalid steps data: Step 15 has invalid params: None is not of type 'object'"]}`

And the attempt using "element_user_locator", gave me this other:

`Error: error updating synthetics browser test from https://api.datadoghq.com/api/v1/synthetics/tests/browser/3be-adr-kc8: 400 Bad Request: {"errors":["Invalid steps data: Step 15 has invalid params: Additional properties are not allowed ('element' was unexpected)"]}`

### Steps to Reproduce

terraform apply

### Important Factoids

Documentation doesn't offer examples or further information for "assertFileDownload" browser steps.

Any chance of getting help?

**Comment by nkzou** [comment]
Hi, thanks for reporting this. We're looking into improving the documentation. The `file` field is actually a jsonencoded string with some more fields within. For the time being, you can use this syntax, and remove the md5/sizeCheck if you don't need them.
```hcl
browser_step {
  name                 = "Test a downloaded file"
  type                 = "assertFileDownload"
  params {
    file = jsonencode(
      {
        md5       = "hash"
        sizeCheck = {
            type  = "equals"
            value = 1 // in kb
        }
        nameCheck = {
          type  = "contains"
          value = ".xls"
        }
      }
    )
  }
}
```

**Comment by TenKenZero** [comment]
It works... Thanks!
