### ISSUE TITLE
variables with heredoc values keep showing changes when running apply

### ISSUE THREAD

**Issue by arendhummeling** [DataDog/terraform-provider-datadog#2176]
### Datadog Terraform Provider Version

v3.32.0

### Terraform Version

v1.5.7

### What resources or data sources are affected?

datadog_monitor

### Terraform Configuration Files

```hcl
resource "datadog_monitor" "step_function_failure" {
  lifecycle {
    ignore_changes = [message]
  }
  count   = var.step_functions_failure_enabled ? 1 : 0
  name    = "${var.prefix_slug == "" ? "" : "[${var.prefix_slug}]"}[${var.environment}] Step Function Execution Failure {{#is_alert}}{{{comparator}}} {{threshold}}% ({{value}}%){{/is_alert}}{{#is_warning}}{{{comparator}}} {{warn_threshold}}% ({{value}}%){{/is_warning}}"
  message = <<EOT
redacted multiline message containing multiple variables 
  spanning over multiple lines
EOT
  type    = "metric alert"

  query = <<-EOT
sum(${var.timeframe}):
  sum:aws.states.executions_failed{aws_account:${data.aws_caller_identity.current.account_id}} by {statemachinename}.as_count()
> ${var.threshold_critical}
EOT
```

### Expected Behavior

Running terraform plan should not report this as a change.

### Actual Behavior

Running terraform plan reports a change.

### Steps to Reproduce

`terraform plan`

### Important Factoids

We resorted to putting all messages in lifecycle ignore changes, because we have about 22 of these monitors and we'd like to be able to read the output of terraform plan/apply. This means we cannot use terraform to change the message of the monitor, which is somewhat acceptable, but the query should be able to change, so we will not be able to lifecycle ignore the query.

**Comment by therve** [comment]
Hi,

Do you have a fully reproducible example? I tried a few variations and it worked fine for me. Here is an example:

```hcl
resource "datadog_monitor" "foo" {
  name               = "Name for monitor foo"
  type               = "metric alert"
  message = <<EOT
redacted multiline message containing multiple variables
  spanning over multiple lines
EOT
  escalation_message = "Escalation message @pagerduty"

  query = <<EOT
avg(last_1d):
  avg:aws.ec2.cpu{environment:foo,host:foo} by {host} > 4
EOT

  monitor_thresholds {
    warning  = 2
    critical = 4
  }

  include_tags = true

  tags = ["foo:bar", "team:fooBar"]
}
```

Thanks.

**Comment by arendhummeling** [comment]
Hi, strangely enough the issue seems to have disappeared over the weekend. If it pops back up, I'll open a new issue with a fully reproducible example.
