### ISSUE TITLE
Locating a Checkbox item in Datadog/Terraform synthetic browser test

### ISSUE THREAD

**Issue by TenKenZero** [DataDog/terraform-provider-datadog#2191]
### Datadog Terraform Provider Version

v3.30.0

### Terraform Version

v3.30.0

### What resources or data sources are affected?

datadog_synthetics_test, type: browser

### Relevant debug or panic output

Sorry for posting this question here, but it was impossible to get examples or templates in the Documentation or any other source. Even the Datadog support team wasn't able to help me with this (Request #1441112).

### Expected Behavior

I'm building a Datadog's Synthetic Browser test with Terraform, but I'm facing issues to address this HTML element: 
`<input type="checkbox" name="payrollInstructionIds" value="957e1f96-377d-4cec-a815-e6ec0e52402d">`

The step I'm trying to do is a click on that checkbox. But, should be considered that the page have 9 checkboxes, and all of them have the same 'type' and 'name' properties. Only 'value' changes.

I have tried with these options, but the test always fails at that step, saying that the element couldn't be located.

**Option 1:**
```
  browser_step {
    name = "Click checkbox: Reg. Salary Pay"
    type = "click"
    params {
      element_user_locator {
        fail_test_on_cannot_locate = "true"
        value {
          type  = "css"
          value = "input[value='957e1f96-377d-4cec-a815-e6ec0e52402d']"
        }
      }
    }
  }
```

**Option 2:**
```
  browser_step {
    name = "Click checkbox: Reg. Salary Pay"
    type = "click"
    params {
      element_user_locator {
        fail_test_on_cannot_locate = "true"
        value {
          type  = "css"
          value = "input[type='checkbox',value='957e1f96-377d-4cec-a815-e6ec0e52402d']"
        }
      }
    }
  }
```

**Option 3:**
```
  browser_step {
    name = "Click checkbox: Reg. Salary Pay"
    type = "click"
    params {
      element_user_locator {
        fail_test_on_cannot_locate = "true"
        value {
          type  = "css"
          value = "input[type='checkbox']"
        }
      }
    }
  }
```

All the three options give me this result on the Datadog's GUI: 
**Error Cannot locate element.**

Any chance to get a example for this step?

**Expectation:** The synthetic browser test is able to click the checkbox and continue with the next test's steps.

### Actual Behavior

All the three options give me this result on the Datadog's GUI: 
**Error Cannot locate element.**

### Steps to Reproduce

terraform apply

### Important Factoids

Documentation doesn't offer examples or further information this kind of browser steps.

Any chance of getting help?

**Comment by nkzou** [comment]
Hi, it looks like the CSS selector syntax for combining attribute matches is to have multiple brackets, like so:
`input[type='checkbox'][name='payrollInstructionIds'][value='957e1f96-377d-4cec-a815-e6ec0e52402d']`
Could you try that, and if that doesn't work, try removing the single quotes around the attributes. Hopefully this helps.

**Comment by TenKenZero** [comment]
The solution you gave me worked! Thank you so much.
I'll mark this issue as resolved and comment the solution in the questions I opened in StackOverflow and Datadog's support platform.
I really appreciate this help, since the documentation and examples are pretty hard to find.

Please, consider to help me with this new stopper.
I'm trying to perform a Browser Step of Click Type over a table cell **<td></td>**.
This is the table and the element I want to click (highlighted)
<img width="479" alt="image" src="https://github.com/DataDog/terraform-provider-datadog/assets/11514837/b28eb57b-4312-4c81-ba34-9da2e958b6f0">

I've already tried this options:
**1) Putting both attributes together (like the previous solutions)**
```
  browser_step {
    name = "Click on '2020TaxTest' Organization"
    type = "click"
    params {
      element_user_locator {
        fail_test_on_cannot_locate = "true"
        value {
          type  = "css"
          value = "a[onclick='CloseDialog(0);'][href='/everest/OrganizationContext/ChangeContext.mr?OrganizationId=a19498c6-15c1-45aa-a5cd-1b2a74f18d0a']"
        }
      }
    }
  }
```

**2) Putting the attributes separatedly.**
```
  browser_step {
    name = "Click on '2020TaxTest' Organization"
    type = "click"
    params {
      element_user_locator {
        fail_test_on_cannot_locate = "true"
        value {
          type  = "css"
          value = "a[href='/everest/OrganizationContext/ChangeContext.mr?OrganizationId=a19498c6-15c1-45aa-a5cd-1b2a74f18d0a']"
        }
      }
    }
  }
```

Both ways give me the same error:
`None or multiple elements detected: a[onclick='CloseDialog(0);'][href='/everest/OrganizationContext/Chan..`

I would appreciate help with this, or some examples to use the `element = jsonencode({})` or the **element multi locator**.

**Comment by nkzou** [comment]
The only way I could reproduce this error is when there are multiple `a` elements on the page with the same `onclick` and `href` values. In that case you need some other way to differentiate. I suggest looking at https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_selectors to see what other selectors you could use.

**Comment by TenKenZero** [comment]
Thanks!
