### ISSUE TITLE
Error: Plugin did not respond with datadog_integration_gcp_sts.gcp_project_integration

### ISSUE THREAD

**Issue by dfernandoDev** [DataDog/terraform-provider-datadog#2197]
### Datadog Terraform Provider Version

v3.33.0

### Terraform Version

v1.5.4

### What resources or data sources are affected?

datadog_integration_gcp_sts

### Terraform Configuration Files

```hcl
locals {
  labels = merge({
    owner = var.owner
    env   = var.environment.name
  }, var.labels)
  consul_project_id = coalesce(var.consul_project_id, module.project_factory.project_id)
}

# Create opinionated Google Cloud Platform project
# Documentation: https://registry.terraform.io/modules/terraform-google-modules/project-factory/google/11.3.1
module "project_factory" {
  source  = "terraform-google-modules/project-factory/google"
  version = "~> 11.3"

  activate_apis = concat([
    "cloudasset.googleapis.com",
    "cloudbilling.googleapis.com",
    "compute.googleapis.com",
    "dns.googleapis.com",
    "iam.googleapis.com",
    "iamcredentials.googleapis.com",
    "logging.googleapis.com",
    "monitoring.googleapis.com",
    "secretmanager.googleapis.com",
    ],
    var.additional_apis,
    var.enable_dataproc ? ["dataproc.googleapis.com"] : [],
    var.enable_notebooks ? ["notebooks.googleapis.com"] : [],
    # Enable vpcaccess only if we're using an access connector
    var.vpc_access_connector_project_id == null ? [] : ["vpcaccess.googleapis.com"],
  )
  auto_create_network = var.auto_create_network
  billing_account     = var.billing_account
  folder_id           = var.environment.folder_id
  name                = "${var.base_name}-${var.environment.short_name}"
  org_id              = var.org_id
  random_project_id   = true
  shared_vpc_subnets  = var.shared_vpc_subnets

  # project_factory doesn't work right with null, so if we're null we need to substitute "" instead
  svpc_host_project_id = var.vpc_project_id != null ? var.vpc_project_id : ""

  disable_dependent_services = true

  labels = local.labels
}

resource "google_compute_project_metadata_item" "base_items" {
  # enable-oslogin lets us log in with IAM instead of ssh keys on every compute instance in the project
  # short-env is used in chef to know what environment the compute instance is in
  # consul-project-id is needed to join the correct consul cluster for the environment
  for_each = merge({
    "enable-oslogin" = "TRUE"
    "short-env"      = var.environment.short_name
    },
    var.allow_consul_access ? { "consul-project-id" = local.consul_project_id } : {},
    var.secrets_project_id != null ? { "secrets-project-id" = var.secrets_project_id } : {},
    var.additional_metadata
  )

  key     = each.key
  value   = each.value
  project = module.project_factory.project_id
}

# Allow OSLogin for provided groups
# See: https://cloud.google.com/compute/docs/instances/managing-instance-access#grant-iam-roles
resource "google_project_iam_member" "os_login" {
  for_each = toset(var.os_login_members)
  project  = module.project_factory.project_id
  role     = "roles/compute.osLogin"
  member   = each.value
}

resource "google_project_iam_member" "sa_user" {
  for_each = toset(var.os_login_members)
  project  = module.project_factory.project_id
  role     = "roles/iam.serviceAccountUser"
  member   = each.value
}

# Give the service account roles as specified
resource "google_project_iam_member" "project_roles" {
  for_each = toset(concat([
    "roles/compute.viewer",
    # Required for the service account to write logs to stackdriver
    "roles/logging.logWriter",
    # Required for the service account to write metrics to stackdriver
    "roles/monitoring.metricWriter"
    ],
    var.additional_service_account_roles,
    # Grant network viewer if we're setting up vpc access connectors
    var.vpc_access_connector_project_id == null ? [] : ["roles/compute.networkViewer"],
  ))
  project = module.project_factory.project_id
  role    = each.value
  member  = "serviceAccount:${module.project_factory.service_account_email}"
}

# Give the service account access to list zones and find instances in the consul project
resource "google_project_iam_member" "consul_roles" {
  count   = var.allow_consul_access ? 1 : 0
  project = local.consul_project_id
  role    = "roles/compute.viewer"
  member  = "serviceAccount:${module.project_factory.service_account_email}"
}

# Give the service account access to secrets in the secret project
resource "google_project_iam_member" "secret_accessor" {
  count   = var.secrets_project_id == null ? 0 : 1
  project = var.secrets_project_id
  role    = "roles/secretmanager.secretAccessor"
  member  = "serviceAccount:${module.project_factory.service_account_email}"
}

# Constructing a list of service agent accounts that need permission to use the VPC access connector
locals {
  # Map of APIs to their service agent accounts
  # Key: GCP API
  # Value: Constructed service agent email, as described here: https://cloud.google.com/iam/docs/service-agents
  api_service_agent_accounts = {
    "cloudfunctions.googleapis.com" = "service-${module.project_factory.project_number}@gcf-admin-robot.iam.gserviceaccount.com"
    "run.googleapis.com"            = "service-${module.project_factory.project_number}@serverless-robot-prod.iam.gserviceaccount.com"
    "notebooks.googleapis.com"      = "service-${module.project_factory.project_number}@gcp-sa-notebooks.iam.gserviceaccount.com"
  }

  used_apis_with_service_agents = setintersection(toset(var.additional_apis), keys(local.api_service_agent_accounts))

  used_service_agent_accounts = [for i in local.used_apis_with_service_agents : local.api_service_agent_accounts[i]]
}
# If this project has a vpc_access_connector_project_id, grant roles
# See: https://cloud.google.com/functions/docs/networking/connecting-shared-vpc
resource "google_project_iam_member" "vpc_access_user" {
  count   = var.vpc_access_connector_project_id == null ? 0 : length(local.used_service_agent_accounts)
  project = var.vpc_access_connector_project_id
  role    = "roles/vpcaccess.user"
  member  = "serviceAccount:${local.used_service_agent_accounts[count.index]}"
}

resource "google_project_iam_member" "vpc_access_viewer" {
  count   = var.vpc_access_connector_project_id == null ? 0 : 1
  project = var.vpc_access_connector_project_id
  role    = "roles/vpcaccess.user"
  member  = "serviceAccount:${module.project_factory.service_account_email}"
}

resource "google_project_iam_member" "mig_access_images" {
  count   = var.enable_managed_instance_group ? 1 : 0
  project = "sifi-images"
  role    = "roles/compute.imageUser"
  member  = "serviceAccount:${module.project_factory.project_number}@cloudservices.gserviceaccount.com"
}

resource "google_project_iam_member" "dataproc_access_images" {
  count   = var.enable_dataproc ? 1 : 0
  project = "sifi-images"
  role    = "roles/compute.imageUser"
  member  = "serviceAccount:service-${module.project_factory.project_number}@dataproc-accounts.iam.gserviceaccount.com"
}

resource "google_project_iam_member" "dataproc_network_user" {
  count   = var.enable_dataproc && var.vpc_project_id != null ? 1 : 0
  project = var.vpc_project_id
  role    = "roles/compute.networkUser"
  member  = "serviceAccount:service-${module.project_factory.project_number}@dataproc-accounts.iam.gserviceaccount.com"
}

resource "google_project_iam_member" "notebook_network_user" {
  count   = var.enable_notebooks && var.vpc_project_id != null ? 1 : 0
  project = var.vpc_project_id
  role    = "roles/compute.networkUser"
  member  = "serviceAccount:service-${module.project_factory.project_number}@gcp-sa-notebooks.iam.gserviceaccount.com"
}

# Allow select groups to clickzone OAuth consent screen (because it is not supported by the API)
# https://issuetracker.google.com/116182848
resource "google_project_iam_member" "oauth_editor" {
  for_each = var.vpc_project_id == null ? toset([]) : toset(var.oauth_editors)
  project  = var.vpc_project_id
  role     = "roles/oauthconfig.editor"
  member   = each.value
}

# Monitoring Setup
# See: https://docs.datadoghq.com/integrations/google_cloud_platform/
resource "google_service_account" "dd_monitoring_reporter" {
  account_id = "tf-dd-monitoring-reporter"
  project    = module.project_factory.project_id
}

resource "google_project_iam_member" "dd_project_roles" {
  for_each = toset(concat([
    # Required for the service account to access to cloud assets metadata
    "roles/cloudasset.viewer",
    "roles/compute.viewer",
    # Required for the service account to get all monitoring data and configurations
    "roles/monitoring.viewer",
    "roles/iam.serviceAccountTokenCreator",
  ]))
  project = module.project_factory.project_id
  role    = each.value
  member  = "serviceAccount:${google_service_account.dd_monitoring_reporter.email}"
}

resource "datadog_integration_gcp_sts" "gcp_project_integration" {
  automute     = var.datadog_automute
  client_email = google_service_account.dd_monitoring_reporter.email
  depends_on   = [google_project_iam_member.dd_project_roles]
}
```

### Relevant debug or panic output

TestPackerProjectFactoryModule 2023-12-04T09:22:20-06:00 logger.go:66: │ Error: Plugin did not respond
TestPackerProjectFactoryModule 2023-12-04T09:22:20-06:00 logger.go:66: │
TestPackerProjectFactoryModule 2023-12-04T09:22:20-06:00 logger.go:66: │   with module.base.datadog_integration_gcp_sts.gcp_project_integration,
TestPackerProjectFactoryModule 2023-12-04T09:22:20-06:00 logger.go:66: │   on modules/base/main.tf line 210, in resource "datadog_integration_gcp_sts" "gcp_project_integration":
TestPackerProjectFactoryModule 2023-12-04T09:22:20-06:00 logger.go:66: │  210: resource "datadog_integration_gcp_sts" "gcp_project_integration" {
TestPackerProjectFactoryModule 2023-12-04T09:22:20-06:00 logger.go:66: │
TestPackerProjectFactoryModule 2023-12-04T09:22:20-06:00 logger.go:66: │ The plugin encountered an error, and failed to respond to the
TestPackerProjectFactoryModule 2023-12-04T09:22:20-06:00 logger.go:66: │ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
TestPackerProjectFactoryModule 2023-12-04T09:22:20-06:00 logger.go:66: │ contain more details.
TestPackerProjectFactoryModule 2023-12-04T09:22:20-06:00 logger.go:66: ╵
TestPackerProjectFactoryModule 2023-12-04T09:22:20-06:00 logger.go:66:
TestPackerProjectFactoryModule 2023-12-04T09:22:20-06:00 logger.go:66: Stack trace from the terraform-provider-datadog_v3.33.0 plugin:
TestPackerProjectFactoryModule 2023-12-04T09:22:20-06:00 logger.go:66:
TestPackerProjectFactoryModule 2023-12-04T09:22:20-06:00 logger.go:66: panic: runtime error: invalid memory address or nil pointer dereference
TestPackerProjectFactoryModule 2023-12-04T09:22:20-06:00 logger.go:66: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1fc5db8]
TestPackerProjectFactoryModule 2023-12-04T09:22:20-06:00 logger.go:66:
TestPackerProjectFactoryModule 2023-12-04T09:22:20-06:00 logger.go:66: goroutine 85 [running]:
TestPackerProjectFactoryModule 2023-12-04T09:22:20-06:00 logger.go:66: github.com/terraform-providers/terraform-provider-datadog/datadog/fwprovider.(*integrationGcpStsResource).Create(0xc000129470, {0x26fec80, 0xc000b21470}, {{{{0x2703f38, 0xc000b2a1b0}, {0x21c5340, 0xc000b2a090}}, {0x2705a08, 0xc000c48550}}, {{{0x2703f38, ...}, ...}, ...}, ...}, ...)
TestPackerProjectFactoryModule 2023-12-04T09:22:20-06:00 logger.go:66:  github.com/terraform-providers/terraform-provider-datadog/datadog/fwprovider/resource_datadog_integration_gcp_sts.go:148 +0x198
TestPackerProjectFactoryModule 2023-12-04T09:22:20-06:00 logger.go:66: github.com/terraform-providers/terraform-provider-datadog/datadog/fwprovider.(*FrameworkResourceWrapper).Create(0xd?, {0x26fec80?, 0xc000b21470?}, {{{{0x2703f38, 0xc000b2a1b0}, {0x21c5340, 0xc000b2a090}}, {0x2705a08, 0xc000c48550}}, {{{0x2703f38, ...}, ...}, ...}, ...}, ...)
TestPackerProjectFactoryModule 2023-12-04T09:22:20-06:00 logger.go:66:  github.com/terraform-providers/terraform-provider-datadog/datadog/fwprovider/framework_provider.go:481 +0x78
TestPackerProjectFactoryModule 2023-12-04T09:22:20-06:00 logger.go:66: github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).CreateResource(0xc00015f4a0, {0x26fec80, 0xc000b21470}, 0xc001137190, 0xc001137130)
TestPackerProjectFactoryModule 2023-12-04T09:22:20-06:00 logger.go:66:  github.com/hashicorp/terraform-plugin-framework@v1.3.3/internal/fwserver/server_createresource.go:101 +0x598
TestPackerProjectFactoryModule 2023-12-04T09:22:20-06:00 logger.go:66: github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ApplyResourceChange(0xc0011372e8?, {0x26fec80, 0xc000b21470}, 0xc0002e4730, 0xc0011372e8)
TestPackerProjectFactoryModule 2023-12-04T09:22:20-06:00 logger.go:66:  github.com/hashicorp/terraform-plugin-framework@v1.3.3/internal/fwserver/server_applyresourcechange.go:57 +0x4a8
TestPackerProjectFactoryModule 2023-12-04T09:22:20-06:00 logger.go:66: github.com/hashicorp/terraform-plugin-framework/internal/proto5server.(*Server).ApplyResourceChange(0xc00015f4a0, {0x26fec80?, 0xc000b21290?}, 0xc0002e4550)
TestPackerProjectFactoryModule 2023-12-04T09:22:20-06:00 logger.go:66:  github.com/hashicorp/terraform-plugin-framework@v1.3.3/internal/proto5server/server_applyresourcechange.go:55 +0x41a
TestPackerProjectFactoryModule 2023-12-04T09:22:20-06:00 logger.go:66: github.com/hashicorp/terraform-plugin-mux/tf5muxserver.muxServer.ApplyResourceChange({0xc000251cb0, 0xc000251d10, {0xc00013a580, 0x2, 0x2}, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...)
TestPackerProjectFactoryModule 2023-12-04T09:22:20-06:00 logger.go:66:  github.com/hashicorp/terraform-plugin-mux@v0.8.0/tf5muxserver/mux_server_ApplyResourceChange.go:27 +0x102
TestPackerProjectFactoryModule 2023-12-04T09:22:20-06:00 logger.go:66: github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc000dc8000, {0x26fec80?, 0xc000b20180?}, 0xc0001de460)
TestPackerProjectFactoryModule 2023-12-04T09:22:20-06:00 logger.go:66:  github.com/hashicorp/terraform-plugin-go@v0.18.0/tfprotov5/tf5server/server.go:821 +0x574
TestPackerProjectFactoryModule 2023-12-04T09:22:20-06:00 logger.go:66: github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x23b6160?, 0xc000dc8000}, {0x26fec80, 0xc000b20180}, 0xc0001de0e0, 0x0)
TestPackerProjectFactoryModule 2023-12-04T09:22:20-06:00 logger.go:66:  github.com/hashicorp/terraform-plugin-go@v0.18.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:422 +0x170
TestPackerProjectFactoryModule 2023-12-04T09:22:20-06:00 logger.go:66: google.golang.org/grpc.(*Server).processUnaryRPC(0xc00036c000, {0x2704340, 0xc0004649c0}, 0xc000374000, 0xc0001ea720, 0x33f5560, 0x0)
TestPackerProjectFactoryModule 2023-12-04T09:22:20-06:00 logger.go:66:  google.golang.org/grpc@v1.56.3/server.go:1335 +0xdf3
TestPackerProjectFactoryModule 2023-12-04T09:22:20-06:00 logger.go:66: google.golang.org/grpc.(*Server).handleStream(0xc00036c000, {0x2704340, 0xc0004649c0}, 0xc000374000, 0x0)
TestPackerProjectFactoryModule 2023-12-04T09:22:20-06:00 logger.go:66:  google.golang.org/grpc@v1.56.3/server.go:1712 +0xa36
TestPackerProjectFactoryModule 2023-12-04T09:22:20-06:00 logger.go:66: google.golang.org/grpc.(*Server).serveStreams.func1.1()
TestPackerProjectFactoryModule 2023-12-04T09:22:20-06:00 logger.go:66:  google.golang.org/grpc@v1.56.3/server.go:947 +0xca
TestPackerProjectFactoryModule 2023-12-04T09:22:20-06:00 logger.go:66: created by google.golang.org/grpc.(*Server).serveStreams.func1
TestPackerProjectFactoryModule 2023-12-04T09:22:20-06:00 logger.go:66:  google.golang.org/grpc@v1.56.3/server.go:958 +0x15c
TestPackerProjectFactoryModule 2023-12-04T09:22:20-06:00 logger.go:66:
TestPackerProjectFactoryModule 2023-12-04T09:22:20-06:00 logger.go:66: Error: The terraform-provider-datadog_v3.33.0 plugin crashed!
TestPackerProjectFactoryModule 2023-12-04T09:22:20-06:00 logger.go:66:
TestPackerProjectFactoryModule 2023-12-04T09:22:20-06:00 logger.go:66: This is always indicative of a bug within the plugin. It would be immensely
TestPackerProjectFactoryModule 2023-12-04T09:22:20-06:00 logger.go:66: helpful if you could report the crash with the plugin's maintainers so that it
TestPackerProjectFactoryModule 2023-12-04T09:22:20-06:00 logger.go:66: can be fixed. The output above should help diagnose the issue.
TestPackerProjectFactoryModule 2023-12-04T09:22:20-06:00 logger.go:66:
TestPackerProjectFactoryModule 2023-12-04T09:22:20-06:00 logger.go:66: time=2023-12-04T09:22:20-06:00 level=error msg=Terraform invocation failed in /Users/joshscott/dev/simplifi/terraform-google-sifi-project-factory/terratest/project_factory/.terragrunt-cache/59vmQfMKMJmc9_nbQmJb9shRaAU/LapXwZb52oo8IKxCH5njXZrqM6k prefix=[/Users/joshscott/dev/simplifi/terraform-google-sifi-project-factory/terratest/project_factory]
TestPackerProjectFactoryModule 2023-12-04T09:22:20-06:00 logger.go:66: time=2023-12-04T09:22:20-06:00 level=error msg=Module /Users/joshscott/dev/simplifi/terraform-google-sifi-project-factory/terratest/project_factory has finished with an error: 1 error occurred:
TestPackerProjectFactoryModule 2023-12-04T09:22:20-06:00 logger.go:66:  * [/Users/joshscott/dev/simplifi/terraform-google-sifi-project-factory/terratest/project_factory/.terragrunt-cache/59vmQfMKMJmc9_nbQmJb9shRaAU/LapXwZb52oo8IKxCH5njXZrqM6k] exit status 1
TestPackerProjectFactoryModule 2023-12-04T09:22:20-06:00 logger.go:66:
TestPackerProjectFactoryModule 2023-12-04T09:22:20-06:00 logger.go:66:  prefix=[/Users/joshscott/dev/simplifi/terraform-google-sifi-project-factory/terratest/project_factory]
TestPackerProjectFactoryModule 2023-12-04T09:22:20-06:00 logger.go:66: time=2023-12-04T09:22:20-06:00 level=error msg=1 error occurred:
TestPackerProjectFactoryModule 2023-12-04T09:22:20-06:00 logger.go:66:  * [/Users/joshscott/dev/simplifi/terraform-google-sifi-project-factory/terratest/project_factory/.terragrunt-cache/59vmQfMKMJmc9_nbQmJb9shRaAU/LapXwZb52oo8IKxCH5njXZrqM6k] exit status 1
TestPackerProjectFactoryModule 2023-12-04T09:22:20-06:00 logger.go:66:
TestPackerProjectFactoryModule 2023-12-04T09:22:20-06:00 logger.go:66:
TestPackerProjectFactoryModule 2023-12-04T09:22:20-06:00 retry.go:99: Returning due to fatal error: FatalError{Underlying: error while running command: exit status 1; time=2023-12-04T09:16:53-06:00 level=info msg=The stack at /Users/joshscott/dev/simplifi/terraform-google-sifi-project-factory/terratest/project_factory will be processed in the following order for command apply:
Group 1
- Module /Users/joshscott/dev/simplifi/terraform-google-sifi-project-factory/terratest

Group 2
- Module /Users/joshscott/dev/simplifi/terraform-google-sifi-project-factory/terratest/project_factory

╷
│ Error: Plugin did not respond
│
│   with module.base.datadog_integration_gcp_sts.gcp_project_integration,
│   on modules/base/main.tf line 210, in resource "datadog_integration_gcp_sts" "gcp_project_integration":
│  210: resource "datadog_integration_gcp_sts" "gcp_project_integration" {
│
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵

Stack trace from the terraform-provider-datadog_v3.33.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1fc5db8]

goroutine 85 [running]:
github.com/terraform-providers/terraform-provider-datadog/datadog/fwprovider.(*integrationGcpStsResource).Create(0xc000129470, {0x26fec80, 0xc000b21470}, {{{{0x2703f38, 0xc000b2a1b0}, {0x21c5340, 0xc000b2a090}}, {0x2705a08, 0xc000c48550}}, {{{0x2703f38, ...}, ...}, ...}, ...}, ...)
        github.com/terraform-providers/terraform-provider-datadog/datadog/fwprovider/resource_datadog_integration_gcp_sts.go:148 +0x198
github.com/terraform-providers/terraform-provider-datadog/datadog/fwprovider.(*FrameworkResourceWrapper).Create(0xd?, {0x26fec80?, 0xc000b21470?}, {{{{0x2703f38, 0xc000b2a1b0}, {0x21c5340, 0xc000b2a090}}, {0x2705a08, 0xc000c48550}}, {{{0x2703f38, ...}, ...}, ...}, ...}, ...)
        github.com/terraform-providers/terraform-provider-datadog/datadog/fwprovider/framework_provider.go:481 +0x78
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).CreateResource(0xc00015f4a0, {0x26fec80, 0xc000b21470}, 0xc001137190, 0xc001137130)
        github.com/hashicorp/terraform-plugin-framework@v1.3.3/internal/fwserver/server_createresource.go:101 +0x598
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ApplyResourceChange(0xc0011372e8?, {0x26fec80, 0xc000b21470}, 0xc0002e4730, 0xc0011372e8)
        github.com/hashicorp/terraform-plugin-framework@v1.3.3/internal/fwserver/server_applyresourcechange.go:57 +0x4a8
github.com/hashicorp/terraform-plugin-framework/internal/proto5server.(*Server).ApplyResourceChange(0xc00015f4a0, {0x26fec80?, 0xc000b21290?}, 0xc0002e4550)
        github.com/hashicorp/terraform-plugin-framework@v1.3.3/internal/proto5server/server_applyresourcechange.go:55 +0x41a
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.muxServer.ApplyResourceChange({0xc000251cb0, 0xc000251d10, {0xc00013a580, 0x2, 0x2}, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...)
        github.com/hashicorp/terraform-plugin-mux@v0.8.0/tf5muxserver/mux_server_ApplyResourceChange.go:27 +0x102
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc000dc8000, {0x26fec80?, 0xc000b20180?}, 0xc0001de460)
        github.com/hashicorp/terraform-plugin-go@v0.18.0/tfprotov5/tf5server/server.go:821 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x23b6160?, 0xc000dc8000}, {0x26fec80, 0xc000b20180}, 0xc0001de0e0, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.18.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:422 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00036c000, {0x2704340, 0xc0004649c0}, 0xc000374000, 0xc0001ea720, 0x33f5560, 0x0)
        google.golang.org/grpc@v1.56.3/server.go:1335 +0xdf3
google.golang.org/grpc.(*Server).handleStream(0xc00036c000, {0x2704340, 0xc0004649c0}, 0xc000374000, 0x0)
        google.golang.org/grpc@v1.56.3/server.go:1712 +0xa36
google.golang.org/grpc.(*Server).serveStreams.func1.1()
        google.golang.org/grpc@v1.56.3/server.go:947 +0xca
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.56.3/server.go:958 +0x15c

Error: The terraform-provider-datadog_v3.33.0 plugin crashed!

### Steps to Reproduce

terraform apply

**Comment by nkzou** [comment]
Hi, would you be able to try running this with the `TF_LOG=debug` environment variable set? Specifically looking for the response body of the `/api/v2/integration/gcp/sts_delegate` http endpoint call. Please redact any sensitive info from it, like the value of `id` and `delegate_account_email` (if those are even there - based on your stack trace I think they're missing, but we'd like to confirm if that's whats going wrong, since we haven't been able to reproduce this internally)

**Comment by nkzou** [comment]
Please re-open with debug info and/or more details if the issue persists, thanks!
