### ISSUE TITLE
Add documentation for cloud_cost resources

### ISSUE THREAD

**Issue by josh-mcq** [DataDog/terraform-provider-datadog#2206]
### What resources or data sources are affected?

datadog_dashboard

### Feature Request

a recent [issue](https://github.com/DataDog/terraform-provider-datadog/issues/1438) was closed for a request to support `data_source:cloud_cost` widgets in datadog_dashboards.   Ticket closer reported that this support has been implemented.  

The examples in the documentation could use an example of a widget with `data_source: cloud_cost` - the only data_source I see in the examples are [metrics, logs, process](https://github.com/search?q=repo%3ADataDog%2Fterraform-provider-datadog+path%3A%2F%5Eexamples%5C%2Fresources%5C%2Fdatadog_dashboard%5C%2F%2F+data_source&type=code) 

I've tried using configurations that work and are deployable like [this](https://github.com/DataDog/terraform-provider-datadog/blob/ef28d1e073ec449b840daae2edd7015bd1fe5209/examples/resources/datadog_dashboard/resource.tf#L586C1-L625C4) and modifying the data_source, and changing `metric_query` to `cloud_cost_query` and other things, none of that works.  

If using `cloud_cost` data_source for dashboard widgets is supported by this provider, it would be great to see some documentation or examples.

### References
https://github.com/DataDog/terraform-provider-datadog/issues/1438

**Comment by nkzou** [comment]
Hey, thanks for raising this issue. It turns out the underlying Go SDK change was not enough to enable support for cloud cost queries in dashboards. The linked PR properly implements this, and should be usable in any dashboard widget that supports cloud cost queries.

The feature should be usable with our next release, which we're planning to do sometime next week. Thanks!

**Comment by josh-mcq** [comment]
> Hey, thanks for raising this issue. It turns out the underlying Go SDK change was not enough to enable support for cloud cost queries in dashboards. The linked PR properly implements this, and should be usable in any dashboard widget that supports cloud cost queries.
> 
> The feature should be usable with our next release, which we're planning to do sometime next week. Thanks!

@nkzou - thanks so much!  Tried it out today and it works for me as expected 👍
