### ISSUE TITLE
datadog_users - support for Data Source for multiple users

### ISSUE THREAD

**Issue by hazam** [DataDog/terraform-provider-datadog#2214]
### What resources or data sources are affected?

datadog_users - list version of existing datadog_user

### Feature Request

A feature that would be useful is to have a "users" data_source that could really filter and select lists of users.
In many cases, we are not sure if the user is there or not, but _in case it is_ we may want to associate to other resources. 
Especially useful when Federated SSO is active and user may not yet be created since first login not done.

**Comment by skarimo** [comment]
Closed by: https://github.com/DataDog/terraform-provider-datadog/pull/2220 Thanks!
