### ISSUE TITLE
Users roles cannot be changed with datadog_user resource

### ISSUE THREAD

**Issue by tommije** [DataDog/terraform-provider-datadog#2226]
### Datadog Terraform Provider Version

v3.34.0

### Terraform Version

v1.6.6

### What resources or data sources are affected?

- resource_datadog_user

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    datadog = {
      source = "DataDog/datadog"
    }
  }
}

locals {
  users = distinct(concat(var.group1, var.group2))
  admins = distinct(concat(var.admin_group, var.admin_group2))
}

data "datadog_role" "standard" {
  filter = "Datadog Standard Role"
}

resource "datadog_user" "standard_users" {
  for_each = toset(local.users)
  email    = each.key
  roles    = [data.datadog_role.standard.id]

}

data "datadog_role" "admin" {
  filter = "Datadog Admin Role"
}

resource "datadog_user" "admin_users" {
  for_each = toset(local.admins)
  email    = each.key
  roles    = [data.datadog_role.admin.id]

}
```

### Expected Behavior

Handling Datadog users roles via Terraform should change user state and role depending on the groups they are set to.

### Actual Behavior

Terraform state file stays unchanged, and manually modifying Terraform state file does not change the behaviour of Terraform.

### Steps to Reproduce

1. Add users to `var.group1` with Standard Role
2. Run `terraform plan` and/or `terraform apply`
3. Remove existing users from `var.group1` and add same users to `var.admin_group`
4. Run `terraform plan` and/or `terraform apply`
5. Terraform plan shows that these users will be destroyed and users will be created with new role
6. User state does not change, Terraform state file does not show the changes and users will still be marked as `disabled": false`
7. User will not be disabled from Datadog

**Comment by nkzou** [comment]
I don't think the user is expected to be disabled in this case - the Datadog backend will re-enable a disabled user entity if a user is created with the same email. I tried to reproduce this but couldn't - my state file correctly showed the user's role id changing after the apply, and I confirmed on the web ui that the user's role changed. 

Could you double check that the state/user's role didn't change at all? The user id likely won't change but the role id attached to the user resource should have.

**Comment by tommije** [comment]
I think the issue is that if you are removing/adding users from static list to a group in Terraform module, Terraform cannot do both things at the same time. After running Terraform twice and removing the users from static list and adding the users module between the runs, I was able to enable the users.
