### ISSUE TITLE
`value` should not be required for Synthetic Global Variables that have a `parse_test_id`

### ISSUE THREAD

**Issue by michael-w-swyftx** [DataDog/terraform-provider-datadog#2250]
### What resources or data sources are affected?

`datadog_synthetics_global_variable`

### Feature Request

When configuring a `datadog_synthetics_global_variable` resource, the `value` property is marked as required; however if the value is derived from a test, we should not be sending a value to the Datadog API on edit. 

Our use case is having 1 test that authenticates with a public API and then saves an access token into the global variable. This global variable is used in a chain of other "authenticated" series of synthetics that assert basic platform functionality.

The value is properly populated from the test as you would expect, but then because we are forced to enter a value into the `value` property of the resource, when a terraform apply is ran against the environment, the value is automatically cleared. This causes all "authenticated" tests to fail, unless we ensure that they run at a much lower frequency than the authentication test.

Ideally this field is not required in this instance and does not override the actual value.

Note that in the edit global variable documentation, the `value` key is required, but the nested literal `value` subkey is not: https://docs.datadoghq.com/api/latest/synthetics/#edit-a-global-variable

**Comment by urnotjessie** [comment]
running into the exact same issue, after global variable is created, any following re-deployment will force the value to be empty because the `value` is set to be an empty string

**Comment by nkzou** [comment]
Unfortunately due to some limitations in terraform sdkv2 (mainly around omitted vs null vs default values), this change is more complicated than just removing the `required` flag.

There is a terraform lifecycle meta-argument that sounds like it might be useful for your use case though - the [`ignore_changes`](https://developer.hashicorp.com/terraform/language/meta-arguments/lifecycle#ignore_changes) argument.

> The ignore_changes feature is intended to be used when a resource is created with references to data that may change in the future, but should not affect said resource after its creation. In some rare cases, settings of a remote object are modified by processes outside of Terraform, which Terraform would then attempt to "fix" on the next run. In order to make Terraform share management responsibilities of a single object with a separate process, the ignore_changes meta-argument specifies resource attributes that Terraform should ignore when planning updates to the associated remote object.

A config like
```hcl
resource "datadog_synthetics_global_variable" "test_variable" {
  name        = "EXAMPLE_VARIABLE"
  description = "Description of the variable"
  tags        = ["foo:bar", "env:test"]
  value       = ""
  lifecycle {
    ignore_changes = [ value, ]
  }
}
```
Would ignore any changes detected for the `value` field, and avoid sending an update for the value field if the API returns an unexpected value.

**Comment by michael-w-swyftx** [comment]
> Unfortunately due to some limitations in terraform sdkv2 (mainly around omitted vs null vs default values), this change is more complicated than just removing the `required` flag.
> 
> There is a terraform lifecycle meta-argument that sounds like it might be useful for your use case though - the [`ignore_changes`](https://developer.hashicorp.com/terraform/language/meta-arguments/lifecycle#ignore_changes) argument.
> 
> > The ignore_changes feature is intended to be used when a resource is created with references to data that may change in the future, but should not affect said resource after its creation. In some rare cases, settings of a remote object are modified by processes outside of Terraform, which Terraform would then attempt to "fix" on the next run. In order to make Terraform share management responsibilities of a single object with a separate process, the ignore_changes meta-argument specifies resource attributes that Terraform should ignore when planning updates to the associated remote object.
> 
> A config like
> 
> ```terraform
> resource "datadog_synthetics_global_variable" "test_variable" {
>   name        = "EXAMPLE_VARIABLE"
>   description = "Description of the variable"
>   tags        = ["foo:bar", "env:test"]
>   value       = ""
>   lifecycle {
>     ignore_changes = [ value, ]
>   }
> }
> ```
> 
> Would ignore any changes detected for the `value` field, and avoid sending an update for the value field if the API returns an unexpected value.

Thanks Kevin, the lifecycle does solve this particular problem for us. Though it would be nice to be able to provide no value when configuring the token, I understand it's not worth the complexity.
