### ISSUE TITLE
Datadog service definitions data source

### ISSUE THREAD

**Issue by KieranJamess** [DataDog/terraform-provider-datadog#2256]
### What resources or data sources are affected?

datadog_service_definitions

### Feature Request

New data source to be added to support pulling datadog service definitions using the datadog api go client V2 endpoints. The endpoint doesn't support any major helpful attributes, so you'll have to work with JSON output to get the data you need (or change the endpoint).

I didn't notice I couldn't create a branch before I started working on it, I have a solution myself which uses this client to create the data for service definitions in the state file - happy to add the items to a branch if I can contribute (or let me know if I am missing something).

**Comment by therve** [comment]
HI,

FWIW you can't create a branch in the repository, but you can fork and submit a PR that way.

**Comment by KieranJamess** [comment]
@therve You are correct, thanks! First time contributing towards a repo outside of work
https://github.com/DataDog/terraform-provider-datadog/pull/2277
