### ISSUE TITLE
Terraform datadog provider don't let you use `_` in template variable 

### ISSUE THREAD

**Issue by rushi47** [DataDog/terraform-provider-datadog#2260]
### Datadog Terraform Provider Version

v3.35.0

### Terraform Version

v1.3.5

### What resources or data sources are affected?

`resource "datadog_dashboard_json"` 

### Relevant debug or panic output

````
  ~ resource "datadog_dashboard_json" "test_resource" {
      ~ dashboard               = jsonencode(
          ~ {
              ~ template_variables = [
                  ~ {
                      ~ available_values = [
                          - "test_sp-partition-us",
                          - "test_sp-partition-root",
                          + "test-sp-partition-us",
                          + "test-sp-partition-root",
                        ]
                        name             = "kube_cluster_name"
                        # (2 unchanged elements hidden)
                    },
````

### Expected Behavior

resource should able to respect `_` instead of replacing them in template variables.

### Actual Behavior

Its replacing `_` with `-`

### Steps to Reproduce

- create `.tpl` file by exporting json from datadog dashboard
- Load respective tpl file with below is pseudo terraform
```
locals {
   accounts_list = [
                           "test_sp-partition-us",
                          "test_sp-partition-root",
   ]
}
resource "datadog_dashboard_json" "test" {
  dashboard = templatefile("${path.module}/json/dashboard.tpl", {
    accounts   = jsonencode(local.accounts_list)
  })
}
```
- when you do plan it will show `_` being replaced with `-`.

**Comment by nkzou** [comment]
I was unable to reproduce this behavior. Below is the minimal config I used:
```hcl
locals {
  accounts_list = [
    "test_sp-partition-us",
    "test_sp-partition-root",
  ]
}
resource "datadog_dashboard_json" "test" {
  dashboard = jsonencode({
    "title" : "testing_dashboard",
    "description" : null,
    "widgets" : [],
    "template_variables" : [
      {
        "name" : "kube_cluster_name",
        "available_values" : [for account in local.accounts_list : "${account}"],
        "default" : "*"
      }
    ],
    "layout_type" : "ordered",
    "notify_list" : [],
    "reflow_type" : "fixed"
  })
}
```
Terraform doesn't report any drift after applying, and the UI also show the underscores in the template variable dropdown as expected. I also tried without using any template, and also using a separate template file with the `templatefile` terraform function. Could you provide a minimal terraform config that reproduces this issue?

**Comment by rushi47** [comment]
My bad i investigated more and i noticed we have logic to refactor/replacement, thats the issue.
Thank you @nkzou
