### ISSUE TITLE
Add support for Time Slice SLOs

### ISSUE THREAD

**Issue by vinnymac** [DataDog/terraform-provider-datadog#2264]
### What resources or data sources are affected?

- datadog_service_level_objective

### Feature Request

It seems the type can be set to `time_slice`, but I don't see a way to specify the `sli_specification` that is required.

I came across [this PR](https://github.com/DataDog/terraform-provider-datadog/pull/2245) that appears to have solved the issue, but is yet to be released.

Any idea when we will see a new release cut? Thank you!

### References

https://github.com/DataDog/terraform-provider-datadog/pull/2245

**Comment by nkzou** [comment]
Our typical release cadence is monthly, and we're planning for next week.
