### ISSUE TITLE
Cloudflare Integration Resources

### ISSUE THREAD

**Issue by Lewis-Globacap** [DataDog/terraform-provider-datadog#2268]
### What resources or data sources are affected?

- datadog_integration_cloudflare_account

### Feature Request

The current `datadog_integration_cloudflare_account` does not provide a way to set which resources should be collected. It would be very useful if these could also be managed through the provider.

## Cloudflare Integration Resources

<img width="350" alt="image" src="https://github.com/DataDog/terraform-provider-datadog/assets/145339879/138464da-85df-49a6-b0d5-10fd731f5db0">

**Comment by skarimo** [comment]
Thanks for the FR, support has been added in: https://github.com/DataDog/terraform-provider-datadog/pull/2633
