### ISSUE TITLE
datadog_permissions data source is not returning all permissions that are returned from the permissions API

### ISSUE THREAD

**Issue by LFSb** [DataDog/terraform-provider-datadog#2290]
### Datadog Terraform Provider Version

3.36.1

### Terraform Version

v1.6.3

### What resources or data sources are affected?

datadog_permissions

### Terraform Configuration Files

```hcl
# Available permisions in DD
data "datadog_permissions" "default_permissions" {}
```

### Expected Behavior

The datadog_permissions data source should hold the same amount of permissions as what you get back when you call `curl -X GET "https://api.datadoghq.eu/api/v2/permissions"`.

### Actual Behavior

Instead, we're missing 10 permissions. One permission that is missing is `rum_apps_read`, but you can investigate further when reproducing.

### Steps to Reproduce

1. `curl -X GET "https://api.datadoghq.eu/api/v2/permissions" -H "Accept: application/json"-H "DD-API-KEY: ${DD_API_KEY}" -H "DD-APPLICATION-KEY: ${DD_APP_KEY}" | jq > permissions.json`
2. `terraform console`
3. `data.datadog_permissions.default_permissions`
This results in a list of 149 entries, instead of the 159 that are in permissions.json
[tf-permissions.txt](https://github.com/DataDog/terraform-provider-datadog/files/14373783/tf-permissions.txt)

**Comment by therve** [comment]
Hi, 

I think you set https://registry.terraform.io/providers/DataDog/datadog/latest/docs/data-sources/permissions#include_restricted to true you should get everything.

**Comment by LFSb** [comment]
Hi @therve , I do get everything, and I think I know what the problem is, I'm trying to set a restricted permission (rum_apps_read) that every user already has by default. Problem solved, thanks!
