### ISSUE TITLE
Can not set on_missing_data property in datadog_monitor resource type (invalid monitor option)

### ISSUE THREAD

**Issue by rbjoergensen** [DataDog/terraform-provider-datadog#2291]
### Datadog Terraform Provider Version

v3.36.1

### Terraform Version

v1.5.5

### What resources or data sources are affected?

datadog_monitor

### Terraform Configuration Files

```hcl
resource "datadog_monitor" "kubernetes_jobs" {
  name             = "Kubernetes - Jobs Failed"
  type             = "query alert"
  query            = "sum(last_5m):max:kubernetes_state.job.failed{kube_cluster_name:my-cluster by {kube_job,kube_namespace} > 1"
  message          = "test"
  priority         = 3

  on_missing_data = "resolve"
  include_tags    = false
  new_group_delay = 300

  monitor_thresholds {
    critical = 1
  }
}
```

### Relevant debug or panic output
```
│ Error: error updating monitor from https://api.us3.datadoghq.com/api/v1/monitor/540298: 400 Bad Request: {"errors":["Invalid monitor option: on_missing_data"]}
│ 
│   with datadog_monitor.kubernetes_jobs["platform_services_cluster"],
│   on k8s-jobs.tf line 1, in resource "datadog_monitor" "kubernetes_jobs":
│    1: resource "datadog_monitor" "kubernetes_jobs" {
```

### Expected Behavior

Successful plan/apply

### Actual Behavior

400 Bad Request from API

### Steps to Reproduce

``` terraform
resource "datadog_monitor" "kubernetes_jobs" {
  name             = "Kubernetes - Jobs Failed"
  type             = "query alert"
  query            = "sum(last_5m):max:kubernetes_state.job.failed{kube_cluster_name:my-cluster by {kube_job,kube_namespace} > 1"
  message          = "test"
  priority         = 3

  on_missing_data = "resolve"
  include_tags    = false
  new_group_delay = 300

  monitor_thresholds {
    critical = 1
  }
}
```

### Important Factoids

Tried with different versions of datadog provider from 3.26 to 3.36.1

**Comment by HantingZhang2** [comment]
Hi @rbjoergensen, 
This option is only available for APM Trace Analytics, Audit Trail, CI, Error Tracking, Event, Logs, and RUM monitors.
The api should return a better message. 
See comments in the underlying go api client: 
https://github.com/DataDog/datadog-api-client-go/blob/26298c47b918e8bf360090355685fb326f9d4831/api/datadogV1/model_on_missing_data_option.go#L13-L17

**Comment by uhthomas** [comment]
Is this still the case? The docs suggest that it should be possible to use with metric monitors and slo monitors.

https://docs.datadoghq.com/monitors/guide/on_missing_data/
