### ISSUE TITLE
Spurious diffs for restricted_roles

### ISSUE THREAD

**Issue by pellepelster** [DataDog/terraform-provider-datadog#2326]
### Datadog Terraform Provider Version

3.38.0

### Terraform Version

1.7.2

### What resources or data sources are affected?

datadog_monitor

### Terraform Configuration Files

```hcl
resource "datadog_monitor" "k8s_daemonset_pod_down" {
  name    = "[${local.cluster_name}] DaemonSet Pod is down"
  type    = "query alert"
  message = "********************"

  query   = "max(last_15m):sum:kubernetes_state.daemonset.desired{cluster_name:${local.cluster_name}} by {cluster_name,kube_namespace,daemonset} - sum:kubernetes_state.daemonset.ready{cluster_name:${local.cluster_name}} by {cluster_name,kube_namespace,daemonset} >= 1"

  monitor_thresholds {
    critical = 1
  }

  notify_no_data    = false
  renotify_interval = 0
  notify_audit      = true
  timeout_h         = 0

  new_group_delay     = 300
  include_tags        = true
  require_full_window = false
  enable_logs_sample  = false
  priority            = 3

  tags = [
    "env:${local.dd_env}",
    "autoclose:true"
  ]

  restricted_roles = ["ad93d0a4-****-****-****-************"]
}
```
```


### Relevant debug or panic output

```hcl
~ resource "datadog_monitor" "k8s_daemonset_pod_down" {
        id                   = "10******"
        name                 = "[******] DaemonSet Pod is down"
      ~ restricted_roles     = [
          - "ad93d0a4-****-****-****-************",
        ] -> (known after apply)
        tags                 = [
            "autoclose:true",
            "env:************",
        ]
        # (18 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }
```

### Expected Behavior

We do not expect to see a diff for `restricted_roles` without changing the source and input.

### Actual Behavior

Unfortunately we do not have a 100% reproduce for this issue, but the behavior and context looks like this:

* define a simple datadog_monitor, it does not matter what type
* provide a single role in `restricted_roles`
* apply the monitor everything is fine (even after a second or third apply)
* after some time (now it gets fuzzy) we start to see the diffs like described above, without changing the input and especially not the input for `restricted_roles`
* if we look up the monitor via the API we can see that the role is still in `restricted_roles` (see Important Factoids)
* we are also struggling to understand why Terraform wants to remove the role role, even if we hardcode it like in the code example

### Important Factoids

```hcl
curl --silent -X GET "https://app.datadoghq.eu/api/v1/monitor/10******" \                                             
-H "Accept: application/json" \
-H "DD-API-KEY: ${DD_API_KEY}" \
-H "DD-APPLICATION-KEY: ${DD_APP_KEY}" | jq
{
  "id": 10************,
  "org_id": 10************,
  "type": "query alert",
  "name": "[************] DaemonSet Pod is down",
  "message": "************",
  "tags": [
    "autoclose:true",
    "env:************"
  ],
  "query": "max(last_15m):sum:kubernetes_state.daemonset.desired{cluster_name:************} by {cluster_name,kube_namespace,daemonset} - sum:kubernetes_state.daemonset.ready{cluster_name:************} by {cluster_name,kube_namespace,daemonset} >= 1",
  "options": {
    "include_tags": true,
    "new_group_delay": 300,
    "new_host_delay": 300,
    "notify_audit": true,
    "notify_no_data": false,
    "require_full_window": false,
    "thresholds": {
      "critical": 1
    },
    "silenced": {}
  },
  "multi": true,
  "created_at": 1682423832000,
  "created": "2023-04-25T11:57:12.753074+00:00",
  "modified": "2023-11-09T14:27:34.538355+00:00",
  "deleted": null,
  "restricted_roles": [
    "ad93d0a4-****-****-****-************"
  ],
  "priority": 3,
  "overall_state_modified": "2023-04-25T11:57:23+00:00",
  "overall_state": "No Data",
  "creator": {
    "name": "Datadog Datatdog API User",
    "email": "********",
    "handle": "********",
    "id": 10******
  }
}
```

**Comment by HantingZhang2** [comment]
Hi @pellepelster 

I cant' really reproduce this with your tf configuration. I waited for about 10mins between 2 `terraform apply`

Was there any manual changes on those monitors or roles by other users in your Datadog org? 
If not, how long do you start to see this after the first `terraform apply` ?
Is this behaviour consistent for all the monitor in your org and across all monitor types? 
Feel free to also send us a support ticket so we can have a better look into your dd account, let me know your ticket reference number.

**Comment by pellepelster** [comment]
Hi,

thanks for your feedback. Unfortunately we are not able anymore to reproduce this, so I will close this issue, and re-open should it happen again.
