### ISSUE TITLE
Add support for teams mapping in datadog_authn_mapping 

### ISSUE THREAD

**Issue by kristian-petersen** [DataDog/terraform-provider-datadog#2329]
### What resources or data sources are affected?

datadog_authn_mapping

### Feature Request

Add the same support for datadog_authn_mapping  as we have available in the UI where we can create mappings for Roles and Teams.

**Comment by nkzou** [comment]
This should be closed by #2363 , and will be available in the next release v3.39.0, which we're planning to release this week.

**Comment by kristian-petersen** [comment]
@nkzou Looks like this resource doesnt support role and team mappings being used at the same time. If i add the team and role in the same resource only the role mapping gets created, if I split them into two only team mappings gets created.
