### ISSUE TITLE
Unable to remove suppression filters from datadog_security_monitoring_rule

### ISSUE THREAD

**Issue by georgeopenshaw** [DataDog/terraform-provider-datadog#2330]
### Datadog Terraform Provider Version

v3.38.0

### Terraform Version

v1.7.4

### What resources or data sources are affected?

datadog_security_monitoring_rule

### Terraform Configuration Files

```hcl
Terraform apply output: 
     - filter {
          - action = "suppress" -> null
          - query  = "(@somefield:foo @somefield:bar)" -> null
        }
      - filter {
          - action = "suppress" -> null
          - query  = "(@somefield:foo @somefield:bar)" -> null
        }
```

### Expected Behavior

Terraform apply output shows that the filter has been removed

### Actual Behavior

The filter is not removed from the datadog detection rule

### Steps to Reproduce

1. Create a datadog_security_monitoring_rule resource with a suppression filter
2. terraform apply
3. Remove the filter from the rule
4. terraform apply

### Important Factoids

-

### References

-

**Comment by nkzou** [comment]
reproduced, looking into it. thanks for the report!
