### ISSUE TITLE
Destination should not be null with `datadog_logs_archive`

### ISSUE THREAD

**Issue by langenoja** [DataDog/terraform-provider-datadog#2337]
### Datadog Terraform Provider Version

v3.38.0

### Terraform Version

v1.5.1

### What resources or data sources are affected?

- datadog_logs_archive

### Terraform Configuration Files

```hcl
resource "datadog_logs_archive" "self" {
  name                            = "Test bucket"
  query                           = "env:test"
  include_tags                    = true
  rehydration_tags                = ["archive_source:backup_archive"]
  rehydration_max_scan_size_in_gb = 5

  gcs_archive {
    bucket       = "bucket-at-google-x1234"
    client_email = "<redacted>"
    path         = "/datadog/logs"
    project_id   = "<redacted>
  }
}
```

### Relevant debug or panic output

```
Error: destination should be not null
```

### Expected Behavior

1. Terraform successfully plans after initial deploy, and/or fullt deploys on first deploy.
2. Log archives appear in Datadog that talks to Google Cloud Storage

### Actual Behavior

1. Terraform fails first deploy and consequent plans
2. Log archives DO appear properly in Datadog, only the provider fails

### Steps to Reproduce

1. Define Google Cloud Storage log archive
2. Terraform plan > success
3. Terraform apply > failure
4. Terraform plan > failure

### References

https://github.com/DataDog/terraform-provider-datadog/issues/2093

**Comment by HantingZhang2** [comment]
Hi @langenoja 
We cannot reproduce the issue you described with the terraform configuration you provided.
In order for us to dig deeper into the root cause would you [create a support ticket](https://docs.datadoghq.com/account_management/guide/access-your-support-ticket/#creating-a-support-ticket) with the name of your Datadog org and the time when this issue happened ? 

Thanks,

**Comment by langenoja** [comment]
Thanks to the Datadog support, the problem has now been fixed.

For future reference, the issue was that **the App Token I was using did not have the `logs_read_archives` permission, but only the `logs_write_archives`.**
