### ISSUE TITLE
Provider 3.39.0 doesn't support `extended_resource_collection_enabled` attribute, but documentation says it does

### ISSUE THREAD

**Issue by eduardoasantana** [DataDog/terraform-provider-datadog#2382]
### Datadog Terraform Provider Version

v3.39.0

### Terraform Version

Any (tested on v1.3.9, 1.7.4, 2

### What resources or data sources are affected?

datadog_integration_aws

### Terraform Configuration Files

```hcl
resource "datadog_integration_aws" "datadog_aws_integration" {
  count = var.create_datadog_integration ? 1 : 0

  account_id = data.aws_caller_identity.current.account_id
  role_name  = "datadog-integration-role"

  excluded_regions = local.excluded_regions

  metrics_collection_enabled           = var.enable_datadog_metrics_collection
  extended_resource_collection_enabled = var.enable_datadog_resource_collection
  cspm_resource_collection_enabled     = var.enable_datadog_cspm_resource_collection
}
```

### Expected Behavior

The terraform docs say that v3.39.0 of the Datadog provider has deprecated the [resource_collection_enabled](https://registry.terraform.io/providers/DataDog/datadog/latest/docs/resources/integration_aws#resource_collection_enabled) attribute and replaced it with the [extended_resource_collection_enabled](https://registry.terraform.io/providers/DataDog/datadog/latest/docs/resources/integration_aws#extended_resource_collection_enabled) attribute. I expected to be able to create an aws integration in Terraform using this new attribute

### Actual Behavior

Instead I get the following error:

> Unexpected attribute: An attribute named "extended_resource_collection_enabled" is not expected here

If I change the `extended_resource_collection_enabled` attribute back to the older `resource_collection_enabled` attribute, I do get a deprecation warning for this attribute when I run a plan.

![Screenshot 2024-04-23 at 3 54 01 PM](https://github.com/DataDog/terraform-provider-datadog/assets/89654544/7faf2acf-0ae7-4d09-949c-e8f32425dd86)
Screenshot from the Datadog [provider docs for the datadog_integration_aws resource](https://registry.terraform.io/providers/DataDog/datadog/latest/docs/resources/integration_aws#extended_resource_collection_enabled) that shows this is supposed to be the correct new argument.
![Screenshot 2024-04-23 at 3 55 22 PM](https://github.com/DataDog/terraform-provider-datadog/assets/89654544/13735e4d-a3e4-417b-888e-46d8e48e0151)

### Steps to Reproduce

1. Create a `datadog_integration_aws` resource in terraform with the `extended_resource_collection_enabled` attribute using provider 3.39.0
2. Run `terraform init`
3. Run `terraform validate` or `terraform plan`
4. See error:
![Screenshot 2024-04-23 at 3 52 14 PM](https://github.com/DataDog/terraform-provider-datadog/assets/89654544/caa1e243-47eb-406b-88c7-abc57abef2b1)

### Important Factoids

Nothing in particular is odd about our AWS set up. We're getting these errors before we even run an apply or touch AWS.

### References

extended_resource_collection_enabled

**Comment by skarimo** [comment]
Hello, you are most likely still using an older version of the provider. As the docs are generated from the schemas directly, I do not see how this can occur. I would suggest running terraform commands with `TF_LOG=debug` and see which provider version is being used for your module.

**Comment by HantingZhang2** [comment]
> Hello, you are most likely still using an older version of the provider. As the docs are generated from the schemas directly, I do not see how this can occur. I would suggest running terraform commands with `TF_LOG=debug` and see which provider version is being used for your module.

The deprecation message is added in the same pr that introduced the new parameter `extended_resource_collection_enabled` though, I can't reproduce it on my side. 

+1 on double checking the provider version when using both parameters.

**Comment by eduardoasantana** [comment]
You were correct. The terraform workspace had a lock file locally pinning the Datadog provider to v3.38.0. Deleting this file and confirming it was on v3.39.0 made this issue go away. This lock file doesn't exist in source control, so that can explain the weird behavior of getting the error while also seeing a deprecation warning on a plan.

This issue can be closed.
