### ISSUE TITLE
Cannot update Monitor Downtime

### ISSUE THREAD

**Issue by jengland-victorfi** [DataDog/terraform-provider-datadog#2397]
### Datadog Terraform Provider Version

v3.39.0

### Terraform Version

v1.5.7

### What resources or data sources are affected?

datadog_downtime_schedule

### Terraform Configuration Files

```hcl
resource "datadog_downtime_schedule" "bank_hours" {
  scope = "*"
  monitor_identifier {
    monitor_tags = var.monitor_tags
  }

  # First recurrence: Weekdays (Sun to Fri) from 18:00 for 12 hours
  recurring_schedule {
    # First recurrence: Weekdays (Sun to Fri) from 18:00 for 12 hours
    recurrence {
      duration = "12h"
      rrule    = "FREQ=WEEKLY;INTERVAL=1;BYDAY=SU,MO,TU,WE,TH,FR"
      start    = "2023-01-01T18:00"
    }

    # Second recurrence: Weekends (Sat and Sun) from 00:00 for 24 hours
    recurrence {
      duration = "24h"
      rrule    = "FREQ=WEEKLY;INTERVAL=1;BYDAY=SA,SU"
      start    = "2023-01-01T00:00"
    }

    timezone = var.timezone
  }

  display_timezone                 = var.timezone
  message                          = "Message about the downtime"
  mute_first_recovery_notification = false
  notify_end_states                = ["alert", "warn", "no data"]
  notify_end_types                 = ["canceled", "expired"]
}
```

### Relevant debug or panic output

running "terragrunt apply $PLANFILE" in "/atlantis-data/repos/victor-fi/infra-tf/647/environments_sandbox_infra_datadog-composite/environments/sandbox/infra/datadog-composite": exit status 1: running "terragrunt apply $PLANFILE" in "/atlantis-data/repos/victor-fi/infra-tf/647/environments_sandbox_infra_datadog-composite/environments/sandbox/infra/datadog-composite": 
time=2024-05-07T14:34:26Z level=info msg=Downloading Terraform configurations from file:///atlantis-data/repos/victor-fi/infra-tf/647/environments_sandbox_infra_datadog-composite into /atlantis-data/repos/victor-fi/infra-tf/647/environments_sandbox_infra_datadog-composite/environments/sandbox/infra/datadog-composite/.terragrunt-cache/kpRx-4n9Cuwg5C8A-ZQRBdjFOW0/KvYvK-HLNdnsitVTZ3LvlWwQWew
module.datadog_bank_hours.datadog_downtime_schedule.bank_hours: Modifying... [id=7cb366a0-88be-11ee-8a42-da7ad0900002]
module.datadog_synthetics_alerts.datadog_synthetics_global_variable.config["client_secret"]: Modifying... [id=89ca0bd8-a599-4735-be4f-c3d5349800b9]
module.datadog_synthetics_alerts.datadog_synthetics_global_variable.config["client_id"]: Modifying... [id=a07b8fd3-5f8b-47aa-9cb8-af18c0057dfc]
module.datadog_synthetics_alerts.datadog_synthetics_global_variable.config["client_id"]: Modifications complete after 0s [id=a07b8fd3-5f8b-47aa-9cb8-af18c0057dfc]
module.datadog_synthetics_alerts.datadog_synthetics_global_variable.config["client_secret"]: Modifications complete after 0s [id=89ca0bd8-a599-4735-be4f-c3d5349800b9]

Error: Provider produced inconsistent result after apply

When applying changes to
module.datadog_bank_hours.datadog_downtime_schedule.bank_hours, provider
"provider[\"registry.terraform.io/datadog/datadog\"]" produced an unexpected
new value: .recurring_schedule.recurrence[0].start: was
cty.StringVal("2023-01-01T18:00"), but now
cty.StringVal("2023-01-01T18:00:00").

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

Error: Provider produced inconsistent result after apply

When applying changes to
module.datadog_bank_hours.datadog_downtime_schedule.bank_hours, provider
"provider[\"registry.terraform.io/datadog/datadog\"]" produced an unexpected
new value: .recurring_schedule.recurrence[1].start: was
cty.StringVal("2023-01-01T00:00"), but now
cty.StringVal("2023-01-01T00:00:00").

### Expected Behavior

The terraform should apply and update the scope properly.

### Actual Behavior

Error message included previously

### Steps to Reproduce

terraform apply

### Important Factoids

This relates to data dog case # 1676733

**Comment by kayman-mk** [comment]
@jengland-victorfi  What was the solution? I have the same problem now.
