### ISSUE TITLE
`widget.timeseries_definition.request.query.slo_query.slo_query_type` doesn't support `time_slice` option

### ISSUE THREAD

**Issue by smartfin** [DataDog/terraform-provider-datadog#2411]
### Datadog Terraform Provider Version

v3.39.0

### Terraform Version

v1.5.7

### What resources or data sources are affected?

widget.timeseries_definition.request.query.slo_query, and every resource that has `slo_query_type` field

### Terraform Configuration Files

```hcl
widget {
        timeseries_definition {
          title = "SLO Status"

          request {
            display_type = "area"

            formula {
              formula_expression = "query1"
              style {
                palette = "green"
              }
            }
            query {
              slo_query {
                name           = "query1"
                data_source    = "slo"
                measure        = "slo_status"
                slo_id         = datadog_service_level_objective.sli_response_time_p95.id
                slo_query_type = "metric"
                group_mode     = "overall"
              }
            }
          }
        }
      }
```

### Expected Behavior

`slo_query_type` should support value `time_slice` to display timeseries charts for SLO that has type `time_slice` 

### Actual Behavior

Widget is created but it doesn't show any data

**Comment by pablito-perez** [comment]
fixed in this release: https://github.com/DataDog/terraform-provider-datadog/releases/tag/v3.42.0
