### ISSUE TITLE
Documentation for `datadog_team_permission_settings` is misleading/incomplete

### ISSUE THREAD

**Issue by 2rs2ts** [DataDog/terraform-provider-datadog#2446]
### Datadog Terraform Provider Version

v3.39.0

### Terraform Version

v1.8.5

### What resources or data sources are affected?

* datadog_team_permission_settings

### Terraform Configuration Files

```hcl
resource "datadog_team" "myteam" {
  description = "My team description"
  handle      = "myteam"
  name        = "Myteam"
}

resource "datadog_team_permission_setting" "let_terraform_modify" {
  for_each = toset(["manage_membership", "edit"])
  team_id  = datadog_team.myteam.id
  action   = each.key
  value    = "organization"
}
```

### Expected Behavior

I expected that this configuration would work and would make it so that anyone in my organization would be able to apply this terraform repo (after the `datadog_team` was initially created by someone with the permission to do so, anyway.)

The [docs](https://registry.terraform.io/providers/DataDog/datadog/3.39.0/docs/resources/team_permission_setting) say that the values I used were valid.

### Actual Behavior

```
Error: error updating team permission setting

  with datadog_team_permission_setting.let_terraform_modify["edit"],
  on main.tf line 76, in resource "datadog_team_permission_setting" "let_terraform_modify":
  76: resource "datadog_team_permission_setting" "let_terraform_modify" {

400 Bad Request: {"errors":["Invalid value type \"organization\". Valid values: teams_manage, admins, members"]}
```

I believe that the docs should make it more clear which values are valid. For what it's worth, I got a 403 on the other part of the `for_each`, which indicated that the value I chose was valid but I lack permissions to execute the change. I'm working with my org's admins to get the right permissions, but I believe the 400 error is not caused by me lacking access.

### Steps to Reproduce

1. terraform apply

**Comment by nkzou** [comment]
Hey there, looks like the valid `value` options are dependent on the `action` value. 
- `manage_membership` allows values of `user_access_manage`, `admins`, `members`, `organization`.
- `edit` allows values of `teams_manage`, `admins`, `members`

I'll confirm this with the backend team and get a documentation change out. Thanks for the report.
