### ISSUE TITLE
Synthetics Test Multi-steps client certificate config broken when applied second time

### ISSUE THREAD

**Issue by ibmboy19** [DataDog/terraform-provider-datadog#2471]
### Datadog Terraform Provider Version

v3.39.0

### Terraform Version

v1.8.3

### What resources or data sources are affected?

datadog_synthetics_test - multi-steps

### Expected Behavior

The client certificate config should still working

### Actual Behavior

The client certificate config broken and the API test can't pass the client cer authentication

### Steps to Reproduce

1. Newly terraform apply the Multi-steps synthetic test
2. Modify something on the Multi-steps synthetic test and apply again
3. Trigger the synthetic test and the test start to fail

**Comment by Drarig29** [comment]
Hi @ibmboy19! Is this bug still happening in the latest version of the provider?

**Comment by ibmboy19** [comment]
@Drarig29 Yes, this bug also still exists in v3.46.0.

**Comment by Drarig29** [comment]
Thanks, we added a card in our backlog. We'll get back to you once it's fixed.

**Comment by AntoineDona** [comment]
Hi @ibmboy19! 
Thanks for for reporting this bug.
We made a fix that will be present in the next release of the terraform provider (probably next week).

**Comment by ibmboy19** [comment]
Hi @AntoineDona, 
Thank you so much for your efforts!

**Comment by AntoineDona** [comment]
Hey @ibmboy19 ! The fix was just released in [v3.50.0](https://github.com/DataDog/terraform-provider-datadog/releases/tag/v3.50.0) of the terraform-provider. Thanks again for reporting the issue!
