### ISSUE TITLE
Error creating `datadog_integration_aws_log_collection` fixed on rerun

### ISSUE THREAD

**Issue by carlosjgp** [DataDog/terraform-provider-datadog#2491]
### Datadog Terraform Provider Version

datadog/datadog v3.41.0

### Terraform Version

v1.5.6

### What resources or data sources are affected?

datadog_integration_aws_log_collection

### Terraform Configuration Files

```hcl
resource "datadog_integration_aws" "this" {
  count = var.create ? 1 : 0

  account_id = data.aws_caller_identity.current.account_id
  role_name  = local.datadog_role_name

  filter_tags = var.filter_tags
  host_tags = concat([
    for label, value in var.host_tags :
    "${label}:${value}"
    ],
    [
      "source:aws-datadog-integration",
  ])

  # Warning: the datadog provider doesn't officially support turning on the flag for monitoring alarms
  # and custom metrics, but it does seem to have these undocumented flags that do the job
  account_specific_namespace_rules = {
    crawl_alarms           = var.metrics_collection_enabled
    collect_custom_metrics = var.metrics_collection_enabled
  }
  metrics_collection_enabled = var.metrics_collection_enabled

  extended_resource_collection_enabled = var.resource_collection_enabled
  cspm_resource_collection_enabled     = var.resource_collection_enabled

  excluded_regions = var.excluded_regions
}

resource "time_sleep" "integration_create_plus_45" {
  depends_on      = [datadog_integration_aws.this]
  create_duration = "45s"
}

resource "datadog_integration_aws_log_collection" "this" {
  count = var.create ? 1 : 0

  account_id = data.aws_caller_identity.current.account_id
  services   = var.aws_log_collection_services

  depends_on = [
    # There is some delay in creating the AWS Integration that the
    # provider doesn't expose anywhere so we need to be lenient here
    time_sleep.integration_create_plus_45
  ]
}
```

### Relevant debug or panic output

╷
│ Error: aws integration log collection resource with account id `<account id>` not found after creation
│ 
│   with module.datadog_aws_integration.datadog_integration_aws_log_collection.this[0],
│   on .terraform/modules/datadog_aws_integration/main.tf line 78, in resource "datadog_integration_aws_log_collection" "this":
│   78: resource "datadog_integration_aws_log_collection" "this" {
│ 
╵

### Expected Behavior

Apply without error

### Actual Behavior

Errors on the first apply

It's ok on the second aply

### Steps to Reproduce

terraform apply

### Important Factoids

It would be nice to take this parameter as an input instead of using a datasource... I'm not sure how long we will have to wait but it seems that this is growing up slowly

https://github.com/DataDog/terraform-provider-datadog/blob/40503c76d5b60605293e7642b4e0519d4762c980/datadog/resource_datadog_integration_aws_log_collection.go#L83

**Comment by nkzou** [comment]
In the `datadog_integration_aws_log_collection` resource, instead of setting `account_id` to `data.aws_caller_identity.current.account_id`, try setting it to `datadog_integration_aws.this.account_id`. Alternatively, include a `depends_on = [datadog_integration_aws.this]` meta argument to the `datadog_integration_aws_log_collection` resource.
I believe this is happening because terraform is trying to create the aws integration log collection resource before the actual aws integration is created - referring to the actual aws integration like shown above tells terraform to run the log collection update after the aws integration is finished being created.

**Comment by carlosjgp** [comment]
It tried these and it stills fails

I ended up using sleep for 120s... if feels like this needs to be longer and longer the more accounts we add :(
