### ISSUE TITLE
datadog_synthetics_test request_headers doesn't allow : character

### ISSUE THREAD

**Issue by SanderKnape** [DataDog/terraform-provider-datadog#2575]
### Datadog Terraform Provider Version

3.43.1

### Terraform Version

1.9.5

### What resources or data sources are affected?

datadog_synthetics_test

### Terraform Configuration Files

```hcl
resource "datadog_synthetics_test" "test" {
  [...]
  request_headers = {
    ":authority" = "example.com"
  }
  [...]
}
```

### Relevant debug or panic output

│ Error: invalid value for request_headers (header field must be a valid token)
│
│   with datadog_synthetics_test.test,
│   on modules/uptime-monitoring/main.tf line 51, in resource "datadog_synthetics_test" "test":
│   51:   request_headers = {
│   52:     ":authority" = "example.com"
│   54:   }

### Expected Behavior

The Synthetics Test should be configured with the `:authority` request header.

### Actual Behavior

The Datadog Terraform provider reported an error because the `:` character isn't allowed.

**Comment by Drarig29** [comment]
Hi @SanderKnape! We merged a fix PR (https://github.com/DataDog/terraform-provider-datadog/pull/2581), and this will be available in the next release.

Thanks for reporting! 🙇
