### ISSUE TITLE
Perpetual diff on template_variable

### ISSUE THREAD

**Issue by joelmarty** [DataDog/terraform-provider-datadog#2595]
### Datadog Terraform Provider Version

3.44.1

### Terraform Version

1.9.6

### What resources or data sources are affected?

datadog_dashboard

### Terraform Configuration Files

```hcl
resource "datadog_dashboard" "my_dashboard" {
  title = "my title"

  layout_type = "ordered"
  reflow_type = "fixed"

  template_variable {
    name             = "env"
    prefix           = "env"
    defaults         = ["prod"]
    available_values = ["prod", "stage", "dev"]
  }
 
  ... // widgets
}
```

### Expected Behavior

Terraform does not show diff if template variables do not change.

### Actual Behavior

Template variable always show a diff on `defaults` value, trying to use `default` instead. But `default` is marked as deprecated.
<img width="381" alt="image" src="https://github.com/user-attachments/assets/822c282f-cca4-4017-b673-1de0527ca512">

### Steps to Reproduce

1. terraform plan

**Comment by maikroempagel** [comment]
@joelmarty Still see this with version `3.49.0`. Was there a reason you closed this?

**Comment by joelmarty** [comment]
I do not remember exactly, I should have left a comment 🤔 
It might have been a mistake on my end, feel free to reopen 😄
