### ISSUE TITLE
v3.45.0 update breaking terraform validate

### ISSUE THREAD

**Issue by fkennedy1** [DataDog/terraform-provider-datadog#2605]
### Datadog Terraform Provider Version

v3.45.0

### Terraform Version

1.5.7

### What resources or data sources are affected?

Hello,

When running `terraform validate` pulling in the latest version of the datadog provider is returning:

│ Error: Failed to install provider
│ 
│ Error while installing datadog/datadog v3.45.0: checksum list has
│ unexpected SHA-256 hash
│ c56a54286cff322ea32accb02dee4effad361dcdea291c774f132691170f407d (expected
│ 5ed77f935e71de538e86d7dda03c592a5780a5350c3e1dedc638b20079c66fca)

This previously worked in v3.44.1

### Expected Behavior

Terraform is able to download the new provider version

**Comment by bitmagewb** [comment]
Seeing the same behavior here on TF applys that were working yesterday.

**Comment by skarimo** [comment]
Hello, thanks for the report. We are actively working on resolving this. We will release 3.46.0 to unblock quickly.

**Comment by bcrantsequoia** [comment]
3.46.0 resolved on my side. Thanks for the quick fix!

**Comment by kodermike** [comment]
also confirmed, `init` now....inits

**Comment by eduardoasantana** [comment]
Glad I found this - 3.46.0 fixed it for me too. Good reminder to set Terraform lock files to lock providers to working versions. Thanks for the quick fix!

**Comment by bitmagewb** [comment]
Working here as well with 3.46, thank you!

**Comment by ericmhayes** [comment]
Issues resolved here! Thanks guys for the really fast response on this one 💯 !
