### ISSUE TITLE
Updating datadog_role with empty permission list: "Missing permission_ids"

### ISSUE THREAD

**Issue by sebastien-prudhomme** [DataDog/terraform-provider-datadog#2608]
### Datadog Terraform Provider Version

v3.46.0

### Terraform Version

v1.8.4

### What resources or data sources are affected?

* datadog_role

### Relevant debug or panic output

Yesterday I was able to create a datadog_role with an empty permission list, so that the role has only the mandatory permissions.

Today it seems that the "quality_gates_evaluations_read" new permission was added to all roles.

Unfortunetely the provider (or maybe the Datadog API) is no more able to remove that role:

```
Terraform will perform the following actions:

  # datadog_role.read will be updated in-place
  ~ resource "datadog_role" "read" {
        id         = "xxxx"
        name       = "Read"
        # (1 unchanged attribute hidden)

      - permission {
          - id   = "xxxx" -> null
          - name = "quality_gates_evaluations_read" -> null
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.
datadog_role.read: Modifying... [id=xxxx]
╷
│ Error: error updating role from /api/v2/roles/xxxx: 400 Bad Request: {"errors":["Invalid input Missing permission_ids: []"]}
│
│   with datadog_role.read,
│   on main.tf line 112, in resource "datadog_role" "read":
│  112: resource "datadog_role" "read" {
│
╵

```

**Comment by skarimo** [comment]
Hello, thanks for the report. We have identified the issue and a fix has been put in place. Feel free to follow up if you are still running into issues. Thanks again
