### ISSUE TITLE
api catalog openapi resources get created twice

### ISSUE THREAD

**Issue by MacGurk** [DataDog/terraform-provider-datadog#2635]
### Datadog Terraform Provider Version

v3.46.0

### Terraform Version

v1.9.8

### What resources or data sources are affected?

datadog_openapi_api

### Terraform Configuration Files
```
terraform {
  required_providers {
    datadog = {
      source  = "datadog/datadog"
      version = "3.46.0"
    }
}

provider "datadog" {
  api_url = "https://api.datadoghq.eu/"
  api_key = var.apikey
  app_key = var.appkey
}

resource "datadog_openapi_api" "test1" {
  spec = file("./someapi.json")
}
resource "datadog_openapi_api" "test2" {
  spec = file("./someapi.json")
}
resource "datadog_openapi_api" "test3" {
  spec = file("./someapi.json")
}
```

### Relevant debug or panic output

Apply output creating three resources
```
datadog_openapi_api.test2: Creating...
datadog_openapi_api.test3: Creating...
datadog_openapi_api.test1: Creating...
datadog_openapi_api.test3: Creation complete after 0s [id=f3625fc9-8ef4-407c-8136-*****]
datadog_openapi_api.test1: Creation complete after 0s [id=025ef8c3-47c2-44cc-b147-*****]
datadog_openapi_api.test2: Creation complete after 0s [id=ac0eac78-d14e-456d-bfd5-*****]
```

### Expected Behavior

Create one API in the API Catalog per resource defined in the terraform config.

### Actual Behavior

When creating multiple datadog_openapi_api resources at once at least one of those resources gets created twice. The additionally created API is not tracked in the terraform state.

### Steps to Reproduce

1. Create a terraform config where multiple datadog_openapi_api resources get created
2. `terraform apply`

**Comment by MacGurk** [comment]
The issue seems to be together with the parallelism of terraform. When i run `terraform apply -parallelism=1` all APIs get only created one time.

**Comment by therve** [comment]
Hi,

This has been fixed in the backend, let us know if you're still encountering issues. Thanks and sorry for the inconvenience.
