### ISSUE TITLE
Documentation for datadog_integration_cloudflare_account resources field

### ISSUE THREAD

**Issue by jmitash** [DataDog/terraform-provider-datadog#2656]
We have Terraform which, in 3.46.0 and prior, did not toggle on the metrics for the Cloudflare integration:
```tf
resource "datadog_integration_cloudflare_account" "mine" {
  name    = "mine-cf"
  email   = var.cloudflare_email
  api_key = var.cloudflare_api_token
}
```

Since the metrics could not be turned on via Terraform, I turned them on manually via the UI:
![Image](https://github.com/user-attachments/assets/d3a7f824-0ded-4a77-944b-a36e4ee06c95)

After upgrading to 3.47.0, and without modifying that TF resource, we saw that Terraform plan wanted to empty the `resources`, which to me made sense because we had never configured them in Terraform.

However, we checked the documentation and see this for the new `resources` field:
> An allowlist of resources to restrict pulling metrics for including web, dns, lb (load balancer), worker)

I found the word "restrict" confusing, as it conflicts with the meaning of an allowlist. To me, an allowlist means to allow, and to restrict is the opposite. We found the PR #2633 where this was discussed a bit, but it was still unclear to us what is meant by restrict. I incorrectly believed after reading the PR that the default value for `resources` meant that _all_ metrics would be enabled, and that only by explicitly supplying values does the allowlist take effect (hence, _restricting_ the metrics).

However, after applying the plan, we saw that all metrics were disabled in the UI. We updated the resources to include the 4 metric types specifically:
```tf
resource "datadog_integration_cloudflare_account" "mine" {
  name    = "mine-cf"
  email   = var.cloudflare_email
  api_key = var.cloudflare_api_token
  resources = ["web", "dns", "lb", "worker"]
}
```

And that yielded the desired behavior of keeping all resource metric types enabled.

I wanted to share in case the documentation for this field can be clarified. I'm not sure I understood the intent behind using the word "restrict"-- to me it makes sense to have used the word "permit".

**Comment by skarimo** [comment]
Thanks for the issue. We merged https://github.com/DataDog/terraform-provider-datadog/pull/2658 and should be included in the next release
