### ISSUE TITLE
Error on datadog_integration_aws_tag_filter: Object contains unparsed element

### ISSUE THREAD

**Issue by JulesClaussen** [DataDog/terraform-provider-datadog#2669]
### Datadog Terraform Provider Version

3.48

### Terraform Version

v1.5.7

### What resources or data sources are affected?

datadog_integration_aws_tag_filter

### Terraform Configuration Files

```hcl
resource "datadog_integration_aws_tag_filter" "custom" {
  depends_on = [datadog_integration_aws.default]

  account_id     = datadog_integration_aws.default.account_id
  namespace      = "custom"
  tag_filter_str = "datadog:monitored"
}
```

### Relevant debug or panic output

```
10:57:18.803 STDERR terraform: │ Error: object contains unparsed element: map[namespace:step_functions tag_filter_str:<nil>]
10:57:18.803 STDERR terraform: │ 
10:57:18.803 STDERR terraform: │   with datadog_integration_aws_tag_filter.custom,
10:57:18.803 STDERR terraform: │   on datadog.tf line 141, in resource "datadog_integration_aws_tag_filter" "custom":
10:57:18.803 STDERR terraform: │  141: resource "datadog_integration_aws_tag_filter" "custom" {
10:57:18.803 STDERR terraform: │ 
```

### Expected Behavior

No errors

### Actual Behavior

There's an error when running terraform plan or apply on this resource

### Steps to Reproduce

terraform plan or terraform apply

**Comment by paul-hugill** [comment]
Seeing this as well, tried 3.46 and 3.47 or the provider as well and we have no mention of `stepfunctions` in our code, it is not in the DD UI or the TF Docs, so this seems more like a DD API issue to me though.

It is blocking all of our accounts being run or created currently though.

**Comment by jcajkovic** [comment]
+1 here

**Comment by fatbasstard** [comment]
Just hitting exactly the same issue. No changes, looks like an internal data thing.

Might be related to the fact that we just got this email:

```We want to let you know that we will begin billing for Step Functions Infra starting December 1st, 2024```

Sometime internal changed causing the implementation to break. My 2 cents

We had something similar with the regions (https://github.com/DataDog/terraform-provider-datadog/issues/2548)

**Comment by mmichna** [comment]
+1 here

**Comment by ZsoltPath** [comment]
same here with
Terraform v1.9.1
on darwin_arm64
+ provider registry.terraform.io/datadog/datadog v3.48.0

**Comment by rumenvasilev** [comment]
@ZsoltPath you might wanna rotate your API key now. Line 5 in your debug output.

**Comment by ZsoltPath** [comment]
> [@ZsoltPath](https://github.com/ZsoltPath) you might wanna rotate your API key now. Line 5 in your debug output.

Silly me! Thanks!

**Comment by rumenvasilev** [comment]
I think I found the source of the problem. step_functions is not enumerated as an option here https://github.com/DataDog/datadog-api-client-go/blob/master/api/datadogV1/model_aws_namespace.go#L16-L35 and thus the validation [utils.CheckForUnparsed()](https://github.com/DataDog/terraform-provider-datadog/blob/master/datadog/resource_datadog_integration_aws_tag_filter.go#L122) fails because that last bit in the HTTP response `{"namespace":"step_functions","tag_filter_str":null}` remains unparsed.

**Comment by nkzou** [comment]
Hi all,
The backend change introducing the `step_functions` options has been reverted temporarily while we add the new enum variant to our clients and terraform. We will cut a bugfix release soon to handle this before the api change is rolled out again.

**Comment by nkzou** [comment]
v3.48.1 has been released and handles this new enum variant properly. Please upgrade asap - the backend team is planning to rerelease the `step_functions` change roughly tomorrow afternoon EST.

**Comment by dwikle** [comment]
@anthonyangel We are holding the rerelease until next week to allow customers more time to upgrade if necessary.  It's currently planned for Tuesday November 19.

**Comment by JulesClaussen** [comment]
My bad! Looks like renovate is being fussy at opening lock files maintenance. Sorry for the noise 👍
