### ISSUE TITLE
erros object contains unparsed element datadog provider datadog_integration_aws_tag_filter

### ISSUE THREAD

**Issue by cfazevedo-lab** [DataDog/terraform-provider-datadog#2712]
### Datadog Terraform Provider Version

3.34.0

### Terraform Version

v1.9.2

### What resources or data sources are affected?

datadog_integration_aws_tag_filter (Resource)

### Terraform Configuration Files

```hcl
resource "datadog_integration_aws_tag_filter" "lambda_filter" {
  provider    = datadog.datadog-aws-integration
  account_id     = var.account_id
  namespace      = "lambda"
  tag_filter_str = "project:*"
}
```

### Relevant debug or panic output

Error: object contains unparsed element: map[namespace:step_functions tag_filter_str:<nil>]    
  | with module.datadog_aws_integration.datadog_integration_aws_tag_filter.lambda_filter, on ../../modules/datadog-aws-integration/main.tf line 113, in resource "datadog_integration_aws_tag_filter" "lambda_filter": 113: resource "datadog_integration_aws_tag_filter" "lambda_filter" {
 

### Expected Behavior

Provisions without an error

### Actual Behavior

errors with a module 

### Steps to Reproduce

terraform apply

### Important Factoids

Errors with the module occurred without us having updated the provider version or made parameter changes. We noticed that in version "3.48.1" of the provider, a filter option for "step_functions" was introduced. From that moment, we started encountering errors during the Terraform apply, which should not happen even when using an older version of the provider.

**Comment by ktmq** [comment]
Hi! Thanks for reporting this. The issue is fixed since release v3.48.1: https://github.com/DataDog/terraform-provider-datadog/releases/tag/v3.48.1
