### ISSUE TITLE
Feature Request: Implement Retry object within Options object

### ISSUE THREAD

**Issue by jordantoth** [DataDog/terraform-provider-datadog#363]
Inspecting Datadog's network requests upon saving a synthetic in Datadog's web interface shows an entry in the `Options` object with the key `retry`, which itself has keys `count`, integer number of retries before failing, and `interval`, number of seconds to wait before retrying. It doesn't look like this object is in Datadog's API documentation, but if possible it should be implemented, since otherwise every terraform apply currently sets the retry count to zero.

**Comment by therve** [comment]
Tracking it in #440 , thanks.
