### ISSUE TITLE
FeatureRequest: datadog_monitor to support new AWS IMDSv2 EC2 metric (MetadataNoToken)

### ISSUE THREAD

**Issue by richardclark85** [DataDog/terraform-provider-datadog#367]
### Feature Request
Feature request to support new AWS EC2 Cloudwatch metric "MetadataNoToken" for provisioning within datadog_monitor resource.

resource "datadog_monitor" "foo" {
  name               = "Name for monitor foo"
  type               = "metric alert"
  message            = "Monitor triggered. Notify: @hipchat-channel"
  escalation_message = "Escalation message @pagerduty"

  query = "max(last_1h):max:aws.ec2.**metadata_no_token**{environment:foo,host:foo} by {host} > 4"

### Resources
EC2 Metrics with Cloudwatch - https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/viewing_metrics_with_cloudwatch.html

New AWS IMDSv2 Service - https://aws.amazon.com/blogs/security/defense-in-depth-open-firewalls-reverse-proxies-ssrf-vulnerabilities-ec2-instance-metadata-service/

**Comment by richardclark85** [comment]
Ideally someone would want to be alerted if this metric becomes greater than or equal to 1 as the default by AWS is 0.

Example:
query = "max(last_5m):max:aws.ec2.metadata_no_token{environment:foo,host:foo} by {host} >= 1"

**Comment by therve** [comment]
Thanks for your report. I believe our backend support such a metric, thus making it available in terraform. Please contact support if it doesn't work as expected.
