### ISSUE TITLE
Renotify_interval doesn't exist in datadog_synthetics_test

### ISSUE THREAD

**Issue by DenysHalkin** [DataDog/terraform-provider-datadog#376]
Hello.  There is no available option to enable re-notification if the monitor has not been resolved.

### Affected Resource(s)
- datadog_synthetics_test

### Expected Behavior
As in datadog_monitor resource:

> renotify_interval (Optional) The number of minutes after the last notification before a monitor will re-notify on the current status. It will only re-notify if it's not resolved.

**Comment by KeisukeYamashita** [comment]
@DenysHalkin Hi, thank you for catching this issue. I will like to work on this and raise a pull request:)

**Comment by KeisukeYamashita** [comment]
The `/v1/synthetics/tests/` API doesn't support `renotify_interval` but the monitor does.

**Comment by KeisukeYamashita** [comment]
Looks like the 

```
curl -X "POST" "https://api.datadoghq.com/api/v1/synthetics/tests" \
     -H 'Content-type: application/json' \
     -H 'DD-API-KEY:xxxxxx' \
     -H 'DD-APPLICATION-KEY: xxxxxxxx' \
     -d $'{
  "config": {
    "assertions": [
      {
        "type": "certificate",
        "operator": "isInMoreThan",
        "target": 45
      }
    ],
    "request": {
      "host": "example.com",
      "port": 443
    }
  },
  "message": "[Keke test] KeisukeYamashita",
  "locations": [
    "aws:ap-northeast-1"
  ],
  "subtype": "ssl",
  "type": "api",
  "options": {
    "tick_every": 60,
    "monitor_options": {
      "renotify_interval": 200
    }
  },
  "tags": [
    "env:production",
    "team:merpay-sre",
    "user:keisukeyamashita",
    "host:example.com"
  ],
  "name": "[Keke test] An KeisukeYamashita test"
}'
```
