### ISSUE TITLE
Cannot choose private location - synthetics

### ISSUE THREAD

**Issue by chelapa** [DataDog/terraform-provider-datadog#381]
I don't see any way of choosing / creating a private location when creating a synthetics test. Only options are the non-priv locations. Will this be a feature ?

**Comment by dabcoder** [comment]
Hello, you are correct, you can only choose non private locations for now. Keeping this issue open for a feature request indeed.

**Comment by fwaters-heb** [comment]
I am also interested in this. It looks like https://github.com/terraform-providers/terraform-provider-datadog/pull/309 implements most (all?) of what is really needed. Do you know if that PR is still being considered @dabcoder ? Anything needed to help push it through?

**Comment by MBali-GitHub** [comment]
I am also looking for the ability to use private locations in the tests. Is there a timeline for this yet?

**Comment by MBali-GitHub** [comment]
I tried this, and I am able to successfully create synthetic tests using private location now.

This is how it works : 
locations = ["pl:<locationId>" ]

**Comment by skarimo** [comment]
> I tried this, and I am able to successfully create synthetic tests using private location now.
> 
> This is how it works :
> locations = ["pl:_locationId_" ]

Hello, above is correct. You should now be able to pass the private location with format: `pl:<private-location-id>`

**Comment by nmuesch** [comment]
Hey, I'm going to close this out based on the provided solutions. Please let me know if this continues to be an issue.
