### ISSUE TITLE
Downtime recreated after recurrence

### ISSUE THREAD

**Issue by i524** [DataDog/terraform-provider-datadog#391]
### Terraform Version

```
Terraform v0.12.19
+ provider.datadog v2.5.0
```

### Affected Resource(s)
- datadog_downtime

### Terraform Configuration Files
```hcl
resource "datadog_downtime" "some_down_time" {
  scope = [
    "service:mysql",
  ]
  message    = <<EOT
some messages
EOT
  monitor_id = module.some_module.some_monitor_id
  start      = 1578693000
  end        = 1578696600
  timezone   = "Asia/Tokyo"
  recurrence {
    type   = "days"
    period = 1
  }
  lifecycle {
    ignore_changes = [start, end]
  }
}

```

### Debug Output
Result of `terraform plan` and `terraform state show`:
https://gist.github.com/i524/b2101ea30c8f23a0c3bdb8691b7733df

### Expected Behavior
`terraform plan` shows nothing.

### Actual Behavior
`terraform plan` claims to create a new downtime even if it exists.

### Steps to Reproduce
1. create a recurring downtime with `terraform apply`
1. wait for a downtime to work at least once
1. `terraform plan`

**Comment by tspadi** [comment]
Same issue even specifying `id` within the ignore_changes list like it is documented here : https://www.terraform.io/docs/providers/datadog/r/downtime.html#id
`ignore_changes = [id, start, end]`

**Comment by ktham** [comment]
We're running into the same problem.

I added some debug logging and noticed this:

```
2020-12-08T20:41:27.400Z [DEBUG] plugin.terraform-provider-datadog_v2.17.0: GET /api/v1/downtime/1054768704 HTTP/1.1
2020-12-08T20:41:27.400Z [DEBUG] plugin.terraform-provider-datadog_v2.17.0: Host: api.datadoghq.com
2020-12-08T20:41:27.400Z [DEBUG] plugin.terraform-provider-datadog_v2.17.0: User-Agent: terraform-provider-datadog/2.17.0 (terraform 1.15.0; terraform-cli 0.13.4) datadog-api-client-go/1.0.0-beta.11 (go go1.15.5; os linux; arch amd64)

# ...
2020-12-08T20:41:27.448Z [DEBUG] plugin.terraform-provider-datadog_v2.17.0: 2020/12/08 20:41:27 
2020-12-08T20:41:27.448Z [DEBUG] plugin.terraform-provider-datadog_v2.17.0: HTTP/1.1 404 Not Found
# ...
2020-12-08T20:41:27.449Z [DEBUG] plugin.terraform-provider-datadog_v2.17.0: {"errors":["Downtime not found"]}

```

@therve Could this problem be due to the ID of the downtime resource changing? I noticed when I go into the Datadog UI, the ID of the resource indeed is different (https://app.datadoghq.com/monitors#downtime?id=1062744341).

**Comment by NBParis** [comment]
Hello,

Thanks for your patience on this.
I’m happy to share that the issue has been addressed and recurring downtimes are now properly handled with the new version of the terraform provider ([v3.10 - see updates here](https://github.com/DataDog/terraform-provider-datadog/blob/master/CHANGELOG.md#310-june-17-2021)). 

**You have to update your terraform provider to the version 3.10 to benefit from the fix.** 

You can find [here the PR](https://github.com/DataDog/terraform-provider-datadog/pull/1092) that addresses this issue and which contains a very detailed description about the change made and the remaining caveat that we are still working to improve.

I'll go ahead and resolve this issue but feel free to let us know if you have any question or feedback.

Thanks again for reporting this issue and helping us improve the terraform provider to better manage Downtimes.
