### ISSUE TITLE
datadog_downtime usability issue

### ISSUE THREAD

**Issue by rmoriz** [DataDog/terraform-provider-datadog#430]
### Terraform Version
+ Terraform v0.12.21
+ provider.datadog v2.7.0

### Affected Resource(s)
- datadog_downtime
- datadog_monitor

### Expected Behavior

We had several monitors that had silenced nodes, for example:

```terraform

resource "datadog_monitor" "datadog_agent_up" {
    type         = "service check"
    name         = "datadog.agent.up"
    query        = "\"datadog.agent.up\".over(\"env:_default\").by(\"host\").last(2).count_by_status()"
    message      = "Agent down"
    include_tags = false
    …
    silenced {
      "host:node01.example.com" =  0
      "host:node55.example.com" =  0
      "host:node88.example.com" =  0
      "host:node99.example.com" =  0
    }
}
```

Since `silenced` is deprecated I tried to migrate the code to datadown_downtime with no success:

```terraform

variable "silenced_nodes" {
  default = [
    "node01.example.com",
    "node55.example.com",
    "node88.example.com",
    "node99.example.com"
  ]
}

resource "datadog_monitor" "datadog_agent_up" {
    type         = "service check"
    name         = "datadog.agent.up"
    query        = "\"datadog.agent.up\".over(\"env:_default\").by(\"host\").last(2).count_by_status()"
    message      = "Agent down"
    include_tags = false
…
  # see https://github.com/terraform-providers/terraform-provider-datadog/issues/389
  lifecycle {
    ignore_changes = [silenced]
  }
}

resource "datadog_downtime" "datadog_agent_up" {
  message    = "We don't monitor specific nodes"
  monitor_id = datadog_monitor.datadog_agent_up.id
  scope = [
    for host in concat(
      var.silenced_nodes
    ) :
    "host:${host}"
  ]
  active = true
  start  = 1582890102
}
```

… just to find out that it does not work because, as (only?) described in https://docs.datadoghq.com/api/?lang=bash#schedule-monitor-downtime **_"The resulting downtime applies to sources that matches ALL provided scopes (i.e. env:dev AND env:prod), NOT any of them."_** - https://www.terraform.io/docs/providers/datadog/r/downtime.html does not mention anything!

How should I solve this problem? creating a `downtime_resource` for each node/monitor combination? As far as I know terraform does not support dynamic creation of resources which is a bummer.

**Comment by nmuesch** [comment]
Hey @rmoriz Thanks for the issue report, and apologies for the inconvenience here. Based on your feedback, I've made a PR here - https://github.com/terraform-providers/terraform-provider-datadog/pull/453 - that hopefully helps highlight the `All provided scopes` documentation better going forward. 

That being said, I believe there are a few ways to achieve your use case.
1) You should be able to apply a host level tag to these nodes, for example `monitor:false` and then apply the downtime only over the `monitor:false` `scope`. (https://docs.datadoghq.com/monitors/downtimes/#schedule-downtime)
2) A recent Terraform 0.12.x release introduced support for dynamic resources, so you can create a list of hosts and create one downtime resource per node. More documentation on that here - https://www.terraform.io/docs/configuration/resources.html#for_each-multiple-resource-instances-defined-by-a-map-or-set-of-strings

Would either of those address your use case?

**Comment by rmoriz** [comment]
@nmuesch Thanks for your reply. I don't see these workarounds feasable:
- Using tags clutters everything as we've several monitors to monitor disk space at various levels (think of 80%, 90%, 95%, 99%) - this would require a tremendous number of tags and tag management.

- I was not able to get dynamic resources working

Keep in mind that the existing solution is just a simple `silenced` map and both mentioned workarounds, if made somehow working, introduce further issues regarding complexity and maintanability. I already wasted several hours with this issue :(

**Comment by nuclearnic** [comment]
@nmuesch I hope it's ok to ask here since it is related.

I'd like to understand why `silenced` is being deprecated. We have a use case that is not suited to downtime at all. I'd be happy to describe it if required. What is the correct forum for raising this?

**Comment by colbyshores** [comment]
Your suggestion is extremely convoluted, nor does it fit every use case.  For what?  To save a few calls to the data_dog api?  This is going really irritate your user base who depends on Datadog for monitoring.

**Comment by rmoriz** [comment]
Well, never mind. Closing the issue.

**Comment by colbyshores** [comment]
> 

Sorry it wasn't directed toward you.
