### ISSUE TITLE
datadog_synthetics_test: add retry option

### ISSUE THREAD

**Issue by julianvmodesto** [DataDog/terraform-provider-datadog#440]
The Datadog Synthetics test configuration is missing the `retry` option.

### Terraform Version
0.12.20

### Affected Resource(s)
- datadog_synthetics_test

### References
- https://docs.datadoghq.com/api/?lang=bash#create-a-test

> retry: - optional - dict { count: number (0-3), interval: number (0-1000)} - The number of times (count) and the number of milliseconds (interval) to wait before retrying a test that failed. Default value is {count: 0}.

**Comment by bkabrda** [comment]
Thanks for the feature request. The PR that aims to implement this is at (unmerged for now) https://github.com/terraform-providers/terraform-provider-datadog/pull/425

**Comment by kzap** [comment]
Any update to #425? I am finding that synthetic_test resets the `retry` option to 0 when it makes change to the other options

**Comment by JordanP** [comment]
@gzussa @bkabrda an update on this one ?

**Comment by therve** [comment]
Fixed by #619

**Comment by JordanP** [comment]
Thank you Thomas !

Le jeu. 6 août 2020 à 10:00, Thomas Hervé <notifications@github.com> a
écrit :
