### ISSUE TITLE
[Feature Request] Percentile Aggregations in Metric Metadata

### ISSUE THREAD

**Issue by jcarvalho** [DataDog/terraform-provider-datadog#463]
Hi.

When working with custom Distribution Metrics, I can use the `datadog_metric_metadata` resource to specify basic metadata, such as the Units, which is incredibly useful in an of itself.

However, I would also like to be able to configure the "Percentile Aggregations" for such metrics via Terraform, so I can then reference them in my dashboards to compute percentiles, without having to configure them manually.

This might be tricky, as I haven't found the Datadog API to allow this, so it might also need a Feature Request for Datadog itself.

### Affected Resource(s)
- `datadog_metric_metadata`

**Comment by zen0wu** [comment]
Also the ability to configure tags for distribution metric would be so great!

**Comment by khannajai** [comment]
The Datadog API currently supports configuring tags, metadata, and percentile aggregations for metrics. See [docs](https://docs.datadoghq.com/api/latest/metrics/#create-a-tag-configuration).

**Comment by therve** [comment]
I believe the `datadog_metric_tag_configuration` supports that use case since #960 . Thanks!
