### ISSUE TITLE
start is marked as optional in docs but it seems to be required? (datadog_downtime)

### ISSUE THREAD

**Issue by red8888** [DataDog/terraform-provider-datadog#507]
Terraform v0.12.12
+ provider.datadog v2.7.0

I want to mute a monitor indefinitely so I do this:

```
resource "datadog_downtime" "test" {
  scope = ["*"]
  monitor_id = datadog_monitor.testsdfsdfds.id
  // Mute now and forever
  active = true
}
```

In never comes into state, every time I apply I see this:

```
  ~ resource "datadog_downtime" "test" {
        active     = true
        disabled   = false
        end        = 0
        id         = "123456"
        monitor_id = 212312312
        scope      = [
            "*",
        ]
      - start      = 1588945921 -> null
        timezone   = "UTC"
    }
```

While I can do this, its strange. Requiring ignore of a property as part of normal behaviour I think is poor form, or should I say poor... terra-form HA!
```
  lifecycle {
    ignore_changes = ["start"]
  }
```

I would characterize this as a bug. If active is set with the absence of start, start should just not be checked at all. Maybe Im missing something here

**Comment by bendrucker** [comment]
Hi, this should be a fixable bug. If `start` has a current value and the previous value is `null`, the resource can be considered unchanged. The direct way to accomplish this would be with a [`DiffSuppressFunc`](https://www.terraform.io/docs/extend/schemas/schema-behaviors.html#diffsuppressfunc) for that field.

Why does this behavior need to depend on `active` though?

You can make these changes here, btw, if you're inclined to submit a PR:

https://github.com/terraform-providers/terraform-provider-datadog/blob/master/datadog/resource_datadog_downtime.go
