### ISSUE TITLE
[Feature Request] Support security detection rules

### ISSUE THREAD

**Issue by bendehaan** [DataDog/terraform-provider-datadog#509]
Given the new [security detection rules](https://www.datadoghq.com/blog/announcing-security-monitoring/), I'd very much like to be able to configure this through the Terraform provider as well.

**Comment by jmassey-datadog** [comment]
👋 @bendehaan thanks for the feature request.

We have [documentation](https://docs.datadoghq.com/api/v2/security-monitoring/) on how to manage the Security Detection Rules via API. We have the feature to manage Security Detection Rules via Terraform on our roadmap. We will update this issue, once this feature has been released.
