### ISSUE TITLE
[Feature Request] Support custom_links in timeseries_definition

### ISSUE THREAD

**Issue by maciejqantas** [DataDog/terraform-provider-datadog#557]
It would be good to support Custom Links in widgets that do support it. To my knowledge, at least the timeseries widget supports it.
The API returns 
```
"custom_links":[{"link":"https://example.com","label":"example"}]
```
as a property of the `definition` field.

**Comment by marcohelmerich** [comment]
We are also using custom_links and are missing this feature in the table widget. Would be great to implement it in the provider.
