### ISSUE TITLE
datadog_dashboard note_definition widget parsing error with empty content

### ISSUE THREAD

**Issue by lukeforehand** [DataDog/terraform-provider-datadog#574]
I use an empty note_definition to force lining up my graphs in one column on my "ordered" dashboard.  When I try to create a note_definition with empty "content" (`content = ""`), terraform strips out the `content` field entirely:
```
      + widget {

          + note_definition {}
        }
```

And the plan validates successfully.  However applying the plan breaks:
```
Error: error creating dashboard: json: error calling MarshalJSON for type *datadog.Dashboard: json: error calling MarshalJSON for type datadog.Widget: json: error calling MarshalJSON for type datadog.WidgetDefinition: unexpected end of JSON input

  on dashboard.tf line 19, in resource "datadog_dashboard" "my_dashboard":
  19: resource "datadog_dashboard" "my_dashboard" {
```

My workaround was to set a single space into the content (`content = " "`).

**Comment by therve** [comment]
Thanks for your report. I added a validation function to make sure content is set. Let me know if that works for you.
