### ISSUE TITLE
Change order of logs_pipeline_order apply correctly but exits with an exception 

### ISSUE THREAD

**Issue by emile-jumo** [DataDog/terraform-provider-datadog#593]
### Terraform Version
v0.12.24

### Affected Resource(s)
- logs_pipeline_order

### Terraform Configuration Files
```hcl
resource "datadog_logs_pipeline_order" "pipeline_order" {
  name = "Pipeline Order"
  pipelines = [
    datadog_logs_custom_pipeline.foo1.id,
    datadog_logs_custom_pipeline.foo2.id,
    datadog_logs_custom_pipeline.foo3.id
  ]
}
```

### Debug Output
https://gist.github.com/emile-jumo/1f6e2435379a0034ce745500a1f1ad22

### Expected Behavior
If the order changes:
```hcl
resource "datadog_logs_pipeline_order" "pipeline_order" {
  name = "Pipeline Order"
  pipelines = [
    datadog_logs_custom_pipeline.foo3.id,
    datadog_logs_custom_pipeline.foo2.id,
    datadog_logs_custom_pipeline.foo1.id
  ]
}
```
Then the order is applied successfully without an exception.

### Actual Behavior
Running `terraform apply` changes the order of the log pipelines successfully but exits with the following error:
```
Error: Provider produced inconsistent result after apply

When applying changes to datadog_logs_pipeline_order.pipeline_order, provider
"registry.terraform.io/-/datadog" produced an unexpected new value for was
present, but now absent.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```

### Steps to Reproduce
1. `terraform apply`

**Comment by therve** [comment]
Thanks for your report. What's your provider version? I've tried various combinations, and things seem to work smoothly. Did changes happen in the UI? Even then, it should recover, but I wonder what happened.

**Comment by therve** [comment]
Closing for now, please reopen with more information, thanks.
