### ISSUE TITLE
Is there a Datadog screenboard resource?

### ISSUE THREAD

**Issue by ghost** [DataDog/terraform-provider-datadog#60]
_This issue was originally opened by @munyirik as hashicorp/terraform#17893. It was migrated here as a result of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

I see that there's a timeboard resource available -> https://www.terraform.io/docs/providers/datadog/r/timeboard.html

Is there a "datadog_screenboard" resource that can create/manage screenboards? If not, are there plans to make this available.

**Comment by snemetz** [comment]
This was requested in [Issue #52](https://github.com/terraform-providers/terraform-provider-datadog/issues/52). But I haven't seen anyone working on it
