### ISSUE TITLE
dashboard widget legend_size shows diff permanently

### ISSUE THREAD

**Issue by chroju** [DataDog/terraform-provider-datadog#623]
### Terraform Version

```
❯ terraform -v
Terraform v0.12.24
+ provider.datadog v2.11.0
```

### Affected Resource(s)

- datadog_dashboard

### Terraform Configuration Files
```hcl
resource "datadog_dashboard" "ec2_host_count" {
    is_read_only = false
    layout_type  = "ordered"
    title        = "EC2 host count"

    widget {
        timeseries_definition {
            legend_size = "0"
            show_legend = false
            title       = "EC2 host count"

            request {
                display_type = "line"
                q            = "sum:aws.ec2.host_ok{aws_account_alias:my_aws_account} by {aws_account_alias}"

                style {
                    line_type  = "solid"
                    line_width = "normal"
                    palette    = "dog_classic"
                }
            }

            yaxis {
                include_zero = true
                max          = "auto"
                min          = "auto"
                scale        = "linear"
            }
        }
    }
}
```

### Debug Output

Nothing.

### Panic Output

Nothing.

### Expected Behavior

`widget.timeseries_definition.legend_size` should not be allowed in `orderd` layout type, so `terraform plan` and `apply` should fail by validation.

### Actual Behavior

Not fail. However, since `legend_size` is not set actually, it will be shown as a difference the next time you run `plan`. This difference will never go away.

### Steps to Reproduce

run `apply`, and `plan` .

### Important Factoids

N/A

### References

N/A

**Comment by therve** [comment]
Hello! I don't seem to be able to reproduce your issue, your example doesn't show a diff for me. Not sure why you think `legend_size` is a  `ordered` layout field only? Thanks.

**Comment by chroju** [comment]
Sorry, I was wrong about my provider version. It works fine in the latest provider 2.12. I'm closing this issue. Thanks for your comments.
