### ISSUE TITLE
Please publish provider to terraform registry

### ISSUE THREAD

**Issue by azihsoyn** [DataDog/terraform-provider-datadog#637]
The datadog provider does not seem to be registered in the registry at the moment.

https://registry.terraform.io/browse/providers

### Terraform Version
0.13.0

### Expected Behavior
provider installed

### Actual Behavior
Failed to install providers

### Steps to Reproduce
eps required to reproduce the issue, for example:
1. `terraform init`

### References
https://www.terraform.io/upgrade-guides/0-13.html

**Comment by therve** [comment]
Sorry for the delay. We're aware of this and working on it, it should be available soon.

**Comment by bkabrda** [comment]
FTR, you can still use the pre-registry releases with Terraform 0.13 by adding a following configuration block to your TF config:

```
terraform {
  required_providers {
    datadog = {
      source  = "terraform-providers/datadog"
    }
  }
}
```

**Comment by azihsoyn** [comment]
@bkabrda 
It doesn't work well in my environment.

**Comment by bkabrda** [comment]
@azihsoyn hey 👋 can you please be more specific? What doesn't work well? What errors are you getting?

**Comment by azihsoyn** [comment]
Hi, @bkabrda 

This is all. 

```
$ terraform --version
Terraform v0.13.0
+ provider registry.terraform.io/-/archive v1.3.0
+ provider registry.terraform.io/-/aws v3.2.0
+ provider registry.terraform.io/-/datadog v2.12.1
+ provider registry.terraform.io/-/kubernetes v1.12.0
+ provider registry.terraform.io/-/template v2.1.2
+ provider registry.terraform.io/hashicorp/archive v1.3.0
+ provider registry.terraform.io/hashicorp/aws v2.70.0
+ provider registry.terraform.io/hashicorp/helm v1.2.4
+ provider registry.terraform.io/hashicorp/kubernetes v1.10.0
+ provider registry.terraform.io/hashicorp/template v2.1.2
+ provider registry.terraform.io/terraform-providers/datadog v2.12.1
```

```
terraform {
  required_version = ">= 0.13"
  required_providers {
    archive = {
      source = "hashicorp/archive"
    }
    aws = {
      source = "hashicorp/aws"
    }
    datadog = {
      source = "terraform-providers/datadog"
    }
  }
}
```

```
$ terraform init
Initializing modules...

Initializing the backend...

Initializing provider plugins...
- Using previously-installed -/datadog v2.12.1
- Using previously-installed hashicorp/template v2.1.2
- Using previously-installed hashicorp/kubernetes v1.10.0
- Using previously-installed hashicorp/aws v2.70.0
- Using previously-installed hashicorp/archive v1.3.0
- Using previously-installed -/template v2.1.2
- Using previously-installed -/archive v1.3.0
- Using previously-installed hashicorp/helm v1.2.4
- Using previously-installed terraform-providers/datadog v2.12.1
- terraform.io/builtin/terraform is built in to Terraform
- Using previously-installed -/kubernetes v1.12.0
- Using previously-installed -/aws v3.2.0
- Finding latest version of hashicorp/datadog...


Error: Failed to install providers

Could not find required providers, but found possible alternatives:

  hashicorp/datadog -> terraform-providers/datadog

If these suggestions look correct, upgrade your configuration with the
following command:

The following remote modules must also be upgraded for Terraform 0.13
compatibility:
...
```

**Comment by bkabrda** [comment]
Hmm, this is interesting. It looks like Terraform sees the overriden location (there's a line `- Using previously-installed terraform-providers/datadog v2.12.1`), but it also tries `- Finding latest version of hashicorp/datadog...`. Can you reproduce this if you create just a simple terraform file with just the `terraform.required_providers` configuration that I mentioned? Are you using a complex setup with multiple modules?

**Comment by therve** [comment]
We published the release, sorry for the wait.

**Comment by apryiomka** [comment]
This is till doesn't work:

```
terraform {
  required_providers {
    datadog = {
      source  = "DataDog/datadog"
    }
  }
}
```

output:

```
Error: Failed to install providers

Could not find required providers, but found possible alternatives:

  hashicorp/datadog -> datadog/datadog

```

**Comment by therve** [comment]
@apryiomka Can you open a different bug, possibly with the trace log enabled? This isn't reproducible as-is. Thanks.

**Comment by IrmantasM** [comment]
```bash
- Installing datadog/datadog v2.18.1...
- Installed datadog/datadog v2.18.1 (signed by a HashiCorp partner, key ID FB70BE941301C3EA)
```

Error: Failed to query available provider packages

Could not retrieve the list of available versions for provider
hashicorp/datadog: provider registry registry.terraform.io does not have a
provider named registry.terraform.io/hashicorp/datadog

If you have just upgraded directly from Terraform v0.12 to Terraform v0.14
then please upgrade to Terraform v0.13 first and follow the upgrade guide for
that release, which might help you address this problem.

There is no reference to "hashicorp/datadog"...

**Comment by therve** [comment]
Do you have that bit in your config:

```
terraform {
  required_providers {
    datadog = {
      source  = "DataDog/datadog"
    }
  }
}
```

**Comment by IrmantasM** [comment]
@therve I do:

```bash
    datadog = {
      source  = "DataDog/datadog"
      version = "2.18.1"
    }
```

**Comment by therve** [comment]
Did you just upgrade from 0.12 to 0.14?

**Comment by IrmantasM** [comment]
No, terraform was upgraded a while ago, everything was working fine and still does until I add:

```hcl
resource "datadog_downtime" "turn_off_monitor" {
  count = terraform.workspace == "prod" ? 1 : 0

  scope      = ["*"]
  monitor_id = module.is_notify_sending_sms.id

  timezone = "Europe/Vilnius"
  start    = 1613401200
  end      = 1613444400

  recurrence {
    type   = "days"
    period = 1
  }
}
```

**Comment by cp-jennifer** [comment]
@IrmantasM I had this issue too. I was defining my providers in a file called `providers.tf` and I kept running into that problem until I renamed it to `versions.tf`. The error kept suggesting it was an upgrade issue but I was running it for the first time so it was a little misleading. I ran the upgrade anyways and it renamed my file for me. 

If your configuration is defined in another location than where you're calling it, make sure to have your `versions.tf` file in both locations. This wasn't an issue for me for other providers but I ran into it with the datadog provider. Make sure you don't have old cache lying around too.

**Comment by JordanP** [comment]
@IrmantasM the pb is that your module `is_sending_sms` does not have a `versions.tf` and/or does not have 
```hcl2
datadog = {
      source = "datadog/datadog"
    }
```
somewhere

**Comment by EvanBrianGarcia** [comment]
@therve This isn't working for me either. It looks like Terraform is looking for the provider at: registry.terraform.io/hashicorp/datadog but the provider is actually located at registry.terraform.io/providers/DataDog/datadog

```
Error: Failed to query available provider packages
│ 
│ Could not retrieve the list of available versions for provider
│ hashicorp/datadog: provider registry registry.terraform.io does not have a
│ provider named registry.terraform.io/hashicorp/datadog
```

**Comment by robmosca-travelperk** [comment]
Same problem here:
╷
│ Error: Failed to query available provider packages
│
│ Could not retrieve the list of available versions for provider
│ hashicorp/datadog: provider registry registry.terraform.io does not have a
│ provider named registry.terraform.io/hashicorp/datadog
│
│ Did you intend to use datadog/datadog? If so, you must specify that source
│ address in each module which requires that provider. To see which modules
│ are currently depending on hashicorp/datadog, run the following command:
│     terraform providers

**Comment by jtreguboff** [comment]
Same problem here:

│ Could not retrieve the list of available versions for provider hashicorp/datadog: provider registry registry.terraform.io does not have a provider named
│ registry.terraform.io/hashicorp/datadog
│ 
│ Did you intend to use datadog/datadog? If so, you must specify that source address in each module which requires that provider. To see which modules are currently
│ depending on hashicorp/datadog, run the following command:
│     terraform providers

**Comment by Marwen94** [comment]
Same behaviour here with the following config block : 

`terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 4.26.0"
    }
    datadog = {
      source = "datadog/datadog"
    }
  }

  backend "s3" {
    bucket         = "xxxxx"
    key            = "xxxxx"
    dynamodb_table = "xxxxx"
    region         = "xxxxx"
  }
  required_version = ">= 1.0"
}`



`│ Error: Failed to query available provider packages
│ 
│ Could not retrieve the list of available versions for provider hashicorp/datadog: provider registry registry.terraform.io does not have a provider named
│ registry.terraform.io/hashicorp/datadog
│ 
│ Did you intend to use datadog/datadog? If so, you must specify that source address in each module which requires that provider. To see which modules are currently
│ depending on hashicorp/datadog, run the following command:
│     terraform providers
`

**Comment by JordanP** [comment]
Delete your local `.terraform` directory and run `terraform init -upgrade` again maybe

**Comment by Marwen94** [comment]
@JordanP this did not resolve the issue either unfortunately.
