### ISSUE TITLE
Credentials validation should not validate when disabled

### ISSUE THREAD

**Issue by jurajseffer** [DataDog/terraform-provider-datadog#640]
### Terraform Version
Terraform v0.12.24
Datadog 2.7.0

### Affected Resource(s)
- datadog provider

### Terraform Configuration Files
```hcl
data aws_secretsmanager_secret_version api {
  secret_id = "dd-api"
}

data aws_secretsmanager_secret_version app {
  secret_id = "dd-app"
}

provider datadog {
  api_key = data.aws_secretsmanager_secret_version.api.secret_string
  app_key = data.aws_secretsmanager_secret_version.app.secret_string
}

...
```

### Expected Behavior
Terraform destroys all resources cleanly.

### Actual Behavior
Terraform throws an error that Datadog credentials are not set. Presumably because the data resource has been destroyed at that point. Setting `validate = false` has the strange requirement of having to unset all sources of credentials (including environment variables) - this makes the provider very difficult to work with when using data sources.

I think the `validate = false` should not validate that credentials are unset, it should ignore all credentials, set or not. That's what I would expect validation which is turned off to do, instead it actually does validate that I have unset the credentials as per https://github.com/DataDog/terraform-provider-datadog/pull/474#issuecomment-621579334

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan -destroy -out plan`
1. `terraform apply plan`

### References
- https://github.com/DataDog/terraform-provider-datadog/pull/474

**Comment by therve** [comment]
Thanks, should be fixed with next release!
