### ISSUE TITLE
[Feature Request] expose a dashboard_list data source

### ISSUE THREAD

**Issue by Tony-Proum** [DataDog/terraform-provider-datadog#651]
### Feature request

It could be a good thing to create a data source around : `datadog_dashboard_list`. 
I have a parent project that is responsible to manage the dashboard_list. Also, multiple terraform workspace are refering to different sub part of this parent project. it would be great to store all dashboards of those sub parts in the same dashboard list.
In order to be able to automate component dashboard registration, we thought that the better way to handle it is that each component have to register itself to the dashboard_list

### Current workaround

For now the only way I found to register each dashboard in the same list is to import the `datadog_dashboard_list` resource in each sub projects. Note that because each of those project uses it's own terraform workspace, if I have to modify the dashboard_list, I have to modify it in all of these workspaces in order to keep a consistency between each terraform states.
If this consistency is not assured, a terraform apply in a subproject will potentially remove a dashboard for another component from the dashboard_list.

**Comment by therve** [comment]
Hi!

I'm not exactly sure what you mean. A data source is by nature read-only, so I don't see how it would help you add a dashboard to a list. Unless you

I think the approach that could work is the one described at #379 : a new attribute of dashboards to add them to a dashboard list. What do you think?

**Comment by Tony-Proum** [comment]
totally agree, my request missed this point ! Getting a data source for the dashboard list may help to find the list e.g: by name and use it's ID to add to the datadog_dashboard resource (but agree that I missed a big part of the problem :laughing:)
