### ISSUE TITLE
Feature request: Support for raw JSON dashboards

### ISSUE THREAD

**Issue by ebbeelsborg-unity** [DataDog/terraform-provider-datadog#652]
I'd like to request support for providing DataDog dashboards as raw JSON to Terraform just like the google provider allows for. Please see https://www.terraform.io/docs/providers/google/r/monitoring_dashboard.html#example-usage-monitoring-dashboard-basic.

It looks like this:

```
resource "google_monitoring_dashboard" "dashboard" {
  dashboard_json = <<EOF
{
  "displayName": "Demo Dashboard",
  "gridLayout": {
    "widgets": [
      {
        "blank": {}
      }
    ]
  }
}

EOF
}
```

So, the magic happens due to the dashboard_json field. For DataDog dashboards I seem to need to write my own transformation from exported JSON to HCL since even `jsondecode` doesn't produce valid HCL due to things like JSON arrays and widget type names.

The logic is here: https://github.com/hashicorp/terraform-provider-google/blob/master/google/resource_monitoring_dashboard.go.

I use the 2.12.1 datadog provider.

### Terraform Version

v0.12.16. But this is a provider issue that is unaffected by the Terraform version, I believe.

### Affected Resource(s)

- datadog_dashboard

**Comment by therve** [comment]
That's an interesting approach, but I'm not sure the experience is amazing. It works for the initial import, but then any change will be completely obfuscated.

I'm more interested by pushing something like https://github.com/juliogreff/datadog-to-terraform, what do you think?

**Comment by ebbeelsborg-unity** [comment]
Well, what exactly do you mean by "any change will be completely obfuscated"?

I can live with a tool that transforms exported DD dashboard JSON to HCL that can then be committed. However, I would want DataDog to maintain it to ensure it’ll be kept in lockstep with the provider and with long-term support. Also, I'm not so keen on providing DD keys.

**Comment by therve** [comment]
I mean that if you change one field of a widget for example, the terraform plan will show an update for whole json, without an easy way to inspect the exact changes.

We're looking into supporting that tool (or another) officially. Regarding providing keys, it's simply making API calls, but we could change to take JSON export as an input directly.

**Comment by ebbeelsborg-unity** [comment]
Thanks for being so forthcoming.

Reg. TF diff obfuscation: Yes, that's what I thought you meant and although it is a downside, it is one that I can live with as a tradeoff for a painless update-flow.

Reg. keys: Yes, this is solvable.

Ideally, I could simply export to JSON from DataDog, pipe it into/run that through a tool that produces .tf or .tf.json, and then commit that in Terraform and let it do its thing.

I assume the scope would be all datadog-provider-supported resources.

If the API changes often enough, then it might even make sense to codegen the structs from a spec as well as the operations on them given some map from DataDog concepts to Terraform ones.

**Comment by mlindes** [comment]
You should consider using [Google's Terraformer tool](https://github.com/GoogleCloudPlatform/terraformer) to export Datadog dashboards to the [datadog_dashboard resource](https://www.terraform.io/docs/providers/datadog/r/dashboard.html) provided by the [datadog provider](https://www.terraform.io/docs/providers/datadog/index.html)

**Comment by skarimo** [comment]
We introduced the dashboard json resource with the following PR: https://github.com/DataDog/terraform-provider-datadog/pull/950

Going to close this issue but feel free to follow up if you any further questions/feedback!
