### ISSUE TITLE
EOF error when creating new datadog monitor(s)

### ISSUE THREAD

**Issue by mattw80** [DataDog/terraform-provider-datadog#653]
Terraform 0.12.25
Datadog provider 2.12.1

I have defined lots of datadog monitors in terraform and almost all of them create OK, but two keep failing with the error below. Most of the definitions use re-usable modules so there is no real difference between the ones that work and the ones that don't, as far as I can see.

Please let me know any further info you need.

Error: error creating monitor (url.Error): Post "https://api.datadoghq.com/api/v1/monitor": EOF

  on .terraform/modules/backend_monitors/datadog/monitors/private/wcol_monitor/wcol_monitor.tf line 34, in resource "datadog_monitor" "wcol_monitor":
  34: resource "datadog_monitor" "wcol_monitor" {

**Comment by therve** [comment]
Hi,

Can you provide more details? Can you share the monitors that you have, or extract them in a separate file to see if they work in isolation? A log file in trace level would great too. Thanks.

**Comment by mattw80** [comment]
I've isolated one of the failing monitors and still having issues. There is a fairly complicated nesting of modules but I will try and show how it is configured:

Top level:
module "frontend_monitors" {
  # specify module location and version
  source              = "../../../../../../../sre-terraform-modules/datadog/monitors/frontend"

  # module variables
  sub_environment     = "ppe03"
  regions             = [ "ap-southeast-1" ]
}

'frontend' Module:
locals {
  server = "frontend"
}

# set of monitors common to all server types
module "frontend_common_monitor" {
  source = "../private/common"
  server = local.server
  regions = var.regions
  sub_environment = var.sub_environment
}

'common' Module:
module "common_monitor" {
  source      = "../wcol_monitor"
  server      = var.server
  regions     = var.regions
  sub_environment = var.sub_environment
  metrics = [
    { key = "refinitiv.ntp_time",
      name = "Time",
      notifications = [] }
  ]
}

'wcol_monitor' Module:
locals {
  # format: (1.metric key)(2.server)(3.env)(4.region)
  query               = "max(last_5m):%s{autoscaling-group:a205470-wcol-%s-%s-asg,region:%s} by {host} >= 2"
  webhook_compass     = "@webhook-CAM_PPE"
  include_tags        = true
  type                = "metric alert"
  require_full_window = false
  thresholds          = {
    critical = 2
    warning = 1
  }

  # determine all combinations of region and metric, i.e. each metric in each region
  all_combos = [
    for pair in setproduct(var.regions, var.metrics) : {
      region = pair[0]
      metric = pair[1]
    }
  ]

  # create a map that gives each combination of region and metric a unique name
  # this ensures that the terraform resource name is fixed and not based on a list index
  named_combos = {
    for pair in local.all_combos:
      "${pair.region}:${pair.metric.key}" => {
        r = pair.region
        m = pair.metric
      }
  }

}

# datadog monitor for each combination of metric and region
resource "datadog_monitor" "wcol_monitor" {
  for_each            = local.named_combos
  name                = "${title(var.server)}: ${each.value.m.name}"
	type                = local.type
  require_full_window = local.require_full_window
	query               = format(local.query, each.value.m.key, var.server, var.sub_environment, each.value.r)
  message             = join(" ", concat([local.webhook_compass], each.value.m.notifications))
	tags                = [ "environment:${var.sub_environment}" ]
  include_tags        = local.include_tags
	thresholds          = local.thresholds
}

**Comment by therve** [comment]
Trying your example seems to work for me. I'd really need to have the tf logs to debug further. Feel free to contact support it you can't share it here. Thanks.

**Comment by mattw80** [comment]
thanks - I can provide logs separately. How do I contact support?

**Comment by mattw80** [comment]
Thank you, I have just emailed a log extract to the support email address

**Comment by mattw80** [comment]
Request #393183

**Comment by josev94** [comment]
What was the resolution on this issue?
