### ISSUE TITLE
datadog_logs_integration_pipeline naming issue

### ISSUE THREAD

**Issue by jonnymccullagh** [DataDog/terraform-provider-datadog#655]
Hi
### Terraform Version
Terraform v0.13.2

### Affected Resource(s)

- datadog_logs_integration_pipeline

### Terraform Configuration Files

```hcl
resource "datadog_logs_integration_pipeline" "AWS ELB Access" {
    is_enabled = true
}

resource "datadog_logs_integration_pipeline" "RabbitMQ" {
    is_enabled = true
}

resource "datadog_logs_integration_pipeline" "Cisco Meraki" {
    is_enabled = true
}

```

### Expected Behavior

I would expect to configure this resource type with a name parameter that is used by datadog but specifying my own name for the resource e.g.

```hcl

resource "datadog_logs_integration_pipeline" "cisco_meraki" {
    name = "Cisco Meraki"
    is_enabled = true
}

```
### Actual Behavior

Error: Invalid resource name 
A name must start with a letter or underscore and may contain only letters,
digits, underscores, and dashes.

### Steps to Reproduce

1. `terraform validate`

**Comment by therve** [comment]
Thanks for your report. The resource name you mention is internal to Terraform, it doesn't influence the name of the pipeline in Datadog. Because integrations pipeline can't be created, there is no name to set, you need to set it when you create it in the UI.

I guess what you want is change the name of an existing pipeline? We could add support for the attribute.

**Comment by jonnymccullagh** [comment]
Ah, am I understanding you correctly? that if I define a terraform resource: 
```
resource "datadog_logs_integration_pipeline" "cisco_meraki" {
    is_enabled = true
}
```
It doesn't actually enable a pipeline.
If it still requires a UI interaction then I am probably better off not having this in terraform.

**Comment by therve** [comment]
No unfortunately for integration pipeliines you need to create them in the UI, and then import them in terraform. Terraform mostly allows you to enable/disable them.

**Comment by jonnymccullagh** [comment]
Thanks for the clarification @therve. I'll close this issue. Cheers.

**Comment by flavioelawi** [comment]
This makes pipeline management with terraform impractical within a CI/CD pipeline
