### ISSUE TITLE
Terraform crash while using Datadog provider

### ISSUE THREAD

**Issue by samirmehmedbasic** [DataDog/terraform-provider-datadog#656]
Hi,

couple of days ago I started getting errors while using Datadog provider to build a dashboard. It worked beginning last week but by Thursday/Friday I started experiencing issues. As first steps I tried upgrading Terraform, upgrading Datadog provider and generally rechecked the plan file but nothing helps. Let me know if you need any additional information.

### Terraform Version

```
Terraform v0.13.1
+ provider registry.terraform.io/terraform-providers/datadog v2.12.1
```

### Affected Resource

- datadog_dashboard

### Panic Output

https://gist.github.com/samirmehmedbasic/c9b50b4e0a2f916c6d1c110ee6b159d1

### Expected Behavior

Terraform should say that there are no changes.

### Actual Behavior

Terraform crashes.

### Steps to Reproduce

`terraform plan`

### References

https://github.com/hashicorp/terraform/issues/26012

**Comment by therve** [comment]
Thanks for your report. This should be fixed by #630 . Sorry for the inconvenience.
