### ISSUE TITLE
Address filed error while creating new datadog monitor

### ISSUE THREAD

**Issue by hemantpro** [DataDog/terraform-provider-datadog#658]
Hi there,

Trying to setup Gitlab CI on Terraform to create datadog monitors and always getting this error:

Error: "address": required field is not set
No clue where this field is required,  when I enable TRACE, I see details as below which don't give much insight unfortunately.

 TF_LOG=TRACE terraform apply -auto-approve
382020/09/14 11:47:07 [INFO] Terraform version: 0.13.2  
392020/09/14 11:47:07 [INFO] Go runtime version: go1.14.7
402020/09/14 11:47:07 [INFO] CLI args: []string{"/bin/terraform", "apply", "-auto-approve"}
412020/09/14 11:47:07 [DEBUG] Attempting to open CLI config file: /root/.terraformrc
422020/09/14 11:47:07 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
432020/09/14 11:47:07 [DEBUG] ignoring non-existing provider search directory terraform.d/plugins
442020/09/14 11:47:07 [DEBUG] ignoring non-existing provider search directory /root/.terraform.d/plugins
452020/09/14 11:47:07 [DEBUG] ignoring non-existing provider search directory /root/.local/share/terraform/plugins
462020/09/14 11:47:07 [DEBUG] ignoring non-existing provider search directory /usr/local/share/terraform/plugins
472020/09/14 11:47:07 [DEBUG] ignoring non-existing provider search directory /usr/share/terraform/plugins
482020/09/14 11:47:07 [INFO] CLI command args: []string{"apply", "-auto-approve"}
492020/09/14 11:47:07 [TRACE] Meta.Backend: built configuration for "http" backend with hash value 425699464
502020/09/14 11:47:07 [TRACE] Preserving existing state lineage "575ba0b6-c2cd-91c6-ad1b-cf58e9e0cbef"
512020/09/14 11:47:07 [TRACE] Preserving existing state lineage "575ba0b6-c2cd-91c6-ad1b-cf58e9e0cbef"
522020/09/14 11:47:07 [TRACE] Meta.Backend: working directory was previously initialized for "http" backend
532020/09/14 11:47:07 [TRACE] Meta.Backend: using already-initialized, unchanged "http" backend configuration
54Error: "address": required field is not set
55ERROR: Job failed: exit code 1

**Comment by therve** [comment]
Looks like an issue with the http backend: https://www.terraform.io/docs/backends/types/http.html ? Can you provide your terraform files? Thanks.

**Comment by hemantpro** [comment]
Thanks @therve 
my backend file looks like as below:

terraform {
  backend "http" {
  }
}
and format of it what I referred from GitLab document:
https://docs.gitlab.com/ee/user/infrastructure/

**Comment by therve** [comment]
It looks like the address ought to be set later on with the init call mentioned on that doc. Maybe try to set it directly in your provider config. Regardless, it's not related to the Datadog provider. Thanks.

**Comment by hemantpro** [comment]
thanks, will give it a try 👍
