### ISSUE TITLE
terraform plan crashes with SIGSEGV

### ISSUE THREAD

**Issue by 7oas7er** [DataDog/terraform-provider-datadog#659]
Hi there,

After working with terraform cloud and the terraform-provider-dadatog successfully my terraform plan steps suddenly fail with low level errors. I recreated the environment locally to be able to get the whole output as provided in the linked gist.

### Terraform Version

7oas7er@Franks-MacBook-Pro datadog % terraform -v
2020/09/14 15:54:33 [WARN] Log levels other than TRACE are currently unreliable, and are supported only for backward compatibility.
  Use TF_LOG=TRACE to see Terraform's internal logs.
  ----
2020/09/14 15:54:33 [INFO] Terraform version: 0.13.2
2020/09/14 15:54:33 [INFO] Go runtime version: go1.14.7
2020/09/14 15:54:33 [INFO] CLI args: []string{"/usr/local/bin/terraform", "-v"}
2020/09/14 15:54:33 [DEBUG] Attempting to open CLI config file: /Users/7oas7er/.terraformrc
2020/09/14 15:54:33 Loading CLI configuration from /Users/7oas7er/.terraformrc
2020/09/14 15:54:33 [DEBUG] ignoring non-existing provider search directory terraform.d/plugins
2020/09/14 15:54:33 [DEBUG] ignoring non-existing provider search directory /Users/7oas7er/.terraform.d/plugins
2020/09/14 15:54:33 [DEBUG] ignoring non-existing provider search directory /Users/7oas7er/Library/Application Support/io.terraform/plugins
2020/09/14 15:54:33 [DEBUG] ignoring non-existing provider search directory /Library/Application Support/io.terraform/plugins
2020/09/14 15:54:33 [INFO] Checkpoint disabled. Not running.
2020/09/14 15:54:33 [INFO] CLI command args: []string{"version", "-v"}
Terraform v0.13.2
+ provider registry.terraform.io/-/datadog v2.12.1
+ provider registry.terraform.io/terraform-providers/datadog v2.12.1

### Affected Resource(s)

Please list the resources as a list, for example:

all kinds of datadog_monitor, datadog_dashboard and yes I believe it is not module specific, but rather a core issue.

### Debug Output

https://gist.github.com/7oas7er/93c5c52269b278232f01237b9edea59d

### Expected Behavior

Plan step should work as expected.

### Actual Behavior

Plan step fails with SIGSEGV error. 

### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:

1. `terraform plan`

**Comment by therve** [comment]
Thanks for your report. This should be fixed by #630 . Sorry for the inconvenience.
