### ISSUE TITLE
[Feature Request] Support all options exposed by datadog_integration_pagerduty before it's removal

### ISSUE THREAD

**Issue by cooperbenson-qz** [DataDog/terraform-provider-datadog#665]
### Terraform Version

```
Terraform v0.13.2
+ provider registry.terraform.io/terraform-providers/datadog v2.13.0
+ provider registry.terraform.io/terraform-providers/pagerduty v1.7.10
```

### Affected Resource(s)

- `datadog_integration_pagerduty`

### Terraform Configuration Files

```hcl
resource "datadog_integration_pagerduty" "integration" {
  subdomain           = var.pagerduty_subdomain
  individual_services = true
  api_token           = var.pagerduty_token
  schedules = [
    for schedule_id in var.schedule_ids :
    "https://${var.pagerduty_subdomain}.pagerduty.com/schedules/${schedule_id}"
  ]
}
```

### Issue
The configuration above is producing a warning: 
```
Warning: This resource is deprecated. You can use datadog_integration_pagerduty_service_object resources directly once the integration is activated

  on ../../modules/pagerduty_datadog_integration/main.tf line 14, in resource "datadog_integration_pagerduty" "integration":
  14: resource "datadog_integration_pagerduty" "integration" {
```

This is somewhat worrying since `datadog_integration_pagerduty_service_object` does not provide the ability to configure Pagerduty schedules which is something we rely upon. I understand the reasons for the deprecation, but this warning is unfixable for us because we rely on functionality that is only exposed by the deprecated resource. Would it make sense to add another resource like `datadog_integration_pagerduty_schedule` to configure the schedule mapping?

### References
- The decision to deprecate the resource was made as a result of #564
- Pull Request for the deprecation #584

**Comment by JordanP** [comment]
Hey, I am also using the `schedules` attribute of the `datadog_integration_pagerduty` resource. What's the new way of doing that ?

**Comment by therve** [comment]
Hello,

Sorry for not answering earlier. I talked to the pagerduty integration team, and the current approach using webhooks should only require configuring service objects. Schedules are a pagerduty resource, so should be configured in pagerduty itself.

Can you confirm that it would work for you? Thanks.

**Comment by cooperbenson-qz** [comment]
My understanding is that the schedules are provided to Datadog to show who's on call in the event stream

> Show who is on-call in your event stream: If you would like to view your PagerDuty on-call schedules in your Datadog event stream, you will need to retrieve the PagerDuty schedule URL. In PagerDuty, navigate to the Configuration menu and select Schedules, then click your desired schedule and copy its URL, which should look like this: https://YOURSUBDOMAIN.pagerduty.com/schedules#PXXXXXX. In Datadog, paste this into the Schedule URL field.
From [Pagerduty's documentation](https://www.pagerduty.com/docs/guides/datadog-integration-guide/)

**Comment by therve** [comment]
Hi,

This was an oversight apparently. We need a new API to manage schedules, in the mean time we'll undeprecate the resource. Thanks for your patience.
