### ISSUE TITLE
[v2.13.0] Scope keys applied to mute monitor must match monitor group keys

### ISSUE THREAD

**Issue by AmetDevops** [DataDog/terraform-provider-datadog#669]
Hi there,

After updating tf provider from 2.12.0 to 2.13.0 `terraform plan` fails for monitors that have downtimes assigned on the monitor.

### Terraform Version

`Terraform v0.12.16`

### Affected Resource(s)

- `datadog_monitor`

### Terraform Configuration Files

```hcl
resource "datadog_monitor" "shiny_alert" {
  name         = "shiny doesn't work"
  type         = "query alert"
  query        = "sum(last_1h):avg:network.http.can_connect{host:shiny} <= 0"
  message      = "Looks like shiny doesn't work properly"
  tags         = []
  notify_audit = "false"
  locked       = "false"
  timeout_h    = "0"

  lifecycle {
    ignore_changes = [silenced]
  }

  include_tags        = "true"
  no_data_timeframe   = "150"
  require_full_window = "false"
  new_host_delay      = "300"
  notify_no_data      = "true"
  renotify_interval   = "0"

  thresholds = {
    critical = "0"
  }
}
```

### Expected Behavior

Correct plan.

### Actual Behavior

```
------------------------------------------------------------------------

Error: error validating monitor: 400 Bad Request: {"errors":["Scope keys applied to mute monitor must match monitor group keys"]}

  on monitor.tf line 5337, in resource "datadog_monitor" "shiny_alert":
5337: resource "datadog_monitor" "shiny_alert" {
```

### Steps to Reproduce

1. Create a monitor in terraform
<img width="1450" alt="Screenshot 2020-09-17 at 15 23 10" src="https://user-images.githubusercontent.com/39903467/93469974-e8881900-f8f9-11ea-97cb-43925550dbcb.png">

2. Create a downtime (manually, not via terraform) for it
<img width="805" alt="Screenshot 2020-09-17 at 15 22 57" src="https://user-images.githubusercontent.com/39903467/93469993-ede56380-f8f9-11ea-996f-c2845fc754df.png">

3. Update tf provider to 2.13.0
4. Run `terraform plan`

**Comment by therve** [comment]
Hi,

Thanks for the detailed report. To work around the issue for now, you can set `validate = false` in your resource. This should skip the validation step. I'll check if it makes sense for this error to be raised.

**Comment by therve** [comment]
Note: any update to the monitor will fail the same way, so validation seems to do its job here. The question is if the error is legit.

**Comment by AmetPreply** [comment]
Thanks for the workaround, it works.

**Comment by martinb3** [comment]
It seems that the state now contains information about silenced monitors, and those timestamps fail monitor validation when doing a plan (because they're timestamps in the past).
