### ISSUE TITLE
FeatureRequest - Support access_key_id and secret_access_key in datadog_integration_aws

### ISSUE THREAD

**Issue by shannonrdunn** [DataDog/terraform-provider-datadog#670]
Would like to ability to add aws govcloud integrations via terraform however datadog only support aws access keys in these integrations, not role based.
Datadog API supports this, can we add this to the datadog provider as well?

https://docs.datadoghq.com/api/v1/aws-integration/

### Affected Resource(s)

Please list the resources as a list, for example:

- datadog_integration_aws

**Comment by JacobWeyer** [comment]
Would also like to bump this one a bit, would greatly help management of our org via TF

**Comment by MrMickS** [comment]
We have a similar requirement, but for AWS China, rather than govcloud. The principle is the same though. We would like the integration call to take either the existing role OR an access_key, secret_key pairing.

**Comment by skarimo** [comment]
Closed by: https://github.com/DataDog/terraform-provider-datadog/pull/1101.

Changes should be included in the next release, thanks.
