### ISSUE TITLE
a question: do we need api_key & app_key in the provider, as app_key is tied to a user rather than an org

### ISSUE THREAD

**Issue by anirban1c-maersk** [DataDog/terraform-provider-datadog#692]
Hi there,

do we need both api_key & app_key in the provider, as app_key is tied to a user rather than an org
a concern was raised for any user leaving the organisation, the app key would be deleted.

is there a way to not tie all the keys to a user ?

### Terraform Version

0.12

### Affected Resource(s)

Please list the resources as a list, for example:

"provider": {
    "datadog": {
      "api_key": "",
      "app_key": "",
      "validate": false
    }
}

**Comment by therve** [comment]
Yes an APP key is required to access the programmatic API. https://docs.datadoghq.com/account_management/api-app-keys/#transferring-apiapplication-keys covers some of those aspects, let us know if that works for you. Thanks.

**Comment by anirban1c-maersk** [comment]
thanks a lot @therve for the prompt reply, better to go with a service a/c
