### ISSUE TITLE
Widget layout not updating on plan or apply following initial terraform init

### ISSUE THREAD

**Issue by stevemossovo** [DataDog/terraform-provider-datadog#695]
### Terraform Version

```bash
$ terraform -v
Terraform v0.12.29
+ provider.datadog v2.13.0

Your version of Terraform is out of date! The latest version
is 0.13.4. You can update by downloading from https://www.terraform.io/downloads.html
```

### Affected Resource(s)

- datadog_dashboard

### Terraform Configuration Files

```hcl
  // info widget
  widget {
    layout = {
      "height" = "7"
      "width"  = "32"
      "x"      = "96"
      "y"      = "5"
    }

    note_definition {
      background_color = "gray"
      content          = <<EOT
**Dashboard last deployed**: ${formatdate("DD-MMM-YYYY hh:mm", timestamp())}
**Documentation:** [Reporting on SLOs](https://foo.bar.com/a/b/cd1eFg2h)
EOT
      font_size        = "14"
      show_tick        = false
      text_align       = "left"
      tick_edge        = "left"
      tick_pos         = "50%"
    }
  }
```

### Debug Output

If you need debug output I can provide access to a private Gist, however I'll need to redact any API/APP keys etc. first.

### Panic Output

N/a

### Expected Behavior

The `terraform plan` and `terraform apply` pick up the changes in the widget layout every time.

### Actual Behavior

The widget layout isn't recognised/updated when running `terraform plan` or `terraform apply` after making a change subsequent to an inital change. I need to `rm -rf ./terraform` and run `terraform init` on every change.

### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:

1. Make a change to the widget layout in the .tf file.
2. Generate dynamic terraform json file using terrascript.
3. `terraform init`
4. `terraform plan`
5. `terraform apply`
6. Update widget layout in the .tf file.
7. Generate dynamic terraform json file using terrascript.
8. `terraform plan`
9. `terraform apply`

I need to do an `rm -rf .terraform/` and run through steps 1 to 5 above each time I make a change for it to pick up the new layout. 

### Important Factoids

N/a

### References

N/a

**Comment by nmuesch** [comment]
Hey @stevemossovo thanks for the issue report. Using the provided config I wasn't able to reproduce the issue with terraform 0.12.29 (or 0.13.4)
Applying that config, then modifying the `height` param in the widget layout made the next `apply` show the change in the diff. 

Do you have a full terraform dashboard config that reproduces the issue you could share?

**Comment by stevemossovo** [comment]
Hi, @nmuesch, thanks for getting back to me 😄 

So, just regarding our setup. We have a module that we use to build multiple dashboards with different configurations. We build the main team dashboards configuration dynamically in Terraform's JSON format using Python's terrascript library by parsing a file with the information for each team. The JSON looks like the following:

```
{
  "module": {
    "team1_staging": {
      "source": "/Users/stevemoss/projects/datadog_dashboards/datadog_as_code/modules/team_dd",
      "team_name": "Team One",
      "team_tag": "team-one",
      "mandatory_tags": "*",
      "team_7_day_slo_map": {},
      "team_30_day_slo_map": {},
      "team_90_day_slo_map": {},
      "production": false
    },
    "team2_staging": {
      "source": "/Users/stevemoss/projects/datadog_dashboards/datadog_as_code/modules/team_dd",
      "team_name": "Team Two",
      "team_tag": "team-two",
      "mandatory_tags": "*",
      "team_7_day_slo_map": {},
      "team_30_day_slo_map": {},
      "team_90_day_slo_map": {},
      "production": false
    },
  }
}
```

The `team_dd` terraform module `dashboard.tf` file then looks something like the following:
```
resource "datadog_dashboard" "team_dashboard" {
  is_read_only = false
  layout_type  = "free"
  notify_list  = []
  title        = "${var.production ? "" : "[Staging] "}${var.team_name} SLO Dashboard"

  // Show the team name on the dashboard
  widget {
    layout = {
      "height" = "3"
      "width"  = "40"
      "x"      = "0"
      "y"      = "0"
    }

    free_text_definition {
      color      = "#4d4d4d"
      font_size  = "36"
      text       = "Team: ${var.team_name}"
      text_align = "left"
    }
  }
}
```

Making a change to the layout works fine on the first attempt as detailed above, but any subsequent changes fail to be picked up and I need to `rm -rf .terraform` and `terraform init` to get it to pick them up again 🤷

I think it might be an issue with the `Initializing modules...` step in Terraform when doing a `terraform init` whereby the modules don't get initialised again unless you blat the `.terraform` directory first? I've also figured out you can do a `terraform init -upgrade` to achieve the same.

If I look at `.terraform/modules/team1_staging/dashboard.tf` it contains a copy of the `team_dd` files with the outdated `layout` values. This isn't updated with the changes from `../modules/team_dd/dashboard.tf` unless I do the above. Is this perhaps a terraform bug, as opposed to a bug with your provider? Or is this expected behaviour with modules, i.e. I should be doing a `terraform init -upgrade` every time because of the way we have things configured?

**Comment by nmuesch** [comment]
Thanks for the explanation and context, I haven't used terrascript before, so that was helpful!

I'm just restating here to clarify my understanding, but the idea here is that you use python code to dynamically generate a dashboard JSON based on some variables like team_name, team_tag, etc, and write that to a `.tf.json` file. 

From there the terraform plan and apply work against the json configurations - https://www.terraform.io/docs/configuration/syntax-json.html to perform the create/read/update operations. 

Could you confirm a few points here:
1) When you make the change to `layout` in the `team_dd` module, can you confirm that the newly generated `.tf.json` file contains the modified layout for that widget? If possible, could you also share the `.tf.json` example that gets generated here (please redact any potentially sensitive info 🙂) so I could try that locally?
2) If I can't reproduce the issue with the provided JSON, it may be helpful to get a `TF_LOG=trace` set of logs from the `terraform apply` to further debug.

**Comment by stevemossovo** [comment]
> 1. When you make the change to `layout` in the `team_dd` module, can you confirm that the newly generated `.tf.json` file contains the modified layout for that widget? If possible, could you also share the `.tf.json` example that gets generated here (please redact any potentially sensitive info 🙂) so I could try that locally?

No, it doesn't. It just generates the `.tf.json` as a set of modules as listed above, which references the `team_dd` source module, e.g.:
```
{
  "module": {
    "team1_staging": {
      "source": "/Users/stevemoss/projects/datadog_dashboards/datadog_as_code/modules/team_dd",
      "team_name": "Team One",
      "team_tag": "team-one",
      "mandatory_tags": "*",
      "team_7_day_slo_map": {},
      "team_30_day_slo_map": {},
      "team_90_day_slo_map": {},
      "production": false
    },
    "team2_staging": {
      "source": "/Users/stevemoss/projects/datadog_dashboards/datadog_as_code/modules/team_dd",
      "team_name": "Team Two",
      "team_tag": "team-two",
      "mandatory_tags": "*",
      "team_7_day_slo_map": {},
      "team_30_day_slo_map": {},
      "team_90_day_slo_map": {},
      "production": false
    },
  }
}
```

> 2. If I can't reproduce the issue with the provided JSON, it may be helpful to get a `TF_LOG=trace` set of logs from the `terraform apply` to further debug.

Happy to provide any additional logs if necessary, but I'm beginning to think that with the way we have things setup, it is necessary for us to run `terraform get -update` to update the modules with the updated layout for the widget every time we update the source module. I should have expected this to have occurred as part of the `terraform plan`, but perhaps this is a limitation in how terraform works? I'm not convinced now that this is an issue with the DataDog provider. What do you think?

**Comment by nmuesch** [comment]
Ahh, thanks for clarifying. Based on your descriptions, it looks like its related to when the `team_dd` module source gets loaded. I found what looks to be a similar hashicorp/terraform feature request/bug report about this same scenario, of needing to run `terraform get` when a module is updated - https://github.com/hashicorp/terraform/issues/20114

Based on that, I think you're right about this being the primary workaround and not explicitly connected to the Datadog provider.

**Comment by stevemossovo** [comment]
> Ahh, thanks for clarifying. Based on your descriptions, it looks like its related to when the `team_dd` module source gets loaded. I found what looks to be a similar hashicorp/terraform feature request/bug report about this same scenario, of needing to run `terraform get` when a module is updated - [hashicorp/terraform#20114](https://github.com/hashicorp/terraform/issues/20114)
> 
> Based on that, I think you're right about this being the primary workaround and not explicitly connected to the Datadog provider.

Cool, thanks for that and thanks for your time 🙏 I'm happy to close this here then and hopefully that enhancement gets developed at some point in the future. I'll have to stick with the `terraform get` workaround for now, though.
