### ISSUE TITLE
Changed synthetics_test options to options_list, but options are still in the result of plan.

### ISSUE THREAD

**Issue by chroju** [DataDog/terraform-provider-datadog#697]
### Terraform Version

```
Terraform v0.13.0
+ provider registry.terraform.io/datadog/datadog v2.13.0
```

### Affected Resource(s)

- datadog_synthetics_test

### Terraform Configuration Files

This configuration has been changed from the one for terraform-provider-datadog 2.12.x. Changed deprecated `options` to `options_list`.

```hcl
resource "datadog_synthetics_test" "api_test" {
  type    = "api"
  subtype = "http"

  request = {
    method = "GET"
    url    = "https://example.com"
  }

  assertion {
    type     = "statusCode"
    operator = "is"
    target   = 200
  }
  assertion {
    type     = "header"
    property = "content-type"
    operator = "is"
    target   = "application/json"
  }
  assertion {
    type     = "responseTime"
    operator = "lessThan"
    target   = 1000
  }

  locations = [
     "aws:ap-northeast-1",
  ]

  options_list {
    tick_every           = 300
    min_failure_duration = 180
    min_location_failed  = 1
  }

  name    = "API test for example.com"
  message = "API test"
  status = "live"
}
```

### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior

The expected result of the terraform plan is that `options` are removed and `options_list` is added.

```
  # datadog_synthetics_test.api_test will be updated in-place
  ~ resource "datadog_synthetics_test" "api_test" {
    ...
      - options         = {
          - "min_failure_duration" = "180"
          - "min_location_failed"  = "1"
          - "tick_every"           = "300"
        }
      + options_list {
          + min_failure_duration = 180
          + min_location_failed  = 1
          + tick_every           = 300
        }
    }
```

### Actual Behavior

`options` are still there.

```
  # datadog_synthetics_test.api_test will be updated in-place
  ~ resource "datadog_synthetics_test" "api_test" {
    ...
        options         = {
            "min_failure_duration" = "180"
            "min_location_failed"  = "1"
            "tick_every"           = "300"
        }
      + options_list {
          + min_failure_duration = 180
          + min_location_failed  = 1
          + tick_every           = 300
        }
    }
```

### Steps to Reproduce

1. First, in 2.12.x, apply the config with the `options`.
1. Change the `options` to `options_list`.
1.  `terraform plan`

### Important Factoids

N/A

### References

N/A

**Comment by nmuesch** [comment]
Hey @chroju thanks for the issue report. 

There are some diffSuppress utility methods in place on `options` and `options_list` to ensure a smooth transition from one to the other. the provider code currently looks for `options_list` first, and only falls back to using `options` if the first doesn't exist - https://github.com/DataDog/terraform-provider-datadog/blob/master/datadog/resource_datadog_synthetics_test_.go#L685

Are you noticing any issues arising from this?

**Comment by chroju** [comment]
Thanks for your response.

It works fine. My concern is that `terraform plan` is showing up as if it is making a change to the monitoring configuration, when in fact it is not making any changes. However, this is not a critical issue and I doesn't necessarily need to be resolved.

**Comment by therve** [comment]
I think we should remove `options` from the state, it seems like a bug. Regarding your last comment, I think we can't easily remove the change induced, except by trying to make some state migration, which isn't well supported across all versions.
