### ISSUE TITLE
error getting synthetics test: assertFileDownload is not a valid SyntheticsStepType:

### ISSUE THREAD

**Issue by chrismllr** [DataDog/terraform-provider-datadog#706]
### Terraform Version

terraform: `v0.11.14`
terraform-provider-datadog: `v2.13.0`

### Affected Resource(s)

> Please list the resources as a list, for example:

- `datadog_synthetics_test`

### Terraform Configuration Files

```hcl
resource "datadog_synthetics_test" "ui_prd_report_csv" {
  assertions = []

  device_ids = [
    "laptop_large",
  ]

  locations = [
    "aws:us-west-1",
    "aws:us-east-2",
  ]

  message = "Datadog Browser Synthetic: Unable to download report"
  name    = "(ui-prd) Download Report"

  options = {
    "min_failure_duration" = "0"
    "min_location_failed"  = "1"
    "tick_every"           = "43200"
  }

  request = {
    "method"  = "GET"
    "timeout" = "0"
    "url"     = "https://my_url.com/stuff"
  }

  request_headers = {}
  status          = "live"

  tags = [
    "team:teamname",
  ]

  type = "browser"
}

```

### Debug Output

```
error getting synthetics test: assertFileDownload is not a valid SyntheticsStepType:
```

### Expected Behavior

> What should have happened?

Terraform should have applied the browser synthetics the same way it had prior, maintaining existing steps created in the UI

### Actual Behavior

> What actually happened?

It looks as though a step included in our UI-created synthetic steps was not recognized, and therefor threw an error. I would expect this to not be an exception which breaks application.

### Steps to Reproduce

> Please list the steps required to reproduce the issue, for example:

1. `terraform apply` or `terraform plan`

### Important Factoids

> Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

N/a

### References

> Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:

- #638

**Comment by chrismllr** [comment]
Can provide debug output if necessary

**Comment by chrismllr** [comment]
Update: v0.11.14, NOT v0.11.4

**Comment by romainberger** [comment]
Reopening, the go client needs to be updated to really fix this.
