### ISSUE TITLE
Query with multiple escape sequences are not parsed correctly.

### ISSUE THREAD

**Issue by Kryota** [DataDog/terraform-provider-datadog#716]
### Terraform Version

terraform: `v0.12.18`
terraform-provider-datadog: `v2.13.0`

### Affected Resource(s)

Please list the resources as a list, for example:

- datadog_monitor(type: log alert)

### Terraform Configuration Files

```hcl
resource "datadog_monitor" "resource_name" {
  for_each = {
    dev = {
      env = var.envs.dev
      thresholds = {
        critical = 1
      }
    },
    stg = {
      env = var.envs.stg
      thresholds = {
        critical = 1
      }
    },
    prd = {
      env = var.envs.prd
      thresholds = {
        critical = 1
      }
    },
  }

  name = "Monitor Title"
  type = "log alert"

  message = <<-TEMPLATE
    {{#is_alert}}
    Monitor message
    {{/is_alert}}

    {{#is_recovery}}
    Monitor recovery message
    {{/is_recovery}}
  TEMPLATE

  query = "logs(\"env:${each.key} -\"undefined field: \\\"filed\\\"\"\").index(\"${each.key}\").rollup(\"count\").by(\"pod_name\").last(\"5m\") >= ${each.value.thresholds.critical}"

  thresholds = each.value.thresholds

  notify_no_data     = false
  enable_logs_sample = true

  tags = concat(each.value.env.tags, var.service_tag)

  lifecycle {
    ignore_changes = [silenced]
  }
}
```

### Expected Behavior

What should have happened?

I expected the `\"` was generated by `\\\"`.
if ${each.key} is prd:
`logs("env:prd -"undefined field: \"filed\"" ").index("prd").rollup("count").by("pod_name").last("5m") >= 1`

### Actual Behavior

But, actually behavior was that `"` was generated by `\\\"`.
if ${each.key} is prd:
`logs("env:prd -"undefined field: " filed"" ").index("prd").rollup("count").by("pod_name").last("5m") >= 1`

I guess this problem occured from a chain of `\\` escapes.

### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:

1. `terraform apply`
2. Check Datadog Monitor

### Important Factoids

I created this monitor manually as I expected.
<img width="923" alt="Datadog_Monitor_with_double_quote_escape" src="https://user-images.githubusercontent.com/19945898/96970468-b39d6080-154e-11eb-8140-6c90575c14fc.png">

**Comment by therve** [comment]
Thanks for you report. I believe you need to double the existing slashes, ie `-\"undefined field: \\\\\"filed\\\\\"\"`. It seemed to work during my testing.

Please reopen if that doesn't work for you.
