### ISSUE TITLE
Support advanced and boolean filters in resource datadog_monitor

### ISSUE THREAD

**Issue by jfreeland** [DataDog/terraform-provider-datadog#721]
I can create monitors with advanced filters through the datadog web UI but not with the datadog terraform provider.  I quickly looked through the code and don't see any reference of an option to pass this along, nor do I see any reference in the documentation.  It's quite possible that I'm missing it.

### Affected Resource(s)

Please list the resources as a list, for example:

- datadog_monitor

### Terraform Configuration Files

```hcl
locals {
  my_dict = {
    "region" = {
      c = [
        "cluster1",
        "cluster2"
      ]
      threshold_critical_put = 4
      threshold_warning_put  = 2
    }
  }
}

resource "datadog_monitor" "my_monitor" {
  for_each = local.my_dict
  name     = "Test: ${each.key}"
  type     = "query alert"
  tags     = ["thing"]

  message = <<EOT
...
EOT

  escalation_message = <<EOT
...
EOT

  query               = "max(last_5m):${join(" + ", formatlist("sum:some.metric{cluster:%s AND method IN (post,put)}.as_rate()", each.value.c))} > ${each.value.threshold_critical_put}"
  notify_no_data      = false
  renotify_interval   = 0
  timeout_h           = 0
  include_tags        = true
  require_full_window = false
  new_host_delay      = 300

  thresholds = {
    critical = each.value.threshold_critical_put
    warning  = each.value.threshold_warning_put
  }
}
```

### Expected Behavior

The monitor should be created.

### Actual Behavior

```
Error: error validating monitor: 400 Bad Request: {"errors":["The monitor could not be saved, because advanced and boolean filters are not enabled."]}
```

**Comment by therve** [comment]
Hi! Do you mind opening a support ticket for this particular problem and reference this issue? Thank you.

**Comment by paulkore** [comment]
Hello,
I wonder if there's any progress on this issue? 
We have heard from another source, that this is not merely a bug in `terraform-provider-datadog`, but it's Datadog itself that doesn't currently support advanced queries in monitors. 
If anyone has access to that information, it would be very helpful to know whether there are plans to implement that support in the near future?

**Comment by nmuesch** [comment]
Hey @jfreeland and @paulkore would you be able to try this again and see if you run into any issues? This was recently enabled and should work as expected now!

If you still experience any issues, can you confirm the terraform config being used?

**Comment by therve** [comment]
Please reopen if the issue is still happening, thanks.
