### ISSUE TITLE
"unexpected end of JSON input" when creating datadog_integration_gcp

### ISSUE THREAD

**Issue by Sardonic-1** [DataDog/terraform-provider-datadog#727]
### Terraform Version

Terraform v0.13.5
+ provider registry.terraform.io/datadog/datadog v2.14.0

### Affected Resource(s)

Please list the resources as a list, for example:

- datadog_integration_gcp
- provider "datadog" (possibly)

### Terraform Configuration Files

```hcl
terraform {
  backend "local" {
    path = "local.tfstate"
  }
}


provider "datadog" {
  api_url = "https://api.datadoghq.eu/api/"
  api_key = var.datadog_api_key
  app_key = var.datadog_app_key
}

resource "datadog_integration_gcp" "gcp_project_integration" {
  client_email = "<hardcoded value>"
  client_id = "<hardcoded value>"
  private_key = "hardcoded value>"
  private_key_id = "<hardcoded value>"
  project_id = "<hardcoded value>"
}
```

### Debug Output

[https://gist.github.com/Sardonic-1/f7654a0498f1af0ecde06a3f030b1bc9](https://gist.github.com/Sardonic-1/f7654a0498f1af0ecde06a3f030b1bc9)

### Expected Behavior

datadog-gcp integration should have been formed

### Actual Behavior

terraform plan process failed with the error

```
Error: unexpected end of JSON input

  on main.tf line 7, in provider "datadog":
   7: provider "datadog" {
```

### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:

0. copy the above code with valid Datadog app and api key
1. configure the datadog_integration_gcp resource
2. run `terraform plan`
(if datadog_integration_gcp is commented, the plan action succeeds)

**Comment by therve** [comment]
The issue is with your api_url, it should be `https://api.datadoghq.eu`. I'll see if we can improve the error message.

**Comment by Sardonic-1** [comment]
Right, new url works, cheers!
