### ISSUE TITLE
datadog_logs_custom_pipeline grok_parser samples is being replaced when no need in terraform apply 

### ISSUE THREAD

**Issue by thehouk** [DataDog/terraform-provider-datadog#736]
### Terraform Version

Terraform v0.13.5
+ provider registry.terraform.io/datadog/datadog v2.14.0

### Affected Resource(s)

Please list the resources as a list, for example:

-   datadog_logs_custom_pipeline

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Expected Behavior

when terraform apply grok_parser samples should be replaced only if the state and the datadog_logs_custom_pipeline block doesn't match
### Actual Behavior

when running terraform apply, it ask to replace the grok_parser samples with identical samples.

### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:

1. create a terraform block "datadog_logs_custom_pipeline" "example"
2. terraform import  datadog_logs_custom_pipeline.example ${some_pipeline_id}
3. terraform state show 'datadog_logs_custom_pipeline.example'
4. copy state output and paste in newly created  block "datadog_logs_custom_pipeline" "example"
5. fix syntax
6. terraform apply

### Important Factoids

None
### References

None

**Comment by therve** [comment]
Hi,

Can you provide your TF file? I tried the example grok parser, and it worked fine, so I wonder if there is some specific attributes causing this. Thanks.

**Comment by therve** [comment]
@thehouk Hi, is it still happening? Thanks.

**Comment by therve** [comment]
Closing for now, please reopen with more information.
