### ISSUE TITLE
Issue using 'lifecycle' attribute

### ISSUE THREAD

**Issue by ashki1** [DataDog/terraform-provider-datadog#737]
Hello

I'm on Terraform v0.11.14. I'm following https://registry.terraform.io/providers/DataDog/datadog/latest/docs/resources/monitor and trying to use the below to make sure any changes to the 'silence' attribute are ignored. Ideally i do not want anything to be changed when i manually mute/unmute the monitor on Datadog portal.

lifecycle {
  ignore_changes = [silenced]
}

 When i run 'terraform fmt' i get this error - "unexpected token while parsing list: IDENT" . I'm unable to find what the issue is. Can someone pls help.  

This is how my code looks like :
========================= 
`resource "datadog_monitor" "prod-datadog-agent-service-down" {
  name    = "prod-datadog-agent-service-down"
  type    = "service check"
  message = "datadog-agent-service-down on host - {{name}}\n\n@${var.slack_channel} \n@${var.jira_channel}"

  query        = "\"process.up\".over(\"environment:prod\",\"process:datadog-agent\",\"process_name:datadog-agent\").by(\"host\",\"process\").last(4).count_by_status()"
  notify_audit = "${var.notify_audit}"
  locked       = "${var.locked}"
  timeout_h    = 0
  include_tags = "${var.include_tags}"
  silenced     = {}
 
  thresholds = {
    ok       = 3
    warning  = 1
    critical = 2
  }
  
  lifecycle {
  ignore_changes = [silenced]
  }

  new_host_delay     = "${var.new_host_delay}"
  notify_no_data     = "true"
  renotify_interval  = 30
  require_full_window = "${var.require_full_window}"
  escalation_message = "Renotification: datadog-agent-service-down - {{name}}\n\n@${var.slack_channel}"
  no_data_timeframe  = 7
  tags               = ["iac", "datadog-agent", "prod"]
}
`
==========================

**Comment by therve** [comment]
Hello,

Can you try upgrading terraform? Looks like you're using 0.12 features. Thanks.

**Comment by ashki1** [comment]
@therve Thanks, Do you mean to say the below is not applicable for version 0.11?

lifecycle {
ignore_changes = [silenced]
}

Thanks

**Comment by therve** [comment]
No the error seems to be with something else in your configuration. Maybe if you reformat it properly I can try?

**Comment by ashki1** [comment]
I have attached the code. Can you please review. Thanks
[sample.tf.txt](https://github.com/DataDog/terraform-provider-datadog/files/5474046/sample.tf.txt)

**Comment by therve** [comment]
`silenced = -1`  is incorrect, if I comment it I can create your monitor correctly.

**Comment by ashki1** [comment]
I did try commenting that out but I still get the same error.

**Comment by therve** [comment]
Did you upgrade terrraform?

**Comment by therve** [comment]
I tried 0.11, if you replace `silenced` by `"silenced"` it should work.

**Comment by therve** [comment]
Closing for now, let me know if it doesn't work for you.
