### ISSUE TITLE
query_table_definition -  Data failed to match schemas in oneOf(WidgetDefinition):

### ISSUE THREAD

**Issue by sibizaestruch** [DataDog/terraform-provider-datadog#742]
Hi,
I got some issues when trying to create/import a dashboard containing a `query_table` widget using TF.

### Terraform Version

```
Terraform v0.13.3
+ provider registry.terraform.io/datadog/datadog v2.15.0
```

### Affected Resource(s)

-   `datadog_dashboard`

### Terraform Configuration Files

```hcl
resource "datadog_dashboard" "issue" {
  title       = "Issue dashboard"
  description = ""
  widget {
    query_table_definition {
      request {
        q          = "max:aws.ecs.service.desired{$owner,$env} by {service}"
        aggregator = "max"
        limit      = 50
        order      = "desc"
        alias      = "Desired"
        conditional_formats {
          comparator = "<="
          value      = 0
          palette    = "black_on_light_red"
        }
        cell_display_mode = ["bar"]
      }
      request {
        q          = "max:aws.ecs.service.pending{$owner,$env} by {service}"
        aggregator = "max"
        alias      = "Pending"
        conditional_formats {
          comparator = ">"
          value      = 0
          palette    = "black_on_light_red"
        }
        cell_display_mode = ["bar"]
      }
      request {
        q          = "max:aws.ecs.service.running{$owner,$env} by {service}"
        aggregator = "max"
        alias      = "Running"
        conditional_formats {
          comparator = "<="
          value      = 0
          palette    = "white_on_red"
        }
        cell_display_mode = ["bar"]
      }
      time = {
      }
      has_search_bar = "auto"
    }
    layout = {
      x      = -1
      y      = -1
      width  = 54
      height = 32
    }
  }
  template_variable {
    name    = "env"
    default = "*"
    prefix  = "env"
  }
  template_variable {
    name    = "owner"
    default = "*"
    prefix  = "owner"
  }
  layout_type  = "free"
  is_read_only = false
  notify_list  = []
}
```

### Debug Output

- `terraform apply` : https://gist.github.com/sibizaestruch/14f17734b82ddd2b251c40ea2b687e8f

### Expected Behavior

- Dashboard gets created and saved properly in the tfstate.

### Actual Behavior

- Dashboard it's getting created in DD, but because of that error looks like that it's not saved properly in the tfstate.
- Using `terraform import...` reports the same error.

(`terraform plan` works properly)

### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:

1. `terraform apply`
or 
1. ` terraform import datadog_dashboard.squad <dashboard_id>`

--- 
Thank you!

**Comment by therve** [comment]
Thanks for your report,

That's a little bit sad, but I believe the issue comes from your palette. If you switch from `black_on_light_red` to `red_on_white` for example, it should work. I'm looking into fixing this.

**Comment by sibizaestruch** [comment]
> Thanks for your report,
> 
> That's a little bit sad, but I believe the issue comes from your palette. If you switch from `black_on_light_red` to `red_on_white` for example, it should work. I'm looking into fixing this.

Correct! That solved the issue!

Thank you!

**Comment by ianvernon** [comment]
> That's a little bit sad, but I believe the issue comes from your palette. If you switch from black_on_light_red to red_on_white for example, it should work. I'm looking into fixing this.

I realize that this is quite an old issue, but how did you come to this conclusion? I am seeing a similar failure as well, but I have no idea how to debug it. I suspect updating the provider is the way to go, but would like to know to what version, since a major version upgrade may not be feasible for me.
