### ISSUE TITLE
[v2.13.0] `terraform import` of monitors loses the value for `no_data_timeframe`

### ISSUE THREAD

**Issue by brushbox** [DataDog/terraform-provider-datadog#746]
Hi there,

Since upgrading from Terraform 0.12 I have been having problems with terraform import not recording the values for `no_data_timeframe` as anything other than `null`.

### Terraform Version

```bash
› terraform -v
Terraform v0.13.5
+ provider registry.terraform.io/datadog/datadog v2.13.0
```
### Affected Resource(s)

-  `datadog_monitor`

### Debug Output

Redacted log output: https://gist.github.com/brushbox/15d8bc93e1ecc06c02e55b112dc005c8

### Expected Behavior

If the monitor in datadog has a value of, say `30` for the `no_data_timeframe` it should show:

`"no_data_timeframe": 30,`

### Actual Behavior

`"no_data_timeframe": null,`

### Steps to Reproduce

1. `terraform import -allow-missing-config datadog_monitor.{terraform_id} {id}`

### Important Factoids

* We generate our terraform config from the `terraform.tfstate` file. We cannot apply the generated files as they all end up with the default value for `no_data_timeframe` of `10` regardless of what values they were set to.
* The log output shows that the api client is receiving the correct value.
  * I've confirmed this via the Ruby `dogapi` gem and via `datadog-api-client-go`

**Comment by therve** [comment]
Thanks for the report! The fix will be in the next release, let me know if it still doesn't work for you.

**Comment by brushbox** [comment]
Thanks for the quick response @therve !

When will the next release be available (and where should I look to find out about that in future)?

**Comment by therve** [comment]
We don't have an official schedule, but it should happen in the next few weeks.
