### ISSUE TITLE
[Feature Request] - Create Synthetic Global Variables from HTTP Test

### ISSUE THREAD

**Issue by ccampo133** [DataDog/terraform-provider-datadog#755]
PR #691 introduced support for creating global variables for synthetic tests. However #691 only allows you to create static values, i.e. a string defined within the Terraform files themselves. In addition to static global variables, DataDog allows you to [create global variables from an HTTP test](https://docs.datadoghq.com/synthetics/settings/?tab=createfromhttptest#global-variables).

This is useful for things like short-lived OAuth tokens, which cannot be defined as static variables.

It would be nice to see this feature introduced to the Terraform provider. For now, these types of variables must be created by hand in DataDog.

**Comment by romainberger** [comment]
Hi, support for Synthetics global variables from test has been added in the latest release: https://github.com/DataDog/terraform-provider-datadog/releases/tag/v2.20.0

**Comment by ccampo133** [comment]
Excellent, thank you @romainberger.
