### ISSUE TITLE
Order of monitor and SLO resource execution when deleting a monitor

### ISSUE THREAD

**Issue by felixfriedrich** [DataDog/terraform-provider-datadog#756]
Hello everyone!

### Terraform Version

0.13.5

### Affected Resource(s)

- https://registry.terraform.io/providers/DataDog/datadog/latest/docs/resources/monitor
- https://registry.terraform.io/providers/DataDog/datadog/latest/docs/resources/service_level_objective

### Terraform Configuration Files

```hcl
resource "datadog_monitor" "error_rate_monitor" {
  for_each = var.enable_error_rate ? var.operators : []
 [...]
}
```

```hcl
resource "datadog_service_level_objective" "error_rate_monitor_slo" {
  monitor_ids = [for operator in var.operators : datadog_monitor.error_rate_monitor[operator].id]
[...]
}
```

### Debug Output

When removing one element from the `operators` list and executing `apply`, I get this output:

```
Error: error deleting monitor: 400 Bad Request: {"errors":["monitor [425633,Error Rate | service:user-home-service-api | env:development] is referenced in slos: [72c1f05f994d5377a6d2f5233d1335b1,Error Rate SLO | service:user-home-service-api | env:development]"]}
```

### Expected Behavior

Obviously the monitor cannot be destroyed as long as the SLO uses it. I'd expect TF to realise this and change the SLO *before* it destroys the monitor.

### Actual Behavior

TF tries to destroy a monitor, which is still referenced by a SLO.

### Steps to Reproduce

The variable `operators` is a list of operators, basically metrics to use. Based on the operators list monitors are created for each of the operators. The SLO however references all of those monitors.
When removing an operator from the list, the monitor for that operator is deleted first, which fails, due to the SLO having the ID of that monitor still in it's list.

I tried to work around this by using `depends_on`, which does't work here as the list of ids needs to be knows at plan time.
```
Arbitrary expressions are not allowed in the depends_on argument value, because its value must be known before Terraform knows resource relationships and thus before it can safely evaluate expressions.
```
Source: https://www.terraform.io/docs/configuration/resources.html#depends_on-explicit-resource-dependencies

I also tried to move the monitor and the SLO (not at the same time of course) into a submodule to enforce order, by using output vars or by providing the list of monitor IDs as an argument to the SLO, no luck here. The order doesn't change.

### References

-  https://github.com/DataDog/terraform-provider-datadog/issues/667 might be related.

Thanks,
Felix

**Comment by nmuesch** [comment]
@felixfriedrich would the `force_delete` flag address your use case here? https://registry.terraform.io/providers/DataDog/datadog/latest/docs/resources/monitor#force_delete

You'd have to run the apply with the force_delete flag prior to trying to do the modification so that the flag is there when terraform tries to delete the resource. (There's some more context in #667 about why this is a manually set flag)

**Comment by therve** [comment]
Closing in favor of #667
