### ISSUE TITLE
On the Terraform Registry, the `secure` argument has not yet been released

### ISSUE THREAD

**Issue by MickVanDuijn** [DataDog/terraform-provider-datadog#767]
Not sure if this is the correct place for filing an issue about the documentation, but this is where the Terraform Registry directed me to. I noticed that the [`Argument Reference`](https://registry.terraform.io/providers/DataDog/datadog/latest/docs/resources/synthetics_global_variable#argument-reference) on the Terraform Registry isn't up to date with the [`Argument Reference`](https://github.com/DataDog/terraform-provider-datadog/blob/master/docs/resources/synthetics_global_variable.md#argument-reference) in the repository. The Terraform Registry has no mention of the `secure` argument.

**On the Terraform Registry**
![Terraform Registry](https://user-images.githubusercontent.com/1350647/100599662-96537300-3300-11eb-800e-32a540235ff6.png)

**On Github**
![Github Docs](https://user-images.githubusercontent.com/1350647/100599705-a703e900-3300-11eb-82ec-3e0b833224bf.png)

**Comment by MickVanDuijn** [comment]
Oh I noticed just now, [this feature](https://github.com/DataDog/terraform-provider-datadog/pull/758) was only merged but not released yet. Any rough estimate of an ETA?

**Comment by MickVanDuijn** [comment]
I have updated the issue title accordingly!

**Comment by therve** [comment]
Hi! We don't have a strict schedule, but we should release next week if everything is ok.

**Comment by MickVanDuijn** [comment]
👍 Thanks for the response! We'll eagerly await the next release!

**Comment by bkimbrough88** [comment]
Also eagerly awaiting this release!

**Comment by therve** [comment]
Hi, this is available in 2.18.0. Let us know if this works for you.

**Comment by MickVanDuijn** [comment]
Works like a charm! 🚀

**Comment by bkimbrough88** [comment]
Works great, thanks!
