### ISSUE TITLE
Error when updating Dashboard from `ordered` layout type to `free` layout type.

### ISSUE THREAD

**Issue by marinsalinas** [DataDog/terraform-provider-datadog#772]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version

```
v0.12.29 on Terraform Enterprise.
```

### Affected Resource(s)

Please list the resources as a list, for example:

-   datadog_dashaboard.

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```
Reach c-marin.salinas@hulu.com for some additional info.
### Debug Output

Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output

If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Actual Behavior

I found something on dd provider, if I want to update a dashboard from ordered  to free  layout, I got the following error:

```
Error: error updating dashboard: 400 Bad Request: {"errors": ["'layout_type' is not editable for existing dashboards. This dashboard uses ordered layout."]}
```

### Expected Behavior

The dashboard will update in place or I'm wondering if `layout_type`  should be changed as ForceNew attribute to avoid this error?
https://github.com/DataDog/terraform-provider-datadog/blob/master/datadog/resource_datadog_dashboard.go#L52

### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:

1. `terraform apply`

### Important Factoids

Since we are writing Terraform modules for all our organization we used to have an ordered layout in v1.2.4 of our Datadog module so then we upgraded the module to use free layout and the users who jump to this new version are getting this error.

A workaround of this is to run `terraform taint` to force the dashboard recreation but since we are using Terraform Enterprise the users don't have permissions to perform that manual actions.

**Comment by therve** [comment]
Hi,

Thanks for your report. We're trying to be conservative with `ForceNew`, but I think it's warranted in that case. We'll come up with a fix.
