### ISSUE TITLE
"monitor" SLO threshold target/warning truncated

### ISSUE THREAD

**Issue by fschmager** [DataDog/terraform-provider-datadog#780]
Hi,
I'm having an SLO with 2 `thresholds` (same applies to 3, but 2 is simpler to discuss). The thresholds have target/warning with 3 (or more) factions (digits after the period). The threshold declared last will get created correctly in DD. But, the earlier thresholds will have only 2 fractions in DD.

### Affected Resource(s)
- `service_level_objective`

### Terraform Configuration Files

```hcl
resource "datadog_service_level_objective" "my-slo" {
  thresholds {
    target          = 75.432
    warning         = 87.653
    timeframe       = "30d"
  }

  thresholds {
    target          = 67.543
    warning         = 76.532
    timeframe       = "90d"
  }

  name = "my-slo"
  type = "monitor"

  monitor_ids = ["27248290"]
}
```

### Observations

Initial `plan` and `apply`
```
  # datadog_service_level_objective.my-slo will be created
  + resource "datadog_service_level_objective" "my-slo" {
      + id             = (known after apply)
      + monitor_ids    = [
          + 27248290,
        ]
      + monitor_search = (known after apply)
      + name           = "my-slo"
      + type           = "monitor"

      + thresholds {
          + target    = 75.432
          + timeframe = "30d"
          + warning   = 87.653
        }
      + thresholds {
          + target    = 67.543
          + timeframe = "90d"
          + warning   = 76.532
        }
    }
```
The "last" threshold `"90d"` gets created with all its digits. However, the "earlier" `"30d"` threshold has it's digits cut off.
![Screen Shot 2020-12-09 at 16 51 14](https://user-images.githubusercontent.com/10031576/101693211-96c2db00-3a71-11eb-80b9-7082bef831d8.png)

The next `plan` confirms this:
```
Terraform will perform the following actions:

  # datadog_service_level_objective.my-slo will be updated in-place
  ~ resource "datadog_service_level_objective" "my-slo" {
        groups      = []
        id          = "525bb788abca586b9d7649ee3f8a95fb"
        monitor_ids = [
            27248290,
        ]
        name        = "my-slo"
        tags        = []
        type        = "monitor"

      ~ thresholds {
          ~ target          = 75.43 -> 75.432
            target_display  = "75.43"
            timeframe       = "30d"
          ~ warning         = 87.65 -> 87.653
            warning_display = "87.65"
        }
        thresholds {
            target          = 67.543
            target_display  = "67.543"
            timeframe       = "90d"
            warning         = 76.532
            warning_display = "76.532"
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

The same happens with 3 thresholds, only the "last" will have all the digits.

I don't know if this is a DD-provider or a DD-API issue, but something is up.

### Terraform Version
I'm working on upgrading to latest terraform, but this feels more like a provider issue.
```
➭ terraform --version
Terraform v0.12.26
+ provider.datadog v2.18.1

Your version of Terraform is out of date! The latest version
is 0.14.0. You can update by downloading from https://www.terraform.io/downloads.html
```

**Comment by fschmager** [comment]
Whatever is causing the truncation is also doing it for `target_display` and `warning_display`.

**Comment by fschmager** [comment]
Same result with terraform `0.13.5`
```
➭ terraform --version
Terraform v0.13.5
+ provider registry.terraform.io/datadog/datadog v2.18.1
```

**Comment by fschmager** [comment]
Same with terraform `0.14.2`
```
➭ terraform --version
Terraform v0.14.2
+ provider registry.terraform.io/datadog/datadog v2.18.1
```

**Comment by therve** [comment]
Hi,

I'm catching up on how things work in SLO backend, but from what I can tell, precision depends on your timeframe. For 7 and 30 days, you only get 2 digits of precision. For 90 days you get 3 digits. That's why you have a diff, the API is not accepting your precision on the smaller timeframes, but does on the bigger one.

Does that make sense? Thanks.

**Comment by fschmager** [comment]
Interesting. The way you describe it makes total sense. Is that documented anywhere? The API docs don't mention that: https://docs.datadoghq.com/api/v1/service-level-objectives/#create-a-slo-object

However, I have "proof" to the contrary.

I do have SLOs with a `7d` target of 3 digit precision:
<img width="605" alt="Screen Shot 2020-12-11 at 07 58 36" src="https://user-images.githubusercontent.com/10031576/101906275-faa3eb80-3bb8-11eb-80f0-5f8a96105665.png">

Used DD Postman collection to retrieve that SLO (https://api.datadoghq.com/api/v1/slo/:sloid:). 
Here's the relevant bit of the response:
```javascript
        "thresholds": [
            {
                "warning": 99.9995,
                "warning_display": "99.9995",
                "target": 99.999,
                "target_display": "99.999",
                "timeframe": "7d"
            },
            {
                "warning": 99.999,
                "warning_display": "99.999",
                "target": 99.995,
                "target_display": "99.995",
                "timeframe": "30d"
            },
            {
                "warning": 99.999,
                "warning_display": "99.999",
                "target": 99.995,
                "target_display": "99.995",
                "timeframe": "90d"
            }
        ],
```

So the DD API does seem to be able to handle "shorter timeframe" SLOs with high-precision.

**Comment by therve** [comment]
I haven't gotten feedback from the backend team yet for a document. It's strange that you have a SLO with such precision, I surely can't create one using either the UI or the API right now. Maybe it's old and the behavior changed? I'll try to get a definitive answer, thanks for your patience.

**Comment by fschmager** [comment]
Don't know about "old".

![Screen Shot 2020-12-11 at 12 57 27](https://user-images.githubusercontent.com/10031576/101937921-cf35f680-3be2-11eb-9dc4-a655f5872bb0.png)

from API response:
```json
        "created_at": 1606233043,
        "modified_at": 1606233043,
```

**Comment by therve** [comment]
Oh, is it a `monitor` SLO? If it's a `metric` one it may explain why precision is calculated differently.

**Comment by fschmager** [comment]
Thomas, thanks for sticking with me and for looking at it that closely. There really is a difference between `metrics` and `monitor` SLOs.

I've re-done my testing with both types. I've `destroyed` everything, starting with a clean slate.

Here's the `plan`:
```
  # datadog_service_level_objective.my-metric-slo will be created
  + resource "datadog_service_level_objective" "my-metric-slo" {
      + id             = (known after apply)
      + monitor_search = (known after apply)
      + name           = "my-metric-slo"
      + type           = "metric"

      + query {
          + denominator = "..."
          + numerator   = "..."
        }

      + thresholds {
          + target    = 87.654
          + timeframe = "7d"
          + warning   = 98.765
        }
      + thresholds {
          + target    = 76.543
          + timeframe = "30d"
          + warning   = 87.654
        }
      + thresholds {
          + target    = 65.432
          + timeframe = "90d"
          + warning   = 76.543
        }
    }

  # datadog_service_level_objective.my-monitor-slo will be created
  + resource "datadog_service_level_objective" "my-monitor-slo" {
      + id             = (known after apply)
      + monitor_ids    = (known after apply)
      + monitor_search = (known after apply)
      + name           = "my-monitor-slo"
      + type           = "monitor"

      + thresholds {
          + target    = 87.654
          + timeframe = "7d"
          + warning   = 98.765
        }
      + thresholds {
          + target    = 76.543
          + timeframe = "30d"
          + warning   = 87.654
        }
      + thresholds {
          + target    = 65.432
          + timeframe = "90d"
          + warning   = 76.543
        }
    }
```

I `apply`-ed that plan, followed by another `plan`:
```
  # datadog_service_level_objective.my-monitor-slo will be updated in-place
  ~ resource "datadog_service_level_objective" "my-monitor-slo" {
        groups      = []
        id          = "a6e93e5ee78d59e6b741596641693d72"
        monitor_ids = [
            27461566,
        ]
        name        = "my-monitor-slo"
        tags        = []
        type        = "monitor"

      ~ thresholds {
          ~ target          = 87.65 -> 87.654
            target_display  = "87.65"
            timeframe       = "7d"
          ~ warning         = 98.76 -> 98.765
            warning_display = "98.76"
        }
      ~ thresholds {
          ~ target          = 76.54 -> 76.543
            target_display  = "76.54"
            timeframe       = "30d"
          ~ warning         = 87.65 -> 87.654
            warning_display = "87.65"
        }
        thresholds {
            target          = 65.432
            target_display  = "65.432"
            timeframe       = "90d"
            warning         = 76.543
            warning_display = "76.543"
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```
Seems really like the `target|warning` are being truncated for `monitor` SLOs but not for `metric` SLOs. 

So many questions:
1. What's the motivation behind that? 
2. Where's that documented? If it isn't, could it get documented?
3. Could there be a warning about this? Or even an error? No point in me expecting a more precise `target|warning` if it isn't honored anyway.

**Comment by phillip-dd** [comment]
> What's the motivation behind that?

Based on the underlying data and systems involved, there's a maximum precision that can be supported.

> Could there be a warning about this? Or even an error?

We're going to go down this route, rejecting requests that have a precision higher than what's supported instead of silently truncating.

**Comment by therve** [comment]
Closing this now that the backend checks for the precision. Thanks!
