### ISSUE TITLE
Error when trying to use "matches" operator with "statusCode"

### ISSUE THREAD

**Issue by zachkknowbe4** [DataDog/terraform-provider-datadog#783]
Even though the DataDog API fully supports sending,
```
"assertions": [
            {
                "operator": "matches",
                "type": "statusCode",
                "target": "20[04]"
            }
        ]
```

The provider is changing the JSON structure to,
```
"assertions": [
            {
                "operator": "matches",
                "type": "statusCode",
                "target": 0
            }
        ]
```
Which obviously causes the API to throw an error because it wasn't expecting a `0`. Not sure why the API docs and this provider have not been updated to show that this combination is supported.

As you can see below, the web interface also supports setting status code to a regex,
![image](https://user-images.githubusercontent.com/42388953/101949316-68ecac00-3bc1-11eb-8c91-ef9ca93bbd1d.png)

### Terraform Version
Terraform v0.13.5
+ provider registry.terraform.io/datadog/datadog v2.18.1
+ provider registry.terraform.io/hashicorp/aws v3.21.0
+ provider registry.terraform.io/hashicorp/null v3.0.0

### Affected Resource(s)

-   datadog_synthetics_test

### Terraform Configuration Files

```hcl
resource "datadog_synthetics_test" "test_api" {
  for_each = var.internal_apps

  type = "api"
  request = {
    method = "GET"
    url    = "https://${each.value}"
  }
  tags = ["env:${terraform.workspace}"]
  assertion {
      type     = "statusCode"
      operator = "matches"
      target   = "20[04]"
  } 
...
```

### Debug Output
```
2020/12/11 14:37:00 [WARN] Provider "registry.terraform.io/datadog/datadog" produced an unexpected new value for datadog_synthetics_test.test_api["gitlab_readiness"], but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .assertion[0].target: was cty.StringVal("20[40]"), but now cty.StringVal("0")
```
---
```
Error: error updating synthetics test: 400 Bad Request: {"errors": ["0.type: 0 is not of type 'string'\n\nFailed validating 'type' in schema[0]:\n    {'maxLength': 51200, 'type': 'string'}\n\nOn instance:\n    0"]}
```

### Expected Behavior

It should have created the synthetic monitor using the regex.

### Actual Behavior

It converted the regex to 0 and made the API request fail to DataDog.

### Steps to Reproduce

1. Create a `datadog_synthetics_test` resource.
1. Add a `statusCode` assertion with `matches` and a regex as the `target`
1. Run `terraform apply` to see the error

**Comment by therve** [comment]
Thanks for your report. I haven't reproduced yet, but considering the code at https://github.com/DataDog/terraform-provider-datadog/blob/f350de0ec8fc8bab2d5a43d6c4847b0a88c00329/datadog/resource_datadog_synthetics_test_.go#L556 that makes sense. We'll need to come up with a workaround.

**Comment by zachkknowbe4** [comment]
@zippolyte @therve Just attempted to use the new provider this morning with this fix, unfortunately it still is sending a `0` to the API, thus the status code ends up being `0` instead of `20[04]`.

**Comment by zippolyte** [comment]
That's strange. We added some test cases exactly for this and they pass.
Also I cannot reproduce locally. With version 2.20.0 of the provider, the API does return the proper "20[04]" target string.
Are you sure the provider was actually upgraded ?

**Comment by zachkknowbe4** [comment]
@zippolyte Actually, I see my mistake, I did
```
  assertion {
    type     = "statusCode"
    operator = "is"
    target   = "20[04]"
  }
```
instead of 
```
  assertion {
    type     = "statusCode"
    operator = "matches"
    target   = "20[04]"
  }
```
Doesn't look like there was any validation to make sure the regex was used with the correct operator. I tested it with the correct operator and the API updated correctly.

**Comment by zippolyte** [comment]
OK good to know ! We'll see if we can add validation for this.
