### ISSUE TITLE
Monitor check ignore ok threshold

### ISSUE THREAD

**Issue by Adiii717** [DataDog/terraform-provider-datadog#796]
### Terraform Version

Terraform v0.13.5

### Affected Resource(s)

-   datadog_monitor

### Terraform Configuration Files

```hcl


provider "datadog" {
  api_key = var.datadog_api_key
  app_key = var.datadog_app_key
}

terraform {
  required_providers {
    datadog = {
      source = "terraform-providers/datadog"
      #https://github.com/DataDog/terraform-provider-datadog/tags
      version = ">= 2.15.0"
    }
  }
}

resource "datadog_monitor" "kafka_lagging_monitor" {
  count               = Count
  name                = "Name"
  require_full_window = false
  evaluation_delay    = 400
  type                = "metric alert"
  message             = "Message here"
  query               = "avg(${var.kafka_avg_time}):avg:kafka.consumer_lag{service:${var.service_name},environment:${var.environment},topic:${var.kafka_topic_name[count.index]}} > ${var.kafka_alert_threshold}"
  thresholds = {
    ok       = var.kafka_recovery_threshold
    critical = var.kafka_alert_threshold
  }
}
```

### Plan Output
```hcl
  resource "datadog_monitor" "kafka_lagging_monitor" {
        evaluation_delay    = 300
        id                  = "26334304"
        include_tags        = true
        locked              = false
        message             = message
        name                = "name"
        new_host_delay      = 300
        notify_audit        = false
        notify_no_data      = false
        priority            = 0
        query               = "avg(last_30m):avg:kafka.consumer_lag{service:kafka,environment:prod,topic:topic_name} > 1000"
        renotify_interval   = 0
        require_full_window = false
        silenced            = {}
        tags                = []
        threshold_windows   = {}
      thresholds          = {
          "critical" = "1200"
            "ok"       = "800"
        }
        timeout_h           = 0
        type                = "metric alert"
    }
```

### Expected Behavior
```
       thresholds          = {
          "critical" = "1200"
            "ok"       = "800"
        }
```
On the console, "OK" should be 800

<img width="629" alt="Screenshot 2020-12-19 at 9 37 35 AM" src="https://user-images.githubusercontent.com/23054298/102680842-02c5e180-41de-11eb-8447-dae3b0cc5080.png">

### Actual Behavior

On the console, the OK threshold is empty, while it should be 800
```
       thresholds          = {
          "critical" = "1200"
            "ok"       = "800"
        }
```

<img width="629" alt="Screenshot 2020-12-19 at 9 34 18 AM" src="https://user-images.githubusercontent.com/23054298/102680831-e7f36d00-41dd-11eb-8601-71d6dc2bf1ff.png">

### Steps to Reproduce

1. `terraform apply`
2. Open Datadog Monitoring dashboard and check the threshold section

**Comment by therve** [comment]
Hi,

The field you see in the UI is the `critical_recovery` field, not the `ok` one. We don't seem to display `ok` anymore, not sure it's super relevant.

**Comment by Adiii717** [comment]
@therve seems working, thanks. I can see in the [documentation](https://docs.datadoghq.com/monitors/guide/monitor_api_options/) as well.

But I did not find any information about `ok`, in most of the example `ok` is used in terraform check. can you please provide any link to documentation or any information when and how `ok` can help in check?

**Comment by therve** [comment]
I found it: `ok` is only relevant when for `service check` monitor type. We'll update the documentation.
