### ISSUE TITLE
'timeout' argument is invalid in API Synthetics Test (SSL)

### ISSUE THREAD

**Issue by samirageb** [DataDog/terraform-provider-datadog#828]
### Terraform Version
14.4

### Affected Resource(s)

-   datadog_synthetics_test

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    datadog = {
      source = "DataDog/datadog"
      version = "2.19.1"
    }
  }
}

provider "datadog" {
  api_key = "xxx"
  app_key = "xxx"
}

resource "datadog_synthetics_test" "test_ssl" {
  type = "api"
  subtype = "ssl"
  request = {
    host = "example.org"
    port = 443
    timeout = 10
  }
  locations = [ "aws:eu-central-1" ]
  options_list {
    tick_every = 900
  }
  name = "An API test on example.org"
  status = "live"
}
```

### Debug Output
https://gist.github.com/samirageb/959a5c4caef031fbd6f15ca72908bdf9

### Panic Output

None

### Expected Behavior
Resource should have been created without issue in Datadog

### Actual Behavior
400 error bad request during some sort of schema validation

### Steps to Reproduce

1. Paste above HCL code into main.tf
2. Add valid DD API/APP key in provider config
3.  `terraform init`  and then `terraform apply`

### Important Factoids
- Removing this timeout property WILL create the resource successfully
- Originally this was discovered using the Pulumi DD provider, and I've traced it back to TF implementation. The issue with Pulumi however, is that this optional timeout property is automatically injected into every pulumi request as though it's 'required'. **Effectively you cannot create an API SSL Synthetics Test with Pulumi at all**. See reference below
- The TF documentation should also be updated to reflect that this property is actually not valid for SSL tests: https://registry.terraform.io/providers/DataDog/datadog/latest/docs/resources/synthetics_test#attributes-reference

### References

Issue filed in Pulumi Provider for Datadog: [reference](https://github.com/pulumi/pulumi-datadog/issues/102)

**Comment by therve** [comment]
Thanks for your report. You're right that this is a documentation mismatch: `timeout` is only supported by HTTP tests. We can't fix the pulumi side of things unfortunately.

**Comment by samirageb** [comment]
Hm... Ok. Anyway to bring this up internally on the Pulumi side? Issue activity there seems like it might be awhile before this gets addressed.

**Comment by therve** [comment]
Can you open a support ticket? Someone here may know about Pulumi and see how to address this. Thanks.

**Comment by samirageb** [comment]
@therve Ok thanks. Opened under request #433628

**Comment by stack72** [comment]
Hi @therve 

I work on Pulumi so thought I'd jump in here. In the linked PR you made, the entry has been removed from the docs but not from the codebase itself. I am now confused as to why that would be the case?

Paul

**Comment by therve** [comment]
Hi @stack72 , the same block is used regardless of the type of test done, but only valid for a specific type (HTTP).

**Comment by stack72** [comment]
Hi @therve 

So if the parameter is valid, then why remove the docs rather than just update the docs? 

P.

**Comment by therve** [comment]
It's documented in the section where it's valid, and removed in the section where it's not.

**Comment by stack72** [comment]
Got it - my apologies for my lack of understanding here

P.
