### ISSUE TITLE
Feature Request: Add better support for Browser Tests and/or Document surrounding

### ISSUE THREAD

**Issue by Gowiem** [DataDog/terraform-provider-datadog#830]
The current documentation for the Synthetic Test resource states the following: 

> Support for Synthetics Browser test is limited when creating steps. Some steps types (like steps involving elements) cannot be created, but they can be imported.

This really limits the ability to use this resource as it doesn't seem I can do much beyond assert the URL as far as I understand? I'm creating these synthetic tests for dozens of single tenant environments so importing tests isn't really an option. 

Would like to know your folks thoughts / understand this a bit better.

**Comment by adampeklay** [comment]
Does Datadog have any plans on supporting element usage and/or updating the documentation showing examples? 

Useful examples:
- Logging into a website using an element "username" and "password", then clicking on "submit". 
- Going to a search engine and performing a search, then looking for a result using elements

Not having any browser_step.params and elements in the documentation makes trying to figure this out very challenging.  I didn't want to chime in just to bump this issue, but to follow up with some good examples and hopefully get some attention on this soon.

I'd rather not build out dozens of synthetic browser test by hand.

**Comment by james-tractable** [comment]
Any update on this? Just some examples of how to do a few common checks would be very helpful.

**Comment by cosme-ddog** [comment]
Hello everyone, these steps are indeed supported in fact.

They can all be created using a **user locator**. Today you also have to set a default value for our **multilocator**, like so:

```params {
        element= jsonencode({
           "multiLocator" : { "placeholder" : true }
        })
       element_user_locator {
         value {
           type = "xpath"
           value = "some_xpath_value"
         }
       }
     }```

Having to set the **multilocator** will soon be fixed.

We do recommend initially importing a test that was created from the UI though, it provides great examples that are relevant to your flow.
