### ISSUE TITLE
[Feature Request] create datadog_integration_opsgenie

### ISSUE THREAD

**Issue by Tony-Proum** [DataDog/terraform-provider-datadog#836]
### Terraform Version

Terraform v0.14.2

### Affected Resource(s)
- datadog_integration_opsgenie

### Expected Behavior

We would like to have find a way to automatically configure OpsGenie integrations as we are using this solution to manage our on-calls and escalation policies

### Actual Behavior

Seems like there is no way to do this with terraform

**Comment by mschurenko** [comment]
👍

**Comment by smitthakkar96** [comment]
+1 for this. Even the API doesn't support adding this so cannot even do local-exec and call the API.

**Comment by andymac4182** [comment]
This would be great. We are looking at moving from Pageduty to Opsgenie and this will be a requirement for us.

**Comment by nitrocode** [comment]
@smitthakkar96 just to clarify. It seems that the [`opsgenie_api_integration`](https://registry.terraform.io/providers/opsgenie/opsgenie/latest/docs/resources/api_integration#attributes-reference) will export the `api_key` and the `id` but the [datadog API](https://docs.datadoghq.com/api/latest/) will not allow us to set the opsgenie integration.

**Comment by tomellis91** [comment]
+1 please :)

**Comment by therve** [comment]
This has been done in #1466
