### ISSUE TITLE
[Feature Request] Add log-based metrics support

### ISSUE THREAD

**Issue by ahf90** [DataDog/terraform-provider-datadog#837]
It would be great to support log-based metrics operations via Terraform.

CRUD for log-based metrics is available via the Datadog API: https://docs.datadoghq.com/api/v2/logs-metrics/

Currently, these metrics have to be created manually in the console.

**Comment by therve** [comment]
It's in implement in #823 so should be released soon. Thanks.

**Comment by ahf90** [comment]
Great, thanks
