### ISSUE TITLE
Support terraform providers lock

### ISSUE THREAD

**Issue by kenchan0130** [DataDog/terraform-provider-datadog#840]
We need two checksums when the development environment on Mac and CI/CD on Linux.

### Terraform Version

```sh
terraform -v
Terraform v0.14.2
+ provider registry.terraform.io/datadog/datadog v2.19.1
```

### Debug Output

https://gist.github.com/kenchan0130/60f7f414e87866dd5c96a01d2223558c

### Expected Behavior

```sh
terraform providers lock -platform=darwin_amd64 -platform=linux_amd64
```

I expect that this command will not cause any errors and that the lockfile will be updated.

### Actual Behavior

It looks like the linux checksum cannot be verified and is causing an error.

```log
- Fetching datadog/datadog 2.19.1 for darwin_amd64...
- Obtained datadog/datadog checksums for darwin_amd64 (signed by a HashiCorp partner, key ID FB70BE941301C3EA)
- Fetching datadog/datadog 2.19.1 for linux_amd64...

Error: Could not retrieve providers for locking

Terraform failed to fetch the requested providers for linux_amd64 in order to
calculate their checksums: some providers could not be installed:
- registry.terraform.io/datadog/datadog: the current package for
registry.terraform.io/datadog/datadog 2.19.1 doesn't match any of the
checksums previously recorded in the dependency lock file.
```

### Steps to Reproduce

```terraform
# sample.tf
terraform {
  required_version = "0.14.2"

  required_providers {
    datadog = {
      source  = "datadog/datadog"
      version = ">= 2.18.0"
    }
  }
}

variable "datadog_api_key" {}
variable "datadog_app_key" {}

provider "datadog" {
  api_key = var.datadog_api_key
  app_key = var.datadog_app_key
}
```

You can reproduce this phenomenon by simply running the following command in same directory where the above file exists.

```sh
terraform init
terraform providers lock -platform=darwin_amd64 -platform=linux_amd64
```

### Important Factoids

```sh
sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.6
BuildVersion:	18G7016
```

**Comment by therve** [comment]
I just tried that exact scenario and it worked for me. Any other specific info about your environment that could influence this?

**Comment by therve** [comment]
Can you remove your `.terraform.lock.hcl` file and retry? Thanks.

**Comment by kenchan0130** [comment]
> Can you remove your `.terraform.lock.hcl` file and retry? Thanks.

Would you expect it to run on macOS devices?
I deleted `.terraform.lock.hcl` and tried again, but the exact same situation was reproduced.

**Comment by therve** [comment]
> Would you expect it to run on macOS devices?

I'm on 10.15.7 myself, so yes. Can you paste the content of your lock file.

**Comment by kenchan0130** [comment]
My `.terraform.lock.hcl` is as follows.

```terraform
# This file is maintained automatically by "terraform init".
# Manual edits may be lost in future updates.

provider "registry.terraform.io/datadog/datadog" {
  version     = "2.19.1"
  constraints = ">= 2.18.0"
  hashes = [
    "h1:unoyy1BcxjxTpjpNSLlie/Zs4kK0133riDDjQsxIBKs=",
  ]
}
```

**Comment by therve** [comment]
OK, sorry but not idea what's happening here. You only get the checksum of the darwin build it seems. Can you try opening an issue in terraform itself? I don't see how we can do something in our provider which would influence this. Thanks.

**Comment by kenchan0130** [comment]
This was due to [the cache setting](https://github.com/hashicorp/terraform/issues/27388). As this is a terraform issue, I will close this issue. 
Thank you.
