### ISSUE TITLE
Bug in datadog monitor resource example

### ISSUE THREAD

**Issue by ciscoios** [DataDog/terraform-provider-datadog#857]
Hi there,

It looks like your datadog_monitor resource example contains an issue regarding migrating "thresholds" to "monitor_thresholds" parameter which was released in datadog provider version 2.20.0. Please take a look into the issue description below.

### Terraform Version
0.12.29

### Affected Resource(s)

Please list the resources as a list, for example:

-   datadog_monitor

### Expected Behavior

What should have happened?
According to datadog_monitor resource example (https://github.com/DataDog/terraform-provider-datadog/blob/master/examples/resources/datadog_monitor/resource.tf) terraform should have handled this code 
  monitor_thresholds {
    warning           = 2
    warning_recovery  = 1
    critical          = 4
    critical_recovery = 3
  }

### Actual Behavior

What actually happened?
Actually I get the following output - 
Missing key/value separator

../../modules/dd-monitors/main.tf line 11: Expected an equals sign ("=") to
mark the beginning of the attribute value.
Error: Missing key/value separator

So could you please clarify is it expected behaviour or example contains an error that needs to be fixed?
And what documentation should I refer to regarding "monitor_thresholds" parameter?

**Comment by zippolyte** [comment]
Hi !
This example you linked works perfectly fine for me with the datadog provider 2.20.0 and terraform 0.12.29.

Can you paste the entire content of your `../../modules/dd-monitors/main.tf` file (after redacting sensitive info if any) ?

**Comment by ciscoios** [comment]
I've just tested a code from the example and it works as expected - 
# Create a new Datadog monitor
resource "datadog_monitor" "foo" {
  name               = "Testing - provider 2.20.0"
  type               = "metric alert"
  message            = "Monitor triggered. Notify: @test@test.com"
  #escalation_message = "Escalation message @pagerduty"

  query = "avg(last_1h):avg:aws.ec2.cpu{environment:foo,host:foo} by {host} > 4"

  monitor_thresholds {
    warning           = 2
    warning_recovery  = 1
    critical          = 4
    critical_recovery = 3
  }

  notify_no_data    = false
  renotify_interval = 60

  notify_audit = false
  timeout_h    = 60
  include_tags = true

  # ignore any changes in silenced value; using silenced is deprecated in favor of downtimes
  lifecycle {
    ignore_changes = [silenced]
  }

  tags = ["foo:bar", "baz"]
}

I'll retest my code located in ../../modules/dd-monitors/main.tf during next week and let you know.

**Comment by ciscoios** [comment]
Hi. I've worked out how to correctly updated code in my module.
resource "datadog_monitor" "general" {
  for_each   = local.monitor_settings_without_threshold
  name       = each.value.name
  type       = each.value.type
  query      = each.value.query
  message    = each.value.message
  tags       = each.value.tags
  #thresholds = each.value.thresholds
   monitor_thresholds {
    critical = each.value.thresholds["critical"]
  } 
}
So, I've just change thresholds = each.value.thresholds
with
monitor_thresholds {
    critical = each.value.thresholds["critical"]
  } 
  
And all is working as expected. This issue can be closed.
