### ISSUE TITLE
[Feature Request] Support groupby_simple_monitor option using log alert

### ISSUE THREAD

**Issue by kenchan0130** [DataDog/terraform-provider-datadog#873]
### Terraform Version

```sh
$ terraform -v
Terraform v0.14.2
+ provider registry.terraform.io/datadog/datadog v2.20.0
```

### Affected Resource(s)

datadog_monitor

### Expected Behavior

I want to define `groupby_simple_monitor` in terraform and customize the alert.

### Actual Behavior

It seems like there is no way to do this with datadog terraform provider.

---

If it is difficult to provide individual items, it would be great if the provider could provide items that allow you to freely set some of the values in the json output by the "export monitor" function.

**Comment by therve** [comment]
Closes #952
