### ISSUE TITLE
Terraform Apply: Getting SLO definition is throttled

### ISSUE THREAD

**Issue by vivasaayi** [DataDog/terraform-provider-datadog#907]
SLO creation via Terraform is throttled

### Terraform Version

Terraform v0.12.29
+ provider.datadog v2.19.1

### Affected Resource(s)

SLOs

### Expected Behavior

DD Provide should consider the DD rate-limiting and send fewer requests. 

### Actual Behavior

Terraform apply failed due to rate limiting.

```
Error: error getting service level objective: 429 Too Many Requests: {"errors": ["Rate limit of 100 requests in 10 seconds reached. Please try again later."]}
```

### Steps to Reproduce

We are running more than 300 microservices, which are owned by different teams. So, we are managing hundreds of SLO using terraform.

This was working earlier - but looks like a recent API change started to throttle requests.

**Comment by skarimo** [comment]
Hi there, thanks for reaching out. Could you open a support ticket regarding this: https://docs.datadoghq.com/help/
Thanks!

**Comment by matt-canty-dragon** [comment]
Also experiencing this issue. Could it be related to the recent release: https://github.com/DataDog/terraform-provider-datadog/releases/tag/v2.21.0

In the notes:
> Backport performance fix to SDK v1.

The monitors at least I know are on V1.

**Comment by therve** [comment]
Hello,

This is not a client issue, this is a backend change. As mentioned if you can contact support they can raise that limit for you. Thanks.

**Comment by vivasaayi** [comment]
For us, I increased the rate limit by raising a DataDog support ticket, and after that, I am able to successfully apply the terraform.

However, is it possible to handle throttling in the DataDog TF provider natively? A similar problem and solution can be found here: https://registry.terraform.io/providers/ns1-terraform/ns1/latest/docs#ns1_rate_limit_parallelism

**Comment by therve** [comment]
Not unfortunately we don't have any way to configure throttling in the provider itself. One workaround might be to reduce terraform parallelism, but that will impact all API calls.

**Comment by nmuesch** [comment]
I've checked in with the appropriate team internally, and they've reevaluated the default limits and set a general increase for these APIs to avoid hitting these rate limits in the future, thanks for raising! I'll go ahead and close this issue for now, but let us know if you continue to experience any issues here.
