### ISSUE TITLE
Please add datadog_service_level_objective data source to provider

### ISSUE THREAD

**Issue by anoonan-zz** [DataDog/terraform-provider-datadog#911]
```
We use the DD provider to manage some, but not all dashboards in DataDog.  One common pattern we use is to build out a product specific dashboard and then consolidate some basic stats about that product with other products in a team or group overview dashboard.  Today, that is done in a central workspace that many teams modify to add their dashboards, exporting the widget information that is then consumed by modules that build the central dashboards.  This leads to a very tightly coupled design that results in a workspace that becomes larger and larger, and users have begun to bump into each other.  

Splitting the workspace up is possible, but accessing remote state for those workspaces ends up loading a very large amount of data in the central workspace memory due to an inability to pull "part" of a state.

If the dashboard data source supported exporting additional data about the dashboards, especially the widget information (id, text), that would allow for more decoupled designs, where we search for dashboards, and pull the widgetids out to build the centralized dashboards.
```
Editing this to preserve the original statement, but see conversation below, this initial description of the issue was wrong.

**Comment by therve** [comment]
Hello,

Can you detail a bit more what you would do? Because I don't understand what you use widget IDs for: AFAIU they can't be referenced elsewhere, so I don't get what exposing them in the datasource offer you.

Ie, if you had, `data.datadog_dashboard.widgets[0].id` available, where would you feed it?

Thanks!

**Comment by anoonan-zz** [comment]
This was explained poorly to me, as I'm digging into this, most of the description is wrong, so this ticket is a little premature.  Here's a little better description:

There seem to be two "cross-module" use cases:

1. A central SLO dashboard.  This SLO dashboard builds widgets using the SLO ids of the "datadog_service_level_objective" resources built out for a category of SLOs, like Availability.  So a product team, A, calls a module with inputs that sets up values for various SLOs, like availability and latency.  The result is a series of datadog_monitor, and datadog_service_level_objective, and few other resources, but NOT a dashboard, as I previously understood.  The outputs of this module include the id of the SLO resources.  Team A then edits the central slo_dashboard code to add the widgets for their products, using the slo_id output from their product's module.

2. A site "Overview" dashboard.  This one is a little more complex.  This dashboard manipulates the queries used in the monitors and SLOs to generate widgets that show traffic stats gathered from our nginx and other metric emitting systems.  These queries go through several phases of manipulation both in the module, and in the overview dashboard, so, given that you can pull the queries from the datadog_monitor data source, there probably isn't much of an ask here.

So to rephrase, I suspect that the thing that would help decouple would to be to add a datadog_service_level_objective data source that outputs the slo_id.

**Comment by therve** [comment]
Ah that's makes much more sense! So we could rephrase the issue as "Add a datadog_service_level_objective datasource"?

**Comment by anoonan-zz** [comment]
Yep!  I've edited the description and modified the first comment to more correctly reflect the ask.

**Comment by apollocreed** [comment]
Yes I really would like to have this feature also !
It will help to link existing SLO to screenboard 
Thanks

**Comment by adrien-f** [comment]
Would you be open to a pull request for this feature?

According to [API](https://docs.datadoghq.com/api/latest/service-level-objectives/):

* ids: A comma separated list of the IDs of the service level objectives objects.
* query: The query string to filter results based on SLO names.
* tags_query: The query string to filter results based on a single SLO tag.
* metrics_query: The query string to filter results based on SLO numerator and denominator.

```hcl
data "datadog_slo" "my_project_reliability_slo" {
  id = "e9b8c777b99a58869c7c3e6ea205bff7"
  name_filter         = "SLO - Project - Reliability"
  tags_filter = "project:foo"
  metrics_filter = "aws.elb.request_count"
}

# or datadog_slos ?
data "datadog_slo_list" "project_slos" {
  ids = ["e9b8c777b99a58869c7c3e6ea205bff7"]
  name_filter = "Foo"
  tags_filter = "project:foo"
  metrics_filter = "aws.elb.request_count"
}
```

Speaking of which, the query key says "tags" as in plural but seems to only support a single tag? UI supports `env:prd AND site:www.foo.tld` but API doesn't look like it does, I suppose it's currently done in the UI? So should the `tags_filter` actually be `tag_filter` ? Let me know what you think 😄

**Comment by therve** [comment]
Sure, contributions are very welcome. I think we should keep the name in the API,ie `tags_query` and `metrics_query`. The name is plural because it operates on tags and metrics.

**Comment by adrien-f** [comment]
Awesome :)

Which fields would you like to expose? From what I read from the issue and our personal use case, only the ID is fine for Dashboarding usage so we could start with this. Maybe the name as well?

**Comment by therve** [comment]
Right we can include id/name/type for now.

**Comment by adrien-f** [comment]
@anoonan-zz @apollocreed would you be able to test out the linked PR and see if it fits your needs as well 🙌 ?

**Comment by apollocreed** [comment]
Yeah sure I'll give you feedback ASAP

**Comment by apollocreed** [comment]
Well thanks a lot for this MR it is working like a charm:
## input
~~~hcl
data "datadog_service_level_objective" "testslo"{
  name_query = "CORTEX"
  tags_query = "test"
  metrics_query = ""
  #id = "a990b9ae782f51c499feba57dbf5c9cd"
}

data "datadog_service_level_objectives" "testslos"{
  #name_query = "CORTEX"
  tags_query = "cortex"
  metrics_query = ""
  #id = "a990b9ae782f51c499feba57dbf5c9cd"
}
output "slo" {
  value = data.datadog_service_level_objective.testslo.name
}
output "sloid" {
  value = data.datadog_service_level_objective.testslo.id
}
output "slos" {
  value = data.datadog_service_level_objectives.testslos.slos
}
output "slos1" {
  value = data.datadog_service_level_objectives.testslos.slos[1].id
}
output "slosid" {
  value = data.datadog_service_level_objectives.testslos.id
}

~~~
## output
~~~bash
Terraform will perform the following actions:

Plan: 0 to add, 0 to change, 0 to destroy.

Changes to Outputs:
  + slo    = "Availablity of  Engines Around The World"
  + sloid  = "7f887d3744c3571bba271addcfae4a52"
  + slos   = [
      + {
          + id   = "a990b9ae782f51c499feba57dbf5c9cd"
          + name = "Availability of Engines"
          + type = "monitor"
        },
      + {
          + id   = "ddac0b175a5f5d1d9f04f2d610106546"
          + name = "Availability Engines"
          + type = "monitor"
        },
      + {
          + id   = "41b04991e2985518aacffb864b1da3aa"
          + name = "Availability of Engines"
          + type = "monitor"
        },
      + {
          + id   = "7f887d3744c3571bba271addcfae4a52"
          + name = "Availablity of  Engines Around The World"
          + type = "monitor"
        },
    ]
  + slos1  = "ddac0b175a5f5d1d9f04f2d610106546"
  + slosid = "datadog-service-level-objectives"

~~~

Do you think that it is possible to add the resource creation also ? 
I might be able to help, however I'm not a Go person but I'm eager to learn.
I'm french also by the way :wink: 

thanks again
