### ISSUE TITLE
Provider can't apply exported dashboard, refuses template_variable_presets without template_variable

### ISSUE THREAD

**Issue by mgarstecki** [DataDog/terraform-provider-datadog#926]
### Terraform Version

```
$ terraform-0.14.6 -v
Terraform v0.14.6
+ provider registry.terraform.io/datadog/datadog v2.21.0
```

### Affected Resource(s)
- datadog_dashboard

### Terraform Configuration Files

Simplified to best showcase the issue.

```hcl
resource "datadog_dashboard" "redacted_id" {
  is_read_only = "false"
  layout_type  = "ordered"
  title = "Sample dashboard"

  template_variable {
    default = "prod"
    name    = "env"
    prefix  = "env"
  }

  template_variable {
    default = "eu"
    name    = "continent"
    prefix  = "continent"
  }

  template_variable_preset {
    name = "prod-eu"
  }

  template_variable_preset {
    name = "prod-us"

    template_variable {
      name  = "continent"
      value = "us"
    }

    template_variable {
      name  = "env"
      value = "prod"
    }
  }

  widget {
    timeseries_definition {
      request {
        display_type   = "line"
        on_right_yaxis = "false"
        q              = "max:kubernetes_state.deployment.replicas_desired{$env,$continent,kube_deployment:badoom3} by {kube_deployment}, max:kubernetes_state.deployment.replicas_unavailable{$env,$continent,kube_deployment:badoom3} by {kube_deployment}.rollup(max)"
      }
    }
  }
}

```

### Debug Output

https://gist.github.com/mgarstecki/1a20c39f5fc6e5f3dcb76c29e42b6f39

### Panic Output

None

### Expected Behavior

The plan finishes without errors.

### Actual Behavior

The plan gives this error:

```
Error: "template_variable_preset.0.template_variable": required field is not set

  on dashboard.tf line 1, in resource "datadog_dashboard" "redacted_id":
   1: resource "datadog_dashboard" "redacted_id" {
```

### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:

1. `terraform plan` or `terraform apply`

### Important Factoids

This TF configuration was generated with [Terraformer](https://github.com/GoogleCloudPlatform/terraformer), but a manual export of the dashboard to JSON through the Datadog UI also returns an empty block, so this seems correct behavior from Terraformer. 

`template_variable_preset` blocks without `template_variable` subblocks look legit to the Datadog API, and can be imported through the Datadog UI, so this looks like to me like the TF provider is too restrictive.

**Comment by therve** [comment]
Hi,

It doesn't make sense to have a preset that doesn't map variables, does it? I understand your argument that the UI allows it, but I wonder if it catches more unexpected errors this way. In your case, you want the variable to get back to the default, that's why you don't set anything?

Thanks.

**Comment by mgarstecki** [comment]
Hi,
Thank you for your fast answer @therve :slightly_smiling_face: 

> It doesn't make sense to have a preset that doesn't map variables, does it? I understand your argument that the UI allows it, but I wonder if it catches more unexpected errors this way.

As I understand it, an empty preset is a _named_ copy of the default preset. This kind of duplication is heavily used in our organization: having a named preset named _prod_ is easier to use than wondering if the default settings target _prod_. Feels like a deliberate and useful feature for me.

More practically, this issue prevents Terraformer from generating a working configuration from the data returned by the Datadog API. It feels to me like a wrong approach for Terraformer to modify the returned data before importing it: it would mean the imported dashboard definition would be different from what is actually deployed in Datadog. It would also likely mean a `terraform plan` right after the import would generate a diff :slightly_frowning_face: 

I believe the Datadog provider should accept what the underlying API accepts without imposing additional restrictions on it, to provide the same capabilities. This looks like the convention for other Terraform providers :slightly_smiling_face:

**Comment by therve** [comment]
Thanks for your reply, that makes a lot of sense. It's clearly something supported by the UI and API, we'll fix it.
