### ISSUE TITLE
Support Composite Monitors Message

### ISSUE THREAD

**Issue by stanislavkozlovski** [DataDog/terraform-provider-datadog#940]
It would be useful if the terraform provider would support the ability to specify any inner monitor's messages from a composite monitor. An example speaks best:

## Example

```terraform
resource "datadog_monitor" "A" {
  message = "A"
}
resource "datadog_monitor" "B" {
  message = "B"
}

resource "datadog_monitor" "Composite" {

  query = "A || B"

  message = <<EOM
    A or B failed!
    ${alert.message}
  EOM
}
```

**Comment by nmuesch** [comment]
Hey @stanislavkozlovski Thanks for the issue report. 

Let me know if I'm not fully following, but could you do something like:

```
resource "datadog_monitor" "Composite" {
  query = "A || B"
  message = <<EOM
    A or B failed!
   ${datadog_monitor.A.message}
  EOM
}
```

**Comment by stanislavkozlovski** [comment]
Hi @nmuesch, thanks fr the prompt response.

Your example would always print A's message if I understand correctly. I would prefer it to print the alerting monitor's message - e.g if A was false and B was true, I'd want to see B's message. Does that make sense?

**Comment by nmuesch** [comment]
Ahh thanks for the clarification I believe I understand your use case. I checked in internally and there isn't a way to do this today. Given the feature here would involve a new variable in the monitor message itself (and not really a terraform variable) can you open a ticket with support?

**Comment by stanislavkozlovski** [comment]
Could you clarify? Should I ask support to add support for this variable in the datadog UI, backend, or smoewhere else?

**Comment by skarimo** [comment]
Hello, this is now possible by using conditionals in your composite monitors message. See here: https://app.datadoghq.com/release-notes/customize-the-content-of-your-composite-monitor-notification-message-based-on-which-child-monitor-is-causing-an-alert

```
{{#is_exact_match "a.status" "Alert"}}
Consumer stopped processing messages. Investigate using runbook below.
{{/is_exact_match}}

{{#is_exact_match "b.status" "Alert"}}
Producer stopped producing messages. Investigate using runbook below.
{{/is_exact_match}}
```
