### ISSUE TITLE
Terraform init: unable to verify checksum

### ISSUE THREAD

**Issue by jk1m** [DataDog/terraform-provider-datadog#941]
### Terraform Version

Terraform v0.12.30

### OS Version

macOS 11.2.1

### Expected Behavior

Terraform downloads the datadog provider

### Actual Behavior

```
Initializing the backend...

Initializing provider plugins...
- Checking for available provider plugins...

Error verifying checksum for provider "datadog"
The checksum for provider distribution from the Terraform Registry
did not match the source. This may mean that the distributed files
were changed after this version was released to the Registry.
```

### Steps to Reproduce

1. Using Terraform v0.12.30, run `terraform init`

**Comment by skarimo** [comment]
I believe this might be related to https://github.com/hashicorp/terraform/issues/27872
Could you try again as the terraform outage seems to now have been resolved.

**Comment by jk1m** [comment]
Thanks @skarimo . Sorry, I should have checked there first. All is well now, thank you.
