### ISSUE TITLE
Unable to use Datadog provider - eu

### ISSUE THREAD

**Issue by chfrodin** [DataDog/terraform-provider-datadog#946]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version

0.14.7

### Affected Resource(s)

datadog_provider

### Terraform Configuration Files

```hcl
provider "datadog" {
  api_key = var.datadog_api_key
  app_key = var.datadog_app_key
}

data "datadog_dashboard" "test" {
  name = "VM Status"
}
```

### Debug Output

Error: Invalid or missing credentials provided to the Datadog Provider. Please confirm your API and APP keys are valid and are for the correct region, see https://www.terraform.io/docs/providers/datadog/ for more information on providing credentials for the Datadog Provider

### Expected Behavior

Data gathered from the dashboards

### Actual Behavior

Error using the provider

### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:

1. `terraform apply`

-   GH-1234

Notes:
The APP key and API key are both valid, as I have created several of them and tried them all. Same result every time.

The keys are generated on datadoghq.eu, is there a difference for the provider when it comes to eu and us?

**Comment by zippolyte** [comment]
Hi, yes absolutely there is a difference. You have to set the `api_url` parameter in the provider configuration.
See here https://registry.terraform.io/providers/DataDog/datadog/latest/docs#schema

**Comment by chfrodin** [comment]
> Hi, yes absolutely there is a difference. You have to set the `api_url` parameter in the provider configuration. Value for eu should be `https://api.datadoghq.eu`.
> See here https://registry.terraform.io/providers/DataDog/datadog/latest/docs#schema

Thank you so much. I totally entirely missed that part. Kind of guessed what the problem was. Thank you! Closing issue.
