### ISSUE TITLE
`Error: : invalid or unknown key: id` on datadog dashboard

### ISSUE THREAD

**Issue by sparky005** [DataDog/terraform-provider-datadog#947]
### Terraform Version

```Terraform v0.13.6
+ provider registry.terraform.io/hashicorp/aws v3.29.1
+ provider registry.terraform.io/terraform-providers/datadog v2.21.0
```

### Affected Resource(s)

-   datadog_dashboard

### Terraform Configuration Files
Any datadog dashboard with an `id` parameter specified

### Expected Behavior

Terraform should plan / apply the dashboard with my chosen ID

### Actual Behavior

`Error: : invalid or unknown key: id`

### Steps to Reproduce

`terraform plan` or `terraform apply` any datadog dashboard with an ID parameter set.

### Important Factoids

The [docs](https://registry.terraform.io/providers/DataDog/datadog/latest/docs/resources/dashboard#optional) mention that an ID parameter can be set, but the [code](https://github.com/DataDog/terraform-provider-datadog/blob/master/datadog/resource_datadog_dashboard.go) doesn't actually have that parameter. So either the docs need to be updated or the provider does, I'm just not sure which.

**Comment by therve** [comment]
`id` is a protected attribute in Terraform. We switched to generated documentation and it started exposing this I think (because It's an attribute? Not sure why it's not marked as such). We'll update the doc, thanks.

**Comment by sparky005** [comment]
Got it, thanks @therve!

**Comment by sandeeplamb** [comment]
Faced same here and this took me here. Clear now.
Was working to get the dashboard URL in outputs. If I know the ID before, it's possible to make dashboard URL.
But it's possible via like this too. I don't need to know the ID beforehand.

`output "dashboard_url" {
  value = join("", [
    "https://app.datadoghq.eu",
    datadog_dashboard.dashboard_resource_name.url
  ])
  description = "URL for the dashboard"
}
`

**Comment by nmuesch** [comment]
Thanks for the report on this. As therve noted, we're using the `tfplugindocs` generation tool. I've opened an issue upstream (and a corresponding PR to attempt a fix) - https://github.com/hashicorp/terraform-plugin-docs/issues/45
