### ISSUE TITLE
datadog_service_level_objective resource unexpectedly transforms tags

### ISSUE THREAD

**Issue by hockeygoonnorm** [DataDog/terraform-provider-datadog#961]
The datadog_service_level_objective resource unexpectedly transforms tags by doing the following:

- Spaces are replaced with underscores
- Capital letters are converted to lowercase
- Special characters are removed. 

Tag behavior should be consistent across all resources. 

### Terraform Version

Terraform v0.13.5
provider registry.terraform.io/datadog/datadog v2.21.0

### Affected Resource(s)

datadog_service_level_objective

### Terraform Configuration Files

```hcl

provider "datadog" {
  api_key = var.datadog_api_key
  app_key = var.datadog_app_key
}

variable "datadog_app_key" {}
variable "datadog_api_key" {}

resource "datadog_monitor" "test" {
  name                = "Test Monitor"
  type                = "service check"
  message             = "Someting broke"
  query     = "\"aws.status\".over(\"service:ec2\").last(2).count_by_status()"
  monitor_thresholds {
    warning     = 1
    critical    = 1
    ok          = 1
  }
  tags = ["Monitor tag: spaces and CAPS are fine with Monitors."]
}

resource "datadog_service_level_objective" "test" {
  name        = "Test SLO"
  type        = "monitor"
  monitor_ids = [datadog_monitor.test.id]
  thresholds {
    timeframe = "7d"
    target    = 99
  }
  tags = ["SLO tag: why does it replace spaces and CAPS?"]
}
```

### Debug Output

n/a

### Panic Output

n/a

### Expected Behavior

What should have happened?
Tag(s) added to the SLO should retain the same formatting as input. 
ex: "SLO tag: why does it replace spaces and CAPS?"

### Actual Behavior

What actually happened?
Capital letters are replaced with lowercase letters. 
Spaces are replaced with underscores. 
Special characters are remove. 
ex: slo_tag:_why_does_it_replace_spaces_and_caps

### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:

1. `terraform apply` - yep. that's all. well, need to export your api_key and app_key first. 

### Important Factoids

n/a

### References

Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
n/a

**Comment by zippolyte** [comment]
Hi !

So tags need to follow some rules: see https://docs.datadoghq.com/getting_started/tagging/#defining-tags
Tags that don't follow them are fixed on the backend side.
I would argue that the SLO API actually has the expected behaviour, by following the documented behaviour.

This isn't a provider issue though, could you open a [support ticket](https://docs.datadoghq.com/help/) for proper tracking with the backend teams ?

Thanks

**Comment by hockeygoonnorm** [comment]
Ah, ok. So maybe it is the monitor backend that is not adhering to the tagging rules. I've been able to create tags against monitors that contain spaces, caps, special chars, etc. I'll verify and follow up with support.
