### ISSUE TITLE
Provide a way to selectively enable AWS services with the AWS integration

### ISSUE THREAD

**Issue by finferflu** [DataDog/terraform-provider-datadog#969]
Hi,

It looks like the Datadog provider doesn't provide us with a way to disable the AWS services enabled by the AWS integration and they are _all_ enabled by default, which means we have to manually do this in the Datadog UI. As we're all for IaC, this would be greatly beneficial, especially because having these extra services enabled costs money.

Thanks!

**Comment by therve** [comment]
Hi,

You should be able to do this using the `account_specific_namespace_rules` attribute. Would that work for you? Thanks.

**Comment by finferflu** [comment]
@therve I am assuming this will override the active integrations because they stay all green even when I specify a list of services in `account_specific_namespace_rules`. Is that correct?

**Comment by skarimo** [comment]
@finferflu `account_specific_namespace_rules` will override the default values that are set via the checkboxes in the integrations aws tile for the given aws account. Meaning, setting's applied via `account_specific_namespace_rules` will only apply to that specific aws account.

**Comment by finferflu** [comment]
@skarimo thanks very much for confirming. Closing this issue.
