### ISSUE TITLE
Apple Silicon (darwin/arm64) support

### ISSUE THREAD

**Issue by ntsutake** [DataDog/terraform-provider-datadog#971]
Now I can not use datadog provider with M1 mac book(darwin/arm64).
I can see below logs.

```
Error: Incompatible provider version
Provider registry.terraform.io/datadog/datadog v2.22.0 does not have a package
available for your current platform, darwin_arm64.
Provider releases are separate from Terraform CLI releases, so not all
providers are available for all platforms. Other versions of this provider may
have different platforms supported.
```

### References
* hashicorp/terraform#27257
* hashicorp/terraform-provider-aws#16948

### Request
I hope this repo uses go 1.16+.
https://github.com/DataDog/terraform-provider-datadog/blob/master/.github/workflows/release.yml#L18

**Comment by therve** [comment]
Hi, `2.23.0` should be compatible. Let us know if it works for you. Thanks!
