### ISSUE TITLE
Feature Request: support for multistep synthetics tests

### ISSUE THREAD

**Issue by jeff-rasmussen** [DataDog/terraform-provider-datadog#995]
Terraform 0.14.3
DataDog Provider 2.23.0

Currently Terraform will fail and deliver an exception if type ="multistep". i realize this is a new feature from datadog, but please consider adding support for this wonderful feature!

Thank you

Jeff Rasmussen

**Comment by therve** [comment]
Closing in favor of #938 , thanks
